### ISSUE TITLE
[Harem] [currency] missing Arguments after crash/reboot

### ISSUE THREAD

**Issue by Marlo2106** [itsamewayu/OLFallenDoll#102]
After i got an error message and a game crash, i lost all of the, i think standart, 48 Arguments, you get on the first login. 

The crash occured after i left a scene and wanted to place a new one.

**Comment by Reetonzzz** [comment]
Yeah happened to me too.

**Comment by Santis95** [comment]
same

**Comment by jinjin525** [comment]
From Tuzo9 in issue #124 
When I started the game. Probably 30 mins after the update, before server crash I got a fatal error and lost all my currency including the booster pack thing. Obviously I can’t reproduce it or anything.

From MarcusKane1 in same issue
Happened to me as well.
Lost connection to server while opening packs ,when reconnecting lost all research points(those one that you get for daily activities).

**Comment by jinjin525** [comment]
From TextAfterDark in issue #169 
Trying to purchase additional packs via blueprint with arguments seem to not work.
Unsure if this a graphical error on the number of arguments i have or something else.  
Please Note: The argument that i have seem to go up and down.
I started with 48 with the first time login but with the server crash and a game crash it went down to zero, then it when back to 150 when i accepted the in-game mail.

**Screenshots**
![image](https://user-images.githubusercontent.com/95316882/144130085-bc87d2fc-9d00-47da-a622-b22add785bae.png)
