### ISSUE TITLE
Erika's Night Maid outfit leg texture issue

### ISSUE THREAD

**Issue by Fiwzie** [itsamewayu/OLFallenDoll#1020]
**Describe the bug**

If you undress Erika's Night Maid leggings it changes the leg texture color. Not pose specific. The texture issue goes away when dressing or undressing Upper Apparel, but have to repeat the process if leggings setting is changed again.

![Screenshot 2023-11-29 115006](https://github.com/itsamewayu/OLFallenDoll/assets/129328061/70ef82fc-910a-4a0c-a000-2920ddf6125f)
![Screenshot 2023-11-29 115009](https://github.com/itsamewayu/OLFallenDoll/assets/129328061/cfff0587-ccd2-47f0-9cae-5509acb7a655)
![Screenshot 2023-11-29 115016](https://github.com/itsamewayu/OLFallenDoll/assets/129328061/cc85084a-1ff8-4d46-a11a-93e2b0f59d75)

**Comment by Awfulwaffle1** [comment]
This looks to be resolved as of 0.7.9. Closing.
