### ISSUE TITLE
Some issues on the model of alet

### ISSUE THREAD

**Issue by lalakiop** [itsamewayu/OLFallenDoll#1032]
**Describe the bug**
There are obvious gaps in Alet's legs, there is a color difference between the body texture and the hand texture, and there is a color difference between the body and waist texture

**Screenshots**
![屏幕截图 2023-12-02 175329](https://github.com/itsamewayu/OLFallenDoll/assets/89827373/d180cf93-7f8a-49fe-8ea8-f6a60514f40e)
![屏幕截图 2023-12-02 175333](https://github.com/itsamewayu/OLFallenDoll/assets/89827373/41cf465a-0108-4101-b90f-3d2b2c802fb1)
![屏幕截图 2023-12-02 175358](https://github.com/itsamewayu/OLFallenDoll/assets/89827373/74fee020-1b9e-484b-8d35-8484a724bc2f)

**Desktop (please complete the following information):**
 - OS: [e.g. Win10/Ubuntu 20.04]
 - Game Version [e.g. 0.42]
 Complete the following Computer Hardware Configurations if necessary:
 - Processor(CPU): [e.g. i7-9700K]
 - Graphics Card:[e.g. RTX 2070s]
 - Memory:[e.g. 16GB]

*If your game crashed, remember to upload the dmp file with your issue.

It's located in C:\Users\ (USER ID) \AppData\Local\Paralogue

**Additional context**

**Comment by Awfulwaffle1** [comment]
This is looking good now as of 0.7.9. Closing
