### ISSUE TITLE
Connexion problem.

### ISSUE THREAD

**Issue by DsertFoxx** [itsamewayu/OLFallenDoll#1038]
hi, I let Alet @ the space station in that boundage cube and left the game.
I tried to launch the game a few minutes later and now i can't connect to harem anymore.
I see a space station door for less then 1 second then it charge again. After a few times i have this message.
![operation lovecreft](https://github.com/itsamewayu/OLFallenDoll/assets/153556626/237c0f0e-6492-4a09-9172-7d3d2e19265f)

**Comment by Awfulwaffle1** [comment]
@DsertFoxx are you still running into this issue?

**Comment by Awfulwaffle1** [comment]
Closing for now. Please reopen if this is still an issue @DsertFoxx
