### ISSUE TITLE
[UI] Delete key removes UI

### ISSUE THREAD

**Issue by jstibbsy** [itsamewayu/OLFallenDoll#104]
**Describe the bug**
Pressing the Delete key (del) removes UI permanently

**To Reproduce**
1. Go into Harem mode
2. Click start
3. Load in and press delete

**Expected behavior**
Nothing to happen.

**Desktop (please complete the following information):**
 - OS: Windows 11

**Comment by TheSoulWizard** [comment]
Could you try this and tell if it's still present or not? On my end, pressing delete does nothing.

**Comment by Awfulwaffle1** [comment]
Could not reproduce as of 0.7.41. Closing.
