### ISSUE TITLE
No. 508 is labeled as [Restrained] but does not complete at least one Daily Task that it should qualify for

### ISSUE THREAD

**Issue by AsclepiusO** [itsamewayu/OLFallenDoll#1040]
**Describe the bug**
No. 508 Tied Up Both Ends is labeled as [Restrained] which is appropriate given the nature of the experiment. However, it does not count towards the Daily Task for a female to orgasm during a restrained experiment. The task itself works properly with other experiments.

**To Reproduce**
Get the task in question and try experiment 508 to try to complete it

**Expected behavior**
Doing experiment 508 should count towards completing the Daily Task

**Comment by Awfulwaffle1** [comment]
Resolved as of 0.7.9. Closing.
