### ISSUE TITLE
Experiment No. 507 Semen counter wrong

### ISSUE THREAD

**Issue by PimpDaddyLlama** [itsamewayu/OLFallenDoll#1048]
![507](https://github.com/itsamewayu/OLFallenDoll/assets/154084045/31e244d0-93d2-4337-b77b-96807f77fdf5)
![counter](https://github.com/itsamewayu/OLFallenDoll/assets/154084045/5b2c2bc8-cf26-4a76-a986-79cb3693abab)
Counter just adds to Womb instead of GI Tract.

**Comment by Awfulwaffle1** [comment]
As of 0.7.9 it correctly displays on the GI Tract after ejaculating inside. Closing
