### ISSUE TITLE
[System] Fatal error when entering matchmaking

### ISSUE THREAD

**Issue by mejackwong** [itsamewayu/OLFallenDoll#105]
**Describe the bug**
Fatal error when entering matchmaking

Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x00000041

0x00007ff784020445 Paralogue-Win64-Shipping.exe!UnknownFunction []
0x00007ff783a96d2b Paralogue-Win64-Shipping.exe!UnknownFunction []
0x00007ff785b03c67 Paralogue-Win64-Shipping.exe!UnknownFunction []
0x00007ff785b119ff Paralogue-Win64-Shipping.exe!UnknownFunction []
0x00007ff785b0359b Paralogue-Win64-Shipping.exe!UnknownFunction []
0x00007ff785b03f75 Paralogue-Win64-Shipping.exe!UnknownFunction []
0x00007ff785b03810 Paralogue-Win64-Shipping.exe!UnknownFunction []
0x00007ff785b023b1 Paralogue-Win64-Shipping.exe!UnknownFunction []
0x00007ff783a96479 Paralogue-Win64-Shipping.exe!UnknownFunction []
0x00007ff783a968e3 Paralogue-Win64-Shipping.exe!UnknownFunction []
0x00007ff783a967db Paralogue-Win64-Shipping.exe!UnknownFunction []
0x00007ff783ae418c Paralogue-Win64-Shipping.exe!UnknownFunction []
0x00007ff783edde49 Paralogue-Win64-Shipping.exe!UnknownFunction []
0x00007ff7840204b5 Paralogue-Win64-Shipping.exe!UnknownFunction []
0x00007ff784ea15f9 Paralogue-Win64-Shipping.exe!UnknownFunction []
0x00007ff784e49f7a Paralogue-Win64-Shipping.exe!UnknownFunction []
0x00007ff7840d8b80 Paralogue-Win64-Shipping.exe!UnknownFunction []
0x00007ff784e519cd Paralogue-Win64-Shipping.exe!UnknownFunction []
0x00007ff78414d9ba Paralogue-Win64-Shipping.exe!UnknownFunction []
0x00007ff784ea08ef Paralogue-Win64-Shipping.exe!UnknownFunction []
0x00007ff784e850ef Paralogue-Win64-Shipping.exe!UnknownFunction []
0x00007ff783af0278 Paralogue-Win64-Shipping.exe!UnknownFunction []
0x00007ff7856b4de2 Paralogue-Win64-Shipping.exe!UnknownFunction []
0x00007ff7856a0650 Paralogue-Win64-Shipping.exe!UnknownFunction []
0x00007ff7856c0b82 Paralogue-Win64-Shipping.exe!UnknownFunction []
0x00007ff7852dc424 Paralogue-Win64-Shipping.exe!UnknownFunction []
0x00007ff7836d6ac5 Paralogue-Win64-Shipping.exe!UnknownFunction []
0x00007ff7836dd22c Paralogue-Win64-Shipping.exe!UnknownFunction []
0x00007ff7836dd29a Paralogue-Win64-Shipping.exe!UnknownFunction []
0x00007ff7836e73bf Paralogue-Win64-Shipping.exe!UnknownFunction []
0x00007ff786016cd2 Paralogue-Win64-Shipping.exe!UnknownFunction []
0x00007ffd490f7bd4 KERNEL32.DLL!UnknownFunction []
0x00007ffd4a50ced1 ntdll.dll!UnknownFunction []

**Expected behavior**

**Screenshots**
![_H(%{R~56DS4KEX8U_A_MU](https://user-images.githubusercontent.com/95271294/143994636-87cc2aba-f7b8-483c-8db7-168d3ba1813c.png)

**Comment by Awfulwaffle1** [comment]
No more fatal error reported. Closing.
