### ISSUE TITLE
4th barchair and poledance chairs not highlighting when investigating in nightclub

### ISSUE THREAD

**Issue by Neliahawk** [itsamewayu/OLFallenDoll#1051]
**Describe the bug**
i noticed while holding down the right mouse button that the 4th bar stool isnt highlighted in the nightclub where 3 of them are highlighted.
the chairs at the main poledance stage also dont highlight.

**To Reproduce**
1. Go to nightclub
2. hold down right mousebutton
3. check if chairs are highlighted

**Expected behavior**
all 4 barstools to highlight and the chairs around the poledance stage too. as all other chairs do highlight in that map.
![Screenshot_8](https://github.com/itsamewayu/OLFallenDoll/assets/79424890/c2c9e0fd-7c4b-448f-b538-d58a933f4c98)
![Screenshot_12](https://github.com/itsamewayu/OLFallenDoll/assets/79424890/5ccad4d7-7c65-4acd-94de-e66ffa50fde9)

**Comment by Awfulwaffle1** [comment]
Resolved as of 0.7.8b. Closing
