### ISSUE TITLE
UI leaking USER ID's in Anonymous Mode

### ISSUE THREAD

**Issue by TheSoulWizard** [itsamewayu/OLFallenDoll#1053]
When a user is in Anonymous Mode and gives you likes or enters bondage device his USER ID will be revealed 

![image](https://github.com/itsamewayu/OLFallenDoll/assets/40411642/1532cb45-f7b8-4ffd-af75-ee829b1e8d45)
![image](https://github.com/itsamewayu/OLFallenDoll/assets/40411642/8024d069-97aa-46de-9fb8-51a1c0227c1e)
![image](https://github.com/itsamewayu/OLFallenDoll/assets/40411642/0bc77b59-209e-40af-b150-937997b132c4)

**Comment by Awfulwaffle1** [comment]
Confirmed fixed on 0.7.9. Closing.
