### ISSUE TITLE
My sanity recover time struck at 48:32 then change to 152:41 is it normal ?

### ISSUE THREAD

**Issue by luckandlovery** [itsamewayu/OLFallenDoll#1054]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Win10/Ubuntu 20.04]
 - Game Version [e.g. 0.42]
 Complete the following Computer Hardware Configurations if necessary:
 - Processor(CPU): [e.g. i7-9700K]
 - Graphics Card:[e.g. RTX 2070s]
 - Memory:[e.g. 16GB]

*If your game crashed, remember to upload the dmp file with your issue.

It's located in C:\Users\ (USER ID) \AppData\Local\Paralogue

**Additional context**

**Comment by PuffyVulva** [comment]
same issue i had 48:32 last night at 115/162 now played a bit this morning and im at 100/162 or somethin and timer is at 152 hours (6 days) xd

**Comment by Awfulwaffle1** [comment]
Sanity will become obsolete most likely, but still documenting the issue.

**Comment by PuffyVulva** [comment]
my sanity has reset so its only visual bug

**Comment by Awfulwaffle1** [comment]
UI has been adjusted to reflect the correct remaining HH:MM before reset as of 0.7.9 build. Closing.
