### ISSUE TITLE
[Animation] [position] Alet Position bug

### ISSUE THREAD

**Issue by Marlo2106** [itsamewayu/OLFallenDoll#106]
So in the "Bent Over Leaning Rear Entry" animation with the "spawn of basatan" monster, in the Laboratory section, theres a bug for placing the position inside the desk.
![Operation Lovecraft Fallen Doll Closed Beta_2021 11 30-07 07](https://user-images.githubusercontent.com/79604882/143994809-7f628283-3075-4f4f-8d00-08daa6ad3514.png)
![Operation Lovecraft Fallen Doll Closed Beta_2021 11 30-07 05](https://user-images.githubusercontent.com/79604882/143994827-c69ae5a6-8fc3-42c7-9c5f-9105627f7414.png)

Second one i found:

in the Leg Up Rear-Entry animation with the "Sylph" drone, not beeing able to press the play button.

![Operation Lovecraft Fallen Doll Closed Beta_2021 11 30-07 17](https://user-images.githubusercontent.com/79604882/143995932-e7530fc6-a53b-4e9e-bfe7-c7dfd2a6f438.png)

In the Cunnilingus Piledrive animation with "Dr. Anya", trying to place the animation on the laboratory glas wall protet the camera outsite the Space ship. Rotate camera/free cam/cinematic cam doesnt work and is fixed on one randome point outside the ship. Eventually the animation is the problem. Tried it in different rooms but evertime the same outcome. Camera is fixed on another point, mostly outside the ship or in another wall.

![Operation Lovecraft Fallen Doll Closed Beta_2021 11 30-18 08](https://user-images.githubusercontent.com/79604882/144096449-53a62605-20ac-4e5e-a4af-450c008123a6.png)

**Comment by yodatheman81-hub** [comment]
Women xxxx 3D PS5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4

**Comment by yodatheman81-hub** [comment]
![Image](https://github.com/user-attachments/assets/276a9146-6460-4075-8111-a2a88d0494ae) world to do anything for a lot of your life in their own life in their own life in their own life in their own life in their own life in their own life in their own life in their

**Comment by yodatheman81-hub** [comment]
Women xxxx 3D PS5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 0k

**Comment by yodatheman81-hub** [comment]
Women xxxx 3D PS5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 

![Image](https://github.com/user-attachments/assets/e6d8a773-2f5c-4d31-9c5c-e5f97438b95d)

**Comment by yodatheman81-hub** [comment]
Women xxxx 3D PS5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 0k

**Comment by yodatheman81-hub** [comment]
Women xxxx 3D PS5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 

![Image](https://github.com/user-attachments/assets/23d55a5b-10f5-469f-afc7-74544c477270)

**Comment by yodatheman81-hub** [comment]
Women xxxx 3D PS5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 Xbox women superhero superhero women are not allowed to do anything for a lot of your life in their own life in their own life in their 

![Image](https://github.com/user-attachments/assets/ad2c5caa-68af-42b9-883c-cc79162885bd)

**Comment by yodatheman81-hub** [comment]
![Image](https://github.com/user-attachments/assets/c38756cd-019a-4e63-b6c9-d3c4eba51202) womaon xxxx 3D PS5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5

**Comment by yodatheman81-hub** [comment]
Women xxxx 3D PS5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 0k ps5 ps4 

![Image](https://github.com/user-attachments/assets/f303d42b-df37-4254-8f42-16f2e4629642)

**Comment by yodatheman81-hub** [comment]
Women xxxx 3D women superhero women with no one is a lot to get a pier 5 but I have to do anything for a lot of your life in their own life in
