### ISSUE TITLE
Gifts

### ISSUE THREAD

**Issue by Deth666** [itsamewayu/OLFallenDoll#1065]
can't give any characters gifts. i click the gift i want to give but it closes the gift menu.

**Comment by GilbGlibber** [comment]
Can confirm that. Also characters are stuck at level 1 "stranger" and don't level up when reached or theoretically passed 100 affection points.

**Comment by Awfulwaffle1** [comment]
@Deth666 This is unfortunately not a bug, just a feature that has not been implemented just yet. So this is a known thing that the devs are working on. Closing.
