### ISSUE TITLE
为什么我的patreon账号绑定不上我的游戏，拜托我开了＄295的会员

### ISSUE THREAD

**Issue by SCP329** [itsamewayu/OLFallenDoll#1067]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Win10/Ubuntu 20.04]
 - Game Version [e.g. 0.42]
 Complete the following Computer Hardware Configurations if necessary:
 - Processor(CPU): [e.g. i7-9700K]
 - Graphics Card:[e.g. RTX 2070s]
 - Memory:[e.g. 16GB]

*If your game crashed, remember to upload the dmp file with your issue.

It's located in C:\Users\ (USER ID) \AppData\Local\Paralogue

**Additional context**

**Comment by Awfulwaffle1** [comment]
We need more information to help. You can go to the discord for quicker support or e-mail contacts@ProjectHelius.com

我们需要更多信息来提供帮助。您可以前往 Discord 以获得更快的支持或发送电子邮件至 contact@ProjectHelius.com
