### ISSUE TITLE
[Harem] [Animations] Clipping issues with 2 animations on the Laboratory desk

### ISSUE THREAD

**Issue by Marlo2106** [itsamewayu/OLFallenDoll#107]
2 animations clipping each oth
![Operation Lovecraft Fallen Doll Closed Beta_2021 11 30-07 14](https://user-images.githubusercontent.com/79604882/143995532-40792814-c458-4e9f-933b-577c78eeb080.png)
er

**Comment by jinjin525** [comment]
Not enough information. Please resubmit the issue using the right form.
