### ISSUE TITLE
I paid 95usd but i only got 3 character expansion passes赞助了资本家级别，但只有3个角色通行证

### ISSUE THREAD

**Issue by lcpdguy** [itsamewayu/OLFallenDoll#1072]
在21年的时候赞助了95美元，已绑定patreon，也收到游戏内邮件，但只有3个角色解锁了通行证，另外两个角色通行证要花游戏币购买
![IMG_1990](https://github.com/itsamewayu/OLFallenDoll/assets/40915849/6ae02440-18f7-4389-8b41-51780ac3ae7a)
I paid 95USD in2021，i bind patreon account in game .but only 3 character expansion passes were unlocked ，the other character are still lock down.
![IMG_1991](https://github.com/itsamewayu/OLFallenDoll/assets/40915849/8fb4002f-cb8a-456c-bc1f-dcca96b6562f)

**Comment by Awfulwaffle1** [comment]
@lcpdguy Pardon the google translate. if you have not already, please go to the discord to create a support ticket for help.

请原谅谷歌翻译。如果您还没有，请转到不和谐创建支持票证以寻求帮助。

**Comment by lcpdguy** [comment]
![20231230230837](https://github.com/itsamewayu/OLFallenDoll/assets/40915849/ab481eca-0f0e-4c94-8e22-c9d3dad55170)
![20231230230848](https://github.com/itsamewayu/OLFallenDoll/assets/40915849/9b1723c7-ce42-4309-a080-33acc13c8e2d)
![20231230230852](https://github.com/itsamewayu/OLFallenDoll/assets/40915849/091d4e62-45d9-468d-84ae-67ce5c6c0e78)
 I connected my Discord account to Patreon,but I found nothing in my discord .@Awfulwaffle1

**Comment by Awfulwaffle1** [comment]
We'll troubleshoot from here then @lcpdguy Can you please give me your patreon email and your 17 digit steamID. I'll send your issue to a developer to have your NEP sent for your other pass. One of the 150 NEP you received should go towards Celia's Advanced pass. It should mention the name in the mail.

**Comment by lcpdguy** [comment]
@Awfulwaffle1  Yes,i already got 150 NEP  to unlock Celia
My patreon email :lcpdjanleung@hotmail.com and steam id :76561198043275438

**Comment by Awfulwaffle1** [comment]
And the bottom right of Harem page, you've already clicked that to link  your patreon account in-game?

**Comment by lcpdguy** [comment]
yes，i already link my patreon account in-game

**Comment by Awfulwaffle1** [comment]
@lcpdguy Sorry for the long wait. You should have received your 150 NEP in the in-game mail. Please let me know

**Comment by lcpdguy** [comment]
OK，I got it ,thanks for the help
 @Awfulwaffle1
