### ISSUE TITLE
The problem caused by binding the incorrect Patreon account

### ISSUE THREAD

**Issue by ScentWoman2333** [itsamewayu/OLFallenDoll#1074]
Before starting the game, I bound a Pateon account. However, I bound a Pateon account that did not purchase a Steam key, which resulted in the game being unable to claim the bound rewards. How to unbind and rebind a Pateon account that has purchased a Steam key

My Steam ID: 76561199154911489

Please help me unbind Pateon, thank you

**Comment by Awfulwaffle1** [comment]
@ScentWoman2333 Please provide your patreon e-mail both the currently bound one + the one you're suppose to bind. I'll send a request to the devs once I have that.

**Comment by ScentWoman2333** [comment]
@Awfulwaffle1 
my patreon e-mail: 310871741@qq.com
currently bound e-mail: ysxj7777@gmail.com
i suppose to bind e-mail: 310871741@qq.com
thank you for your help

**Comment by Awfulwaffle1** [comment]
@ScentWoman2333 You should know be unlinked. Please log in with the correct patreon prior to linking in-game :) Let me know if you need any other assistance.
