### ISSUE TITLE
后宮模式封測已知BUG列表

### ISSUE THREAD

**Issue by TymonLi** [itsamewayu/OLFallenDoll#108]
避免看不懂繁體我翻成了簡體中文

1.抽卡画面的BGM与游戏背景BGM重叠。
2.ESC无法退出邮件，要用滑鼠点郵件視窗外才能取消該UI。
3.邮件右侧的按钮无作用。
4.卡在电梯并且无角色，无法操作。
5.在电梯内切换更衣室鼠标会不见。
6.后宫模式下"开始"有机率遇到fatal error弹出式视窗强制关闭游戏。

**Comment by 1843890303** [comment]
增加一个，高采样率声卡没有声音（明明以前版本是有的）

**Comment by Awfulwaffle1** [comment]
Closing as all of the issues have been resolved except for the high sample rate.
