### ISSUE TITLE
很多姿势有穿模，物理效果不准确

### ISSUE THREAD

**Issue by qingcai5204** [itsamewayu/OLFallenDoll#1085]
很多姿势有穿模，物理效果不准确
很多姿势有穿模，物理效果不准确
很多姿势有穿模，物理效果不准确

**Comment by yuanyuankuang** [comment]
Would you like to list the pose index?

**Comment by qingcai5204** [comment]
No.105：男性内射没有音效
No.101：女性没有喷水，性交动画不准确
No.104：音效与动画不同步，阴茎拔出插入动画有穿模问题
No.204：女性头发位置不准确
No.312：女性手腕位置变化不准确
No.530：抽插动画有穿模问题
No.550：男性射精动画有问题
No.524：待机动画有穿模问题
No.427：男性阴茎插入动画有穿模问题
No.424：阴茎拔出插入动画有穿模问题
No.434：阴茎拔出插入动画有穿模问题
No.410：肛交动画有穿模问题
No.410：肛交动画有穿模问题，阴茎拔出插入动画有穿模问题
No.219：阴茎拔出插入动画有穿模问题
No.220：阴茎拔出插入动画有穿模问题，肛交动画有穿模问题
No.518：阴茎拔出插入动画有穿模问题，肛交动画有穿模问题

**Comment by Awfulwaffle1** [comment]
You provided this same information in #1087 Closing for duplicate issue.
