### ISSUE TITLE
进入后宫模式之后无法移动，切换输入法也无法完成移动。加载结束后会被放置在一个小房间中，有三个大门但是我按了所有按键，都不曾开启过。

### ISSUE THREAD

**Issue by CRYINGCATW** [itsamewayu/OLFallenDoll#109]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jinjin525** [comment]
Duplicate of #101
