### ISSUE TITLE
[Harem] [UI] Insufficient Likes image missing when purchasing new outfits

### ISSUE THREAD

**Issue by RueGorE** [itsamewayu/OLFallenDoll#110]
**Describe the bug**
When attempting to purchase a new outfit without having the required number of likes, a notice flashes on the screen. The text of this notice is spilling out the markup instead of displaying the "LIKE" graphic.

**To Reproduce**
1. Go to Harem 
2. Click on Character
3. Attempt to purchase an outfit you don't have without enough Likes needed

**Expected behavior**
I assume the "LIKE" graphic should appear beside the text "Insufficient Likes" in place of "**<img id="LIKE"/>**.

**Screenshots**
![insuff](https://user-images.githubusercontent.com/68206765/143996384-5a6957be-c67c-4c74-a6b2-a2c741ac32e2.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro, 20H2

**Comment by Awfulwaffle1** [comment]
Should be resolved now with new UI. Closing.
