### ISSUE TITLE
The problem caused by binding the incorrect Patreon account

### ISSUE THREAD

**Issue by EchiechiMyKanojo** [itsamewayu/OLFallenDoll#1100]
Before starting the game, I bound a Patreon account. However, I bound a Patreon account that did not purchase a Steam key, which resulted in the game being unable to claim the bound rewards. How to unbind and rebind a Patreon account that has purchased a Steam key?
My Steam ID：02150039( URL:https://steamcommunity.com/id/02150039/)
My game name：红露凝香
Please help me unbind Patreon, thank you

**Comment by Awfulwaffle1** [comment]
@EchiechiMyKanojo I'll need your 17 digit SteamID and Patreon email.

**Comment by Awfulwaffle1** [comment]
> My Steam17 digit id is 76561198307368887 My patreon email is ***@***.*** Thank you. ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "itsamewayu/OLFallenDoll" ***@***.***&gt;; 发送时间:&nbsp;2024年1月15日(星期一) 凌晨5:36 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [itsamewayu/OLFallenDoll] The problem caused by binding the incorrect Patreon account (Issue #1100) @EchiechiMyKanojo I'll need your 17 digit SteamID and Patreon email. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

You might need to reply directly to the github post instead of through the e-mail. I cannot see your patreon email. It's showing up as ***@***.***

**Comment by Awfulwaffle1** [comment]
ty. I'll put in a request and reply back here once the dev gets fulfills the request.

**Comment by Awfulwaffle1** [comment]
@EchiechiMyKanojo please check now. Make sure to log into your correct patreon e-mail prior to linking and let me know if you need anything else.
