### ISSUE TITLE
[Harem] [Performance] Abnormal fps and CPU usage

### ISSUE THREAD

**Issue by Marlo2106** [itsamewayu/OLFallenDoll#112]
Playing on my setup i get 30 fps on alet in Harem mode after 20/30 mins ingame walking. could also be couse i alt/tab out of the game to write in discord
![grafik](https://user-images.githubusercontent.com/79604882/143997229-3f4e9f4a-c5b6-4d77-a072-8d43c66ce924.png)

while stuck in the elevator and alt/tab out of the game for like 5 mins the game is on 1 fps 
![Operation Lovecraft Fallen Doll Closed Beta_2021 11 30-07 53](https://user-images.githubusercontent.com/79604882/143999925-7aedd223-7454-4dde-a8ee-511b37d98001.png)

**Comment by TheSoulWizard** [comment]
Game has some serious problems with CPU utilization from what it seems. My CPU keeps Hitting 100% but the CPU stays chill at 25%

Specs:
CPU: Intel Core i7 7700k
GPU: GTX 1070 OC Edition
RAM: Yes (8GB Physical and 50 GB Virtual)

**Comment by YuminaNirvalen** [comment]
Same here (only harem, the solo mode works perfectly fine with 4k/60fps), I hit 100% CPU usage in harem mode, but ram only 14/32gb and gpu at ~50%.

Specs: 
CPU: Intel Core  i7-7700HQ
GPU: AMD 5700 RX (actually an eGpu to be precise)
RAM: 32GB

**Comment by TheSoulWizard** [comment]
Update: Issue is present in 0.4.1
Harem uses 100% CPU (Even on empty loby)

**Comment by Awfulwaffle1** [comment]
CPU issue has been resolved, the only thing that remains is a high VRAM usage. Closing.
