### ISSUE TITLE
My Patreon account‘s level is Capitalist but  I did not receive the "six character expansion passes"

### ISSUE THREAD

**Issue by NaughtyQuin** [itsamewayu/OLFallenDoll#1126]
I upgraded my membership level from Clerk to Capitalist, but I only received 480 Neo England Pounds in the game and did not receive the "six character expansion passes" mentioned in Patreon

My Patreon account is lhl1484935813@gmail.com

My in-game ID is RECHO

May I ask how to solve it?

**Comment by Awfulwaffle1** [comment]
@NaughtyQuin If you just did that recently give it time before the processing kicks in and you should receive the rest.
The roll out for the Advanced Research passes will get distributed as new characters are released. You should have already received 150 for Celia's Advanced Pass as well as 150 for Elizabeth's Advanced pass. If something doesn't add up please let me know and provide me with your 17-Digit Steam ID

**Comment by NaughtyQuin** [comment]
I haven't received 150 for Celia's Advanced Pass as well as 150 for Elizabeth's Advanced pass yet.My  Elizabeth's Advanced pass has been unlocked,but this is because I unlocked it with Neo England Pounds before upgrading my membership level to Capitalist.
My Steam ID is 76561198217282552

**Comment by NaughtyQuin** [comment]
@Awfulwaffle1

**Comment by Awfulwaffle1** [comment]
@NaughtyQuin Got it. The devs are still taking a look. I'll be in contact once I hear back.

**Comment by Awfulwaffle1** [comment]
@NaughtyQuin the devs only saw 150 NEP missing from what you should have received. It should be in you in-game mail now.

**Comment by NaughtyQuin** [comment]
<img width="300" alt="屏幕截图 2024-01-14 121019" src="https://github.com/itsamewayu/OLFallenDoll/assets/120302944/b8c5d244-35f3-446e-b2b3-ff0a3bc0630d">
<img width="559" alt="屏幕截图 2024-01-14 121042" src="https://github.com/itsamewayu/OLFallenDoll/assets/120302944/32107bb9-19f8-430d-a681-cca8cf90b11a">

@Awfulwaffle1 
I unlocked Elizabeth's Advanced pass with Neo England Pounds before upgrading my membership level to Capitalist,so  I understand why the email sent me "150NEP for Elizabeth".But my CELIA's  pass is still BASIC,but not advanced

**Comment by Awfulwaffle1** [comment]
The 4th email on the list was suppose to used to unlock Celia's pass. The other when new researchers are released you will receive 150 NEP each time.

**Comment by NaughtyQuin** [comment]
Okay, I understand. Thank you for your answer.

**Comment by Awfulwaffle1** [comment]
Yep anything else I can do tonhelp or can we close out this issue?
