### ISSUE TITLE
[Harem mode][Ui] Poses are not filtering by character properly

### ISSUE THREAD

**Issue by OrokinGhost** [itsamewayu/OLFallenDoll#113]
**To Reproduce**
1. Go to 'experiments'
2. Click on 'any of the girl specific tabs'
3. there should be many poses specific to only a character that does not match the filter

**Screenshots**
![image](https://user-images.githubusercontent.com/95271981/143996679-8fe5a0f8-b37d-4e2a-b7d0-b8df1352b5da.png)

**Comment by RueGorE** [comment]
I noticed the same thing.

**Comment by jinjin525** [comment]
Issue #383 with the same issue but provided detailed information

**Comment by jinjin525** [comment]
From Clifftor in #383:

**Full list of cards under incorrect category**
* Tab `Dr.Anya`
  * Erika's `Kneeling Missionary`
  * Alet's `Doggystyle on Crane`
  * Alet's `On Back Footjob`
* Tab `Alet`
  * Erika's `Reverse Footjob`
  * Erika's `Squatting Cowgirl`
  * Erika's `Betty Rocker`
  * Erika's `Thrust Behind`
  * Erika's `Hands Bound Missionary`
  * Erika's `Hugging Cowgirl`
  * Anya's `Feet Held Footjob`
  * Anya's `Anal Missionary`
  * Anya's `Threesome Reverse Cowgirl Double Penetration`
  * Anya's `Prone Bone`
  * Anya's `Threesome Kneeling Spitroast with Standing Blowjob`
* Tab `Erika`
  * Alet's `Reclined Entry`
  * Alet's `Fondling Handjob`
  * Alet's `Doggystyle Massage`
  * Alet's `Leg Raised Missionary`
  * Alet's `Leg-up Kneeling Blowjob`
  * Anya's `Handcuffed Crouch Anal`
  * Anya's `Bent Over Rear Entry On Table`

**Comment by Awfulwaffle1** [comment]
Should be working correctly. Closing.
