### ISSUE TITLE
Patreon account is banned, how to unbind it

### ISSUE THREAD

**Issue by dyingus** [itsamewayu/OLFallenDoll#1140]
gameid 什么叫黑手
patreon:3164792218@qq.com
steamid:76561199145188119

**Comment by Awfulwaffle1** [comment]
You'll need to reach out to patreon support to see if you can get it unbanned or unsuspended. If you linked your account already and no longer have a subscription, you don't need a 2nd account to link unless you're planning to continue subscribing.

**Comment by dyingus** [comment]
> 您需要联系 patreon 支持，看看是否可以将其解禁或解封。如果您已经关联了帐户，但不再有订阅，则不需要第二个帐户即可关联，除非您打算继续订阅。

I have a new Patreon account, please help me unbind it

**Comment by Awfulwaffle1** [comment]
@dyingus your account has been unlinked. Please check now.
