### ISSUE TITLE
Binding a Wrong Patreon Account in the Game

### ISSUE THREAD

**Issue by laggingdik** [itsamewayu/OLFallenDoll#1142]
I have linked a wrong Patreon account (yczcpcotlf@gmail.com), which I did not use to purchase the game. The correct one should be 1565226440@qq.com and the username is oldsix.

I am gonna use this account to continue subscribing, so would you please give the permission to unbind the current Patreon account?
Gameid: OLDSIX
Patreon: 1565226440@qq.com
Steamid: 76561198340421315

**Comment by Awfulwaffle1** [comment]
@laggingdik I'll put in a request.

**Comment by Awfulwaffle1** [comment]
@laggingdik your account should be unlinked now.

**Comment by laggingdik** [comment]
Thank you so much!

Awfulwaffle ***@***.***>于2024年1月18日 周四下午7:39写道：
