### ISSUE TITLE
The bump is still bump when released

### ISSUE THREAD

**Issue by YUNMO1007** [itsamewayu/OLFallenDoll#1144]
**Describe the bug**
After Anya releases the semen in the belly state, it shows that the semen has been emptied, but the state and the belly are still in the fitting room

**Desktop (please complete the following information):**
 - OS: [Win10]
 - Game Version [0.7.75]

**Comment by Awfulwaffle1** [comment]
Already an issue made for this. @YUNMO1007 the best way to clear inflation is by going to erotes, going to a seat, masturbating and expelling fluid. Closing this duplicate issue.
