### ISSUE TITLE
[Harem] [UI] Mouse cursor invisible on settings

### ISSUE THREAD

**Issue by TheSoulWizard** [itsamewayu/OLFallenDoll#115]
Title pretty much says everything.

Hitting ESC (In-Session) on Harem Mode and then clicking Settings, the mouse cursor goes invisible, you can still click stuff though but it's a challenge.

**Comment by jinjin525** [comment]
Kinda similiar so merging this issue to issue #90 .

**Comment by TheSoulWizard** [comment]
> Kinda similiar so merging this issue to issue #90 .

Similar or not, it has already been fixed.
