### ISSUE TITLE
[Harem] [Model] Unable to place owned experiment in Harem mode

### ISSUE THREAD

**Issue by dios042** [itsamewayu/OLFallenDoll#116]
**Describe the bug**
Basically, when I get to harem mode, there is only one scene, and it cannot be placed anywhere in the room. No idea how to advance. 

**To Reproduce**
1. Go to Main Menu
2. Click on 'Harem'
3. Click 'Start'
4. Click 'Enter Harem' (Standard, Archemedes Orbital Station)
5. E
6. Click on Alet, then creature. 
7. Click NEW Method
8. Can't place experiment anywhere in room/ Even when it is green. If you left click, it just vanishes. 

**Expected behavior**
You just cant place anything. No Clue how to place it, or advance. Have already verfied files multiple times. What and I missing?

**Screenshots**
![Screenshot (61)](https://user-images.githubusercontent.com/95271800/143998313-33a78ce5-dde6-4e95-9a3a-609596e73679.png)
![Screenshot (66)](https://user-images.githubusercontent.com/95271800/143998354-a082f55e-ef16-4bbd-8b13-9981ba82672f.png)
![Screenshot (67)](https://user-images.githubusercontent.com/95271800/143998367-c0bbf94b-ce9a-44b3-887e-bccfb988c005.png)
![Screenshot (68)](https://user-images.githubusercontent.com/95271800/143998388-6c76e11f-4d69-48d9-ab12-36e15ebe5c48.png)
![Screenshot (70)](https://user-images.githubusercontent.com/95271800/143998416-823d563f-ab3c-4c32-a29e-86007983ad20.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version FD:OL Ver 0.4.0

**Comment by Exarch23** [comment]
Reproducable , happened to me on my first time , it somehow worked once after rejoining a lobby.

after that did not work again

**Comment by jinjin525** [comment]
From DenkiKitsune in issue #307 
[animation][alet/dreamer]Rear admiral cannot be placed
Occasionally after it fails I’m unable to open doors or place other experiments.

From DenkiKitsune in issue #312 
[Gameplay] Already got the scene card but cannot use
No detailed information

From Knezzzo in issue #320  
Cant place/ use certain positions
Squatting cowgirl, Apollo:unable to use

From Cyrellos in issue #336 
[Animation][Alet/Nymph]Ass Grapping Buttjob cannot be placed
When trying to place the Ass Grapping Buttjob experiment nothing happens.
Green marks on the floor but if i place it nothing happend

From johnathandarkly in issue #345 
[Harem] Can't place "Betty Rocker"
the placeholder turns green indicating a valid placement, but placing it just exits the experiment mode.

**Comment by DenkiKitsune** [comment]
Today I noticed that one of the experiments i did a write up on was not actually showing up as an unlocked experiment when you clicked on the experiments list from the changing room. This bug might be associated with studied experiments not clearing properly from the UI after the time limit expires.

**Comment by metthewzy** [comment]
I had some similar issues. My latest guess is that the trigger is flipped because I was able to perform certain experiments I just studied within 24 hours (which I shouldn't be able to) but after they were supposedly unlocked after 24 hours I was not able to perform them again. This applies to multiple experiments I currently own.

**Comment by johnathandarkly** [comment]
#387 seems related: can't place alet leg raised rear entry experiment.

**Comment by salsabeard** [comment]
Seeing the same behavior with Anya+Hound/Dreamer Threesome Reverse Cowgirl DP scene
