### ISSUE TITLE
我赞助了70USD为什么我不能加入Credits

### ISSUE THREAD

**Issue by Ange4012** [itsamewayu/OLFallenDoll#1161]
![image](https://github.com/itsamewayu/OLFallenDoll/assets/81287863/c68fd609-45df-4d11-99ab-d9165941d262)
我看我的名字无法加入credits

**Comment by Awfulwaffle1** [comment]
@Ange4012 Please file a ticket through fallendoll discord for assistance.
请通过 Fallendoll Discord 提交请求以寻求帮助。
