### ISSUE TITLE
Never get Anya's Abdominal protuberance back

### ISSUE THREAD

**Issue by Kuoasis** [itsamewayu/OLFallenDoll#1168]
Anya always be with a pregnant abdomen，can‘t get back to normal in any ways including BDSM wire and bondage.

**Comment by Pearl-Fish** [comment]
I also have this same issue.  My Anya has been stuck with it since before Christmas & have tried the usual ways to empty but does not work.

**Comment by Yeboslav** [comment]
I had same issue. Solving it by expeling semen in erotes club by masturbating on couch.

**Comment by Pearl-Fish** [comment]
> I had same issue. Solving it by expeling semen in erotes club by masturbating on couch.

Thank you! this worked perfectly!

**Comment by Awfulwaffle1** [comment]
Known issue. Closing.
