### ISSUE TITLE
another person linking wrong patreon account :( 

### ISSUE THREAD

**Issue by Pearl-Fish** [itsamewayu/OLFallenDoll#1169]
Hi all, sorry this is not a bug.

I linked the wrong patreon account back when that was first made possible to do & have not got around to asking for help yet.  Could I please have my account unlinked so that I can link the correct one. Thanks :)

in-game ID: Pearl
Steam ID: 76561197985886419

Sorry for taking up your time.

**Comment by apex-555** [comment]
I'm looking to do this also if I can..

**Comment by Awfulwaffle1** [comment]
@Pearl-Fish @apex-555 if you  have not already, please create a support ticket in the Operation Lovecraft discord. It'll be easier to track account issues there than here. The github is meant for issues with the game rather than individual account issues.

**Comment by apex-555** [comment]
discord is confusing as hell. I tired patreon account. No one answer there which is annoying. Considering I was a capitalist supporter,  going to a aristocrat when the issue happened......its more annoying.

**Comment by Awfulwaffle1** [comment]
If that's the case, you can always DM me in that discord if needed. I'm the community manager there.

**Comment by apex-555** [comment]
sent you a message on discord. Account ghost230091
