### ISSUE TITLE
Bug of 🤰

### ISSUE THREAD

**Issue by haydn1227** [itsamewayu/OLFallenDoll#1175]
**Describe the bug**
The character shows the 🤰 mark even goes to the lab and would not take off the mark. 

![Screenshot 2024-02-09 003733](https://github.com/itsamewayu/OLFallenDoll/assets/32927942/7450d371-bc25-42f3-aa7a-08c819317c8f)
**To Reproduce**

**Comment by Awfulwaffle1** [comment]
@haydn1227 already known bug. Workaround is to go to erotes, sit, masturbate and expel fluids. Closing for duplicate issue.
