### ISSUE TITLE
[Cards] Xeno cards in Anthro packs

### ISSUE THREAD

**Issue by Drad3i** [itsamewayu/OLFallenDoll#118]
Description:
Received xeno cards in anthro packs when I only selected anthro packs and was opening them. Alet/dog/on top straddling
Erika/dog/milking handjob

**To Reproduce**
1. Go to 'blueprints’
2. Click on 'analyze”
3. See error

**Expected behavior**
Anthro cards only in anthro pack

**Comment by Awfulwaffle1** [comment]
Should be resolved by now. Closing.
