### ISSUE TITLE
[Harem] Changing Hair colour cause game crash in the elevator 后宫模式的载入电梯中，更改角色发色会导致游戏崩溃

### ISSUE THREAD

**Issue by lemonir** [itsamewayu/OLFallenDoll#120]
**描述错误**
Changing Hair colour cause game crash in the elevator, with message of "Fatal error"
Relogin again may cause Windows to reboot
后宫模式的载入电梯中，更改角色发色会导致游戏崩溃，错误信息：Fatal error！
再次登入游戏，会导致Windows系统重启

**重现**
重现该行为的步骤。
1.Enter Harem mode
2.Click start and enter the loading zone (elevator)
3.Customize character
4.Change hair colour and game crashes
1. 进入后宫模式
2. 点击'开始'，进入载入电梯
3. 选择右下角的角色自定义
4. 更改发色

**预期的行为**
发色与我在鉴赏模式中的颜色一样，且游戏正常运行

**环境配置**
 - 操作系统:Windows 11Pro 21H2 22000.348
 - 游戏版本：0.40 封闭测试
 - CPU：AMD 5600X
 - GPU：RTX 3080ti
 - RAM：32GB

**Comment by RueGorE** [comment]
I can confirm this bug does indeed crash the game with a fatal error. However, Windows did not restart upon logging into the game again.

**Comment by lemonir** [comment]
> .

也许和我的硬件有关？Windows11+AMD处理器是个很糟糕的组合😢

**Comment by RueGorE** [comment]
> 

I wouldn't necessarily say that. You found a legitimate bug that fatally crashes the game. The devs will get it fixed eventually. I am also using an AMD processor.

**Comment by jinjin525** [comment]
From turpinst in #139 :
**Screenshots**
![image](https://user-images.githubusercontent.com/95287970/144043865-9e5d75b0-876c-4393-862a-51c5fb46fb3a.png)

**Additional context**
Only tested with hair colour, but another player mentioned it happening with jiggle intensity as well.

**Comment by Awfulwaffle1** [comment]
This should be working now. Closing.
