### ISSUE TITLE
[Harem] Sanity recovery time is not zero when sanity is full.

### ISSUE THREAD

**Issue by ETERNAL-U9** [itsamewayu/OLFallenDoll#121]
**Describe the bug**
Sanity recovery time is not zero when sanity is full. The recovery time shown on screen was 17:07
 while sanity is 100/100. This recovery time keeps counting down.

**To Reproduce**
1. Go to harem mode
2. Stay in lobby
3. See "Fully recovers in xx:xx" at the left bottom of tne screen.

**Expected behavior**
It should say "Fully recovers in 00:00" or "Sanity is full"

**Screenshot**
![20211130015811_1](https://user-images.githubusercontent.com/86328918/144001392-b9d79e16-d087-4036-85d2-dbd659ffb55c.jpg)

**Comment by jinjin525** [comment]
Might related with issue #254 
Merging this issue to issue No.254
