### ISSUE TITLE
没有收到0.8.0版本回溯后的150补偿

### ISSUE THREAD

**Issue by ClaybornK** [itsamewayu/OLFallenDoll#1213]
账户名称统一是Clayborn 邮箱是2503602955@qq.com

**Comment by Awfulwaffle1** [comment]
Still being worked on. Devs will send it out soon if they have not already.

**Comment by YoWaddupFD** [comment]
@ClaybornK 

The github is not the place to submit account issues for NEP. 
If you have not already, please go to https://discord.gg/projecthelius and submit a bug report there.
 
1. Go to read-me-first, read the contents of the channel especially rule 15 to open up the rest of the server.
2. Go to support tickets
3. Submit a ticket with your information and we'll get to you as soon as possible.

For any issues submitting, please direct message Awfulwaffle or YoWaddup on discord


github 不是提交 NEP 帐户问题的地方。
如果您还没有这样做，请访问 https://discord.gg/projecthelius 并在那里提交错误报告。
 
1. 进入自述文件，阅读频道内容，尤其是规则 15，以打开服务器的其余部分。
2. 转到support-tickets
3. 提交包含您的信息的票证，我们会尽快与您联系

对于提交的任何问题，请直接在discord上留言 Awfulwaffle/Yowaddup.

**Comment by Awfulwaffle1** [comment]
@ClaybornK 

The github is not the place to submit account issues for NEP. 
If you have not already, please go to https://discord.gg/projecthelius and submit a bug report there.
 
Go to ⁠read-me-first, read the contents of the channel especially rule 15 to open up the rest of the server.
Go to ⁠support-tickets
Submit a ticket with your information and we'll get to you as soon as possible.

For any issues submitting, please direct message Awfulwaffle on discord


github 不是提交 NEP 帐户问题的地方。
如果您还没有这样做，请访问 https://discord.gg/projecthelius 并在那里提交错误报告。
 
进入自述文件，阅读频道内容，尤其是规则 15，以打开服务器的其余部分。
转到⁠support-tickets
提交包含您的信息的票证，我们会尽快与您联系

对于提交的任何问题，请直接在discord上留言Awfulwaffle
