### ISSUE TITLE
Juzi Xeno experiments allowed in Erotes Nightclub

### ISSUE THREAD

**Issue by narium413** [itsamewayu/OLFallenDoll#1227]
**Describe the bug**
Some Xeno experiments for Juzi are available to be used in Erotes Nightclub.  Examples include but are not limited to No 650 Riding, No 638 Pushed Down Bulldog, No 648 Handrest Anal

**Comment by gavi99k** [comment]
Xenos are allowed in Erotes now

**Comment by Awfulwaffle1** [comment]
Closing.
