### ISSUE TITLE
[System] Switching language in harem mode will only change part of UI texts

### ISSUE THREAD

**Issue by ETERNAL-U9** [itsamewayu/OLFallenDoll#123]
**Describe the bug**
Switching language in harem mode will only change part of UI texts. Part of the UI texts get changed and the rests remain in original language.

**To Reproduce**
1. Go to Harem mode
2. Click on "Settings"
3. Switch to another language 
4. See texts remain in original language at lobby
5. Click on "Settings"
6. See language switch applied to settings texts.

**Expected behavior**
All texts should remain in original language until next boot, or all texts should switch to another language immediately.

**Screenshots**
![20211130021006_1](https://user-images.githubusercontent.com/86328918/144002408-09305030-5c08-4674-b204-ec732450558b.jpg)

**Comment by Awfulwaffle1** [comment]
This should be working now. There will be localization issues here and there with each build, but those can be handled with separate issues. Closing.
