### ISSUE TITLE
Yuzi Stamina

### ISSUE THREAD

**Issue by NebirosA** [itsamewayu/OLFallenDoll#1230]
**Describe the bug**
Yuzis stamina doesnt regenerate.

**To Reproduce**
Dont know, but i used a bondage machine.

**Expected behavior**
Stamina should regenerate. Waited for 2 hours.

Edit: After using a repair gel the bug stays.
Edit2: Waited for 1 day and used a bondage machine again. Didnt change anything.

**Screenshots**
![image](https://github.com/itsamewayu/OLFallenDoll/assets/161737889/7a98f4a2-0562-4138-a917-7a3ae01514b4)

**Desktop (please complete the following information):**
 - OS: [Win11
 - Game Version [0.8.0f]
 Complete the following Computer Hardware Configurations if necessary:
 - Processor(CPU): [AMD Ryzen 7 5800X 3D 8-Core]
 - Graphics Card:[RTX 7900 XT]
 - Memory:[64GB]

**Comment by NebirosA** [comment]
SteamID: 76561198030292865

**Comment by AlexYae** [comment]
Same problem as yours

**Comment by awingloong** [comment]
@AlexYae steamid?

**Comment by NebirosA** [comment]
juzis stamina is back, if the other person replied, the ticket can be closed
