### ISSUE TITLE
[Harem][Ui] Leaving Experiment / Esc Pose not working

### ISSUE THREAD

**Issue by LakiBakiLL** [itsamewayu/OLFallenDoll#127]
After an Experiment, i cannot leave the animation/scene. The "leave" button (is greyed out) aswell as "Esc" dont work and the game just locks itself into the pose. I have to restart the entire game, after Alt-F4 -ing, to get into a new experiment.

Not sure what caused this bug or how to replicate it.

**Comment by salsabeard** [comment]
This seems to be a duplicate of issue #100

**Comment by jinjin525** [comment]
Confirmed duplicate of #100
