### ISSUE TITLE
Points needed to raise the advanced pass

### ISSUE THREAD

**Issue by DARKSCHNEIDER95** [itsamewayu/OLFallenDoll#1280]
The points needed to raise the advanced pass keeps giving me that they are 150 instead of 100
 
Game Version 0. 8. 0g
Operating system Windows 11 version 23H2 02-24
![IMG_0457](https://github.com/itsamewayu/OLFallenDoll/assets/161959260/607fd525-0060-4da8-be05-d70725660aee)

**Comment by Awfulwaffle1** [comment]
Dupe of #1239 . closing.
