### ISSUE TITLE
havent received Juzi NEP

### ISSUE THREAD

**Issue by IllyzeJK** [itsamewayu/OLFallenDoll#1282]
i have pledged $50+
received celia and elizabeth NEP before but not Juzi.

Or what i need to do to get NEP from Juzi?

**Comment by NebirosA** [comment]
![image](https://github.com/itsamewayu/OLFallenDoll/assets/161737889/ca50030a-cfcf-4b1a-bbae-936c525952e5)

Depends on the time you have pledged. And Juzi NEP is although an issue right now.

**Comment by TheSoulWizard** [comment]
@IllyzeJK please make a ticket on our discord.
