### ISSUE TITLE
juzi's stamina is not restored.

### ISSUE THREAD

**Issue by Yumeji4580** [itsamewayu/OLFallenDoll#1294]
juzi's stamina is not restored.

Dont know.

Stamina has never recovered since Juzi joined.

Steam ID：76561198339450974

**Comment by awingloong** [comment]
確保角色沒有進入拘束器，再次進入遊戲，在大廳或者房間內逗留，觀察10分鐘。

**Comment by awingloong** [comment]
leave the dummy device，restart the game， stay in the room or lobby for 10 minutes, then observe it. @Yumeji4580

**Comment by Yumeji4580** [comment]
@awingloong 
I have confirmed that stamina is restored. Thanks.
