### ISSUE TITLE
[Harem]  后宫模式无法进入 始终会退回菜单cannot  get into the harem mode and always return to menu

### ISSUE THREAD

**Issue by MaverickYing** [itsamewayu/OLFallenDoll#136]
**封闭测试版无法进入后宫模式**
后宫模式始终无法进入，在loading菜单等待半分钟后会自动跳回菜单

**复现BUG**
1. 打开游戏，登陆至菜单
2. 点击后宫模式，出现loading画面
3. 返回至菜单

**桌面版 (请填写下列信息):**
-操作系统：Windows11 R5-3600+RTX3070
-游戏版本：0.40

**额外内容**
7.7G的更新包打完以后VR模式没了

**Comment by Fank** [comment]
Duplicate of #86

**Comment by jinjin525** [comment]
Confirmed duplicate of #86
