### ISSUE TITLE
Cant learn Experiments from other players

### ISSUE THREAD

**Issue by Venator1001** [itsamewayu/OLFallenDoll#1388]
**Describe the bug**
When I click on a player that is using an experiment that I don't have and spend the points to learn it starts a 24 hour timer. After the times gets to zero the experiment doesn't unlock it just goes back into my locked experiments. 

**To Reproduce**

**Expected behavior**
After spending the points on researching an experiment I expect to get that experiment and don't expect it to go back to being locked. this has been an issue for a long time now and nothing seems to have been done.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Win10/Ubuntu 20.04]
 - Game Version [e.g. 0.42]
 Complete the following Computer Hardware Configurations if necessary:
 - Processor(CPU): [e.g. i7-9700K]
 - Graphics Card:[e.g. RTX 2070s]
 - Memory:[e.g. 16GB]

*If your game crashed, remember to upload the dmp file with your issue.

It's located in C:\Users\ (USER ID) \AppData\Local\Paralogue

**Additional context**

**Comment by OLFallenDoll-FanMu** [comment]
when you study，It will only be unlocked for 24 hours，You can use it within this time.
after time is over，you will lose it.

**Comment by TheSoulWizard** [comment]
This is the intended behaviour. Studied experiments are only kept for 24 hours.
