### ISSUE TITLE
Customization Fatal Error

### ISSUE THREAD

**Issue by turpinst** [itsamewayu/OLFallenDoll#139]
**Describe the bug**
Attempting to customize the characters while they haven't rendered in, which won't be happening at all with the elevator bug right now, the game will encounter a fatal error. In my case, with hair colour.

**To Reproduce**
1. Start Harem mode.
2. Infamous elevator bug.
3. Change a physical feature of a girl.
4. Fatal Error.

**Expected behavior**
Changing hair colour.

**Screenshots**
![image](https://user-images.githubusercontent.com/95287970/144043865-9e5d75b0-876c-4393-862a-51c5fb46fb3a.png)

**Additional context**
Only tested with hair colour, but another player mentioned it happening with jiggle intensity as well.

**Comment by jinjin525** [comment]
Duplicate of #120
