### ISSUE TITLE
Affinity

### ISSUE THREAD

**Issue by iwfdr** [itsamewayu/OLFallenDoll#1392]
Hi everyone, I have a problem with the affinity level, with Celia I have 154\100 and I'm at stranger level 0, how do I level up?
When I try to give a gift, after selecting the gift, it doesn't let me send it, how can I resolve this?

**Comment by OLFallenDoll-FanMu** [comment]
affinity system not yet realized，it hasn't been made yet.

**Comment by iwfdr** [comment]
Ok, thanks very much
