### ISSUE TITLE
Cannot Gift to girls

### ISSUE THREAD

**Issue by Umbral022** [itsamewayu/OLFallenDoll#1409]
I have a relationship over 200/100  affinity for one of the girls. Only shows for 0 still. Cant give a gift to any of them.

**Comment by OLFallenDoll-FanMu** [comment]
The favorability system is not yet complete, it is just a placeholder.

**Comment by TheSoulWizard** [comment]
The affinity system is not implemented yet. The gifts are intentionally disabled.
