### ISSUE TITLE
Erotes Nightclub allows many Xeno experiments -v081a

### ISSUE THREAD

**Issue by batterystapled** [itsamewayu/OLFallenDoll#1412]
Erotes is meant to disallow Xeno experiments. Many are allowed and used, including but not limited to experiments:
138 115 147 131 148 137 146 136
231 206 207 236 245 216 233 52 219
336 
417
548 
546
648 612 618 643 645 625

Please would you re-instate the Xeno ban in Erotes nightclub?
Thank you!

**Comment by TheSoulWizard** [comment]
Hey @batterystapled. After many requests this has been recently changed and xeno poses are now allowed on all maps.

There are new filter options under the "Do not disturb" that allow you to hide xeno poses from others.

**Comment by batterystapled** [comment]
OK, thank you for responding and letting me know!
