### ISSUE TITLE
VR lack of sound

### ISSUE THREAD

**Issue by Nacreeper** [itsamewayu/OLFallenDoll#1413]
When played through Steam VR no audio is played whatsoever.

1. Launch through Steam VR / Virtual Desktop
2. Start any scene
3. No audio is played

When playing the game on Desktop there is full voice acting and sound effects so I would expect there to be audio in VR as well.

**Comment by TheSoulWizard** [comment]
@Nacreeper you're likely running the demo version of the game.

Try deleting the paralogue folder from here:

Press Win + R and type `%localappdata%`
