### ISSUE TITLE
游戏里的绿票丢失

### ISSUE THREAD

**Issue by eva199614** [itsamewayu/OLFallenDoll#1414]
昨天进游戏进不去反复好几次，然后发现原来好几百的绿票就剩50张了，灵感莫名其妙的多出几百，我是580绿票档位的，就开通了一个句子的同行证是580-150=430，刚开始玩没搞懂的时候花了几十绿票，大概记得剩380左右，昨天进游戏就剩50了，我确定不是我误触花的，因为游戏里我580档位能买的东西有限，把我能买的东西的绿票数额都减去也对不上我剩余的绿票数额，所以我确定不是我误触，有可能是网络原因，能否后台查看一下我的绿票到底哪去了。

**Comment by Nananutmilk** [comment]
このリジトリはバグ報告のみを目的としています。 Discord にアクセスし、チケット ツールを使用してアカウントの問題を報告してください。
