### ISSUE TITLE
[Harem] Likes from Boost Pack disappeared

### ISSUE THREAD

**Issue by NoodleRules** [itsamewayu/OLFallenDoll#142]
**Describe the bug**
Bug: After logging out and back in, the 100 likes I had reset to 0.

Windows 10, initial beta test release version.

**Comment by jinjin525** [comment]
Another guy with similiar problem claimed the booster pack that was in his inbox. it gave him 100 likes, 50 data and 150 arguments but when he switched between menus, his arguments disappeared and he can't get any packs.
