### ISSUE TITLE
[Not A Bug]無法連接Patreon，新英格蘭磅變成負數  Why can't I connect my patreon account，new england pound negative number

### ISSUE THREAD

**Issue by CHJOJO** [itsamewayu/OLFallenDoll#1455]
**Describe the bug**

無法連接PATREON，新英格蘭磅變成負數
重新綁定也還是一樣

Why can't I connect my patreon account，new england pound negative number
Rebinding is still the same

**Screenshots**
![2024-4-13-Patreon](https://github.com/itsamewayu/OLFallenDoll/assets/109846595/2ab3453f-803e-4ae9-a046-68c9d38fbbf0)
![2024-4-13-projecthelius-error](https://github.com/itsamewayu/OLFallenDoll/assets/109846595/de7f3a58-363a-4349-9b8d-4682a9ac0b94)
![2024-4-12-new england pound](https://github.com/itsamewayu/OLFallenDoll/assets/109846595/41421629-8492-4b35-adde-de7b89660919)
**Additionalcontext**
Patreon account number：qoo82827272@gmail.com
Steam ID：76561199025234183

**Comment by ErisaEGG** [comment]
有消息了嗎...

**Comment by ErisaEGG** [comment]
我才剛提高會員資格就這樣了，發訊息patreon 也沒回覆 ，DISCORD也不知要找誰
Patreon帳號：tsftks1994@gmail,com

**Comment by CHJOJO** [comment]
去DC #Support-ticket 頻道裡面開單，那裡會有人回答您的問題

**Comment by ErisaEGG** [comment]
我的沒有看到#Support-ticket

**Comment by ErisaEGG** [comment]
該不會DC還要付費才能看到吧

**Comment by CHJOJO** [comment]
read-me-first頻道 規則看完 最按上面有本書的符號代表你同意了

**Comment by ErisaEGG** [comment]
WOW DC發展這樣了呀

**Comment by ErisaEGG** [comment]
他們表示瀏覽器問題...你的他們怎麼處理的

**Comment by CHJOJO** [comment]
有待商確中，這是極為複雜程序

**Comment by Buot51211** [comment]
一样的毛病，我已经去DC开单报告了，暂时无法解决，官方还在找问题

**Comment by ErisaEGG** [comment]
我的也是等到很無言

**Comment by CHJOJO** [comment]
我帳號已經處理完了，我的新英格蘭磅回來了
大致說明一下
在DC開票後就要排隊人工審查，最慢1個月吧最快4週，所以說就只能慢慢等待吧
喔對了在這等待期間別手癢去解除patreon的帳號綁定不然你又有得等了
