### ISSUE TITLE
[Harem][model]Part of body dissapears 

### ISSUE THREAD

**Issue by wazzuuup** [itsamewayu/OLFallenDoll#146]
**Describe the bug**
After a sex scene with Erika as the main character, with the Artemis Stealth Suit equiped, the naked portion of the body dissapears, as seen on the screenshots. Does not happen all the time, but often enough. Usually the hair turns black(was blond), though not sure if related.

**To Reproduce**
1. Finish a sex scene where Erika is with the Artemis Stealth Suit and was half dressed.

**Expected behavior**
Erika's body does not dissapear.

**Screenshots**
![2021-11-30 (1)](https://user-images.githubusercontent.com/95295087/144062591-fb0e9da0-cd06-46e6-81c7-124c2a0fe0ed.png)
![2021-11-30](https://user-images.githubusercontent.com/95295087/144062542-d2968f5e-8eef-4005-b611-0bc3e8329f1d.png)

**Desktop (please complete the following information):**
OS: windows 10
Processor: Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 CPUs), ~3.4GHz
NVIDIA GeForce RTX 3080

**Additional note**
It seems this happens to other characters too and was already reported here:
Mesh Clipping Ayana standard outfit #134

**Comment by jari428** [comment]
![Paralogue Screenshot 2021 12 05 - 20 21 44 91](https://user-images.githubusercontent.com/95413769/144798696-a97d31dd-dd41-45a8-9e30-938052aea6f6.png)
![Paralogue Screenshot 2021 12 05 - 20 21 55 73](https://user-images.githubusercontent.com/95413769/144798702-7b61b83e-b98f-4b46-bf52-1f81f03dfd71.png)

Happens on Erika's Funeral Violinist outfit too.
Screenshots only show missing arms, but I also had a separate instance where her legs were invisible instead.

Windows 10 21H1
Ryzen 7 2700x
RTX 2070
