### ISSUE TITLE
Issues at higher resolutions (3440x1440)

### ISSUE THREAD

**Issue by lv1mp** [itsamewayu/OLFallenDoll#1464]
**Describe the bug**
When the game is run at **3440x1440** you are no longer able to load into any of the Harem modes. 
The menu works, you can click the locations, and press to enter them, the button then becomes 'greyed out', but it refuses to load or even attempt to connect to the server, you are left on the location selection screen and can even select the other location and try to enter that too (nothing happens).
You can return to the previous menu (esc) and try again, but the same thing happens.

Not all UI elements function correctly at higher resolution either.

Clicking on the "Research Pass" will result in a soft lock of sorts, where the research pass screen has loaded but is not visible (when clicking randomly I can hear the sound of item selections), all background elements are no longer interactable/you can not navigate away (because the research pass menu has taken focus), thus ALT+F4 is the only escape (or getting lucky and finding the "X" button).
The same thing happens when clicking character portraits in the top right (likely because it too opens up the research pass).

All other UI elements appear to function just fine, though.

Switching to **1920x1080** fixes all issues with UI elements and loading into Harem mode locations.

**To Reproduce**
1. Set resolution to 3440x1440
2. Click on "Research Pass"
3. Be unable to see menu or navigate away#

**To Reproduce**
1. Set resolution to 3440x1440
2. Enter Harem mode navigation screen
3. Try to enter a location
5. Be unable to load into any location

**Expected behavior**
Research Pass menu should appear on the screen once activated
Harem mode should let you load into locations

**Screenshots**
![image](https://github.com/itsamewayu/OLFallenDoll/assets/167024196/e04e44ed-79ae-42da-bf79-36b1bd63d392)

**Desktop (please complete the following information):**
 - OS: Windows 11 (Version1 0.0.22631 Build 22631)
 - Game Version 0.8.2b
 Complete the following Computer Hardware Configurations if necessary:
 - Processor(CPU): Ryzen 7 5800X3D
 - Graphics Card: 3080Ti
 - Memory: 32GB

**Additional context**

**Comment by Tzhin** [comment]
I'm having the same problem too, but switching to 1920x1080 is not fixing anything.
Still stuck at the loading screen, after pressing the UI menu.

**Comment by lv1mp** [comment]
> I'm having the same problem too, but switching to 1920x1080 is not fixing anything. Still stuck at the loading screen, after pressing the UI menu.

Just a quick check, and I doubt it's this, but when you set the resolution 1920x1080, did it **actually** change the resolution once applied?
I ask because on a few occasions, I have set a different resolution, hit apply, and nothing changed. The settings state the resolution is what I had selected, but it remained at the old resolution.

Other things I've seen dotted around as potential fixes for connection problems:
- Setting graphical settings to "Low"
- Deleting the "Paralogue" folder (located in %localappdata%)
- Flushing your DNS cache (ipconfig /flushdns)

If they don't fix it, I'm afraid there might be another issue to solve.
All I know is that, for some reason, switching resolution allowed me to play the game.

**Comment by xHollis** [comment]
Same problem here.  I'm not convinced it's related to resolution however, I do run at 3440x1440.  I am just stuck on loading after trying to enter either Harem.  Can't return, can't do anything accept alt+tab and close the Operation Lovecraft window.

I did reduce resolution, reduced graphic settings, deleted the Paralogue folder, flushed DNS cache and nothing made a difference.  I cannot enter Harem mode which essentially makes the game unplayable at this point.

I am using RTX4080, AMD7700X, 32GM RAM, SSDs, etc.

**Comment by lv1mp** [comment]
How odd. 
I can consistently fix the Harem loading problem by switching/lowering the resolution, but if others can't then perhaps it **is** unrelated, seems to be a unique solution to my set up only.

Would love to know **why** though.

**Comment by lv1mp** [comment]
Can confirm, version 0.8.2d has fixed the issue with both the Research Pass menu not showing correctly and loading into Harem modes at 3440x1440.
