### ISSUE TITLE
[Model] Clothes Switching Issues Anya

### ISSUE THREAD

**Issue by itsamewayu** [itsamewayu/OLFallenDoll#15]
切换衣服时候会发生穿模 显卡3080ti，32G内存
![unknown](https://user-images.githubusercontent.com/11155504/143679462-36079146-9d79-464f-8fee-60cc62147c8b.png)

**Comment by TheSoulWizard** [comment]
Additional info: Anya's clothes won't change when located on the position shown in the picture.

**Comment by Awfulwaffle1** [comment]
Works fine on my end. Closing.
