### ISSUE TITLE
I have been banned from the Game before even getting started

### ISSUE THREAD

**Issue by Crematedwalker** [itsamewayu/OLFallenDoll#150]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Crematedwalker** [comment]
![Screenshot (11)](https://user-images.githubusercontent.com/95300555/144078018-a925a6e1-26d8-4a1f-b2e4-d34479cc2b11.png)
I have tried to play the game for the first time, and this is the only message I keep getting. I got my code from the Patreon website. Could somoene please help me with this. I have pledged for way longer than the money amount or time needed.
Thank you for your time.

**Comment by Swizop123** [comment]
Same thing happened to me
![Banned](https://user-images.githubusercontent.com/95301383/144114323-d8718703-6f8a-4006-a7b5-d0c3e523f74a.png)
e

**Comment by cederjack** [comment]
same
