### ISSUE TITLE
[model][animation] Neck of dr. Anya missing in animations

### ISSUE THREAD

**Issue by alfi301** [itsamewayu/OLFallenDoll#151]
**Describe the bug**
The Neck of the model is invisable in some animations.

**To Reproduce**
1. select a pose with Dr anya in standard outfit.
2.  play animation

**Expected behavior**
Animation plays but neck is invisable

**Screenshots**
![1](https://user-images.githubusercontent.com/95278116/144083449-b5ee65ff-6c75-46ef-b194-71f8ec606f40.jpg)

![2](https://user-images.githubusercontent.com/95278116/144083435-6f746bcf-9f2a-4af0-8230-6c3cff3b61b2.png)

**Desktop (please complete the following information):**
 - OS: [Windows]
- GameVersion: [CB 0.4.0]

**Comment by HeyItsNyX** [comment]
Duplicated post, please refer to https://github.com/itsamewayu/OLFallenDoll/issues/70

**Comment by jinjin525** [comment]
Confirmed duplicate post
