### ISSUE TITLE
买衣服花赞了不给东西 Buy outfits pay “like" no gain

### ISSUE THREAD

**Issue by 0b5erv3r** [itsamewayu/OLFallenDoll#1512]
浪费我两千赞，把赞还给我
waste my 2000 like，give me back！

**Comment by lyn0530** [comment]
The items in the store and in the costume were not valid after purchase and cost me hundreds of likes

**Comment by awingloong** [comment]
we will fix it and recover your data.  @0b5erv3r @lyn0530

**Comment by awingloong** [comment]
@0b5erv3r @lyn0530  please commit your steamid. thanks.

**Comment by lyn0530** [comment]
> @0b5erv3r @lyn0530 please commit your steamid. thanks.

0530kk

**Comment by awingloong** [comment]
@lyn0530 the steamid is  string of numbers.  steamid is better than username. @0b5erv3r

**Comment by lyn0530** [comment]
> @lyn0530 the steamid is string of numbers. steamid is better than username. @0b5erv3r

76561198367878382

**Comment by 0b5erv3r** [comment]
> @0b5erv3r @lyn0530 please commit your steamid. thanks.

76561198390970129

**Comment by awingloong** [comment]
@0b5erv3r @lyn0530 please relogin， check it.

**Comment by lyn0530** [comment]
> @0b5erv3r @lyn0530 please relogin， check it.

ok，recovered
