### ISSUE TITLE
Affinitylevel is stuck

### ISSUE THREAD

**Issue by Sp65test** [itsamewayu/OLFallenDoll#1516]
**Describe the bug**
Affinitylevel won't gain. I'm at 211/200 for Level 0 to Level 1

![grafik](https://github.com/itsamewayu/OLFallenDoll/assets/168007573/2d6589a4-3aa1-4565-95ce-770373995917)

**Comment by Kyoshiro1** [comment]
I'm having the same issues as well

**Comment by 0b5erv3r** [comment]
NO Affinity system NOW，not bug
