### ISSUE TITLE
[Feature Request][Costume Purchase] Adding Prompt before purchase

### ISSUE THREAD

**Issue by poykun** [itsamewayu/OLFallenDoll#152]
**Is your feature request related to a problem? Please describe.**
I wanted to see if I could preview outfits before purchasing. Clicked the outfit icon and instantly purchased.

**Describe the solution you'd like**
A prompt asking if you're sure you'd like to purchase the selected item

**Describe alternatives you've considered**
An alternative is to limit the purchase hit box to the lower 1/4 where the Like/Purchase button is displayed

**Additional context**
Not a big deal, but purchased an outfit I didn't want. Beta woes hehe. Loving the game so far though. Thanks!

**Comment by jinjin525** [comment]
Mixed the issue with #95
