### ISSUE TITLE
OodleData Failed to Load

### ISSUE THREAD

**Issue by DukeJukem591** [itsamewayu/OLFallenDoll#1520]
**Describe the bug**
The game will not launch or load properly, every time the app is launched it gives an error message then crashes.

**To Reproduce**
1. Launch the game
2. See error

**Expected behavior**
The game loading properly and launching.

**Screenshots**
Screenshot is attached of error message.

**Desktop (please complete the following information):**
 - OS: Windows 11 23H2
 - Game Version: Steam Version believe it is 0.7.8b
 Complete the following Computer Hardware Configurations if necessary:
 - Processor(CPU): i7-13700k
 - Graphics Card: RTX 3080
 - Memory: DDR5 32gb

**Additional context**
Troubleshooting Performed: GPU driver update, reinstall without deleting paralogue folder, reinstall with deleting paralogue folder, running as admin, running in windows comparability mode, running with and without -dx11 in steam startup. From what I can tell online it might be an issue with unreal engine.

![ErrorMessage](https://github.com/itsamewayu/OLFallenDoll/assets/168128069/23f9ca9f-7878-4cc6-a8e1-d67a9228fad2)
[UEMinidump.dmp](https://github.com/itsamewayu/OLFallenDoll/files/15119541/UEMinidump.dmp)

**Comment by awingloong** [comment]
now game version is 0.8.2e， please update it. @DukeJukem591

**Comment by DukeJukem591** [comment]
@awingloong if that's the newest version in steam then that's probably the one I have. I can't see what version I have because I can't launch the game.

**Comment by DukeJukem591** [comment]
I've been looking into it further, I may have an older version of the game but steam will not update to 0.8.2f it seems to be stuck on 0.7.8b.
![SteamGameNews](https://github.com/itsamewayu/OLFallenDoll/assets/168128069/11713206-9edc-490f-b2c1-f292492b093d)

**Comment by awingloong** [comment]
![image](https://github.com/itsamewayu/OLFallenDoll/assets/18610053/98af7f5e-9027-41fa-87b0-5bb000713ebd)

**Comment by awingloong** [comment]
please try to remove the game and reinstall it. @DukeJukem591

**Comment by awingloong** [comment]
> I've been looking into it further, I may have an older version of the game but steam will not update to 0.8.2f it seems to be stuck on 0.7.8b. ![SteamGameNews](https://private-user-images.githubusercontent.com/168128069/326053379-11713206-9edc-490f-b2c1-f292492b093d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyNjY5MjMsIm5iZiI6MTcxNDI2NjYyMywicGF0aCI6Ii8xNjgxMjgwNjkvMzI2MDUzMzc5LTExNzEzMjA2LTllZGMtNDkwZi1iMmMxLWYyOTI0OTJiMDkzZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyOFQwMTEwMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZDUxNWVhOTc1MTBkMDRiOTc5NWExNTBjZWExN2ExOWFjMDllNmMwMmVmMTFhZmZkODU0ZTU2NzEwYTMwNWRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DZEH9_zZWcz-6BEe80-hhA4qPrBsyVSa9rI4M1JdlsA)

we don't update the steam news.

**Comment by DukeJukem591** [comment]
I did try reinstalling, I've done 4 reinstalls all together

**Comment by DukeJukem591** [comment]
@awingloong maybe I just need to wait for the next update to see if it is fixed then?

**Comment by DukeJukem591** [comment]
@awingloong nevermind I found the issue, steam was not completely uninstalling the game whenever I tried through steam. I had to manually uninstall the game and appdata using file explorer. After doing that I was able to reinstall the game and it works now. Appreciate the help
