### ISSUE TITLE
账号关联

### ISSUE THREAD

**Issue by jiuqiyuzhi** [itsamewayu/OLFallenDoll#1523]
**Is your feature request related to a problem? Please describe.**
账号关联不小心取消了，无法再次关联
**Describe the solution you'd like**
希望可以重新关联
**Describe alternatives you've considered**

**Additional context**

**Comment by TheSoulWizard** [comment]
嘿 @jiuqiyuzhi . 如果您仍然遇到这个问题，请在我们的 Discord 上开票，以获得进一步帮助 https://discord.gg/projecthelius
