### ISSUE TITLE
unlink in game by mistake 

### ISSUE THREAD

**Issue by drlove29526** [itsamewayu/OLFallenDoll#1525]
hello i am new I pressed unlink by mistake Patreon account Dr Love I moved to capitalist level but I don't receive the benefits I'm discouraged I canceled the subscription if you don't solve it I can't help but give up on the renewal  ps. I don't speak English I used google translator thanks

**Comment by TheSoulWizard** [comment]
Hey @drlove29526 . Please open up a ticket on our discord server if you still have that issue. https://discord.gg/projecthelius
