### ISSUE TITLE
Can't link patreon account!

### ISSUE THREAD

**Issue by Xendor29** [itsamewayu/OLFallenDoll#1533]
![Névtelen](https://github.com/itsamewayu/OLFallenDoll/assets/145223171/003c961f-6a78-4309-8d6f-780021abe667)
I can't link my patreon account in the game.

![Névtelen](https://github.com/itsamewayu/OLFallenDoll/assets/145223171/8a727fb4-3d3c-4b22-943f-9e5da999ab83)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Win10/Ubuntu 20.04]
 - Game Version [e.g. 0.42]
 Complete the following Computer Hardware Configurations if necessary:
 - Processor(CPU): [e.g. i7-9700K]
 - Graphics Card:[e.g. RTX 2070s]
 - Memory:[e.g. 16GB]

*If your game crashed, remember to upload the dmp file with your issue.

It's located in C:\Users\ (USER ID) \AppData\Local\Paralogue

**Additional context**

**Comment by TheSoulWizard** [comment]
Hey @Xendor29. Please open up a ticket on our discord server if you're still facing that issue. https://discord.gg/projecthelius
