### ISSUE TITLE
Graphic

### ISSUE THREAD

**Issue by Gitt79** [itsamewayu/OLFallenDoll#1537]
**Describe the bug**
My charecters have no nipple/areola colour just same as their skin colour exept Anya
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Win10]
 - Game Version [0.8.2e]
 Complete the following Computer Hardware Configurations if necessary:
 - Processor(CPU): [e.g. i5]
 - Graphics Card:[e.g. gtx 1650]
 - Memory:[e.g. 6GB]

*If your game crashed, remember to upload the dmp file with your issue.

It's located in C:\Users\ (USER ID) \AppData\Local\Paralogue

**Additional context**

**Comment by TheSoulWizard** [comment]
@Gitt79 You are likely limited by the ammount of VRAM of your GPU. The game at its current state can use about 7.1 GB of VRAM.

You can also try adding `-dx11` as a start option/command on steam, it may help ease out some vram usage.
