### ISSUE TITLE
希望解决下人物头发乱飘的问题

### ISSUE THREAD

**Issue by liebaokuangben** [itsamewayu/OLFallenDoll#1538]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Win10/Ubuntu 20.04]
 - Game Version [e.g. 0.42]
 Complete the following Computer Hardware Configurations if necessary:
 - Processor(CPU): [e.g. i7-9700K]
 - Graphics Card:[e.g. RTX 2070s]
 - Memory:[e.g. 16GB]

*If your game crashed, remember to upload the dmp file with your issue.

It's located in C:\Users\ (USER ID) \AppData\Local\Paralogue

**Additional context**

**Comment by TheSoulWizard** [comment]
请分享一些问题的截图或视频。

由于缺乏细节，我将关闭此主题。
