### ISSUE TITLE
[Harem] Using VPN or not causes User to re-register

### ISSUE THREAD

**Issue by Yukikaze-OLFD** [itsamewayu/OLFallenDoll#154]
**Describe the bug**
Connecting into the game using VPN to a different region causes it to restart User Creation. Old users are still recognized (I cannot create my original username of Yukikaze) but cannot be used. 

**To Reproduce**
1. VPN into another Region (I went from US to UK-Docklands)
2. Log into Harem Mode

**Expected behavior**
Loads character account based on Steam ID

**Screenshots**
![image](https://user-images.githubusercontent.com/95274126/144087959-b1d5e898-21fd-4875-a177-26d9ca370a8a.png)
Created EU account

**Desktop (please complete the following information):**
 - OS: Win11

**Additional context**

**Comment by TheAlunora** [comment]
Confirming this bug, switching regions with a VPN removes access to all old accounts, and forces you to generate new ones every time a region switch is made.

**Suggestion**
Have region/account selection as an option.

**Comment by Yukikaze-OLFD** [comment]
![image](https://user-images.githubusercontent.com/95274126/144099550-dcd3361f-51cf-4beb-8040-53f58e9b4417.png)
Logging back into original region causes user creation to happen again, however there appears to be some account confusion.

1. Created Yukikaze_US
2. Logged in and received 48 Blueprints
3. Found two mail (one previously opened on Yukikaze and new one opened on Yukikaze_US)
4. Opening mail on Yukikaze US yields no resource and resets resource graphic. Resource backend value remains.

**Comment by OdinsRightEye** [comment]
Confirming this bug. Btw looks like currently it is only way to change User ID.

**Comment by Valamore** [comment]
When I had this issue I wasn't using a VPN and it signed me out of my first account, so it's not solely VPN based.
