### ISSUE TITLE
[Harem][Model][Outfit] Dr.Anya: wearing clothing one does not own

### ISSUE THREAD

**Issue by Suytanell** [itsamewayu/OLFallenDoll#155]
**Describe the bug**
Recently in harem mode, I was able to see Dr.Anya in her "Laboratory"? uniform (the one where she got the lab coat and her glasses on) inside animations, although I do not own that specific type of clothing. I was also able to toggle parts of it.

**To Reproduce**
1. I went into Classic Mode and switched my standard-outfit for her (Voivode Command Suit) into the (Miskatonic Scholar) one.
2. Played some animations in Classic Mode
3. Left the game
4. Started the game and went right into Harem Mode, not buying anything from Harem Store.
5. Walked around in Harem Mode (Still had Voivode Command Suit clothing)
6. Started Sex Scene not available in Classic Mode: "Dildo Piledriver", Anya wore her Miskatonic Scholar outfit.
7. (Tried to replicate without steps 1-4, still works)

**Expected behavior**
I shouldve definetly seen Anya still wearing her Voivode Command Suit- Outift

**Desktop (please complete the following information):**
 - OS: Win10
![20211130174106_1](https://user-images.githubusercontent.com/95303658/144089757-4478bbb1-4a59-4d1f-92e8-16b2d5877e17.jpg)

**Comment by poykun** [comment]
Just stumbled upon this as well. Verified for Dr. Anya. Not sure about Alet and Erika quite yet.

**Comment by poykun** [comment]
This should be fixed now with v.0.4.2

**Comment by jinjin525** [comment]
0.4.2 Patch Notes:
·Character customization should now correctly synchronize with other players in the lobby and all players' avatar will be displayed in their current dressing state. Please note this fix is experimental and will be continually improved upon.

Please submit the issue again if it's not fixed. Thanks.
