### ISSUE TITLE
I think the game may need improve on Harem mode graphic

### ISSUE THREAD

**Issue by ZELA-SAMA** [itsamewayu/OLFallenDoll#159]
I think the quality of Harem mode may need an improve on graphic
On the first picture is from Harem mode, the quality of graphic is look like from PS2 or older
![1](https://user-images.githubusercontent.com/95305751/144094984-925e4f33-5d89-4627-b330-f7481f5c8367.jpg)

This is from Gallery mode, This look nice as a game to play.
![2](https://user-images.githubusercontent.com/95305751/144094998-3e7fdc53-c490-4edb-88b0-1350a30be164.jpg)

So I think it may not be the same because of the object to lode is more on Harem. 
But at least the game has to be nice and playable with the nearly close graphic between two.

My notebook that I use is 
LENOVO LEGION
Intel core I7-9750HF with 16GB of RAM
GPU is NVIDIA GeForce GTX1650

Please fix the game to be more playable

**Comment by YuminaNirvalen** [comment]
It's the same for me too. (Solo mode: 4k with 60 fps stable, but harem literally same as the picture from @ ZELA-SAMA) 

Specs (laptop):
CPU: Intel Core  i7-7700HQ
eGPU: AMD 5700 RX 
RAM: 32GB

**Comment by jinjin525** [comment]
Should be same issue as #183
