### ISSUE TITLE
[Texture] Skin Distortion Erika

### ISSUE THREAD

**Issue by itsamewayu** [itsamewayu/OLFallenDoll#16]
Kuramoto sensei — Yesterday at 8:12 PM
visual tearing and distortion with erika if using darker skin with said outfit 

![phb1](https://user-images.githubusercontent.com/11155504/143679485-f7f4d5ac-6abf-49d7-b13c-eb7f4d28d6af.png)

![phb2](https://user-images.githubusercontent.com/11155504/143679486-178d89e8-0a13-43f8-bfe6-25d21d1fa1f3.png)

game adjust self when switching back to nude
![unknown](https://user-images.githubusercontent.com/11155504/143679490-116af587-41d7-4ab3-8bfc-43a0f8a6b978.png)
![unknown](https://user-images.githubusercontent.com/11155504/143679494-c1bfb879-08ce-4000-acfb-e54c35833958.png)

**Comment by Awfulwaffle1** [comment]
Bunny suit no longer available in Gallery. Closing.
