### ISSUE TITLE
[Harem] [Menu] "resume" button instead of "start"

### ISSUE THREAD

**Issue by Marlo2106** [itsamewayu/OLFallenDoll#160]
After alt/f4 the game, the start button is changed with the resume button. (i alt/f4 after getting stuck in the animation i mentioned in one of my other post about alet animations)

![Operation Lovecraft Fallen Doll Closed Beta_2021 11 30-18 23_1](https://user-images.githubusercontent.com/79604882/144097353-12f9072f-d8df-40a6-bcb4-ef6d3f1e3308.png)

**Comment by poykun** [comment]
Workaround would be to Quit > Return to Title and go back into Harem mode. Possibly still detecting your previous session if you were harem mode prior.

**Comment by Marlo2106** [comment]
Could be a work around and it works. But still it is not intendet, imo

**Comment by TheSoulWizard** [comment]
i believe this has been fixed on either 0.4.2 or 0.4.5.
