### ISSUE TITLE
[sound] footstep sound

### ISSUE THREAD

**Issue by fallenDollPhobos** [itsamewayu/OLFallenDoll#161]
although all sounds are muted in options, footsteps are still being played when you switch to another character in harem mode

**Comment by TheSoulWizard** [comment]
There are multiple UI Sound leaks, Even Door sounds, UI sounds are playing when everything muted

**Comment by YuminaNirvalen** [comment]
Yeah it's the same for me, but there is no option to adjust the footsteps/door openings/... It's annoying since it's quite loud and makes it so that you get distracted from the actual game and femal sounds.

**Comment by jinjin525** [comment]
Mixing the issue with issue #97 .
