### ISSUE TITLE
[Ver0.8.28][Costume]Stockings with a "half-Dressing" option lack the "Dressing" option in sex experiments.性爱实验当中拥有“半脱”选项的丝袜缺少“着装”选项。

### ISSUE THREAD

**Issue by OLFallenDoll-FanMu** [itsamewayu/OLFallenDoll#1617]
Note: My English is not very good. If you know Chinese, please go to the Chinese section below.

【Describe the bug】
Some stockings with a "half-Dressing"" option that allows you to fully wear them in the dressing room or on the main page.
But in the sex experiment, there are only "half-dressed" and "completely naked" options.

【To Reproduce】
1. Log in to the game and enter "Harem Mode"
2. Choose a character and wear stockings with the "half-Dressing" option.
3. Select an experimental map, enter and conduct the character's sex experiment
4. See error，Found that the stockings only have "half-off" and "completely naked" options

【Expected behavior】
These stockings that have a "half-dressed" option should also have a "fully-dressed" option during sex experiments and be displayed correctly.

【Screenshots】
![_%NTD(1Q{B56OX1EFZT5VU1](https://github.com/itsamewayu/OLFallenDoll/assets/61645208/f681a268-c382-49dd-b1b6-909b23ece2e6)
![N `QX (H@UHJSLLY$D_{3WU](https://github.com/itsamewayu/OLFallenDoll/assets/61645208/515659a2-88dc-4072-8082-6c1d3bf954b1)
![5DIVD HW7FEL 5Q557%F``E](https://github.com/itsamewayu/OLFallenDoll/assets/61645208/59812f80-6ddf-4558-8e17-b62664471f7b)
![({M9M}R0ZBFE7HAQP_HX{}Q](https://github.com/itsamewayu/OLFallenDoll/assets/61645208/32816ce4-39e7-414e-9ab7-6c147e498ca3)

【Additional context】
中文部分：
【描述错误】
一些拥有“半穿”选项的丝袜即使在更衣室或主界面可以完全着装，但在性爱实验当中却仅能选择“半穿”或“全裸”。

【重现步骤】
1.登录游戏并进入“后宫模式”
2.选择一个拥有“半穿丝袜”选项服装的角色
3.选择一张实验场地地图进入，然后使用该角色进行性爱实验动作
4.发现这个错误，发现丝袜只有“半脱”和“全裸”的选项

【预期行为】
这些具有“半穿”选项的丝袜在性实验时也应该具有“完整着装”选项，并正确显示。

截图部分同上↑

**Comment by OLFallenDoll-FanMu** [comment]
已被证实不是bug
![XFR7}EQM0_ 7%RDNURU__R3](https://github.com/itsamewayu/OLFallenDoll/assets/61645208/f0431fcf-eeb5-4da3-a628-e7fc4501db99)

**Comment by lauisdhquih** [comment]
老哥请问你后宫模式咋进去的，我一直显示网络异常
