### ISSUE TITLE
[Harem][Pose][Camera] Erika - Dreamer Cuddling Handjob Camera Stuck

### ISSUE THREAD

**Issue by GunsightOne** [itsamewayu/OLFallenDoll#163]
**Describe the bug**
When selecting the pose Cuddling Handjob with Dreamer as Erika, the camera zooms inside the models and can only be moved around a fixed point. No zoom or pan function works.

**To Reproduce**
1. In Harem mode as Erika select Experiments - Dreamer - Cuddling Handjob Card
2. Pick any spot for the pose on the floor
3. See error

**Screenshots**
![20211130140946_1](https://user-images.githubusercontent.com/95268275/144113073-29dc95a7-3f4e-4d23-84f4-baf40d2c3c9a.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 21H2
 - Version 0.4.0

**Additional Context**
Erika was wearing "Funeral Violinist" outfit. Unsure if bug occurs with other outfits.

**Comment by jari428** [comment]
![Desktop Screenshot 2021 12 02 - 04 17 09 68](https://user-images.githubusercontent.com/95413769/144403644-b0e8ba9d-4ff1-4277-98d8-8eee09bd6f68.png)

Confirming this bug occurs with Erika wearing the Adjutant outfit. 
The camera would randomly return to the normal view before returning to this zoomed-in view. I was also able to pan the camera, but not orbit it, while in this bugged view.
