### ISSUE TITLE
[Ver 0.8.28a][bug]更新以后我绿票少了

### ISSUE THREAD

**Issue by wlspy008** [itsamewayu/OLFallenDoll#1637]
**Describe the bug**

就是更新以后我的绿票少了变成了200了 之前是550

**Comment by wlspy008** [comment]
Steam ID：76561198088480132

**Comment by wlspy008** [comment]
41413333@163.com

**Comment by TheSoulWizard** [comment]
我们已经意识到这个问题，并正在努力修复。

**Comment by TheSoulWizard** [comment]
I see this issue is now resolved. Closing
