### ISSUE TITLE
[daily missions] not getting updated correctly

### ISSUE THREAD

**Issue by alfi301** [itsamewayu/OLFallenDoll#164]
**Describe the bug**
The Daily missions are not getting updated correctly.
I know it's a lot to ask for at this state of the game but I thought I let u know anyway.
I had the mission to study 5 times from other players. And it got stuck at 1. Check the screenshots. 1/5 and I got several animations that got a timer on them ( I studied them from other players)

**Expected behavior**
The counter counts correctly

**Screenshots**

![Screenshot (160)_LI](https://user-images.githubusercontent.com/95278116/144114438-2468b180-ac3b-440c-85f5-1d3512c02500.jpg)
![Screenshot (162)_LI](https://user-images.githubusercontent.com/95278116/144114570-9a1c4ea8-35f4-45c2-9c3f-fb1a5f2a65ec.jpg)

**Comment by poykun** [comment]
Current workaround that's been circling around in the discord discussion is restarting the game. All-in-all it's still a bug that needs to get looked at.
