### ISSUE TITLE
[Version 0.8.28a][Bug] After the update, my green tickets turned directly into negative numbers

### ISSUE THREAD

**Issue by xiawei19920222** [itsamewayu/OLFallenDoll#1640]
**Describe the bug**

**To Reproduce**
1. Update to version 0.8.28a
2. Open the game
3. Check the number of green tickets
4. See the number of green tickets is negative

**Expected behavior**
The number of green tickets should be positive.

**Screenshots**
![image](https://github.com/itsamewayu/OLFallenDoll/assets/29226677/b8225693-1186-47dd-bd97-ca31b6098b39)

![image](https://github.com/itsamewayu/OLFallenDoll/assets/29226677/a6159f76-680b-496e-baf1-a8fb1bd06d4e)

![image](https://github.com/itsamewayu/OLFallenDoll/assets/29226677/bc293967-3258-46db-ba21-6945a823f50f)

**Desktop (please complete the following information):**
 - OS: windows 11 
 - Game Version : 0.8.28a
 Complete the following Computer Hardware Configurations if necessary:
 - Processor(CPU): i9-13900ks
 - Graphics Card:RTX 4090
 - Memory:96GB

**Comment by TheSoulWizard** [comment]
We are aware of the issue and we're working on a fix

**Comment by TheSoulWizard** [comment]
@xiawei19920222 Please relink your patreon account if you haven't done it yet.

If you still encounter issues, please create a support ticket on our discord  https://discord.gg/projecthelius
