### ISSUE TITLE
更新以后我感觉我的绿票少了

### ISSUE THREAD

**Issue by shysakura** [itsamewayu/OLFallenDoll#1642]
My game username is: SPRINGFIELD. 
steam ID is 76561199210357197
Patreon email : 17608480861@163.com
The amount of British pounds in my account has decreased from 580 to 20, and I don't remember spending them in any circumstances. Please check my bill and verify if this is a bug.

**Comment by TheSoulWizard** [comment]
We are aware of the issue and we're working on a fix.

**Comment by TheSoulWizard** [comment]
appears resolved, closing.

**Comment by shysakura** [comment]
problems have been solved.



---- 回复的原邮件 ----
| 发件人 | Soul ***@***.***> |
| 日期 | 2024年07月06日 14:23 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [itsamewayu/OLFallenDoll] 更新以后我感觉我的绿票少了 (Issue #1642) |

Closed #1642 as completed.
