### ISSUE TITLE
更新后绿票变成负数了

### ISSUE THREAD

**Issue by bulibulibu** [itsamewayu/OLFallenDoll#1645]
Green ticket went negative after the update

game ID: Buli
steam ID  441697579
Patreon email : 1530345833@qq.com
![1718523221685](https://github.com/itsamewayu/OLFallenDoll/assets/172955825/fc38b9cc-1e3a-47c5-a5ed-c23d5bbbd468)

![1718523150585](https://github.com/itsamewayu/OLFallenDoll/assets/172955825/77479c59-feaf-48d1-a078-56e0c016c18b)

**Comment by TheSoulWizard** [comment]
我们已经意识到这个问题，并正在努力修复。
We are aware of the issue and we're working on a fix

**Comment by TheSoulWizard** [comment]
@bulibulibu Please rebind your patreon account if you did not yet.

If you still encounter issues please make a support ticket on our discord  https://discord.gg/projecthelius
