### ISSUE TITLE
更新后绿票扣为负数

### ISSUE THREAD

**Issue by veratadsy** [itsamewayu/OLFallenDoll#1647]
6月16日登陆游戏发现绿票被扣为负数，6月15日登陆时为180绿票
steam id:76561199040749347
email：GUNDAM00RXN@gmail.com

![IMG_20240616_164418](https://github.com/itsamewayu/OLFallenDoll/assets/172961911/654862dc-4e91-433e-b5df-b0895a0fc27b)

**Comment by TheSoulWizard** [comment]
我们已经意识到这个问题，并正在努力修复。

**Comment by goingeverywhere** [comment]
![1998fc5e-5941-4131-a42d-648e86cd9540](https://github.com/itsamewayu/OLFallenDoll/assets/93190911/2bb6122d-bde7-46c7-852a-02813f376c88)
![image](https://github.com/itsamewayu/OLFallenDoll/assets/93190911/d1c46bf3-7139-487d-94c6-9f77adabeb04)

**Comment by TheSoulWizard** [comment]
@veratadsy 我看到你现在有160个NEP，这是正确的数量。之前有一个bug导致了Patreon账户与玩家的解绑。

For further issues, please make a support ticket on our discord.  https://discord.gg/projecthelius
