### ISSUE TITLE
[Suggestion] Add your own private room you can decorate with 希望能在後宮模式加個玩家的個人房間

### ISSUE THREAD

**Issue by TangKingSing** [itsamewayu/OLFallenDoll#165]
你好，希望你們可以在後宮模式那加入一個玩家的私人房間，玩家能放自己喜歡的角色進去，也可以用遊戲貨幣去購買家具佈置自己房間，季票那可以的話會送一些限定家具，跪求製作組大佬們採納小弟建議。最後祝你們工作順利，身體健康。

**Comment by jinjin525** [comment]
Detailed request in #340
