### ISSUE TITLE
重新绑定帕特隆之后绿票回来了，但是之前用绿票购买的部件仍是锁定不可用的并没有恢复

### ISSUE THREAD

**Issue by GilisiZM** [itsamewayu/OLFallenDoll#1650]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Win10/Ubuntu 20.04]
 - Game Version [e.g. 0.42]
 Complete the following Computer Hardware Configurations if necessary:
 - Processor(CPU): [e.g. i7-9700K]
 - Graphics Card:[e.g. RTX 2070s]
 - Memory:[e.g. 16GB]

*If your game crashed, remember to upload the dmp file with your issue.

It's located in C:\Users\ (USER ID) \AppData\Local\Paralogue

**Additional context**

**Comment by 77007** [comment]
Please provide your steam id and item information

**Comment by GilisiZM** [comment]
Steam ID：Gilis Ong
物品信息：热情嘉年华-胸罩，热情嘉年华-内裤

**Comment by 77007** [comment]
Id consists of 17 digits

**Comment by GilisiZM** [comment]
ID:76561198863398055

**Comment by TheSoulWizard** [comment]
@GilisiZM 一旦你的 patreon 账户不再绑定，NEP 就会丢失。在您恢复您的 patreon 之后，您又收到了这些 NEP。
(你曾有 -2675，后来又收到了 3664）。

您没有弄错任何东西。

如果您仍有疑问或问题，请在我们的 Discord 上提交支持票据  https://discord.gg/projecthelius

Once your patreon account is no longer bound, the NEPs are being lost. After you rebounded your patreon you received those NEPs back.
(you had -2675 and then you received 3664)

You are not misisng anything.

If you still have questions or issues, please make a support ticket on our discord https://discord.gg/projecthelius
