### ISSUE TITLE
升级至295$会籍，未收到任何东西

### ISSUE THREAD

**Issue by HMANKY** [itsamewayu/OLFallenDoll#1656]
patreon email：2207069088@qq.com
steam ID : 76561198317374912
game ID: VALK

![image](https://github.com/itsamewayu/OLFallenDoll/assets/173060931/e5a3ac6b-630e-48aa-b830-a08a95c23a58)

**Comment by TheSoulWizard** [comment]
@HMANKY 2024 年 6 月 17 日，您收到了一封包含 2744 的邮件，与您的认捐总额相符。

如果您仍然遇到此问题，请在我们的 Discord 上提交报告  https://discord.gg/projecthelius
