### ISSUE TITLE
got 150 nep for Celia on 17/06/2024 which made me a total of 184 nep, logged in on 18/06/2024 and my nep was 34, where has my 150 nep gone?

### ISSUE THREAD

**Issue by Kezbot1** [itsamewayu/OLFallenDoll#1659]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Win10/Ubuntu 20.04]
 - Game Version [e.g. 0.42]
 Complete the following Computer Hardware Configurations if necessary:
 - Processor(CPU): [e.g. i7-9700K]
 - Graphics Card:[e.g. RTX 2070s]
 - Memory:[e.g. 16GB]

*If your game crashed, remember to upload the dmp file with your issue.

It's located in C:\Users\ (USER ID) \AppData\Local\Paralogue

**Additional context**

**Comment by TheSoulWizard** [comment]
@Kezbot1 You have most likely already received Celia before. The fact you received Celia again was probably a bug.

If you'd like to, we can take a deeper look by making a support ticket on our Discord  https://discord.gg/projecthelius
