### ISSUE TITLE
[Daily Tasks] CLAIM button not working

### ISSUE THREAD

**Issue by Exarch23** [itsamewayu/OLFallenDoll#166]
**Describe the bug**
Finished 1 daily task and the CLAIM button when pressed seems to not function properly , does not add more Argument points.
I've tried to log off Harem Mode and log back in and hit claim again , still no update to the funds I have ingame

**To Reproduce**
1. Go to 'Harem Mode'
2. Click on 'CLAIM'
3. See error

**Expected behavior**
Claim button should be pressed and Arguments should be added to my ingame currency pool

**Comment by johnathandarkly** [comment]
tried to claim second bonus "11/30 Maintenance Boost Pack" and it said "claimed" but likes and data remained the same. this was an hour before the patch was released, so maybe that's the issue? dunno.

**Comment by jinjin525** [comment]
Do you mean finished the task, clicked CLAIM button, task progress reset but still there, and you get nothing?
