### ISSUE TITLE
游戏内新英格兰镑突然减少360

### ISSUE THREAD

**Issue by ltz6278715** [itsamewayu/OLFallenDoll#1664]
游戏版本0.8.2
id：0啦啦啦0
之前账户有710新英格兰镑，6.19上线变成350镑
未购买任何物品
请修复并恢复账户新英格兰镑

**Comment by ltz6278715** [comment]
steam ID：76561199155152615
email：2042584174@qq.com

**Comment by TheSoulWizard** [comment]
@ltz6278715 您可能不再与 Patreon 账户关联。请打开游戏并点击右下角的按钮重新链接您的 Patreon 账户。链接后，您应该会通过游戏内邮箱收到它们。

如果之后您仍然遇到问题，请在我们的 Discord 上提交支持票。 https://discord.gg/projecthelius
