### ISSUE TITLE
[UI] [Controls] UI says mousewheel controls speed, but it does not

### ISSUE THREAD

**Issue by apugo** [itsamewayu/OLFallenDoll#167]
**Describe the bug**
The UI says to scroll the mouse wheel to control speed during sex poses. However, the mouse wheel only controls the camera zoom.

**To Reproduce**
Begin playing an experiment. Observe the bottom-right corner of the screen, where it says to control speed with the mouse wheel. Scroll the mouse wheel. Observe that this moves the camera but has no effect on speed.

**Expected behavior**
I would expect the camera and speed to use different controls and for them to function.

**Screenshots**
https://i.imgur.com/jzecQAb.png

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by poykun** [comment]
In response to this, try hovering over your cursor on the mouse icon before scrolling.

**Comment by apugo** [comment]
I have tried that, and it has no effect.
