### ISSUE TITLE
Lost 2000 Nep on update

### ISSUE THREAD

**Issue by RSeiler666** [itsamewayu/OLFallenDoll#1676]
After logging in, my remaining 450 NEP is now -1550 NEP
I am a 2020 subscriber, with several off and on renewals, and I don't keep track of how much I've spent,  But I know I had 450 as I was saving it for upcoming DLC

**Comment by TheSoulWizard** [comment]
Hey @RSeiler666 You are likely no longer linked with your patreon account. Please click the [Link Patreon] button on the bottom right corner, and then check the in-game mailbox.

If you are still facing issues, please make a support ticket on our Discord.  https://discord.gg/projecthelius
