### ISSUE TITLE
新英格兰镑丢失

### ISSUE THREAD

**Issue by zkx998** [itsamewayu/OLFallenDoll#1677]
游戏版本0.8.2
id：ZKXMEI998
之前账户有940新英格兰镑，6.19上线变成180镑
未购买任何物品
请修复并恢复账户新英格兰镑

**Comment by TheSoulWizard** [comment]
@zkx998 您可能不再与 Patreon 账户关联。请打开游戏并点击右下角的按钮重新链接您的 Patreon 账户。链接后，您应该会通过游戏内邮箱收到它们。

如果之后您仍然遇到问题，请在我们的 Discord 上提交支持票。 https://discord.gg/projecthelius
