### ISSUE TITLE
更新后丢失280NEP

### ISSUE THREAD

**Issue by lpq888** [itsamewayu/OLFallenDoll#1681]
steam ID：euqij3ia
邮箱676056106@qq.com
游戏版本：0.8.28a
更新后丢失280新英格兰英镑（NEP）

**Comment by TheSoulWizard** [comment]
@lpq888 您很可能未被 Patreon 绑定。

请首先访问 patreon.com，确保您登录的账户正确无误。

然后打开游戏，点击右下角的按钮重新绑定您的 Patreon 帐户。

绑定后，您应该会从游戏内的邮箱中收到您的 NEP。

如果您仍然遇到问题，请在我们的 Discord 上提交支持票据。  https://discord.gg/projecthelius
