### ISSUE TITLE
NEP LOSS

### ISSUE THREAD

**Issue by lynn0906** [itsamewayu/OLFallenDoll#1682]
Game version 0.8.28
id：AZ0906
Registration email: lynn72801@gmail.com
The account should have 480NEP, but after logging in today, I found that it has decreased to 200NEP
No items purchased
Please fix the bug and restore the New England pounds for this account

**Comment by lynn0906** [comment]
After rebinding the Patreon account, NEP still has not been restored

**Comment by TheSoulWizard** [comment]
@lynn0906 The patreon account you have rebinded, is not the right one. (it has no pledge history to ProjectH)

Please go back to patreon.com and ensure you are logged into the correct account by checking the pledge/billing history for pledges to ProjectH.

After that navigate to projecthelius.com and log in to the correct account there as well.

After than open the game, unlink your patreon (you can ignore the warning), restart the game and relink the correct one.

Then you should have your Neo England Pounds to your in-game mailbox.

If you still have issues, please make a support ticket on our Discord.  https://discord.gg/projecthelius
