### ISSUE TITLE
新英格兰镑丢失

### ISSUE THREAD

**Issue by hentaigod21** [itsamewayu/OLFallenDoll#1683]
id：76561198242020966
email: abcde12523649@gmail.com
之前沒有新英格兰镑丢失
 6.19上线变成-750镑
剛領完新發的760後變成了10
未购买任何物品
请修复并恢复账户新英格兰镑

**Comment by TheSoulWizard** [comment]
@hentaigod21 你之前拥有的10个NEP是正确的。由于一个bug，你的账户最近解绑了。一旦解绑，应得的NEP将会丢失。（你三月份也有10个NEP）

根据你的捐款历史，你应该总共收到了760个NEP。你本来有10个NEP，但在账户解绑后丢失了760个NEP（10 - 760 = -750），重新绑定账户后恢复回来。

你最近在商店里花了10个NEP，所以现在你的NEP余额是0。

你当前拥有的NEP数量是正确的，没有丢失任何NEP。
