### ISSUE TITLE
新英格兰镑变成负数了

### ISSUE THREAD

**Issue by DiHongStar** [itsamewayu/OLFallenDoll#1688]
丢失180新英格兰镑，变成-65了，现在新赞助的钱是不是就直接没了
Email：zuotangzhang@gmail.com
之前换绑过patreon账号，是不是因为这个原因

**Comment by TheSoulWizard** [comment]
@DiHongStar 您可能不再与 Patreon 账户关联。请打开游戏并点击右下角的按钮重新链接您的 Patreon 账户。链接后，您应该会通过游戏内邮箱收到它们。

如果之后您仍然遇到问题，请在我们的 Discord 上提交支持票。 https://discord.gg/projecthelius
