### ISSUE TITLE
[bug] 更新后丢失280NEP，重新绑定patreon也没用

### ISSUE THREAD

**Issue by lyn0530** [itsamewayu/OLFallenDoll#1693]
steamID：76561198367878382

**Comment by TheSoulWizard** [comment]
你目前绑定的账户没有捐款历史。请解除绑定您的账户，然后访问 patreon.com 确认您是否登录到了正确的账户。然后重新打开游戏，重新绑定您的账户。

如果您还有其他问题，请在我们的 Discord 上提交支持票。 https://discord.gg/projecthelius
