### ISSUE TITLE
更新之后丢失了英格兰比，重新绑定也没恢复

### ISSUE THREAD

**Issue by wwmy5990** [itsamewayu/OLFallenDoll#1694]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Win10/Ubuntu 20.04]
 - Game Version [e.g. 0.42]
 Complete the following Computer Hardware Configurations if necessary:
 - Processor(CPU): [e.g. i7-9700K]
 - Graphics Card:[e.g. RTX 2070s]
 - Memory:[e.g. 16GB]

*If your game crashed, remember to upload the dmp file with your issue.

It's located in C:\Users\ (USER ID) \AppData\Local\Paralogue

**Additional context**

**Comment by TheSoulWizard** [comment]
@wwmy5990 请先确保您登录了正确的 patreon 账户，然后取消绑定（不用担心警告信息）。

重新绑定后，您的游戏邮箱中应该会出现绿色票据。

如果您仍然遇到问题，请在我们的 Discord https://discord.gg/projecthelius 上提交支持票据。
