### ISSUE TITLE
[Graphics] Motion Blur Enabling

### ISSUE THREAD

**Issue by itsamewayu** [itsamewayu/OLFallenDoll#17]
Jovidian — Yesterday at 8:13 PM
Motion blur is on by default. To turn it off you must first re-enable it and then turn it off again. This resets every single time you start the game (screenshot is after fixing it, leaving game and restarting). Settings show Motion blur is set to OFF
![unknown](https://user-images.githubusercontent.com/11155504/143679515-2cf58f6c-a7ab-47f3-847d-59fa7ca3e0d8.png)
![unknown](https://user-images.githubusercontent.com/11155504/143679520-7a077223-c660-410c-b680-7426951d0639.png)

**Comment by jinjin525** [comment]
Issue No.42 : Also Unable to turn off V-sync.
Extra issue in Issue No.42 From TheSoulWizard:
Same with the v-sync. I'm unable to get over 60 FPS. They won't unlock. (its not my GPU)
