### ISSUE TITLE
Suspicious activity falsely detected, resulting in a ban

### ISSUE THREAD

**Issue by Eddy5646** [itsamewayu/OLFallenDoll#170]
**Description** 
When first accessing the game and attempting to enter the 'Harem' mode, immediately after loading begins, and error window will appear saying "Suspicious login activity detected. For account security purposes, your Harem Mode account has been temporarily suspended for 24 hours." As far as I am aware, I have not engaged in any activities that would be defined as 'suspicious'  

**To Reproduce** 
Open game and wait until title screen is loaded in. 
Select the 'Harem Mode' option. 
Error appears almost immediately after loading starts.  

**Expected behavior** 
Game loads into the Harem Mode  

**Screenshots** 
https://imgur.com/a/Oc7fFwx  

**Desktop (please complete the following information):**  
- OS: Windows 10  
- Version: 0.4.0

**Comment by Cryshah** [comment]
same here
first start of the game, and can't enter in harem mode

**Comment by yuezhenglingluan** [comment]
same here, trying to enter harem mode for the first time today and got a 24 hour ban, is on windows 11 22504.1010 and game version 0.4.0

**Comment by NEOLEE98** [comment]
same, 24 hours passed, another 24 hours ban

**Comment by junpieeh** [comment]
Same, another 24 hours, another ban for 24 hours.

**Comment by AQQQAAAqqq** [comment]
Same, another 24 hours, another ban for 24 hours.

**Comment by Zisors** [comment]
Same here, as junpieeh states, i have the same problem. 24 hours and now another 24 hours

**Comment by XHXJ** [comment]
I was banned for 24 hours for the same problem

**Comment by Cryshah** [comment]
solved for me today

**Comment by jinjin525** [comment]
Should be solved after 0.41. Please submit another issue if this happened again.
