### ISSUE TITLE
BUG 新英格兰镑丢失

### ISSUE THREAD

**Issue by lalakiop** [itsamewayu/OLFallenDoll#1705]
**Describe the bug**
未使用的情况下新英格兰镑变少
会自动解绑patron账户

*

**Comment by TheSoulWizard** [comment]
@lalakiop 请重新绑定您的 Patreon 账户，并查看游戏内邮箱中的绿色票据。自动解除绑定的错误已经修复。

如果您仍有问题，请在我们的 Discord https://discord.gg/projecthelius 上提交支持请求。
