### ISSUE TITLE
BUG NEP LOSS

### ISSUE THREAD

**Issue by doudoumie** [itsamewayu/OLFallenDoll#1709]
遊戲上的NEP變成了-310，更新前還剩下十幾

patreon當時綁定的賬號郵箱為384304518mie@gmail.com，因綁定的手機欠费被註銷，導致原先的賬號無法登陸，現換成了郵箱為384304518@qq.com的賬號，原先的賬號一共贊助了39USD,希望官方能把以前的贊助額度繼承到現在的郵箱為384304518@qq.com的賬號上

Steam ID：76561198197774830

![20240629023912](https://github.com/itsamewayu/OLFallenDoll/assets/111416769/ce4a0adc-32d9-4c63-9860-1b4d59fb823a)
![20240629023916](https://github.com/itsamewayu/OLFallenDoll/assets/111416769/fc4e402b-4eb9-4d6c-8e4b-5ebcd7c33a40)
![20240629023919](https://github.com/itsamewayu/OLFallenDoll/assets/111416769/f1aa7828-c90f-468a-b91c-4911ae581b9e)

**Comment by TheSoulWizard** [comment]
@doudoumie 我们无法将捐款历史从一个账户转移到另一个账户。

很遗憾，我们也无法处理与 Gmail 或 Patreon 相关的问题。您应该联系他们，看看他们是否可以更改该电话号码或解锁账户。

我们无法提供进一步的帮助，必须重新链接原来的 Patreon 账户。
