### ISSUE TITLE
[Harem]点击后宫模式后无限loading

### ISSUE THREAD

**Issue by SteakNatural** [itsamewayu/OLFallenDoll#171]
封闭测试版点击后宫模式后进入了超长时间的loading
如题，至今已loading了4个小时，仍然无法进入后宫模式的主界面

复现BUG

1，打开游戏，登陆至菜单
2，点击后宫模式，出现loading画面
3，至今仍然处于loading画面，已达4小时，已确认服务器为开启状态

桌面版 (请填写下列信息):
-操作系统：Windows10 R7-5000+RTX3060
-游戏版本：0.40

**Comment by ReBearRain** [comment]
我也遇见这个BUG，但是千万不要点取消，否则他很可能让你重新创建一个角色，目前没有找到继续使用以前角色的办法

**Comment by jinjin525** [comment]
已知的网络问题，正在着手修复中
