### ISSUE TITLE
[Sound][Experiment] Elizabeth's VO turns off after doing "Kiss" in Experiment 501

### ISSUE THREAD

**Issue by kumouri** [itsamewayu/OLFallenDoll#1729]
**Describe the bug**
In experiment 501 if you use the 2nd action "Kiss", Elizabeth stops making any noise.

**To Reproduce**
1. Start Experiment 501 (I tested on Archimedes Station)
2. Use the 2nd action
3. Observe Elizabeth no longer makes any sound

**Expected behavior**
After using the 2nd action Elizabeth's audio continues.

**Screenshots**

https://github.com/itsamewayu/OLFallenDoll/assets/1312174/9098a87c-2f7f-43c5-8fc7-106131ce430e

**Desktop (please complete the following information):**
 - OS: Win 10
 - Game Version 0.8.28a
 Complete the following Computer Hardware Configurations if necessary:
 - Processor(CPU): Threadripper 3970X
 - Graphics Card: RTX 4090
 - Memory: 192GB

*If your game crashed, remember to upload the dmp file with your issue.

It's located in C:\Users\ (USER ID) \AppData\Local\Paralogue

**Additional context**

**Comment by Awfulwaffle1** [comment]
Verified Fixed as of 0.8.4c build. Closing.
