### ISSUE TITLE
Progress Restarts

### ISSUE THREAD

**Issue by Jjunderdog** [itsamewayu/OLFallenDoll#173]
While trying to log in to the harem mode, it works. But after trying again after a few hours it restarts and makes me write a name and select what scenes/positions I’d like to receive, restarting everything I did. In conclusion I can’t play harem mode as it says that my username is already taken, and making a new name is a temporary fix as it ends up doing to the same thing after a few hours.

**Comment by jinjin525** [comment]
Duplicate of #154
