### ISSUE TITLE
Negative New England Pounds

### ISSUE THREAD

**Issue by IsekaiLife** [itsamewayu/OLFallenDoll#1731]
**Describe the bug**
I have negative money after i got on since its been a bit. I thought it was a visual change so i used an email to get 150 New England Pound but it was actually negative. I now have -1,226 money and need a refund of 2,602 to get to my original balance of 1,376.

**Screenshots**
![Screenshot 2024-07-02 234424](https://github.com/itsamewayu/OLFallenDoll/assets/49611892/7e7a1497-66c8-4510-bfec-d7b9e627df7d)

**Desktop**
 - OS: [Win 11]
 - Game Version [Latest]
 - Processor(CPU): [i7-8700K]
 - Graphics Card:[GTX 1080]
 - Memory:[16GB]

**Comment by TheSoulWizard** [comment]
@IsekaiLife You were probably unlinked from your patreon account. Click the [Link Patreon] button on the bottom right from in-game to relink your patreon account, then check the in-game mailbox.

If you still encounter issues, please make a ticket on our Discord https://discord.gg/projecthelius

**Comment by IsekaiLife** [comment]
@TheSoulWizard I did that and now have two mail with 1,376 each. But I'm minus 300 so ill need to make a ticket for that.
