### ISSUE TITLE
新英格兰磅消失成，负数

### ISSUE THREAD

**Issue by J-GZ** [itsamewayu/OLFallenDoll#1733]
有时间没登录，登陆以后发现绑定账号被解绑了，新英格兰磅也没有了，虽然本来也不多，但是成了负数感觉很不对劲
![账号ID](https://github.com/itsamewayu/OLFallenDoll/assets/174620660/2ef16bcc-b3a0-44df-9a27-b7bb828eef07)
![新英格兰磅](https://github.com/itsamewayu/OLFallenDoll/assets/174620660/91800793-b525-4a22-9e30-980a9e8a70a5)

**Comment by warlongxd** [comment]
被解绑了就重新绑定

**Comment by TheSoulWizard** [comment]
@J-GZ 查看上面的回复。一旦您重新链接您的 Patreon 账户，您将收到一封包含绿票的游戏内邮件。

如果您仍然遇到问题，请在我们的 Discord 上提交支持请求。https://discord.gg/projecthelius
