### ISSUE TITLE
【BUG】角色好感度无法升级，礼物无法赠送，阿蕾特-逆兔女郎显示有问题，鉴赏模式卡死

### ISSUE THREAD

**Issue by anyinmoe** [itsamewayu/OLFallenDoll#1734]
角色好感度无法升级，礼物无法赠送
![360截图20240704050730585](https://github.com/itsamewayu/OLFallenDoll/assets/52145941/d748f5d7-39c2-4474-afd3-792b3d7bff99)
阿蕾特的服装-逆兔女郎 显示缺失部件
![360截图20240704051008071](https://github.com/itsamewayu/OLFallenDoll/assets/52145941/01bba10a-1798-461f-88d2-89a9da1c2121)
主目录鉴赏模式点击就出现卡死

**Comment by warlongxd** [comment]
唉，玩游戏先看官群，好感度系统那个并不是bug是压根没有实装，接下来的版本才开始解封。一直有人问这个，但一直不看官方资讯

**Comment by Awfulwaffle1** [comment]
Affinity is now implemented and Alet's Reverse Bunny Outfit verified fixed as of 0.8.4c. Closing.
