### ISSUE TITLE
新英格兰币负数绑定被解除 邮箱1653820994@qq.com

### ISSUE THREAD

**Issue by 1653820994** [itsamewayu/OLFallenDoll#1735]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Win10/Ubuntu 20.04]
 - Game Version [e.g. 0.42]
 Complete the following Computer Hardware Configurations if necessary:
 - Processor(CPU): [e.g. i7-9700K]
 - Graphics Card:[e.g. RTX 2070s]
 - Memory:[e.g. 16GB]

*If your game crashed, remember to upload the dmp file with your issue.

It's located in C:\Users\ (USER ID) \AppData\Local\Paralogue

**Additional context**

**Comment by TheSoulWizard** [comment]
我们知道这个问题, 大约一周前的一个问题导致用户与 Patreon 解绑。一旦重新链接 Patreon，您将重新获得那些绿票。
