### ISSUE TITLE
[Harem][UI] Daily Tasks Bugged on returning to Harem Mode

### ISSUE THREAD

**Issue by KenyTaverous** [itsamewayu/OLFallenDoll#175]
Daily Tasks rotate through what appears to be other peoples' tasks. Happened after returning to title from Harem Mode while stuck in elevator. When returning to harem mode, Resume has replaced Start and the daily tasks while in the menu rotate through tasks which range from complete, partial complete, to no progress. Timer on daily tasks rotating out appears to be random. 

![image](https://user-images.githubusercontent.com/95321784/144146756-56e273bb-0aef-424d-824f-e85c5dde9aed.png)
![image](https://user-images.githubusercontent.com/95321784/144146829-2d7fb2d8-e609-4dc2-88da-a1a4b22ad474.png)
![image](https://user-images.githubusercontent.com/95321784/144146879-ea8326a2-7320-4c5e-b4de-4522ece15851.png)

**Comment by jinjin525** [comment]
·Fixed the issue of daily tasks automatically refreshing on their own.
Should be fixed in 0.42. Submit again if not fixed.
