### ISSUE TITLE
[UI]Main Menu Distortion

### ISSUE THREAD

**Issue by Awula** [itsamewayu/OLFallenDoll#176]
Alterating quickly between the harem mode and the title screen broke the menu on the initial title screen. [<a href="https://imgur.com/mPZIWuV"><img src="https://i.imgur.com/mPZIWuV.png" title="source: imgur.com" /></a>](url)

**Comment by scocansa** [comment]
This could be fix by going to Glassic mode then return to title.

**Comment by jinjin525** [comment]
From Eddy5646 in issue #262 
When attempting to join the free roam area in Harem mode, the game fails to join in.

Initially after failing, the game return to the Harem mode main menu screen - if an attempt to start the free roam again, you will be sent back to the game's main menu screen with it appearing somewhat distorted from normal (see image).

When attempting to rejoin Harem mode from here, it will load into the Harem Mode Main Menu, however the text for the 'Start' button will be replaced with 'Resume.'

Clicking on the newly renamed 'Resume' button I believe just sends you back to the game's main menu, with the distortion as seen in the image (my memory is a bit foggy on this, it may send you to the free roam setup screen, and form there it sends you back to the game's main menu). This process can be continued as an infinite loop.
