### ISSUE TITLE
[UI] WIP/old UI appears instead of current

### ISSUE THREAD

**Issue by KenyTaverous** [itsamewayu/OLFallenDoll#177]
A WIP UI/old UI appears to show up after entering harem mode and returning to title screen several times consecutively. Have not been able to successfully recreate the bug.

![image](https://user-images.githubusercontent.com/95321784/144148194-abe5195d-6c2e-420e-ba77-04f0d9064456.png)

**Comment by jinjin525** [comment]
Duplicate of #176
