### ISSUE TITLE
Alet脚部模型丢失

### ISSUE THREAD

**Issue by Xmihus** [itsamewayu/OLFallenDoll#1783]
alet在穿着学院制服内裤的时候穿丝袜会导致脚部模型的丢失
![屏幕截图 2024-07-20 195303](https://github.com/user-attachments/assets/e44ae7a9-c77f-4752-8793-5816181ce67b)
![屏幕截图 2024-07-20 195330](https://github.com/user-attachments/assets/d5d4ee79-82ef-4a73-a901-625c5ab1a06e)
![屏幕截图 2024-07-20 195337](https://github.com/user-attachments/assets/adbbbb37-6302-4444-8462-77250450d1e1)

**Comment by Awfulwaffle1** [comment]
Verified fixed as of 0.8.4c. Closing.
