### ISSUE TITLE
阿蕾特服装显示异常

### ISSUE THREAD

**Issue by jamesmccree9** [itsamewayu/OLFallenDoll#1787]
**Describe the bug**
![图片](https://github.com/user-attachments/assets/a45e299e-b38a-4206-96df-fca9ea0d8d05)
阿蕾特衣服显示异常

**Desktop (please complete the following information):**
 - OS: Win11 Pro
 - Game Version 最新版本
 Complete the following Computer Hardware Configurations if necessary:
 - Processor(CPU): i7-8700K
 - Graphics Card: RTX 2080Ti
 - Memory: 32GB

**Additional context**
只有这一件衣服显示异常，其他的都能正常显示，另外我的驱动是安装的英伟达560版本

**Comment by Awfulwaffle1** [comment]
Verified fixed as of 0.8.4c build. Closing
