### ISSUE TITLE
[UI] Incorrect character classification in experiment details

### ISSUE THREAD

**Issue by apugo** [itsamewayu/OLFallenDoll#179]
If you go into the Main Menu > Experiments menu, you can see that some experiments are listed under the wrong girl.

Screenshots: 
[https://i.imgur.com/L3x7yT4.png](https://i.imgur.com/L3x7yT4.png)
[https://i.imgur.com/L3x7yT4.png](https://i.imgur.com/Jnx2fNk.png)

Some, such as Doggystyle Massage, actually appear under _both_ tabs, and I obtained them twice without it being flagged as a duplicate.

**Comment by jinjin525** [comment]
Duplicate of #113
