### ISSUE TITLE
[Ver 0.8.28a][Model]Anya's DVORYANSTVO's HANDMAID: BRA breakthrough model under certain conditions安雅王公侍女胸罩特定条件下穿模

### ISSUE THREAD

**Issue by ShinnZhang** [itsamewayu/OLFallenDoll#1800]
**Describe the bug**
安雅的王公侍女：胸罩在与教导主任：夹克叠穿，且夹克半脱的情况下会穿模。
Anya's DVORYANSTVO's HANDMAID: BRA will breakthrough model if worn with the Dean of student: Jacket and the jacket is half dressed.

**Expected behavior**

**Screenshots**

![FallenDoll   2024_7_25 23_18_33](https://github.com/user-attachments/assets/ccd68595-ae9e-4ecb-9a14-6ea0ffb9f2a0)

**Comment by Awfulwaffle1** [comment]
Tried the combination above and is working as of 0.8.4c. Marking resolved and closing.
