### ISSUE TITLE
ankle is see-through

### ISSUE THREAD

**Issue by seventhstar91** [itsamewayu/OLFallenDoll#1803]
When wearing nurse's uniform stockings and school uniform underwear pants at the same time, the ankle is see-through

![스크린샷 2024-07-27 094301](https://github.com/user-attachments/assets/d651ce50-34aa-4907-a7de-024512514651)

**Comment by Awfulwaffle1** [comment]
Alet's Nurse Outfit is displaying properly now as of version 0.8.4c. Closing.
