### ISSUE TITLE
Missing textures on one of Alet's outfits

### ISSUE THREAD

**Issue by richardgooden** [itsamewayu/OLFallenDoll#1806]
**Describe the bug**
The lower part of the "reverse bunny girl outfit" for Alet is missing textures

**To Reproduce**
1. go to harem mode and select character from the menu, 
2. select alet
3. change her outfit to "reverse bunny girl"
4. also happens if outfit is worn while on the station or in the nightclub

**Expected behavior**
The outfit should look like the preview image.

**Screenshots**
![Paralogue Screenshot 2024 07 28 - 22 34 21 91](https://github.com/user-attachments/assets/cc486b7d-6f2c-42f8-be2d-2665f7f36d6b)
![Paralogue Screenshot 2024 07 28 - 22 47 31 53](https://github.com/user-attachments/assets/85c0c91c-9fb2-4f66-99ef-f4194aa73b93)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Game Version : 0.8.28a
 Complete the following Computer Hardware Configurations if necessary:
 - Processor(CPU): ryzen 5 4000 series
 - Graphics Card: gtx 1650 4gb vram
 - Memory: 32GB

**Additional context**
None

**Comment by Awfulwaffle1** [comment]
Verified Fixed as of the 0.8.4c build. Closing.
