### ISSUE TITLE
[model] Lower Apparel not visible in the Reverse Bunny Girl outfit

### ISSUE THREAD

**Issue by MikuAlice** [itsamewayu/OLFallenDoll#1815]
**Describe the bug**
The Lower Apparel for Reverse Bunny Girl is invisible.

**To Reproduce**
1. Go to Harem
2. Click on Alet's Research Pass
3. Scroll down to Level 35 Reverse Bunny Girl Outfit

**Expected behavior**
The outfit should be visible

**Screenshots**
![outfit_bug](https://github.com/user-attachments/assets/a24ab84d-7688-4bd3-b4ea-04bee9c1c880)

**Desktop:**
 - OS: Win11
 - Game Version 0.8.28a

 - Processor(CPU): AMD Ryzen 9 7950X3D
 - Graphics Card: RTX 4070 Ti
 - Memory: 64G

**Comment by Awfulwaffle1** [comment]
Fixed as of 0.8.4c. Marking Resolved and closing.
