### ISSUE TITLE
[Textures] Random drops to low quality

### ISSUE THREAD

**Issue by Ieaq** [itsamewayu/OLFallenDoll#183]
**Describe the bug**
While playing harem mode, the textures of both male and female actors will sometimes drop from the high quality I have them set to, to a very low quality. 

**To Reproduce**
1. Launch and play harem mode
2. Textures randomly change - can't find a replicable cause.

**Expected behavior**
No change in texture quality.

**Screenshots**
Low quality textures
https://i.imgur.com/0JbokiX.jpeg
https://i.imgur.com/30kF73d.jpeg

**Desktop (please complete the following information):**
 OS Name	Microsoft Windows 10 Home
Version	10.0.19042 Build 19042
Processor	AMD Ryzen 5 5600X 6-Core Processor, 3701 Mhz, 6 Core(s), 12 Logical Processor(s)
GPU RTX 3070

**Comment by johnathandarkly** [comment]
happens to me as well after i've been in game for around 20 minutes, sometimes self-resolves. 
i7 4790k with nvidia rtx 2060 super with 8gb ram. win 10.

**Comment by jinjin525** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=2672086352
Try this before the problem got fixed

**Comment by jinjin525** [comment]
From koulouria in issue #349
In harem mode whenever I move either my character or camera text on walls, graphics and some objects, and characters bodies turn blurry like the resolution got lowered. Some textures seem to have no problem... The issue is only present in harem mode. In gallery mode everything works well.

**Comment by koulouria** [comment]
Hmm... so I have noticed that the textures work normally with max 3-4 in the lobby. When another player joins, the textures drop in quality.
