### ISSUE TITLE
0.8.4阿蕾特的BUG

### ISSUE THREAD

**Issue by Naodail** [itsamewayu/OLFallenDoll#1854]
1.阿蕾特的丝袜穿模
2.阿蕾特的丝袜没有厚度选项
3.阿蕾特的头部乱摆动
4.阿蕾特的丝袜会莫名其妙消失
以下是截图:

![8d4144f647098236b111f21da7377412](https://github.com/user-attachments/assets/bd7afdf4-7e38-4049-b7ba-dd2ce8769bb8)
![15414f5817d2e6e9aa40637637a1ff0c](https://github.com/user-attachments/assets/9bafca74-3b4c-466e-b22b-a5561ac400e6)
![2016fff02ac59793f71d50e28948a8da](https://github.com/user-attachments/assets/a76eb211-6834-44d0-be64-cacfe5bd0691)
![76cabaacb1b1923d1983e4b2517256e5](https://github.com/user-attachments/assets/b07ae724-9f82-4f46-b290-341591eaf17b)
![1aac4581d54b094cfc92999fbf01178c](https://github.com/user-attachments/assets/f120b7cd-d9db-4df3-bc9a-0174dbf279c4)
![a94091fdafd791a8f1817b913d45ad60](https://github.com/user-attachments/assets/70572288-37b3-4657-8ee5-f290b746bcd9)

**Comment by Awfulwaffle1** [comment]
Looks fixed as of 0.8.4c. Closing.
