### ISSUE TITLE
调整指甲颜色时，无论是否勾选”与手指甲颜色一致“都会同时改变手指甲和脚趾甲的颜色。

### ISSUE THREAD

**Issue by Iishinji** [itsamewayu/OLFallenDoll#1858]
调整指甲颜色时，无论是否勾选”与手指甲颜色一致“都会同时改变手指甲和脚趾甲的颜色

**Comment by Awfulwaffle1** [comment]
Working as intended on the 0.8.4c build. Verified Fixed and closing.
