### ISSUE TITLE
Unable to associate patreon-无法关联patreon 

### ISSUE THREAD

**Issue by 449693691** [itsamewayu/OLFallenDoll#1861]
Hello, after I clicked on the associated patreon within the game, the URL that pops up is inaccessible 404, I checked the network and it's normal.
您好，游戏内我点击关联patreon后，弹出的网址无法访问404，我检查了网络，是正常的。

The URL of the pop-up page is as follows:
弹出的网页网址如下：
https://[v2-prod-ap-east-1.heliusapi.com/platform/v1/link/link&scope](https://v2-prod-ap-east-1.heliusapi.com/platform/v1/link/link&scope)
404 page not found
[
![QQ20240815-161843](https://github.com/user-attachments/assets/3475434d-ffdc-46e2-856d-d8b96b88c942)
](url)

Steam ID：76561199758206039
patreon：yibuxiaoxinjiubani@gmail.com

**Comment by Awfulwaffle1** [comment]
Verified account linked on 08/18. Closing.
