### ISSUE TITLE
无法关联Patreon

### ISSUE THREAD

**Issue by h975236069** [itsamewayu/OLFallenDoll#1869]
您好，我点击了游戏中关联的patreon后，弹出的URL是无法访问的404，我检查了网络，一切正常。
您好，游戏内我点击关联patreon后，弹出的网址无法访问404，我检查了网络，是正常的。

弹出页面的URL如下： 弹出的网页网址如下：
https:// [v2-prod-ap-east-1.heliusapi.com/platform/v1/link/link&scope](https://v2-prod-ap-east-1.heliusapi.com/platform/v1/link/link&scope)
404 page not found
steamID：76561199471336157
Patreon账户：975236069@qq.com

**Comment by Awfulwaffle1** [comment]
Verified account is bound 08/17. Closing.
