### ISSUE TITLE
[UI][Harem] Temporary Insanity bug

### ISSUE THREAD

**Issue by MarkOneUp** [itsamewayu/OLFallenDoll#187]
first time logging into Harem mode set up username and loaded in and was instantly set to temporary insanity without actually playing in the experiments and tells me i have to wait for the 24hrs to pass for it to reset. don't know how to replicate this bug

**Comment by AltairPL** [comment]
Same here - first Harem login, 0 Sanity from the get go and need to wait 18:30 for recovery
