### ISSUE TITLE
[Program] 无法从空间站退出到大厅

### ISSUE THREAD

**Issue by xkww3n** [itsamewayu/OLFallenDoll#1873]
**Describe the bug**
从空间站打开菜单，选择“退出到大厅”，短暂显示大厅画面后会再次进入空间站电梯。

**To Reproduce**
1. 登录“后宫模式”>“空间站”
2. 按 ESC 键打开菜单
3. 点击“退出到大厅”
4. 首先会出现一部分渲染错误的空间站电梯场景，稍后才显示大厅画面
5. 大厅画面短暂显示后，会再次出现登录动画，进入空间站电梯场景

**Expected behavior**
应当正常返回到大厅。

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: Windows 11 Insider Preview 24H2 (Canary channel, 26257.5000)
 - Game Version 0.8.4
 Complete the following Computer Hardware Configurations if necessary:
 - Processor(CPU): i7-17500H
 - Graphics Card: NVIDIA Geforce RTX 4060 Laptop
 - Memory: 16 GB

**Additional context**
刚登录游戏时基本不会出现，唯在游玩一段时间后再进入空间站会频繁出现，重启游戏后又会正常一段时间。

**Comment by Awfulwaffle1** [comment]
Verified fixed as of 0.8.4c. Closing
