### ISSUE TITLE
Unable to associate patreon-无法关联patreon

### ISSUE THREAD

**Issue by huifeideyuli** [itsamewayu/OLFallenDoll#1880]
404 page not found？

PATERON：fyuli0629@gmail.com
steam ID：76561198250392892

**Comment by jjsiswellerj** [comment]
The sam problem, 
PATERON : jingjiasheng1@gmail.com STEAM ID: 76561199366871854

**Comment by sbn34** [comment]
Same problem
**PATERON:** Mauricio.Parraguez.V@gmail.com
**Steam ID:** 76561198151430303

Shows message: link request params err :playerId is nil or code is nil.

**Comment by Sadust-FD** [comment]
Same problem
PATERON: 1261726498@qq.com
Steam ID：76561198364358553

**Comment by asejdi** [comment]
同样的问题
PATERON：424050237@qq.com
Steam ID：76561199218918402

**Comment by Awfulwaffle1** [comment]
Issue should be resolved now. Closing.

**Comment by catgrandfa1458** [comment]
PATERON：woaini14583658@gmail.com
Steam ID：7656119910633971

**Comment by catgrandfa1458** [comment]
同样的问题
PATERON：woaini14583658@gmail.com
Steam ID：7656119910633971

**Comment by bigboyyb** [comment]
同样的问题
PATERON：bigboyyibo@gmail.com
Steam ID：76561199585138897
