### ISSUE TITLE
Experiments clipping & not placable

### ISSUE THREAD

**Issue by maxjonas3d** [itsamewayu/OLFallenDoll#1894]
Experiment 408 _couldnt be placed. Nothing happened and pressing E gave the game a stutter, pressing E again brought up the Experiment selection again._

Eperiment 437 _had some clipping of the Vag. Tentacle through the belly when Celia Orgasms._

 - OS: Win10
 - Game Version Latest update on 16.08.02024
 Complete the following Computer Hardware Configurations if necessary:
 - Processor(CPU): Ryzen 9 7950X
 - Graphics Card:[e.g. RTX 3090 Vision OC (Gigabyte)
 - Memory: 32GB DDR5

**Comment by yuanyuankuang** [comment]
![image](https://github.com/user-attachments/assets/ac858bde-78bb-4795-a555-58c27d79181b)‘Experiment 408 couldnt be placed’，may be something wrong with network .
