### ISSUE TITLE
可以把Galatea做成离线补丁吗

### ISSUE THREAD

**Issue by ExcaliburHUN** [itsamewayu/OLFallenDoll#190]
如题。个人很喜欢Galatea这个角色的建模，希望能够通过补丁把角色加入游戏。。

**Comment by jinjin525** [comment]
开发组已经对Galatea的上线方式基本确定了:
Galatea 将在游戏测试结束（Playtest）后加入游戏（如果 Steam 觉得OK）虽然Galatea在游戏测试期间也可能会加入，主要看 Steam 的心情。
