### ISSUE TITLE
[Gameplay Bug][Harem] Special QTE Interaction with Ecstasy Meter

### ISSUE THREAD

**Issue by AvalonDelta** [itsamewayu/OLFallenDoll#191]
**Describe the bug**
Erika's Held up Anal Tentacle Pose will stop generating Ecstasy after the quick time event (where you click the monster during the 5 second QTE to increase pleasure). The special animation will play, the sensitivity meter will rise, but **Both male and female ecstasy meter will deplete as if the scene has stopped, even while the scene is playing** The player will have to pause and resume the pose to reset the meter gain.

**To Reproduce**
1. Go to Erika's Held up Anal Tentacle Pose
2. Wait for the 5 second quick time event and click the tentacle to increase special
3. Ecstasy meters for both male and female stops increasing and starts depleting.
4. Restart pose to reset ecstasy meter gain
5. Reproduction rate 100% in 5 attempts

**Expected behavior**
Ecstasy meter continues increasing after sensitivity special quick time event

**Screenshots**
Can't screenshot the meter behaviour.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser NA
 - Version [e.g. 0.4.0]

**Smartphone (please complete the following information):**
NA

**Additional context**
Have not tested if this issue is present on other positions.

**Comment by HalcyonAnd0n** [comment]
Confirming that this is still an issue in version 0.4.5. Video attached of the meters dropping after activating the special action during this experiment:

https://user-images.githubusercontent.com/95422572/147608699-2d71bee0-fcc1-473f-82af-d8be0ceb2f88.mp4
