### ISSUE TITLE
Easy Anti-Cheat Not Installed

### ISSUE THREAD

**Issue by Reiffi** [itsamewayu/OLFallenDoll#193]
When I try to launch Operation Lovecraft. The launcher opens up with no issue and it shows the Easy Anti-Cheat logo on the bottom. The load bar goes from 0-100% and when the game is ready to launch, it fails and says "Easy Anti-Cheat not installed." I went to the game file and found that it is installed. But for some reason the game thinks it isn't. 

![EAsy Anti-Cheat Loading](https://user-images.githubusercontent.com/95348680/144219895-ba513831-3106-407e-9764-e55a1cb3eeb9.png)

![Failed](https://user-images.githubusercontent.com/95348680/144219955-7c0a6478-cf16-4926-837a-d2aa39fb4473.png)

![Easy AntiCheat Installed](https://user-images.githubusercontent.com/95348680/144220002-bd19dad2-de69-4aec-a985-7298ad1d458c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home 64bit
 - Browser Opera GX

**Comment by LengSicong** [comment]
I have the same problem

**Comment by Tunets92** [comment]
I'm also facing the same problem. I followed the guide in the discord and clicking on the EasyAntiCheat Setup did nothing, even when running as an administrator.

- OSL Windows 10 Pro
- Browser: Chrome

**Comment by jinjin525** [comment]
Same issue from Tunets92 in issue #356

**Comment by giant73** [comment]
![image](https://user-images.githubusercontent.com/20339840/145360969-e570feb5-6380-4f39-a3b9-024049d9cc57.png)
Try running this script

**Comment by LengSicong** [comment]
> 

It doesnt work

**Comment by Tunets92** [comment]
> ![image](https://user-images.githubusercontent.com/20339840/145360969-e570feb5-6380-4f39-a3b9-024049d9cc57.png) Try running this script

That fixed it! Thanks man!

**Comment by HY-SANG** [comment]
Hi, the problem persists even after clicking installation.bat. Antivirus has been turned off. Any suggestions?
![image](https://user-images.githubusercontent.com/40254550/148612588-c3034c4d-3cc4-4135-843a-59a4e0e9497e.png)

**Comment by Dec106** [comment]
Hi, anyone have an update ? I also tried running the script and it still doesn't work.
