### ISSUE TITLE
Suspicious activity falsely detected, resulting in a ban

### ISSUE THREAD

**Issue by AQQQAAAqqq** [itsamewayu/OLFallenDoll#194]
Description
进入游戏，点击后宫模式，提示异常登陆账号封禁24小时
To Reproduce
每次都会发生
Expected behavior
进入后宫模式
Desktop (please complete the following information):
win 10 
0.40

**Comment by godsplan36** [comment]
yesterday i downloeaded the demo version and activated the key i got from my patreon account, but when i tryed to log on a small chat box apperes whitch in it says that my accaount was temperaly suspended in 24 hours, so i thought to my self it might be som A hole who tryed to hack is way in, but to this day im still suspended, so i was hoping for you could help me.

**Comment by IlySmall** [comment]
Also seem to be experiencing the same issue thus far.

**Comment by jinjin525** [comment]
Should be fixed in 0.41. Please submit another issue if this happens again
