### ISSUE TITLE
I am not sure what sort of issue this is...

### ISSUE THREAD

**Issue by Dendrobatus** [itsamewayu/OLFallenDoll#195]
haram mode, human only
![image](https://user-images.githubusercontent.com/9326605/144229007-e6c5358c-a144-47d0-a846-29d9201a6ad5.png)

**Comment by jinjin525** [comment]
Seems like something related with outfit/sex scene. Try changing the scene or outfit. And please provide more detailed information including how this happens.

**Comment by backtoChaos** [comment]
Please excuse me for currently not being able to replicate this in the new release. I will sure report back should I encounter this again.
