### ISSUE TITLE
[Clipping] - Anya Scientist Outfit

### ISSUE THREAD

**Issue by itsamewayu** [itsamewayu/OLFallenDoll#20]
科考队紧身衣
![unknown](https://user-images.githubusercontent.com/11155504/143679639-59927193-fbe7-46f7-9ca4-218a1fc51e56.png)

![unknown](https://user-images.githubusercontent.com/11155504/143679645-b533a9bb-f245-46d5-9bd3-c24a15d57878.png)

**Comment by ombra1501** [comment]
this is normal behavior. doesn't need fixing
