### ISSUE TITLE
[Gameplay] Fever time pressing special action does nothing

### ISSUE THREAD

**Issue by Jimto1** [itsamewayu/OLFallenDoll#200]
**Describe the bug**
When the girl reaches fever time pressing special action will not bring up the mouse prompt, and if it does nothing happens. Happens 75-90% of the time 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to any pose / event
2. Wait for fever time 
3. Press the special action button
4. nothing happens or if mouse does change then nothing happens on click

**Expected behavior**
An animation and the sensitivity increased

**Screenshots**
N/a 

**Desktop (please complete the following information):**
 - OS: Windows 10

 - Version beta release pre patch

**Additional context**
I think it might prove better to have an indication of what the player has selected - the couple/scene or the environment to pan the camera Maybe that would help this moment.

**Comment by SpamFilter9k** [comment]
Also noticed this one.

Happens to me when the cursor generally stops changing its appearance. For example when it stays the default cursor even if i'm changing the pose by dragging on the girls body.
As soon as i get the normal cursor behaviour back, pressing 1-3 starts working again.

Also when 1-3 doesn't work, just clicking on the right place still works. For example when pressing 1 would do a butt slap but doesn't work, it works for me 100% as soon as i find the right place to click on the butt.

**Comment by johnathandarkly** [comment]
I still routinely get this bug post patch. Works pretty good a few times, then less and less reliably. Sometimes no cursor change, sometimes the closed hand with multiple circles, and can either be red or white, but almost always no effect.
