### ISSUE TITLE
"Neo-England Bucks" Special Currency at Balance of -$250

### ISSUE THREAD

**Issue by Selvles** [itsamewayu/OLFallenDoll#2009]
After one of the last 2 updates (I apologize but cannot remember specifically), the special currency I possessed is now marked negative. I hadn't touched it in a while, and have had no success in trying to fix it for a while.

I attached a picture, but I don't think it will be of much use.

Thank you!

- Using Windows 10
- Current version as of posting

![OLFD money pic](https://github.com/user-attachments/assets/f3c8f897-80de-4336-bed2-28439815384d)

**Comment by yiwu0b11** [comment]
try to unlink and relink patreon using the button at bottom-right

**Comment by Selvles** [comment]
Worked, thanks for responding
