### ISSUE TITLE
[UI] Sanity start above 100 after reset

### ISSUE THREAD

**Issue by SpamFilter9k** [itsamewayu/OLFallenDoll#202]
**Describe the bug**
After sanity gets fully used and it resets, it starts above 100

**To Reproduce**
1. Use all your Sanity
2. Play a bit more
3. Wait offline for the sanity reset to happen

**Expected behavior**
Sanity should never be above 100

**Screenshots**
![image](https://user-images.githubusercontent.com/95370798/144275756-9a35cb08-f159-4fa1-b741-ba15e36f9164.png)
![image](https://user-images.githubusercontent.com/95370798/144275812-b24341d1-2e38-4aac-9623-c146b7bc21e3.png)
![image](https://user-images.githubusercontent.com/95370798/144279975-91343e9d-5f96-47d9-9205-1d1c29c90b60.png)

**Additional Information**
This happened after my first reset. I'll give updates on the behaviour of future sanity resets.

**Comment by Marlo2106** [comment]
I think this is wanted. Like when you get 2k each month, but you only use 1.8k. you dont loose the 200 dollars that are left. For the next month you will have 2.2k instead couse you saved some from the month before.

**Comment by SpamFilter9k** [comment]
Thing is, i consumed it to 0 before the reset.

**Comment by Keiki-FD** [comment]
If you check the tooltip on your level (crown icon) it says maximum sanity increases alonside your lvl. You start at 100 on lvl1, so 104 at lvl5 looks fine i think. Maybe the only bug here is that the maximum stays at 100. Would be more logical to show 104/104 aftert the reset.

**Comment by SpamFilter9k** [comment]
Didn't see that. That makes total sense. Closing this Ticket.
