### ISSUE TITLE
Error Message: "gpu device lost" when ejaculating on the outside

### ISSUE THREAD

**Issue by Justify87** [itsamewayu/OLFallenDoll#205]
Title says it all. Cant believe I'd ever type such a sentence.
Leads to a unresponsive game and a refresh of my whole desktop and all open programs.

**Comment by jinjin525** [comment]
Not enough information. Try to update your GPU driver. Also please provide more info about your computer/OS and other stuff including if this happens everytime on any ejacluating scene.

**Comment by jinjin525** [comment]
Not sure if you got the same issue as #207 mentioned
