### ISSUE TITLE
We all are stuck in elevator since 13.00 a.M. UTC+1

### ISSUE THREAD

**Issue by EnvilsXx** [itsamewayu/OLFallenDoll#206]
**Describe the bug**
All steam player are stuck in the elevator since 13.00 a.M. UTC+1.
We can't see the character.

**To Reproduce**
1. Go in menu
2. Click on AREM mode
3. Login

**Comment by Dragonextinction** [comment]
Same issue clicking on F1  doesn't get me anywhere and can't see Alet.   Also my cursor disappears at times

**Comment by jinjin525** [comment]
Net work issue already being worked with. Cursor disappearing also submitted.

**Comment by Dragonextinction** [comment]
Thanks I was able to get in ok last night. You aren’t the only one FF14 early access has been a mess network wise.
