### ISSUE TITLE
[Performance] DUO climax causing soft-lock

### ISSUE THREAD

**Issue by PervertUnited** [itsamewayu/OLFallenDoll#207]
**Describe the bug**
When I started, I started temporarily insane and while playing when sanity returns, couldn't exit experiment mode and lost it all when force closing game without getting any progression after soft-lock occurs post climax. Testing further, soft-lock happens when you make both parties duo climax. While trying gallery, the clothes actually transfer to harem mode. I also noted that when trying gallery, the character loses sanity when transferring to harem mode with clothes from gallery mode.

**To Reproduce**
1. Play Gallery mode
2. Change clothes
3. Log into Harem mode
4. Unobtained clothes are on and sanity is lost immediately.
5. Play Harem mode
6. Attempt to DUO climax
7. Soft-locked from exiting without force closing

**Expected behavior**
Harem mode resets insanity properly after time resets. Exiting after experiment should result in some progress in chosen female models. Should be able to view classic without having unobtained clothes transferring to harem mode and loss of sanity as if played in harem mode.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version: Closed Beta Harem

**Comment by PervertUnited** [comment]
Wish you all the best of luck and understand that things take time to fix. Hope you all have a wonderful holiday and thank you for the amazing game, you legends.

**Comment by jinjin525** [comment]
Temporarily insane being submitted already.
Soft-lock post climax will be noted.
Clothes transfering should be fixed in 0.42
