### ISSUE TITLE
Why is my New England pound negative?

### ISSUE THREAD

**Issue by Kuroki79** [itsamewayu/OLFallenDoll#2079]
![image](https://github.com/user-attachments/assets/6284ffdc-4b79-4a1a-a54f-6b3f68aa2b1a)

As shown in the image, why is my New England pound minus 400?
如图，为什么我的新英格兰镑是负400？

**Comment by TheSoulWizard** [comment]
Check if you are still linked to patreon.

**Comment by Kuroki79** [comment]
I see, after I linked my Patreon account, it was normal to receive the reward in the mailbox.
