### ISSUE TITLE
[Gameplay] daily tasks

### ISSUE THREAD

**Issue by fduser2** [itsamewayu/OLFallenDoll#209]
Issue: Only the 1st of the three daily tasks reset. The other two are still on yesterday's completed task.

**Comment by fduser2** [comment]
![image](https://user-images.githubusercontent.com/95328775/144339919-c643b15a-acbd-454a-8df2-e56feca202bc.png)

**Comment by HalcyonAnd0n** [comment]
Confirming this also happened to me. First daily task reset, last two did not.:

**Comment by fduser2** [comment]
![image](https://user-images.githubusercontent.com/95328775/144458199-c952686b-6b1c-4e3d-ba50-04910c11904a.png)
![image](https://user-images.githubusercontent.com/95328775/144458267-12394660-6034-4c5b-a02a-d6ef93cef220.png)

tasks now keep changing on the harem mode menu. None of them are progressing

**Comment by Myztklkev** [comment]
on tuesday I completed 2 of 3 dailies, the one in the middle got stuck at 1, I rerolled and that one got stuck at 1. I didn't play all day yesterday and today (thursday) I still have all the same dailies: 2 completed and middle one stuck at 1/5. just to confirm, I had 2 dailies in the middle spot get stuck at 1/5

**Comment by jinjin525** [comment]
Daliy Task will only refresh 1 each day. That's not an issue.
Daliy Task Stuck duplicated.
