### ISSUE TITLE
[UI] Languages Missing?

### ISSUE THREAD

**Issue by itsamewayu** [itsamewayu/OLFallenDoll#21]
🌟₮₭Ⱨ0̷3̷9̷5̷✨ — Yesterday at 8:36 PM

language options limited
also plz differentiate traditional chinese with simplified chinese, i remember this is also a problem in 0.34
after choosing traditional chinese in desktop
going into vr and choosing language again dont wont let u choose traditional chinese after u choose something else
![unknown](https://user-images.githubusercontent.com/11155504/143679667-959324f6-ca7a-4392-8cc6-b3c7294bcde7.png)

**Comment by TheSoulWizard** [comment]
Fixed in 0.4.5
