### ISSUE TITLE
[Update 0.8.5][research point]Research point settlement system isn't working.

### ISSUE THREAD

**Issue by C3RBERU2** [itsamewayu/OLFallenDoll#2114]
- Only thing I know it my celia pass now it's at LV39 41/100
- After learning from other people it didn't +10 in the research pass
- My steam id: 76561199511134675

https://github.com/user-attachments/assets/37ce9724-9ef2-45b2-b833-e9b7ebbd1265

**Comment by Kuckich** [comment]
it turned out that after zeroing out the weekly progress, you can raise the experience only with the help of daily tasks, no one has found a solution to the problem yet.
