### ISSUE TITLE
Hearing activation "click" sound constantly in background

### ISSUE THREAD

**Issue by Selvles** [itsamewayu/OLFallenDoll#2121]
The light 'click' sound that comes from selecting a button, sending a like to another player, etc. is sporadically happening with no apparent source. I've been paying attention to the public notifications, leaving and rejoining a server, and several other player-side attempts to fix this with no change, and I still can't tell what is causing it. As far as I can tell, the clicking happens with no provocation from my actions, and happens arbitrarily for the entire duration of my time spent playing, even in the crew quarters.

Thank you for your time, I'm sure your team has been busy.

OS: Windows 10
Game Version: Most recent update for closed beta at time of post (I apologize I don't know)
CPU: AMD Ryzen 5 3600 6-core
Graphics Card: Radeon RX 580
Memory: 32GB

**Comment by awingloong** [comment]
@Selvles Please record a video for a period of time.We can detect it.

**Comment by Selvles** [comment]
I opened the game up today, and the clicking mysteriously vanished. I feel like an asshole that wasted your time, for which I apologize, but I can't give you video footage now.

**Comment by awingloong** [comment]
@Selvles If you find any problems, please commit them to git. Thanks.
