### ISSUE TITLE
[Bug report----进入后宫模式后显示异常登入 封禁24小时]

### ISSUE THREAD

**Issue by TonnyYao123** [itsamewayu/OLFallenDoll#213]
**Describe the bug**
When I install the beta close version of the Operation lovecraft, I launch the game.
When I get to the main page, after I click the Harem Mode, there is a message alert "Suspicious activity, account banned 24 hours". No VPN or orthers

下载封测版本后，打开游戏 ，进入主界面，点击后宫模式，短暂加载过后，弹窗信息“账号登录操作异常，24小时封禁”，无VPN或者加速器 

**To Reproduce**
1. Launch the beta version
2. Get the "main page"
3. Click on 'Harem Mode'

1.打开beta封测版本游戏
2.进入”主菜单“
3.点击“后宫模式”
4.看见消息弹窗

**Expected behavior**
A clear and concise description of this situation and its solution
Hopefully, it would be solve tomorrow.

请提供可能造成此问题的原因描述以及解决方案 避免日后再次出现
希望明天能够正常游玩后宫模式

**Screenshots**
![Screenshot 2021-12-02 014324](https://user-images.githubusercontent.com/62497094/144367215-a072626e-bd09-4024-ac10-bf3f876cd642.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Microsoft Edge]
 - Version [0.4.0] --- The steam key only provide this version for installing

系统: Windows 10
版本: 0.4.0 (steam激活码当时唯一提供的版本)

**Additional context**
HOPEFULLY, this problem can be solved as soon as possible
希望这个问题能够被尽快解决 谢谢

**Comment by jinjin525** [comment]
Should be fixed in 0.41. Please resubmit the issue if this happens again, thanks.
