### ISSUE TITLE
When Clicking HAREM mode loading is infinite (2days of tries)

### ISSUE THREAD

**Issue by ItalianMeatball** [itsamewayu/OLFallenDoll#216]
This has been going on for about 2 days [https://www.youtube.com/watch?v=yAXqvBJEsDQ](url)

**Comment by ItalianMeatball** [comment]
After patch 0.4.2 instead of infinite loading the game kicks you back to main menu after trying to connect, it boils down to the same problem, the issue is not fixed.

**Comment by jinjin525** [comment]
Merge to #101

**Comment by ItalianMeatball** [comment]
NOT the same issue but OK

**Comment by jinjin525** [comment]
I know they're not exactly the same issue but they're all based on server network issue.
