### ISSUE TITLE
[Harem] Using bottons in player list during experiments will return back to the main menu

### ISSUE THREAD

**Issue by ETERNAL-U9** [itsamewayu/OLFallenDoll#217]
**Describe the bug**
Buttons in player lists are not usable during experiments and will return the game to main menu from harem mode.

**To Reproduce**
1. Go to harem mode
2. Start any experiment
3. Click any of two types of buttons of any player in player list
4. Nothing happens at this moment
5. Click any of mentioned button again
6. Game is forced return to main menu.

**Expected behavior**
Those buttons should be usable to like or to hide a player, and game won't return to the main menu.

**Comment by jinjin525** [comment]
From johnathandarkly in issue #271 
this bug also triggers when you press the same hide icon twice

**Comment by Foxtrot1138** [comment]
Mine also does this. If I try to click on users to like, i will usually be kicked to menu
