### ISSUE TITLE
[Model][VR] POV in VR Makes Dreamer Head Visible

### ISSUE THREAD

**Issue by itsamewayu** [itsamewayu/OLFallenDoll#22]
🌟₮₭Ⱨ0̷3̷9̷5̷✨ — Yesterday at 10:20 PM
Also POV in vr now makes the entire head visible, it should be entirely disabled
![unknown](https://user-images.githubusercontent.com/11155504/143679689-da5f4265-7eae-48d6-8da5-6f3054483392.png)

**Comment by Awfulwaffle1** [comment]
Present in Demo Version.
