### ISSUE TITLE
After Update (0.4.1), when logging in to Harem Mode: "Please Update Game"

### ISSUE THREAD

**Issue by Panthear** [itsamewayu/OLFallenDoll#223]
I was trying to log in (Elevator Bug), when the new release announcement happened.

I logged out (Desktop) and updated the Game with the latest release.

When trying to log into Harem Mode following error was displayed: "Please Update Game".
However Version was displayed as 0.4.1. 

At the moment I cannot get over the point. what I tried:

1.) Verify Steam (didn't find any error)
2.) Deinstall / Reinstall - error stayed (no change).

![grafik](https://user-images.githubusercontent.com/95415732/144410339-8facfc63-6028-487d-af50-bc11cee2ab7c.png)

=> OS: Windows 7

**Comment by giant73** [comment]
can you provide the file to us for analyzing this problems?

**Comment by giant73** [comment]
![image](https://user-images.githubusercontent.com/20339840/144412178-8fe66a1a-2375-41fc-a232-50ace144f3d3.png)
can you provide the file to us for analyzing this problems?

**Comment by Panthear** [comment]
I am reinstalling at the moment.. trying to remvoe even registry entries... after that I can (at the moment file was removed).

**Comment by Panthear** [comment]
[ContentInfoDes.zip](https://github.com/itsamewayu/OLFallenDoll/files/7641534/ContentInfoDes.zip)

**Comment by Panthear** [comment]
PS: Also after removing Paralogue/Save and all other data and reinstall... error hasn't changed.

**Comment by Sesamimi** [comment]
Same problem here, also on a Win7

**Comment by DarkXelNaga** [comment]
same problem, same OS

**Comment by nerethar0** [comment]
same problem and OS

**Comment by Narxiz** [comment]
same problem, win7

**Comment by Panthear** [comment]
> same problem and OS,
> 
> After starting FallenDoll.exe via steamapps/common/fallendoll and not via shortcut or steam i´ve been able to join the harem mode

Thx... tried this. Did unfortuantely not work for me... (fallendoll.exe will quit and the start again via. the launcher.... resulting in the same issue...

**Comment by PMahoney21** [comment]
same issue, windows 7
Between each step I have attempted to access Harem mode without success

-downloaded the update
-waited 3+ hours
-Restarted computer
-verified game files
-uninstalled/reinstalled
-set the game to high priority update
-cleared download cache
-launched the game directly from the Steam Apps folder

I'm out of ideas and I still receive the message to update the game

**Comment by Sesamimi** [comment]
I tried the game on my laptop with a RTX2060 mobile and Windows 10, at this point it looks like only Windows 7 users that are getting this "Please update the game" message popping up, hopefully we won't be getting "Windows 7 is too old, this game only support Windows 10 and above"  =\

**Comment by Panthear** [comment]
BTW: Because someone hinted to upload ContentInfoDes here, I tried finding out if ContentInfoDes is used (because when I removed it same error appeared)...
However checking with procmon.exe (sysinternals) I could see that ContentInfoDes isn't accessed at all when accessing Harem Mode... It isn't even accessed when starting the Game (and I checked all processes, nut just Fallen Doll). 
So if the error appears because of that file, then most likely because this file isn't pulled by the executables....

**Comment by giant73** [comment]
This issue will be fixed in the next release

**Comment by Panthear** [comment]
Thx. Any hotfix/WA available, what could be done? (Other than upgrade to Win10 ;). Otherwise I simply need to be patient. Thx.

**Comment by giant73** [comment]
A hotfix for this issue will be released soon, pay attention to update

**Comment by Panthear** [comment]
There was a small update this afternoon (not chaning the version number). This however did not fix the issue (even tried reinstalling once more. So not sure this was the hotfix you talked about.

**Comment by giant73** [comment]
It will be released tomorrow or a little later, the exact time depends on the progress of the work
