### ISSUE TITLE
Got stuck while analyzing a Blueprint

### ISSUE THREAD

**Issue by SEMIPROPERVERT** [itsamewayu/OLFallenDoll#225]
When I spent some Arguments to buy 2 Alet Blueprints, I unlocked the first one fine, but when I hit Next Pack, it didn't freeze, but the card did not load. It left me stuck on the "Analyzing" screen unable to escape without force closing the game.

1. Buy 2 Alet Blueprints
2. Analyze both at the same time

I expected it to continue and show me my new card.

**Desktop (please complete the following information):**
 - OS: Windows 10 64-Bit

**Comment by jinjin525** [comment]
Similar with #157
