### ISSUE TITLE
View mode will cause problems with the experiment

### ISSUE THREAD

**Issue by akiray9** [itsamewayu/OLFallenDoll#226]
如果在實驗模式當下案到 capslook  (檢視模式)  會卡在當前實驗 無法取消或繼續 只能強制關閉遊戲
If you go to capslook (view mode) in experimental mode, you will be stuck in the current experiment, you cannot cancel or continue, you can only forcefully close the game

**Comment by johnathandarkly** [comment]
I get stuck at the end of an experiment at least once every other day, and i have no idea why. this could be that reason. i used to be able to escape by using the double like bug in the player list, but sadly that's been fixed
