### ISSUE TITLE
[Performance] Potential VRAM leak

### ISSUE THREAD

**Issue by itsamewayu** [itsamewayu/OLFallenDoll#23]
Jaylon — Yesterday at 9:00 PM
Potential VRAM memory leak.
When switching between scenes and clothing, VRAM utilization will increase. This doesn't seem to get freed when swapped which could be good for having on hand, but also just quickly fills up VRAM when it's not being freed. Changing the resolution seems to either drastically increase VRAM utilization, or decrease it, but generally if you can max out VRAM (in my case setting to a virtual 4k resolution) and then change resolution (for me back to 1080p), VRAM seems to get purged by quite a bit.

Edit: Probably should've said this before, but the VRAM is also really jumpy. Like, by 100-400MB jumpy

VRAM Utilization at 1080p before changing to 4K and back
![awcSInXGh5](https://user-images.githubusercontent.com/11155504/143679715-194ffb13-db62-492b-b5bf-0fda5b5f71dd.png)

 
VRAM Utilization after
![TNaplSzzRD](https://user-images.githubusercontent.com/11155504/143679717-37ca0281-e541-4fa4-a066-90f26ffe6d40.png)

Happens regardless of set resolution

**Comment by TheSoulWizard** [comment]
Im also experiencing issues according to VRAM allocation/utilization. Even though i have 12GB of VRAM, the game seems to be crashing as soon as it gets to ~5.6.
Random crashes upon entering "Glassic"/Galery mode.
Sometimes moving the camera slightly, instantly crashes the game with a "Out of video memory" message.
![image](https://user-images.githubusercontent.com/40411642/143687979-e2f63eaf-f91f-4516-b562-7552afc84581.png)

**Comment by Psychoham** [comment]
Having exactly the same issues, can provide specs if required.

**Comment by Awfulwaffle1** [comment]
Still valid.
