### ISSUE TITLE
[Bug Report] Arguments gone

### ISSUE THREAD

**Issue by castoli** [itsamewayu/OLFallenDoll#232]
I could not use the 48 arguments that i started with in harem mode, any attempt to purchase a card pack would result in a "insufficient amount of arguments" prompt. 
Furthermore upon claiming the first booster pack from the messages all of my arguments vanished.

**Comment by derpapplesauce** [comment]
yo same

**Comment by castoli** [comment]
it is stated in the Patreon tiers that [https://i.imgur.com/k39kB2g.png](url)
"Your total history pledge amount will be converted into in-game currency of Fallen Doll's online multiplayer Harem Mode" 
Can we please get this problem fixed? Can we get at least some sign that this report has been seen?

**Comment by castoli** [comment]
also, seems like "converted" isn't the right terminology here. i'm certain everyone started with 48 arguments at launch

**Comment by jinjin525** [comment]
"Your total history pledge amount will be converted into in-game currency of Fallen Doll's online multiplayer Harem Mode" is not implemented in this stage.
Duplicate of #102
