### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by Inviop** [itsamewayu/OLFallenDoll#235]
[UI]
When you start a experiment, on the bottom it should display like this:
"ESC : Quit | 1 : Special1 | 2 : Special2"
But if any player join your match, it turns to:
"M : Hide UI | CapsLock : Scan | Space : Switch......."(I could not remember it clearly lol)

当你开始实验时，左下方UI显示应当如下：
"ESC : Quit | 1 : Special1 | 2 : Special2"
但是如果此时有任何玩家加入了你的对局，UI显示将会变为:
"M : Hide UI | CapsLock : Scan | Space : Switch......."(很抱歉我无法清晰记忆那些UI内容)
---------------------------------------------------------------
[Server]
If there are more than 6 or so players, the special action is not available(It means that noting happens after I have pressed the key)
PS: I am not very sure about this error, sometimes it happens but sometimes not

当对局里有超过大约6名玩家时，特殊动作将会不可用，即当我按下对应按键时什么也没有发生
PS: 我对这个错误并不是非常确定，它有时发生有时不发生，不排除是我的操作没有成功触发特殊动作
---------------------------------------------------------------
[UI]
If the inspiration stack is full, when I collect another one all inspiration would be cleared
It should stay full

如果灵感槽满了，当我再次获取一点灵感时灵感将会被清空至1点
它应当保持满的状态
---------------------------------------------------------------
Unfortunately I do not have any screen shot to describe those errors, hope you could get what I am trying to express.....
很不幸的是我并没有截图以描述这些错误，衷心希望你能够理解我想表达什么.......

PHNB!!!!!!!!!!!!

**Comment by jinjin525** [comment]
Deleted duplicated issues.
Please try to provide more detailed information in order to archive those issues.

**Comment by jinjin525** [comment]
Inspiration issue moved to #266
