### ISSUE TITLE
[Issue] Elevator

### ISSUE THREAD

**Issue by fduser2** [itsamewayu/OLFallenDoll#238]
Loading into instances where players are stuck at the elevator. I see other people hanging out on the elevator and the hold F access for elevator doors is unresponsive.

**Comment by fduser2** [comment]
![image](https://user-images.githubusercontent.com/95328775/144458697-de3e730f-c467-4c55-bc6f-6c85a6b75f99.png)
![image](https://user-images.githubusercontent.com/95328775/144458788-96d45d9a-bf56-4ed1-a123-87da1a49208a.png)

**Comment by Dovahkiin1489** [comment]
same issue
