### ISSUE TITLE
Hair color changes between experiment/scene and free cam (no sex)

### ISSUE THREAD

**Issue by Justify87** [itsamewayu/OLFallenDoll#239]
In experiment the hair color of erika is blonde, like I've set it to. After ending the experiment, her hair becomes black (for me).

**Comment by apugo** [comment]
I have experienced this as well. Playing as Erika, after a scene with Erika, her hair will turn black when I am again walking around. Here is a screenshot: https://i.imgur.com/d0DnCQz.png
