### ISSUE TITLE
[Harem] Likes awarded not showing up in player count

### ISSUE THREAD

**Issue by johnathandarkly** [itsamewayu/OLFallenDoll#245]
After another researcher likes or likes awarded for simultaneous orgasms, "like given" notice appears, but the player's like count doesn't increase. I thought this was working well before the latest patch.

1a. Conduct experiment, get a researcher like
1b. Achieve dual orgasm, get a system like
2. See like award on screen
3. Go to harem home and be disappointed by same old like count

System:
i7-4790k oc'd to 4.6 ghz / 16gb ram / win 10 / nvidia 2060 super 8gb

**Comment by johnathandarkly** [comment]
I was getting likes pretty good today. Then after a lovely triple orgasm, i couldn't exit and didn't get any character likes. Went away for 5 minutes, still stuck, so exited to main menu using double hide bug

**Comment by poykun** [comment]
This should be fix as of 4.6. Player recognition updates with the amount of likes that player has given to you.
