### ISSUE TITLE
[Animation]Missionary Massage Special1 motion weird

### ISSUE THREAD

**Issue by noople30** [itsamewayu/OLFallenDoll#246]
**Describe the bug**
Performing "Special 1" during "Missionary Massage" will cause strange behavior.

**To Reproduce**
Select "Missionary Massage"
Wait for Fever Time
Press "Special 1"
Where are you going?

**Screenshots**
https://user-images.githubusercontent.com/95269133/144466848-4b40ffb1-fe8b-4c51-93dd-c696ba24e25a.mp4

**Comment by jinjin525** [comment]
From 47AqUa in #392 
In this pose, model will shift if player uses special position or cum again. When the animation is over, then model will teleport back to the original location.
