### ISSUE TITLE
[Camera] First Person POV Camera glitch

### ISSUE THREAD

**Issue by itsamewayu** [itsamewayu/OLFallenDoll#25]
Moons — Yesterday at 9:19 PM
这个身位不使用第一人称模式切视角的话 找不到人在哪了
![unknown](https://user-images.githubusercontent.com/11155504/143679827-13f4c95c-8e7c-4302-a60a-3e6eaf4b763d.png)

**Comment by jinjin525** [comment]
Duplicate of #5
