### ISSUE TITLE
[Harem] Outfit Loaded from Glassic Mode Selections After Setting Position

### ISSUE THREAD

**Issue by Yukikaze-OLFD** [itsamewayu/OLFallenDoll#250]
**Describe the bug**
Once a position is set for a character, their outfit swaps to one that has been chosen in Glassic. This persists until a new outfit is selected in Harem and it will remain upon logout, etc.

**To Reproduce**
1. Choose an outfit for Alet in Glassic
2. Log into Harem Mode and choose a pose
3. Place pose down

**Expected behavior**
Outfits should remain as what is selected and available in Harem Mode. This will be a way to circumvent certain purchases.

**Comment by poykun** [comment]
Confirmed this is for all characters.

**Comment by jinjin525** [comment]
Should be fixed in 0.42. Please submit the issue again if not fixed.
