### ISSUE TITLE
[Animation] Cannot start Anya x Erika animation

### ISSUE THREAD

**Issue by poykun** [itsamewayu/OLFallenDoll#253]
**Describe the bug**
Can't seem to start Anya x Erika animation: Kneeling Double Dildo

**To Reproduce**
1. Go to HAREM mode
2. Select Anya and Erika as a target
3. Select Kneeling Double Dildo Animation
4. Set animation against a wall and confirm the green overlay of the preview is met.
5. Click left mouse button to start

**Expected behavior**
Animation should begin

**Desktop (please complete the following information):**
 - OS: WIN10

**Comment by fduser2** [comment]
Can you check if you have the scene unlocked in the experiments list (before starting/matchmaking)?

I'm encountering the same issue with other scenes when trying to start them. Noticed that they're scenes don't own and I studied from someone else. The timer lapsed but the scene didn't grey out.

**Comment by poykun** [comment]
> Can you check if you have the scene unlocked in the experiments list (before starting/matchmaking)?
> 
> I'm encountering the same issue with other scenes when trying to start them. Noticed that they're scenes don't own and I studied from someone else. The timer lapsed but the scene didn't grey out.

Right you are. Looks like someone specifically called out that particular issue in #258. Closing this one.
