### ISSUE TITLE
[UI] Maximum sanity does not get updated

### ISSUE THREAD

**Issue by SpamFilter9k** [itsamewayu/OLFallenDoll#254]
**Describe the bug**
The maximum sanity does not update when it increases with your level

**To Reproduce**
1. Grind a few level
2. Wait for sanity reset

**Expected behavior**
Sanity at level 5 after reset for example should read 104/104 and not 104/100

**Screenshots**
![image](https://user-images.githubusercontent.com/95370798/144476986-459d5625-1a55-4ede-8875-131fc042f415.png)

**Comment by jinjin525** [comment]
From Ka1Sa:
It is beacuse that the sanity you got everyday is 100+(level-1)

Me: Well this is still a bug and the description is unclear. Might change the title if this is confirmed.

**Comment by SpamFilter9k** [comment]
It's just an UI related bug. I do get the increased sanity as is stated by level (100 + Level - 1 i assume). The thing is everywhere the current sanity gets shown, it always says xxx/100 as if 100 should be the maximum sanity at all times. It's just confusing to have 110 out of 100.
