### ISSUE TITLE
[System] Unable to access Harem mode

### ISSUE THREAD

**Issue by darthgraygor** [itsamewayu/OLFallenDoll#255]
Currently still unable to access Harem mode. However the amount time until the ESC key option appears has decreased since the previous update

**Comment by anonymouskommando** [comment]
Same here. Running windows 11 in Eastern US.
i9-10900kf
Nvidia RTX 3080
Comcast cable internet connection
Game loaded on M.2 NVME SSD (Drive E) 

I have tried restarting game, steam, and system, and verifying files through steam. None of these fixed the issue.

I'm downloading latest windows 11 patch/redistributable to see if that helps, I will reply to this thread if it does.

**Comment by anonymouskommando** [comment]
I am also replicated the issue on my backup gaming laptop as well

[DxDiag.txt](https://github.com/itsamewayu/OLFallenDoll/files/7644729/DxDiag.txt)
