### ISSUE TITLE
[UI] expired research blueprint shows available in map

### ISSUE THREAD

**Issue by Myztklkev** [itsamewayu/OLFallenDoll#258]
**Describe the bug**
I researched someone else's blueprint, it is now expired. In the blueprints view in the menu (or change room), it shows that I don't own it, in-game it shows available, but when I go to put it down it won't. This hasn't done it to every blueprint so maybe that matters, its the anya/hound/dreamer rare

**To Reproduce**
1. research someone else's blueprint.
2. let it expire
3. go in game and see that it appears to still be available, while showing unavailable in menu.

**Expected behavior**
the blueprint should expire and should no longer show available in game

**Desktop (please complete the following information):**
 - OS: Windows 10 21H1 19043.1348
not sure why browser and version is relative.

**Additional context**
n/a

**Comment by fduser2** [comment]
Confirming the same experience, it gets harder to track what I actually own the more I play because of this issue.

**Comment by jinjin525** [comment]
From HeyItsNyX in issue #333 
https://user-images.githubusercontent.com/95136714/144755523-f045a4ef-d6eb-47fc-8503-67576481d61a.mp4

The pose "threesome Double Penetration" from anya was studies 2 days ago in 0.4.1. After learning the pose and using it frequently, i was expecting to expire within 24h as i didnt had enough points to keep it. 

Today after the update, the pose in harem mode states its avabile but in account it isnt.  Im not sure if this is account related or Server related on this instance.

**Comment by Renmaru8** [comment]
Had the same issue, when you try and use the expired experiment the game just sets you back to being able to walk around with 0 explanation but will allow you to attempt placing the expired experiment.
