### ISSUE TITLE
[Issue] Scene(s) missing from Gallery

### ISSUE THREAD

**Issue by Batnavinatid** [itsamewayu/OLFallenDoll#259]
A Scene is missing from Gallery (it was present in 0.34):
Workshop -> Alet -> Lloigor -> Succumb -> Alet Lloigor Vaginal 02

It's the first one I noticed since it's present in the steam page screenshots. I can work on a comprehensive list of other missing scenes if that's helpful, as there are a few others.

**Comment by jinjin525** [comment]
There are scene used to be in 0.34 but not 0.40 due to model&scene rework.
