### ISSUE TITLE
[Bug][Harem][CTD] CTD from changeroom menu

### ISSUE THREAD

**Issue by Meme-Magic** [itsamewayu/OLFallenDoll#260]
Description:
When in in the changeroom menu, pressing the ESC key causes a Fatal Error and Crash To Desktop 

Reproducible: Yes, It's happened a few times

Version: Ver 0.4.1

**Comment by Sesamimi** [comment]
Description:
When in in the changeroom menu, pressing the ESC key causes game to exit to desktop (did not get any error message popping up)

Reproducible: Not yet

Version: Ver 0.4.2
