### ISSUE TITLE
Getting kicked out of the room when I try to like someone.

### ISSUE THREAD

**Issue by Kevinjiang991217** [itsamewayu/OLFallenDoll#263]
**Describe the bug**
I have tried few times, and the sever will kick me back to the title screen if I try to like someone.

**To Reproduce**
1. Go to 'harem mode'
2. Click on 'the like button under another player's name'
3. I will get kicked out

**Comment by Awula** [comment]
As far as I can tell, it tends to happen you disconnect or desync out of the lobby. The same thing happens when you try to click hidden as well.

**Comment by clifftor** [comment]
It happens to me when I try to "like" someone from the player list rather than left click while holding right click.

**Comment by fduser2** [comment]
Same experience, getting booted out when liking from the player list

**Comment by jinjin525** [comment]
·Fixed an issue that caused the game to sporadically shut down suddenly when giving other players Likes or Hiding them from the player list panel.
Should be fixed in 0.42. Submit the issue again if not fixed.
