### ISSUE TITLE
Connection issue, searching players.

### ISSUE THREAD

**Issue by Fox8907** [itsamewayu/OLFallenDoll#268]
**Describe the bug**
When trying to connect, the elevator is fuzzy and says searching players.

**To Reproduce**
1. Go to Start
2. Click on Enter Harem
3. See error

**Expected behavior**
Connect to lobby.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
I have a packet capture file that shows some re-transmitted packets during the communication with AWS.
![Connection attempt](https://user-images.githubusercontent.com/95458773/144540570-5b17e73d-58a7-4660-9a9e-ba42fb9bce3d.png)

**Comment by Devilbadge** [comment]
I too have this issue

**Comment by Dalek12** [comment]
Im having the same, and everytime after loading for few seconds the blurry elevator scene just switch back to the main menu again.

**Comment by Fox8907** [comment]
The issue came up after I was successfully connected and was forced to Alt+F4 during a scene. Could it be that my account is still logged to a server so it is refusing my connection request?

**Comment by hlfblkcafe** [comment]
I am also having this issue after playing just fine last night

**Comment by donatom3** [comment]
I'm having this issue and haven't been able to get passed the elevator since Monday.

**Comment by Gregnor** [comment]
+1 for the same issue...  Have been able to log in fine in the past but this is the first time since the new hot fix has come out.

**Comment by Jackyjacky64** [comment]
Same issue.  Elevator issue for past 2 days, now this.  Can't wait to play...eventually hopefully.

**Comment by TheSoulWizard** [comment]
@itsamewayu there was a server issue. Now it's fixed

**Comment by jinjin525** [comment]
Merge to #101
