### ISSUE TITLE
[Crashes] system unable to work after exiting the game退出游戏后系统出问题要重启

### ISSUE THREAD

**Issue by soranobuya** [itsamewayu/OLFallenDoll#269]
第一次，在游戏中选择退出到桌面，游戏停止后所有屏幕都隔几秒闪黑屏，重启后恢复正常。
第二次，在游戏中选择推出到桌面，很多应用程序不嫩启动，任务管理器，重启等系统功能也没反应，按重启键重启后恢复正常。
另外，每次在游戏中推出后steam仍然显示游戏在运行，不会自动停止。
Exit the game for the first time, all screens flashing black screen, fixed after reboot.
Second time, computer apps can't run anymore; system function not working including Task manager and rebooting.

计算机组成
cpu: AMD Ryzen 5950x
motherboard: ROG C8DH
memory: crucial DDR4 16GB*2
gpu: zotac trinity RTX3090
ssd: WD SN550 1TB(system)，Sumsung pm981 2TB(game)

OS: Windows11pro

monitor: LG 32UL750(4k60 hdmi2.0), hp 23bw(1080p60 DisplayPort to DVI)

**Comment by jinjin525** [comment]
需要更详细的操作、运行相关信息来将这个问题归档

**Comment by soranobuya** [comment]
貌似是非英文输入法的时候出现的，使用英文输入法尝试几次没有再现问题
