### ISSUE TITLE
[UI] Cursor Controls Position Mismatch

### ISSUE THREAD

**Issue by ysy95109** [itsamewayu/OLFallenDoll#27]
The Actual position of the controls are at the top left of their displayed position.
![image](https://user-images.githubusercontent.com/58617201/143679755-34068cab-7505-410e-865f-df369f0ddeec.png)

**Comment by ysy95109** [comment]
Seems this issue applies to all the controls including buttons, scroll bars, etc

**Comment by Lary3178** [comment]
I also have this issue I have to keep guessing what I am selecting by scrolling above the options I want seems to be selecting whatever is below the actual mouse.

**Comment by clifftor** [comment]
Reports similar issue:

This issue happens after changing resolution.

It doesn't recover after restarting the game.
It doesn't recover after changing the resolution back.

![resolution](https://user-images.githubusercontent.com/20754595/143686039-10f8b06d-008b-4632-82ea-1b5c9af97b32.png)

**Comment by Fank** [comment]
Same issue on 5120x1440 resolution.
It is nearly impossible to drag those sliders, in the settings menu.

**Comment by clifftor** [comment]
Update: change the dpi setting back to 100% solves this issue

**Comment by jinjin525** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=2670148123
Try this before the problem got fixed, it's in Chinese. 
Same as clifftor mentioned before:
> Update: change the dpi setting back to 100% solves this issue

**Comment by ysy95109** [comment]
I just found another workaround:
Press Win+Tab during the EAC screen and switch back after EAC finished loading.
