### ISSUE TITLE
RAM useage

### ISSUE THREAD

**Issue by Devilbadge** [itsamewayu/OLFallenDoll#270]
The game uses so much RAM it crashes my computer

1. Go to the game
2. Click on any animation

**Expected behavior**
The game to crash and complain not enough memory

**Comment by TheSoulWizard** [comment]
Do you meet the requirements?
![image](https://user-images.githubusercontent.com/40411642/144543769-2c5b05e3-dd2a-4a51-9d5e-161a3fbc10bb.png)

**Comment by Devilbadge** [comment]
Yes my computer happily plays games with more intensive needs.

**Comment by Devilbadge** [comment]
The error message says failure in loading a texture

**Comment by jinjin525** [comment]
Not enough information to file the issue
Please check the memory usage in the windows task manager and other related info.
