### ISSUE TITLE
[Model]模型模糊，加载延迟

### ISSUE THREAD

**Issue by reteriax** [itsamewayu/OLFallenDoll#274]
**Describe the bug**
后宫模式 1080p分辨率，画质最高情况下模型精度却很低，包括角色服饰和环境物体模型，alet衣服上的图案几乎不可见，而物体模型只有靠近后稍等片刻才能加载完全。鉴赏模式情况好些，但刚进入时角色服装也存在加载延迟。
0.4.1版本封闭测试

**Comment by jinjin525** [comment]
Duplicate of #183
