### ISSUE TITLE
[Animation][UI]多个多次遇到的bug

### ISSUE THREAD

**Issue by adadast** [itsamewayu/OLFallenDoll#275]
**Describe the bug**
阿蕾特传教士位按摩动作，使用特殊动作时模型会瞬移到远处，特殊动作结束后再回来。
同时高潮后，有相当概率无法退出动作，游戏内按键无效，只能强制结束游戏。
鼠标移动到角色身上可以触发特殊动作的位置时，光标会有变化来提示可以触发动作，但是很多情况下这个机制会失效，尽管点击相应位置仍可触发动作，但光标不会变化来进行提示，另外数字键触发特殊动作也是有时有效，有时没有反应。两个问题结合十分影响游玩，特别是在有多个特殊动作的体位中。

**Expected behavior**
辛苦了，加油。

**Comment by jinjin525** [comment]
第一个问题在 #246 有提出，如果不是相同情况请在对应issue下面留言
第二、第三个问题已收录
