### ISSUE TITLE
[Harem Login Issue]Can't get into harem mode

### ISSUE THREAD

**Issue by lnfzh1015** [itsamewayu/OLFallenDoll#276]
Hi there,

Every time I tried logging in to the harem mode, it always pop me out to the page like the screenshot below. I saw text that reads matchmaking and I saw the blurred yellow bright elevator stuff, but all of them ended up popping me out to the home screen. Any idea how can I fix this issue? Thanks.

![unknown](https://user-images.githubusercontent.com/76079866/144612418-5a994318-f6de-4c34-9421-49fc2a949f05.png)

**Comment by User141414** [comment]
I also have the same issue. I've tried reinstalling and verifying game files, but it did not fix it.

**Comment by User141414** [comment]
Are you still having the issue? I don't know if it was an issue with the servers but I went into Harem and than went to the title page and back into Harem and it loaded correctly.

**Comment by raplin1999** [comment]
I still have the same issue, reloaded several time did not fix anything.
