### ISSUE TITLE
[Harem] Daily task doesn't refresh if only 2 out of 3 tasks has been completed.

### ISSUE THREAD

**Issue by clifftor** [itsamewayu/OLFallenDoll#277]
**Describe the bug**
Daily task doesn't refresh if only 2 out of 3 tasks has been completed.

**To Reproduce**
Complete 2 daily tasks, wait for daily task refresh time. No task refreshed.

**Expected behavior**
Daily one of the two completed daily task refreshes.

**Comment by Exarch23** [comment]
Can reproduce, this is also occuring for me for 2-3 days now , the [Foot] tag task is bugged and does not count when I do foot scenes, so it also breaks the refresh.

my like tally is 87/20 now.. I should have made at least 9 Insights by now from the liking other players.

![image](https://user-images.githubusercontent.com/95268877/144725838-08133c6f-1289-428f-b80a-bbc5a02b1e1e.png)

**Comment by Cyrellos** [comment]
The two lower tasks are older, they are from the start of beta. They dont refresh.
Yesterday i finished the first one, this task refreshed today.
![Unbenannt 1](https://user-images.githubusercontent.com/95551423/144893388-472a1e87-606c-49ad-9544-d4e047f5da62.jpg)

**Comment by jinjin525** [comment]
Not exactly same issue but similar:
From Sanjuun in issue #357
Don't get new daily task when all three completed

**Comment by Panthear** [comment]
I have completed all 3 tasks... 
and now I am only getting 1 new quest every second date... (today again no new quest for me...)

**Comment by johnathandarkly** [comment]
5+ days of tasks 2 and 3 not refreshing. task 1 started refreshing again a few days ago.

**Comment by Panthear** [comment]
While I got new quests in the last 5 days (one per day), today again, no new daily quest appeared. Today is/was 11-Jan-2021
