### ISSUE TITLE
[Resolution] Fullscreen/windowed mode Transition weirdness

### ISSUE THREAD

**Issue by itsamewayu** [itsamewayu/OLFallenDoll#28]
Jaylon — Yesterday at 9:31 PM
Very minor, If the game is in windowed mode and you make it fullscreen by dragging to the top of the screen, once setting fullscreen in game, it won't correctly scale to fit the screen
Happens regardless of set resolution

https://user-images.githubusercontent.com/11155504/143679891-11968110-8e16-442c-bcc1-e2d150ab4595.mp4

**Comment by Camo260** [comment]
I just compared steam release with 0.34 and for me it seems like it isn't taking desktop scaling into account with the steam release so the resolution never seems to fit right.
