### ISSUE TITLE
[Harem][UI] Open the door while placing a sex position causing you unable to open any door

### ISSUE THREAD

**Issue by clifftor** [itsamewayu/OLFallenDoll#282]
**Describe the bug**
Trying to open the door while placing a sex position causing the player no longer being able to open any door

**To Reproduce**
* Go to the harem mode room
* Select a sex position, keep in the state to place the sex position, don't left click
* Walk towards a door, hold F trying to open a door while still in the state to place the sex position
* Do anything to exit the placement, you are no longer being able to open any door.

**Comment by clifftor** [comment]
Exit harem mode doesn't fix this, but I can't reproduce this after restart the game client.

**Comment by johnathandarkly** [comment]
happened to me yesterday, so patch 0.4.2 did not fix.
