### ISSUE TITLE
[model] Gallery outfits transferring onto Harem mode models

### ISSUE THREAD

**Issue by kblah40** [itsamewayu/OLFallenDoll#286]
**Describe the bug**
Saved gallery outfits are transferred onto models in harem mode during scenes.

**To Reproduce**
1. In Gallery mode, use an outfit not unlocked in harem mode
2. Succesfully start harem mode and start a scene
3. Witness glory

**Expected behavior**
The models to only have outfits currently unlocked in harem mode

**Comment by jinjin525** [comment]
·Character customization should now correctly synchronize with other players in the lobby and all players' avatar will be displayed in their current dressing state. Please note this fix is experimental and will be continually improved upon.
Should be fixed in 0.42. Submit the issue if not fixed.
