### ISSUE TITLE
[systerm]Low level fatal error. Error : 0x8876A0006 'HUNG'

### ISSUE THREAD

**Issue by Selena-Veneto** [itsamewayu/OLFallenDoll#287]
**How it performs 表现：**
卡顿数秒，随即弹出报错框（如截图），随后黑屏，程序无响应挂起，无法关闭，只能使用任务管理器结束进程。
Stuck for a few seconds, error pop out like screenshot, black screen, game freeze, not able to end it except killing it using task manager.
**How to trigger it 触发：**
在后宫模式主界面，进行任何较快速的操作——包括：快速翻阅实验列表，在5秒内多次切换人物，多次点击触摸人物等。
In main menu in Harem mode, do anything too fast —— includes: Quickly scroll through the experiment list, switch characters multiple times within 5 seconds, tap and touch characters multiple times, etc.

**Screenshots**
![This is an image](https://ae01.alicdn.com/kf/H2df87d02a98b497eb1e8d8cc575675b5o.png)

**环境：Desktop :**
处理器	AMD Ryzen 7 5800H with Radeon Graphics            3.20 GHz
GPU  NVIDIA 3080 laptop 8g
机带 RAM	16.0 GB (15.4 GB 可用)
系统类型	64 位操作系统, 基于 x64 的处理器
版本	Windows 10 家庭版
版本号	21H1
安装日期	‎2021/‎6/‎10
操作系统内部版本	19043.1348
体验	Windows Feature Experience Pack 120.2212.3920.0

**Comment by jinjin525** [comment]
From Talanias in issue #352 

CTD while walking around in harem mode after leaving laboratory.

This is my first time encountering this issue. Occurred shortly after ending a scene. Hair color changed suddenly and there was also clipping on the outfit after ending the scene.

![The UE4-Paralogue Game has crashed and will close 2021-12-07 12_19_05 AM](https://user-images.githubusercontent.com/95672049/144972286-91d59ab1-d34f-45b3-ab3a-673610b5e54d.png)

AMD Ryzen 9 5900X 3.7Ghz
Nvidia Geforce RTX 3080
32Gb RAM
Windows 10 home
