### ISSUE TITLE
[System] Unable to access Harem mode

### ISSUE THREAD

**Issue by Gocubs2** [itsamewayu/OLFallenDoll#288]
Unable to access Harem mode

**To Reproduce**
couple of days ago i was stuck at elevator every time i tried to join harem mode. then 2 times it crashed. Now i cannot even join harem mode, stuck on loading screen

![image](https://user-images.githubusercontent.com/95493144/144635975-e4d4bbcb-f5ba-460f-9cd9-7121ef39eedb.png)

 - OS: Win 10

**Comment by jinjin525** [comment]
Merge to #101
