### ISSUE TITLE
Unable to access harem mode.  Still active as of patch 0.4.2

### ISSUE THREAD

**Issue by User7276** [itsamewayu/OLFallenDoll#289]
Starting harem mode results with being stuck in elevator like before, but screen does not render, just a blurry elevator.  After about 5-10 seconds, I am kicked back to start screen.  While in elevator, frozen loading icon and searching players is in bottom right corner.  Spacebar, E key for scenes, and tab key for player list all work for the short time stuck in elevator.
![20211203093617_1](https://user-images.githubusercontent.com/95495776/144647478-4fd616d7-b77f-4968-9796-216264becc8b.jpg)
![20211203093619_1](https://user-images.githubusercontent.com/95495776/144647485-02d5ca02-9e13-4ae1-9749-937fb37eaed3.jpg)

**Comment by MarcusKane1** [comment]
Yup. Happened to me just now as well. 24 hours ago everything was perfectly fine.

**Comment by Otsdarva68** [comment]
Been happening to me since last night

**Comment by sevenquit** [comment]
+1

**Comment by Sanjuun** [comment]
+1

**Comment by Otsdarva68** [comment]
This issue persists for me after implementation of 0.4.2

**Comment by jinjin525** [comment]
Merge to #101
