### ISSUE TITLE
[Model] High Heel/Footwear option not available for some poses

### ISSUE THREAD

**Issue by itsamewayu** [itsamewayu/OLFallenDoll#29]
Hi, when I try to enter some sex mode, the high heels option do not appear! 
高跟鞋选项没有了在性爱模式当中
这时候鞋子选项无了
![unknown](https://user-images.githubusercontent.com/11155504/143680004-676f8a1f-d328-4a10-b16c-09433a2d1ab1.png)

**Comment by Awfulwaffle1** [comment]
I believe this is intended as is. Closing.
