### ISSUE TITLE
[Gameplay][daylie task: female climax via sex toys]

### ISSUE THREAD

**Issue by nerethar0** [itsamewayu/OLFallenDoll#290]
Erika´s Standing Dildo does not fill these daylie task. 

Tried it at both research focus, also with only filled pleasure meter her/him and both. it doesn´t count

**Comment by apugo** [comment]
The task to "Female climax via experiments with the (vaginal) tag" doesn't work, either.

**Comment by jinjin525** [comment]
Merge to #164
