### ISSUE TITLE
[animation] [model] Hands Bound Missionary Erika

### ISSUE THREAD

**Issue by Spadiel** [itsamewayu/OLFallenDoll#293]
While using the subject pose, there is an animation and persistent model issue with Erika.  When initializing the Special 1 command, her hands will rotate 360 degrees and then her toes will get scrunched as shown in the pasted image below.  The hands will revert to their intended position after the rotation, but her toes remain that way until the scene is completed and restarted, at which point they will start to curl and scrunch when she moves them.  This was observed in Harem mode and I Erika was wearing her ribbon outfit with shoes disabled.
Screenshot:
![image](https://user-images.githubusercontent.com/95501375/144661400-177ff4af-1614-424d-af34-02e4f3039250.png)

**Comment by jari428** [comment]
![Desktop Screenshot 2021 12 04 - 16 56 03 65](https://user-images.githubusercontent.com/95413769/144730960-c77717b9-374c-4ade-a4a7-afe7abe342a7.png)

Confirming there are issues with Erika's toes in this pose. In the Funeral Violinist outfit, her toes appear to clip outside of her shoes, and at strange angles.

**Comment by nle244** [comment]
![fixtoes](https://user-images.githubusercontent.com/78895941/151495944-5136c7a5-156a-48a1-97e0-8bb4bc580486.png)

Toes still a problem on 0.4.8. AletErika_Sex04
