### ISSUE TITLE
[animation] Anya x Ghast animation stop

### ISSUE THREAD

**Issue by Koitoai** [itsamewayu/OLFallenDoll#295]
Anya x Ghast prone bone animation
When you activate Special 1 animation comes to a stop and ghast penis is taken out without exit transition animation.
The experiment would still be on play however ecstasy levels would drop as if the experiment had come to a halt.
When Anya ecstasy levels reach max, animation would also stop as if experiment has come to a halt but experiment would still be on play, players would have to hit stop experiment again before you can resume.
When Ghast ecstasy levels reach climax, there is no ejaculation animation, it has same penis moves through Anya to outside of body without exit transition animation.

**Comment by Panthear** [comment]
Still existing in 0.4.7. Just tested it, stimulation (Special 1) stops that extasy increases....
