### ISSUE TITLE
[UI] Experiment Tag Icon Error/Missing

### ISSUE THREAD

**Issue by Ocieros** [itsamewayu/OLFallenDoll#298]
**Describe the bug**
When you look at the "betty rocker" experiment in the experiments tab on the main menu, OR when you go to set the scene up in-game, the card displays a "femdom" "vaginal" and "vaginal" again. It should display "femdom" "vaginal" "butt"

**To Reproduce**
1. Go to "experiments" on the main menu
2. Find "Betty Rocker" for Erika. Make sure its unlocked.
3. Note the icons in the bottom of the card are duplicated for the last two. The last should be the "butt" tag icon.
***Semi-optional
4. Start the game
5. Press E to setup experiment
6. Select Erika and Dreamer
7. Select Compatibility: Full
8. Select Location: Floor
9. Hover the cursor over "Betty Rocker" and note the tag descriptions and how the icons differ from what is displayed on the card.

**Expected behavior**
The last Icon should be the "butt" icon on the card/method.

**Screenshots**
![butt icon wrong](https://user-images.githubusercontent.com/85970707/144696361-0623a30f-0e73-4241-99c5-644c9ca47fa8.png)

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser Not relevant.
 - Version 0.4.1

**Comment by jinjin525** [comment]
From jari428 in issue #339 
Experiments titled "Restrained" and "Captive" do not have the appropriate "Restrained" category tag.
