### ISSUE TITLE
[Model] Character (Alet) Underground from Discord

### ISSUE THREAD

**Issue by itsamewayu** [itsamewayu/OLFallenDoll#3]
bug report: character underground 
character: alet
![DBA94752-4811-465F-83CC-F33D52244AE6](https://user-images.githubusercontent.com/11155504/143678387-b012db91-705e-414b-a540-405348745310.jpg)
![B3240673-49A9-495B-ABAF-01176C386A2B](https://user-images.githubusercontent.com/11155504/143678391-0429621f-f399-41ff-97a7-5ca9a0033fe2.jpg)

**Comment by jinjin525** [comment]
Duplicate of #5
