### ISSUE TITLE
后宫模式无法匹配到玩家，返回主页面

### ISSUE THREAD

**Issue by MechakuchaKazuha** [itsamewayu/OLFallenDoll#301]
**Describe the bug**
后宫模式无法匹配到（搜索到）玩家，返回主页面

**To Reproduce**
1. 进入后宫模式
2. 点击开始->进入后宫
3. 无法匹配到玩家（searching player），返回主页面

**Expected behavior**
匹配到玩家，进入游戏或者作为主机创建游戏

**Screenshots**
无法search到player：![image](https://user-images.githubusercontent.com/62276382/144699578-82391d10-c839-45f3-8f2e-d1345292a811.png)
返回主页面：![image](https://user-images.githubusercontent.com/62276382/144699585-9e78b3f9-81e0-4441-af93-158dda9b2ae7.png)

**Desktop (please complete the following information):**
 - OS: [win11]
 - Browser [chrome]
 - Version [0.4.1]

**Additional context**
None

**Comment by raplin1999** [comment]
same
