### ISSUE TITLE
4.2, Game won't launch, "Easy Anti Cheat Unknown File Version"

### ISSUE THREAD

**Issue by PMahoney21** [itsamewayu/OLFallenDoll#303]
Windows 7, 4.2 update has been installed and I have verified the game files. After this update, the game will not launch. Easy Anti Cheat throws an error that reads as follows:
"Unknown file version (E:\Steam\steamapps\common\Operation Lovecraft Fallen Doll Playtest\Paralogue\Binaries\Win64\Paralogue-Win64-Shipping.exe)"

Once this error pops up, the screen stays black and then the game closes.

**Comment by nerethar0** [comment]
Same OS and same issue.

details are:
Problemsignatur:
  Problemereignisname:	APPCRASH
  Anwendungsname:	Paralogue-Win64-Shipping.exe
  Anwendungsversion:	4.25.4.0
  Anwendungszeitstempel:	00000000
  Fehlermodulname:	StackHash_8e0b
  Fehlermodulversion:	6.1.7601.24545
  Fehlermodulzeitstempel:	5e0eb67f
  Ausnahmecode:	c0000374
  Ausnahmeoffset:	00000000000bf262
  Betriebsystemversion:	6.1.7601.2.1.0.768.3
  Gebietsschema-ID:	1031
  Zusatzinformation 1:	8e0b
  Zusatzinformation 2:	8e0b7ca72d60c64f69169d62aac83fc7
  Zusatzinformation 3:	2737
  Zusatzinformation 4:	2737f8875236b8720fafe703d2d4fe68

**Comment by Sesamimi** [comment]
Same issue, Windows 7, FD 0.4.2, Can't even get into the main menu screen now, ouch.

**Comment by Sesamimi** [comment]
Looks like a small update/patch fixed the unknown file version problem.
