### ISSUE TITLE
[game] unknown file version Paralogue-Win64-Shipping.exe

### ISSUE THREAD

**Issue by finitedark** [itsamewayu/OLFallenDoll#304]
When loading the game I get this popup from easy anti cheat: unknown file version: ~/Steam/steamapps/common/Oper~/Paralogue/Binaries/Win64/Paralogue-Win64-Shipping.exe

 - OS: Windows 8.1
 - Game Version 0.4.2

**Comment by jinjin525** [comment]
Duplicate of #303
