### ISSUE TITLE
[Gameplay] Daily missions "Make Male/Female Climax using X tag." count not increasing after climax

### ISSUE THREAD

**Issue by mrpancake12** [itsamewayu/OLFallenDoll#305]
Seems to only be affecting tasks received after daily reset. I was able to complete the original daily tasks when the account was created. 
Rerolled daily tasks in this format also affected.

I tried multiple climax options, but none worked.

Username: mrpancake14

**Comment by jinjin525** [comment]
Duplicate of #164
