### ISSUE TITLE
Cant place/ use certain positions

### ISSUE THREAD

**Issue by Knezzzo** [itsamewayu/OLFallenDoll#320]
I cant seem to use some of the positions, when I put them down nothing happens and they don't work

ones that don't work for me:

Squatting cowgirl:
![image](https://user-images.githubusercontent.com/95556158/144732277-7ec8e9bd-d8ca-42cb-be55-495bf7e7604c.png)
Apollo: 
![image](https://user-images.githubusercontent.com/95556158/144732300-f3c72980-ff22-44d5-96fc-cf834ed81e8e.png)

I'm sure there are more but these are the ones that I have found at the moment

**To Reproduce**
1. Click "E"
2. Find position and click on it
3. Find a place you can place it and click Apply
4. Does not place or work

![image](https://user-images.githubusercontent.com/95556158/144732520-2b3a2696-ecd5-470c-9f85-ee5f3ea1aea5.png)

![image](https://user-images.githubusercontent.com/95556158/144732553-e37d52af-9881-4e2d-a966-c776a9d54bb8.png)

![image](https://user-images.githubusercontent.com/95556158/144732534-031d3382-a1dc-41ee-bb9b-17c3f97b9107.png)

**Expected behavior**
To be able to place and enter the position/ animation

**Comment by jinjin525** [comment]
Merge to #116
