### ISSUE TITLE
[Harem mode fails to load]

### ISSUE THREAD

**Issue by BaeJangles** [itsamewayu/OLFallenDoll#326]
**CRASH ON BLURRY ELEVATOR**

Launched Harem mode. elevator loads player lists are visible, ui is mostly visible, except that everything is completely blurred... it waits like this for a couple seconds, during which you can move the camera, but everything remains blurred,, before kicking back to the Lobby screen.

**Screenshots**
![20211205074403_1](https://user-images.githubusercontent.com/95559789/144736819-049b303d-2353-4aaa-bec4-c9f67bc81f73.jpg)

It seems to be in this non working state for periods. i'll try 3 or 4 times and it will fail each time. but usually after waiting half an hour or an hour, it may load into game correctly.

**Desktop **
 - Windows 10
 - Intel Core i5
 - 32gb RAM
 - 8gb RTX 2070

**Comment by hlfblkcafe** [comment]
also having this issue

**Comment by SunnyD93** [comment]
also hving issue
