### ISSUE TITLE
[Model] Erika Pose - Vials Clipping into pose

### ISSUE THREAD

**Issue by itsamewayu** [itsamewayu/OLFallenDoll#33]
艾丽卡 混种深潜者 兼容度低 传教士肛交穿模
![unknown](https://user-images.githubusercontent.com/11155504/143680148-b726fbe2-b3f9-4510-b655-cf8e86dc145a.png)

from iNyx
![unknown](https://user-images.githubusercontent.com/11155504/143680472-88f4e19b-b97a-4bd8-b921-831f91007491.png)

**Comment by jinjin525** [comment]
Same issue reported in ver.0.45 in issue #426, closing this one
