### ISSUE TITLE
Unable to get into harem mode.

### ISSUE THREAD

**Issue by Azereili** [itsamewayu/OLFallenDoll#332]
Unable to join harem mode, as there is not enough players.
When joining harem mode i am getting connected to room with no players in it and then the game kicks me out.
I am not sure if this is a feature or a bug.
But in my opinion i should be able to roam alone in harem mode and await other players to join.

**Comment by Jjunderdog** [comment]
That has happen to me as soon as the second update dropped

**Comment by Exarch23** [comment]
This is still happening during certain times of day when I try , after the last 2 patches I was able to get into harem mode more frequent but sometimes depending on time of day nobody's playing in my region probably so I cant start a game..

Please just let players play solo in a game instance.

**Comment by Elliphaz** [comment]
I can never leave the blurry 'searching for players' elevator, lost count of attempts.
