### ISSUE TITLE
Stacked animation breaks camera/game

### ISSUE THREAD

**Issue by Gunrunner243** [itsamewayu/OLFallenDoll#338]
**Describe the bug**
When in Harem mode I studied the animation from another person in which Anya has Alet stacked upside down and his doing something to her(I legitimately cannot tell you what because I never got to see it myself.) And the game would throw the camera through a wall where space (literal space) could be seen and the other (under) side of the map can be seen (it has a mesh pattern). You can kinda fly around and look around but not very well. 

**To Reproduce**
1. Go to harem mode
2. Not have the Anya×Alet against the wall animation unlocked
3. Scan that animation from somebody else
4. Place the animation against any wall(I tried 3 or 4 different walls)
5. See error. 

**Expected behavior**
Everything works fine, you are allowed to place the new animation, the animation starts, camera is thrown somewhere into the map, like inside inside the map. 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version I'm not sure. Most recent.

**Comment by dengbomingqx** [comment]
I also encountered this problem, the animations of anya and alet directly wear the mold

**Comment by dengbomingqx** [comment]
![6$}B5P6JA 2SY`1C5TYJZ~K](https://user-images.githubusercontent.com/95612619/144812034-aaed3fd0-05de-4d0b-810e-92b945dedc28.png)

**Comment by jinjin525** [comment]
Should be same issue as #168
