### ISSUE TITLE
[Harem][Experiments][Tags] Alet Restrained Experiment Tag Missing

### ISSUE THREAD

**Issue by jari428** [itsamewayu/OLFallenDoll#339]
**Describe the bug**
Experiments titled "Restrained" and "Captive" do not have the appropriate "Restrained" category tag.

**To Reproduce**
1. Go to Harem Mode
2. Click on 'Experiments'
3. Scroll down to Alet's "Restrained Missionary" and "Captive Rear-Entry"
4. See lack of appropriate tags.

**Expected behavior**
These experiments carrying the "Restrained" tag and handcuffs icon.

**Screenshots**
![Paralogue Screenshot 2021 12 05 - 17 34 44 47](https://user-images.githubusercontent.com/95413769/144799668-7b9154ce-fcba-47c4-b21d-8e4a03396c37.png)
![Paralogue Screenshot 2021 12 05 - 17 35 00 60](https://user-images.githubusercontent.com/95413769/144799674-e04dc8d2-090b-454f-b366-165f2654ee45.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 21H1
 - CPU/GPU: Ryzen 7 2700x, RTX 2070
 - Operation Lovecraft Version: 0.4.2

**Comment by jinjin525** [comment]
Merge to #298
