### ISSUE TITLE
Keyboard: Walking WASD become inverted

### ISSUE THREAD

**Issue by Sesamimi** [itsamewayu/OLFallenDoll#342]
OS: Window 7
Game Version: 0.4.2

After selecting the experiment to use, when trying to walk to a spot to start the experiment, the WASD walking direction become inverted:

W - Backward
A - Right
S - Forward
D - Left

So far this only happened once and may only happen on very rare occasion, will test and see if this can be reproduced on Windows 10 too.

**Comment by jinjin525** [comment]
From Karbonkel:
When i fresh start the game the walking with WASD is normal,
But after choosing an experiment or getting  in a menu, it's like the keys are interchanged for walking.
And the Camera always stays in one position, makes it hard to place a  experiment, when walking is interchanged and the camera don't snap back to default

**To Reproduce**
1. Enter Harem mode
2. Choose an experiment or open menu
3. Issue happens: Walking keys reversed
*during this time, unable to turn camera except zooming.

From Sageras_Simpson:
I think the walking keys are reversed is bacause of that unusual camera lock, your camera is locked in one direction, but the avatar is facing the other way (sometimes in the opposite direction), so it looks like the WASD got reversed
