### ISSUE TITLE
[Harem] Can't place "Betty Rocker"

### ISSUE THREAD

**Issue by johnathandarkly** [itsamewayu/OLFallenDoll#345]
i own the "Betty Rocker" card, but i have been unable to successfully place it. the placeholder turns green indicating a valid placement, but placing it just exits the experiment mode.

![20211206104906_1](https://user-images.githubusercontent.com/95413655/144879194-19aab3c3-6507-48f8-81b1-730c74619014.jpg)

this one hurts because i've seen this in the wild today. ;(

i7-4790k 16gb RAM / RTX 2060 Super 8GB RAM / Win 10

**Comment by jinjin525** [comment]
Merge to #116
