### ISSUE TITLE
Task progress not increasing

### ISSUE THREAD

**Issue by fduser2** [itsamewayu/OLFallenDoll#350]
![image](https://user-images.githubusercontent.com/95328775/144956626-4ee78991-6010-4d60-96bd-ae36e0b8e157.png)

I've had the task involving the "lesbian" tag for a while now and I've been spamming scenes between investigators for a few days, still no progress registered.

For the giving likes to researchers, no progress as well despite using all the inspiration I generate to give likes.

**Comment by jinjin525** [comment]
Duplicate of #164
