### ISSUE TITLE
[bug][harem][CTD] Low level fatal error [File: unknown] [Line: 198] unreal engine is exiting due to D3D device being lost. Error : 0x8876A0007 - 'RESET'

### ISSUE THREAD

**Issue by Talanias** [itsamewayu/OLFallenDoll#352]
**Describe the bug**
CTD while walking around in harem mode after leaving laboratory.

This is my first time encountering this issue. Occurred shortly after ending a scene. Hair color changed suddenly and there was also clipping on the outfit after ending the scene.

![The UE4-Paralogue Game has crashed and will close 2021-12-07 12_19_05 AM](https://user-images.githubusercontent.com/95672049/144972286-91d59ab1-d34f-45b3-ab3a-673610b5e54d.png)

AMD Ryzen 9 5900X 3.7Ghz
Nvidia Geforce RTX 3080
32Gb RAM
Windows 10 home

**Comment by jinjin525** [comment]
Merge to #287
