### ISSUE TITLE
[UI] Purchased Blueprints from store does not show immediately

### ISSUE THREAD

**Issue by Awfulwaffle1** [itsamewayu/OLFallenDoll#354]
**Describe the bug**
Upon purchasing a Blueprint from the store (shopping cart icon), the Blueprint does not show any indication of the targeted blueprint available for analyzing. 

**To Reproduce**
1. Go to Harem Mode > Blueprints
2. Click on Shopping Cart icon on the top screen
3. Purchase a blueprint
4. Exit the store
5. Observe Blueprint screen

**Expected behavior**
Blueprint list is not updated with the amount purchased on the store.

**Workaround**
Navigate out of the Blueprint page and back into it and purchased Blueprint should now be available to analyze.

**Desktop (please complete the following information):**
 - OS: Win10
 - Game Version: 0.42

**Comment by poykun** [comment]
Still persisting in Version 4.6

Another good test is the following:
1. Go to Harem Mode
2. Click shopping cart for the peer review committee store
3. Click on one of the Blueprints to initiate purchase
4. Select quantity of 2 to purchase
5. Click the purchase button
6. Observe on the blueprint page

Expected: If you started out with 0 for the particular blueprint, it should reflect the correct amount you bought. In this case it should be 2.

Actual: It will display only one. 

Workaround: If navigating in and out of the blueprint page doesn't update, closing the entire game session and restarting will work.

**Comment by Awfulwaffle1** [comment]
This seems to be resolved. closing
