### ISSUE TITLE
[UI] Speed control with mouse scrollwheel behaves unexpectedly

### ISSUE THREAD

**Issue by hakanai** [itsamewayu/OLFallenDoll#359]
**Describe the bug**
Moving the mouse to the bottom right of the screen into the speed area and scrolling the mousewheel to try and change the speed does not always change the speed. Sometimes it will still zoom the camera instead.

Additionally, the highlight behaviour of that area appears to be inverted: When it's highlighted in a lighter colour the scrollwheel affects camera zoom, whilst when it's not highlighted, the speed control works.

**To Reproduce**
1. Get into an experiment.
2. Move the mouse to the 'SPEED' area in the bottom right, just under the word 'CONTROL'
3. **Observe:** Button will highlight, but scrolling the mousewheel will zoom the camera.

**Expected behavior**

When the mouse enters the button's shape, the button is highlighted. (currently seems to use the wrong bounds?)
While the button is highlighted, scrolling the mousewheel changes the speed instead of zooming the camera. (currently reversed)

**Screenshots**
![image](https://user-images.githubusercontent.com/43236/145137843-2c749b66-14d6-4989-b2e0-bda3e4753859.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Game Version 4.25.4.0

**Comment by hakanai** [comment]
BTW you could probably do with an edit of the new bug template, to tell people how to get the information they need. Getting the version number of the game wasn't as straightforward as I thought it would be.

**Comment by johnathandarkly** [comment]
i have consistent success with the scroll wheel when hovering over the lower area of the mouse section. the top where your cursor is in the screen shot, not so much.

**Comment by nerethar0** [comment]
It works for me pretty good if i put my mouse over the yellow highlighted mousewheel in the picture

**Comment by hakanai** [comment]
Same here, but it should work in the entire area.

**Comment by hakanai** [comment]
Actually there may be something deeper at play here, because the scroll bars also don't work properly. If I drag slightly to the _left_ of the scroll handle, I can scroll them, but they don't scroll if you click directly on them. That's a bounds issue of the same sort I suspect.
