### ISSUE TITLE
[Clipping] Alet's NAPD outfit physical problem

### ISSUE THREAD

**Issue by AloRitsuko** [itsamewayu/OLFallenDoll#36]
Alet's right hand can pass through her NAPD outfit when she was standing

**Comment by jinjin525** [comment]
Better provide some pictures

**Comment by TheSoulWizard** [comment]
> Better provide some pictures

I think he's talking about that
![image](https://user-images.githubusercontent.com/40411642/147864074-2f9a0644-06f4-4588-8ec4-b4cd7818aa94.png)
