### ISSUE TITLE
Kicked out of harem mode to main screen after some time

### ISSUE THREAD

**Issue by PSsYchoOosE** [itsamewayu/OLFallenDoll#361]
**Description / Steps**
Just enter a Harem game, launch any position, and after 30 sec-1 min I got a loading screen that brings me back to the main menu

**Expected behavior**
At least an error code, but there's no reason that i'm kicked out

**Desktop (please complete the following information):**
 - OS: W10
 - Game Version 0.4.2
 - Location ; France

**Comment by poykun** [comment]
Getting the same issue US-west.

**Comment by nukacharlie** [comment]
Same here (location:france)

**Comment by Renmaru8** [comment]
Also experiencing this issue (Location: Canada-West)

**Comment by T3STUSR56565** [comment]
same, happens everytime  location: netherlands

**Comment by Foxtrot1138** [comment]
Same. Usually have enough time to start an experiment and be kicked after 20 seconds

**Comment by darthgraygor** [comment]
Same here as well, just started using a VPN just to get into harem mode, now i cant get in long enough to even finish a scene

**Comment by Infado** [comment]
Same here. 
Time to kick to the main menu is around 1 min. 
Location: Asia. 
No reason/disconnect notification etc. (network tested and not dropped during the kick)

**Comment by Otsdarva68** [comment]
Same here, US-east.
Can't play the game for longer than 1 minute, can't get through a scene without getting kicked. No error messages

**Comment by hlfblkcafe** [comment]
I am also having this exact issue (US -EAST)

**Comment by DrBeepThis** [comment]
I've been having the same issues. I tried deleting Engine.ini in %localappdata%\Paralogue\Saved\Config\WindowsNoEditor, letting the game make a new one, and seemed to fix it for now. Best guess is that there were old references in it to the previous betas borking it up. Could be a coincidence, mileage may vary.

**Comment by jinjin525** [comment]
Probably the server network issue, I'll leave this open with #101 for now.
