### ISSUE TITLE
Instant crash when entering a lobby/ Gallery Mode

### ISSUE THREAD

**Issue by PorkSoup** [itsamewayu/OLFallenDoll#362]
I run the game and press start until I find a lobby I join and I instantly crash.
 Also when entering gallery mode I crash during the loading screen.

I've uninstalled and reinstalled/ verify no avail

**Comment by Foxtrot1138** [comment]
Mine usually crashed back to main menu after about 30 seconds

**Comment by jinjin525** [comment]
We need your computer info listed when you submitting the issue and the usage when running the game.

**Comment by PorkSoup** [comment]
> We need your computer info listed when you submitting the issue and the usage when running the game.

Win10
Game Version 0.42
Processor(CPU): i7-7700
Graphics Card: GTX 1070Ti
Memory: 16GB
