### ISSUE TITLE
[UI] [Harem] Maximum SANITY Incorrect

### ISSUE THREAD

**Issue by Katakuchiiwashi** [itsamewayu/OLFallenDoll#366]
**Describe the bug**

Level 24.
But only recovered to 116.

**Screenshots**
![無題](https://user-images.githubusercontent.com/95833432/145330448-2e0d1fb4-3cee-4596-852e-1a82c7316fd7.png)

**Comment by johnathandarkly** [comment]
at level 28, its just gone up to 117/100. i guess there's a falloff / diminishing returns?
