### ISSUE TITLE
[Bug] Special animation not display

### ISSUE THREAD

**Issue by mamamiadd** [itsamewayu/OLFallenDoll#367]
**Describe the bug**
Special in scenes do not display, sometimes it shows the loading screen for a split sec and then continue without display the specials, sometimes it just doesn't show

**Expected behavior**
A special animation to happen

**Desktop (please complete the following information):**
 - OS:  Win10
 - Game Version 0.42
 Complete the following Computer Hardware Configurations if necessary:
 - Processor(CPU): i7-8700
 - Graphics Card: GTX 1070Ti
 - Memory: 16GB

**Comment by jinjin525** [comment]
Not sure if same with #200 , please take a look
