### ISSUE TITLE
The refresh rate of the mouse pointer is too low

### ISSUE THREAD

**Issue by guajun** [itsamewayu/OLFallenDoll#369]
The refresh rate of the mouse pointer is too low.
When I move the mouse, the pointer changes its position like 30 times per second or 60 times per second. This is extremely uncomfortable for me using a 170Hz refresh rate monitor.
When it is swapped to TPS mode, the refresh rate sight is low too.

**Comment by jinjin525** [comment]
We need your computer info listed when you submitting the issue and the usage when running the game.

**Comment by guajun** [comment]
![image](https://user-images.githubusercontent.com/30971821/145537043-84374510-cd79-49f4-94d3-3409e0c31162.png)
Thanks for your reply.

My computer info is:
OS：Microsoft Windows 10 家庭中文版 (BUILD:19043) (64 位)
CPU：11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
步进：1 型号：D 系列：6 扩展型号：8D 扩展系列：6
Motherboard：Micro-Star MS-1543
Memory：32.0 GB (16.0 GB / 16.0 GB / )
GPU：NVIDIA GeForce RTX 3070 Laptop GPU
Hard disk：SAMSUNG MZVL21T0HCLR-00B00 (1.0 TB)
INTEL SSDPEKNW010T8 (1.0 TB)
