### ISSUE TITLE
[Animation] male climax prevent you from exiting 

### ISSUE THREAD

**Issue by ColressOLC** [itsamewayu/OLFallenDoll#370]
**Describe the bug**
Male climax specifically is causing animation's to be stuck
when you climax with male and try to exit the animation/scene
you won't be able to do anything, unable to exit or repeat ore restart animation

**To Reproduce**
1. Go to 'Arms Held Sitting Deepthroat'
2. Click on 'make the male climax'
3. try to exit the scene
4. Scene get's stuck

**Expected behavior**
not getting stuck should end animation/scene correctly

**Additional context**
might be cause for more animation not being able to exit

**Comment by clifftor** [comment]
Should be fixed. Please reopen if this still happens
