### ISSUE TITLE
[Bug] Can't claim daily rewards from two dailes of the same task

### ISSUE THREAD

**Issue by Fenebrys** [itsamewayu/OLFallenDoll#372]
**Describe the bug**
After getting the same daily task for two dailies, I completed the requirements. It let me claim the rewards of the first one but I'm unable to claim the rewards of the second one of its type.

**To Reproduce**
1. Get a specific daily
2. Wait for dailies to reset
3. Get the same task as the one mentioned in step 1
4. Complete the requirements and try to claim the rewards

**Expected behavior**
Either it should'nt be possible to get the same task for two dailes at the same time or it should let you claim both rewards after completing.

**Screenshots**
![bug](https://user-images.githubusercontent.com/95884998/145475560-1c17e58e-8163-459d-b2ba-7e59f0a9b988.jpg)

**Desktop:**
 - OS: Win 10
 - 0.4.2
 Complete the following Computer Hardware Configurations if necessary:
 - Processor(CPU): i7-9700K
 - Graphics Card: RTX 2070
 - Memory: 16GB

**Comment by Fenebrys** [comment]
I was able to claim the duplicate tasks rewards after the first one was overwritten with a new daily task

**Comment by TheSoulWizard** [comment]
Issue present in 0.4.6 as well.
