### ISSUE TITLE
Game Restartinng PC

### ISSUE THREAD

**Issue by FarmingRice** [itsamewayu/OLFallenDoll#375]
Summary:
I've been playing the demo version game with no problems at all even on 4k and max graphics, but the closed beta version will force my computer to restart even when running on low graphic settings as well as halving the resolution to 2k after about 5 minutes of running the game. All drivers are up to date as well.

PC Specs: 
Processor- AMD Ryzen 7 5800X 8-Core Processor 3.80 GHz
Ram- 16 GB 
Operating System- 64-bit
Graphics Card- NVIDIA GeForce 3080 RTX 
Windows Version- 10

**Comment by jinjin525** [comment]
Please take a look at the Windows task manager or MSI Afterburner to check how the game is working with your CPU/Memory/GPU usage/Temperature
Also please take a look if you got the same issue as #112
