### ISSUE TITLE
[BUG]network trouble

### ISSUE THREAD

**Issue by PLZletMe1n** [itsamewayu/OLFallenDoll#378]
when i was tryiin to start the game it always shows that
![mmexport1637992284819](https://user-images.githubusercontent.com/95747913/145673533-9ae9b1f6-8de4-4353-b865-9fd6dd6d21b4.png)

**Comment by PLZletMe1n** [comment]
i tried many ways but didnt work,sometimes i can connect to the server but mostly i got kicked out from it.

**Comment by PLZletMe1n** [comment]
BTW when would you add the "public hair"

**Comment by jinjin525** [comment]
Duplicate of #81 
Check Part.7 below for EAC-related issues.
https://docs.google.com/document/d/1MHFPjbxXT7aV_9-a8rXnTaOeaQwTvVPJx88CSa0Ee6U/edit#heading=h.sieugw1ibygl
