### ISSUE TITLE
[UI] Typo - Glassic Mode

### ISSUE THREAD

**Issue by itsamewayu** [itsamewayu/OLFallenDoll#38]
ZelaSan/Zelako — Today at 12:13 AM
Need to change word from Glassic to Classic
![IMG_0874](https://user-images.githubusercontent.com/11155504/143680495-3ce3146f-2daa-41a5-a6d4-85c231fbba65.jpg)

**Comment by TheSoulWizard** [comment]
@itsamewayu @ColressOLC Fixed in 0.4.1.
