### ISSUE TITLE
[Rendering]所有贴图、人物、物件均一直渲染不出来

### ISSUE THREAD

**Issue by makuro0086** [itsamewayu/OLFallenDoll#386]
**Describe the bug**
进入（或者后来加入导致）人数大于两个人的后宫模式后所有贴图都会变得极其模糊，而且一直渲染不出来（已将抗锯齿、画质调至最低）一直在同一位置运行一个体位超过五分钟无操作，最后依旧未渲染完成。

**To Reproduce**
1. Go to '大于2人的后宫模式的房间'
2. See error

**Expected behavior**
正常渲染

**Screenshots**
![18221 939999988535_20211213205400_1](https://user-images.githubusercontent.com/96062890/145825326-3f6f679a-9c12-41e4-ae0f-b5e7a958b4b3.jpg)

**Desktop (please complete the following information):**
 - OS: [Win10]
 - Game Version [e.g. 0.42]
 Complete the following Computer Hardware Configurations if necessary:
(Dell G15 5511)
 - Processor(CPU): [i7-11800H]
 - Graphics Card:[RTX 3060]
 - Memory:[16GB]

**Comment by jinjin525** [comment]
Known Game Bug.
Try Part 3 in the linked google file.
https://docs.google.com/document/d/1MHFPjbxXT7aV_9-a8rXnTaOeaQwTvVPJx88CSa0Ee6U/edit#heading=h.sieugw1ibygl
