### ISSUE TITLE
[UI] Unable to get new daily tasks. Error when refreshing daily tasks manually

### ISSUE THREAD

**Issue by fengyin12** [itsamewayu/OLFallenDoll#389]
**Describe the bug**
The daily tasks are not updated properly. I completed the first and third daily tasks yesterday, but only the first one updated automatically, and the third daily task still seems to be counting.
Also I got an error when I tried to refresh the second daily task. (Can't click CLAIM)

**Expected behavior**
Able to update daily tasks normally

**Screenshots**
![屏幕截图(124)](https://user-images.githubusercontent.com/96066403/145978649-80e91f99-9768-4538-a769-ead3bd1bc48e.png)

**Comment by jinjin525** [comment]
Still happening in 0.45. We'll mix the issue with #411
