### ISSUE TITLE
[Animation] Threesome Kneeling Spitroast - Anya's neck does not render

### ISSUE THREAD

**Issue by apugo** [itsamewayu/OLFallenDoll#390]
Since I can see her neck at all other times, I assume it has to do with this pose specifically. In the screenshot, you can see the dreamer's penis because her neck is invisible.

https://i.imgur.com/v9QOPEe.png

**Comment by johnathandarkly** [comment]
this is a pilot suit issue, first reported in #70

**Comment by jinjin525** [comment]
Confirmed duplicate of #70
