### ISSUE TITLE
New Experiments appeared all having same image (but different descriptions)

### ISSUE THREAD

**Issue by Panthear** [itsamewayu/OLFallenDoll#393]
Just logged into Harem Mode and now see 11 new experiments, all with the same image... 
They defintiely weren't there yesterday (14-Dec-21)...

The new experiements have the following names:
AnyaGhast_Foot02
AnyaMaleAB_VaginalMouth
AnyMale_Anal07
AnyaErika_Sex03
AletMale_Vaginal17
ErikaAnya_DoubleDildo
AnyaMale_Mouth01
AletAnya_Sex02
AlexAnya_Sex03
AnyaErika_DoubleDildo
AnyaErika_DoubleDildo

**Screenshots**
![grafik](https://user-images.githubusercontent.com/95415732/146245431-f8d1abb0-eedb-4c98-974d-f495a232be68.png)

**Desktop (please complete the following information):**
 - OS: [Win7]
 - Game Version [0.42]

**Comment by Keiki-FD** [comment]
![image](https://user-images.githubusercontent.com/95418102/146249643-d297f2ce-0fe5-4ed3-a8ea-479e5ebddf0a.png)
I have even pulled one of those cards.

**Comment by Panthear** [comment]
This seems to be solved with 0.4.6. and can be closed....
