### ISSUE TITLE
Erika in Held Up Anal Tentacle

### ISSUE THREAD

**Issue by korvinx** [itsamewayu/OLFallenDoll#395]
Erika in Held Up Anal Tentacle.
If use "Special 1" then animation break. You have to stop/restart pose.

**Comment by jinjin525** [comment]
Too little information. What kind of "break"? Any screenshot or videos?

**Comment by korvinx** [comment]
Here. Break animation of pose. Need restart.
https://user-images.githubusercontent.com/9914358/146685900-67efb3f5-09c1-4687-968f-53381bc58250.mp4
