### ISSUE TITLE
[Texture] load-in Issue if not on High Settings

### ISSUE THREAD

**Issue by itsamewayu** [itsamewayu/OLFallenDoll#40]
Textures very rarely / never load properly if the game quality is set to anything but High, and the characters look straight up horrifying.
High
![497670c1d384f2fed55af26265ee04ca](https://user-images.githubusercontent.com/11155504/143680564-05cf52ff-82b7-4c02-be76-0d129d577425.png)

medium
![9366425963918afdda0c54b7d20e30b6](https://user-images.githubusercontent.com/11155504/143680569-ac7d0b7f-6278-458a-b7cb-4bfeef53d9af.png)

low
![9504afe8d49e15ec5a119fc1a971fa23](https://user-images.githubusercontent.com/11155504/143680574-6d185772-aedc-4a83-8131-b38e1130303b.png)

i let the game sit for around 2-3 minutes at that point but the textures were still blurry and not fully rendered
i can run High at around 30fps and Medium at 60fps so i used to run Medium in the 0.34 version, but the steam release doesn't load at all
it's pretty unfavorable for players with lower spec machines which is why i wanted to bring it up in case no one did already

**Comment by Lary3178** [comment]
I also ran into this issue immediately on launch. Thank you for telling me the fix I didn't know what was causing this bug.The textures don't load in at all on medium settings for me. In V0.34 I didn't have this texture bug at all so it must of been introduced with this new version. 
![20211126201407_1](https://user-images.githubusercontent.com/95135742/143685889-25fc34fa-f52f-4524-b925-ba91e4bfecfd.jpg)
