### ISSUE TITLE
[harem] [texture] missing graphics on bridge [proton]

### ISSUE THREAD

**Issue by johnathandarkly** [itsamewayu/OLFallenDoll#401]
two of the wall panels are missing textures on the bridge. files have been verified, and error shows up on my ubuntu machine, but not windows.

![20211216120330_1](https://user-images.githubusercontent.com/95413655/146604405-dde893a7-d60d-46ce-8f1b-65f98d504068.jpg)
![20211216120340_1](https://user-images.githubusercontent.com/95413655/146604406-10e4fabf-813c-4466-a552-9040651c9bc0.jpg)

**Desktop**
 - OS: Ubuntu 21.10
 - Game Version: 0.4.2
 - Processor: Ryzen 7 5700G
 - Graphics Card: internal Radeon 8 w/ 8GB allocated
 - Memory: 32GB
 - Emulator: Proton 6.3-8

**Comment by johnathandarkly** [comment]
also seeing this texture on harem loading screens

**Comment by TheSoulWizard** [comment]
You're... **emulating** a Windows game on another OS... Graphical glitches, incompatibilities and poor performance are things to be expected as the game does **not** support other OS's other than Windows 7 and up.

It's not the game's fault that you're experiencing such graphical issues, but probably Proton Emulator's instead.
