### ISSUE TITLE
[Animation] [Model] Anya's vagina and anus do not open for penetration

### ISSUE THREAD

**Issue by apugo** [itsamewayu/OLFallenDoll#402]
I don't know if it's just that her model hasn't been rigged for it yet or there's some kind of bug at play, but penises just clip into her orifices without opening them.

https://i.imgur.com/tcJW1Ug.png

It could be related to her flight suit outfit.

Also, in general, the other girls don't open quite enough for some monster dicks.

**Comment by jinjin525** [comment]
Duplicated issue.
