### ISSUE TITLE
[ui] experiment cost/color mismatch

### ISSUE THREAD

**Issue by johnathandarkly** [itsamewayu/OLFallenDoll#405]
a few experiments have the wrong color or cost, since green is usually 5 points, and blue is usually 10.

![Inked20211220050113_1_LI](https://user-images.githubusercontent.com/95413655/146759341-91ca8975-6a72-4211-bd75-25991b604cdb.jpg)
"exhausted fondling" should either cost 10 points or be purple

![Inked20211220050001_1_LI](https://user-images.githubusercontent.com/95413655/146759345-7b959b7c-a156-4036-aab1-5bd6444435ea.jpg)
 "choking standing doggy style" should either cost 5 points or be blue

there might be others, but i can only test the experiments i dont own.

**Comment by clifftor** [comment]
Fixed
