### ISSUE TITLE
[ui] unable to modify most dreamer atributes until changed in paralogue 0.34

### ISSUE THREAD

**Issue by johnathandarkly** [itsamewayu/OLFallenDoll#407]
i have been unable to modify any dreamer attribute except Full/Transparent/Hidden and Opacity in either harem or gallery mode until i modified these attributes in paralogue build 0.34. when i made the dreamer changes in 0.34 they were applied to the closed beta AND the additional controls appeared in the male customization menu.

I had the paralogue 0.34 build on my machine, but i had recently reinstalled windows, and they had not been run since that reinstall until today.

![Inked20211221060457_1_LI](https://user-images.githubusercontent.com/95413655/146920940-b4bec82f-f790-4594-9cc1-a891f6df1b0e.jpg)
_attributes in the wobbly green box Muscle Volume, Skin Color and Skin Saturation were missing until paralogue build 0.34 (or other older ones?) have been run and the dreamer had been edited. not sure if the edit part was necessary to make the 3 sliders appear._

**Desktop**
 - OS: Win 10 Home
 - Game Version: 0.4.2
 - Processor: i7-4790k
 - Graphics Card: RTX 2060 Super
 - Memory: 16GB

**Comment by jinjin525** [comment]
#10 having the same issue as being unable to change anything.
Probably related to game save files.
