### ISSUE TITLE
Harem Mode Won't Start

### ISSUE THREAD

**Issue by ElPoker** [itsamewayu/OLFallenDoll#409]
**Describe the bug**
When I select Harem Mode it goes to the loading screen and then returns me to the main menu.

**To Reproduce**
1. Go to 'Main Menu'
2. Click on 'Harem Mode'
3. See error

**Expected behavior**
I expect Harem Mode to launch

**Desktop (please complete the following information):**
 - OS: Windows 11 Home
 - Game Version 0.4.2
 Complete the following Computer Hardware Configurations if necessary:
 - Processor(CPU): AMD Ryzen 5 3400G
 - Graphics Card:Radeon Vega Graphics 
 - Memory:12GB

**Comment by KBM2** [comment]
**Describe the bug**
Almost the same:
When I select Harem Mode it goes to the loading screen and ... it stays loading endlessly.

In the Background I can see an entry mask as second screen layer, an E-Mail-adresse named
Y***********g@gmail.com is already filled in (seems chinese, not mine). Maybe that's a part of a misrouting problem?

**Comment by jinjin525** [comment]
connection problem is integrated into #101, including infinite loading and stuck in the elevator
