### ISSUE TITLE
[Harem] Anya's "handcuffed crouch anal" still can continue when weary

### ISSUE THREAD

**Issue by johnathandarkly** [itsamewayu/OLFallenDoll#410]
after a lengthy experiment with dr. anya and "handcuffed crouch anal," i achieved the ahegao state of 'dazed', then ultimately weary. she was able to continue the experiment in the 'weary' state, even though she lost her ahegao demeanor. 

![20211222142642_1](https://user-images.githubusercontent.com/95413655/147147561-6f56c4cc-076a-4707-8e7f-1a37525d02b2.jpg)
_dr. anya is hardcore, snoozing but still able to carry on._ 

it's my understanding that only 'exhausted' style experimented should be possible at this point, but i was able to continue the current experiment, and when i exited, she immediately returned to the fully rested state.

i would expect to be kicked out of the current experiment due to her exhaustion, and for the 'weary' state to remain and limit the next experiment. 

(of course, this might not be implemented yet, but i didn't see that in the plan or release notes, so just in case, here we are! :)

**Desktop**
 - OS: Win 10 Home
 - Game Version: 0.4.2
 - Processor: i7-4790k
 - Graphics Card: RTX 2060 Super
 - Memory: 16GB

**Comment by johnathandarkly** [comment]
prolonged experiments with erika produced the same post dazed behavior: ahegao expression gone and strenuous experiments could continue in "exhausted" state. i also noticed that ahegao expression only happens in later stages of "dazed".. .not sure that's intended.

**Comment by Panthear** [comment]
At least in 0.4.7. continuing an experiment when "Exhausted" (tried with "Standing Double Dildo) did not produce any more inspiration... so looks like while you can continue it now doesn't yield any benefit...
