### ISSUE TITLE
Daily Task cannot show legit task and does not refresh

### ISSUE THREAD

**Issue by drmilkdecow** [itsamewayu/OLFallenDoll#411]
**Describe the bug**
One of my daily tasks in the Harem mode does not show a proper task but only shows 'taskId:0' instead. I cannot claim the task and it does not refresh to a new task even after many days. So I am stuck with only 2 active Daily Tasks instead of 3. 

**To Reproduce**
NA

**Expected behavior**
Daily task is supposed to show a proper task and refresh regularly. 

**Screenshots**
See attached
![Capture](https://user-images.githubusercontent.com/95328819/147319355-39930a0b-095d-47e4-a281-72a21b914fb8.JPG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Game Version 0.42
 Complete the following Computer Hardware Configurations if necessary:
- NA

**Comment by clifftor** [comment]
Please advise if you still find this issue after the 0.4.5 update.

**Comment by drmilkdecow** [comment]
> Please advise if you still find this issue after the 0.4.5 update.

Hi, I just checked yesterday and the issue is still there. 

If it helps my player ID is Eve1977.

**Comment by Agent7427** [comment]
Can confirm issue still persists in 0.45. I have had this issue with 2 of the daily quests not resetting for days and now similar to the OP's photo the 3rd one has a bugged Claim button.

**Comment by drmilkdecow** [comment]
My issue with this has been recently resolved.
