### ISSUE TITLE
Speed up animations/transitions for the game

### ISSUE THREAD

**Issue by drmilkdecow** [itsamewayu/OLFallenDoll#412]
**Is your feature request related to a problem? Please describe.**
The animation for the cards flipping, orgasm, sex scenes, etc is great. However when we play too often (and try to complete certain tasks to get the daily rewards), the long waiting time between the animations (eg. orgasm, pull out, restart) can be very very very tedious and frustrating after some time. 

**Describe the solution you'd like**
Create an option to speed up or skip the animation transition so the waiting time can be reduced dramatically. 

**Describe alternatives you've considered**
No alternatives

**Additional context**

**Comment by johnathandarkly** [comment]
i'd like quicker card flipping, but that's it.

**Comment by jinjin525** [comment]
Similar request as #144

**Comment by solidkazuma** [comment]
Not just the animation of the screen but the sex animation speed as well
