### ISSUE TITLE
Client crash with null reference

### ISSUE THREAD

**Issue by clara10159** [itsamewayu/OLFallenDoll#413]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Win10/Ubuntu 20.04]
 - Game Version [e.g. 0.42]
 Complete the following Computer Hardware Configurations if necessary:
 - Processor(CPU): [e.g. i7-9700K]
 - Graphics Card:[e.g. RTX 2070s]
 - Memory:[e.g. 16GB]

*If your game crashed, remember to upload the dmp file with your issue.

It's located in C:\Users\ (USER ID) \AppData\Local\Paralogue

**Additional context**
![Screenshot (20)](https://user-images.githubusercontent.com/96642890/147377828-82e9ee97-83a4-4a06-8e63-1dcf04bfddbd.png)

**Comment by jinjin525** [comment]
Please upload the crash file with your issue report.
How to do it is mentioned when you submit the issue.

**Comment by jinjin525** [comment]
Also please do not submit the same issue twice.

**Comment by clara10159** [comment]
I want looking for the crash report file today but I could not find it using file explorer. I am also sorry I submitted two claims. 
Thank you, Clara 

Sent from Yahoo Mail on Android 
 
  On Wed, Dec 29, 2021 at 12:37 AM, ***@***.***> wrote:   


Reopened #413.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
