### ISSUE TITLE
Fallen Doll Harem Mode Video Card Memory Issue

### ISSUE THREAD

**Issue by purespoo** [itsamewayu/OLFallenDoll#415]
**Describe the bug**
Just assuming there's a memory leak. Sometimes the game starts up just fine. I don't have to do anything really.
Then at spontaneous times throughout playing the game it crashes saying the game is trying to allocate more memory on my video card than is available. My card is Nvidia GTX 1080 with 16gb of RAM. Not top of  the line but not an infant either. No other game does this. The demo non-harem mode does not crash at all.

**To Reproduce**
1. Play the game on GTX 1080 wait for awhile. Game crashes.

**Expected behavior**
A game that doesn't crash between 5 - 60 minutes into it.

**Desktop (please complete the following information):**
 - OS: Win 10
 - Game Version  0.42
 Complete the following Computer Hardware Configurations if necessary:
 - Processor(CPU): Intel(R) Core(TM) i7-7700 @ 3.60 GHz (8 CPUs) 
 - Graphics Card: NVIDIA GeForce GTX 1080
 - Memory: 16GB,     
 - Memory Card Memory: 16GB, 8GB Display Memory, 8GB Shared Memory

*If your game crashed, remember to upload the dmp file with your issue.

It's located in C:\Users\ (USER ID) \AppData\Local\Paralogue

**Additional context**

**Comment by jinjin525** [comment]
You should be able to find the crash game file in C:\Users\ (USER ID) \AppData\Local\Paralogue.
Submit those files if you can.
