### ISSUE TITLE
Can't place scenes, give likes, or study poses

### ISSUE THREAD

**Issue by beetalogist** [itsamewayu/OLFallenDoll#418]
**Describe the bug**
Can't place most scenes, nor give any likes to players, nor study scenes from other players.
Also game crashed during attempt to study a scene, dmp file attached.

**To Reproduce**
Try placing any scene. Literally any one with any character. It will not work.
Try giving likes to players. They don't deduct inspiration nor give the player a like.
Try studying scenes. Inspiration is not deducted and no scene is studied.
I tried testing every scene with each character combination, and the only one I could get to display at all was a threesome scene with Erika, the Spawn, and the Byakhee.

**Expected behavior**
Scenes should begin shortly after mousing over the correct location and left-clicking.
Sending likes to players should reduce inspiration and bestow a like upon them.
Studying a scene should reduce inspiration and add the scene to your inventory for 24 hours.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Game Version 0.4.5
 
*If your game crashed, remember to upload the dmp file with your issue.

It's located in C:\Users\ (USER ID) \AppData\Local\Paralogue
[UE4Minidump.zip](https://github.com/itsamewayu/OLFallenDoll/files/7778992/UE4Minidump.zip)

DMP file attached.

**Additional context**

**Comment by johnathandarkly** [comment]
I'm in the same boat. I have a full inspiration window, but can't give likes or place experiments. like's make a cute noise, but no text indicating a like was given, and my inspiration wheel remains full. I can target experiments for placement, but they won't start. 

**Desktop**
 - OS: Win 10 Home
 - Game Version: 0.4.2
 - Processor: i7-4790k
 - Graphics Card: RTX 2060 Super
 - Memory: 16GB

**Comment by clifftor** [comment]
The new update should have addressed this issue.
Could you advise if you are still experiencing this issue?

**Comment by beetalogist** [comment]
This issue appears to be resolved now.
