### ISSUE TITLE
[Performance] Unable to Turn Off Motion Blur And V-Sync

### ISSUE THREAD

**Issue by ysy95109** [itsamewayu/OLFallenDoll#42]
Motion blur and v-sync are still active despite appearing as turned off in the options menu.

**Comment by TheSoulWizard** [comment]
Same with the v-sync. Im unable to get over 60 FPS. They won't unlock. (its not my GPU)

**Comment by jinjin525** [comment]
Duplicate of #17 about motion blur.
Discussion moves to Issue No.17.
