### ISSUE TITLE
Experiments previsualizations not correspond with the experiment itself

### ISSUE THREAD

**Issue by AloRitsuko** [itsamewayu/OLFallenDoll#420]
The 3D previsualizations (or the "ghosts") of experiments might be not correspond with the experiment itself
(SAME AS THE TITLE)

**Comment by clifftor** [comment]
Could you elaborate on this issue?
How to reproduce this exactly, like which experiments for example?

**Comment by AloRitsuko** [comment]
Alet x Lloigor（crane）

**Comment by AloRitsuko** [comment]
> 

Nope, the issue itself was reported by another user, but he couldn't remember which one

**Comment by AloRitsuko** [comment]
It's an experiment related to Anya
