### ISSUE TITLE
Harem mode still not working for me

### ISSUE THREAD

**Issue by Antex3** [itsamewayu/OLFallenDoll#421]
Describe the bug
Title says it all

To Reproduce
1. Open game
2. Click on Harem mode
4. Loads a few seconds
5. Gets kicked back to title screen

Expected behavior
I expect to be able to enter and at least play the game

Desktop (please complete the following information):
 - OS: Windows 10
 - Game Version: Ver 4.1 to 4.5
 - Processor(CPU): Ryzen 1500X
 - Graphics Card: GTX 1050Ti
 - Memory: 24GB

Additional context
I have been able to play the game fine in Gallery mode, and the day the game launched in 4.0 I was able to play the game fine with the exceptions of the bugs that everyone else was having, so it definitely not my specs.

**Comment by clifftor** [comment]
Please advise if you are *kicked* or *stuck* on the loading screen.
Please try verify the integrity of the game first if you are kicked back to title screen.

For anyone who's still stuck in the loading screen or still see this after verified the game integrity, could you please provide:
1. Which loading screen you are stuck in?
2. What is the region you are in?
3. Did you use a VPN?
4. Did you use a firewall?
5. What is your in-game id

You can alternatively ping me in discord for this information.

**Comment by Antex3** [comment]
1. I get stuck on the loading screen after I click on 'Harem' after a few seconds it brings me back to the main menu.
2. I am in the U.S.
3. No VPN
4. No firewall
5. Not sure about my ID but the name I used when I was able to play was Antex.

**Comment by johnathandarkly** [comment]
was able to play 0.4.5 on 27dec until 5am, by 11am, was unable to return to harem.

**Describe The Problem**
- click harem from title
- get loading hex  for 10+ seconds
- switches to full loading screen
- drops back to title screen after 2 seconds.

**Details**
- usa east (washington dc area)
- with and without vpn
- with and without bitdefender
- id: "johnathan darkly"

**Desktop**
 - OS: Win 10 Home
 - Game Version: 0.4.2
 - Processor: i7-4790k
 - Graphics Card: RTX 2060 Super
 - Memory: 16GB

**Comment by Gocubs2** [comment]
same thing since 0.4.1. tried everything. 've been reporting this problen about 2 weeks. no progress :c

**Comment by johnathandarkly** [comment]
just checked ver 0.4.7, and no change. anyone else have any luck?

**Comment by johnathandarkly** [comment]
threw in a 256gb ssd in my ryzen 7 build and installed windows 11 and the latest ati drivers. prolly the only "modern" processor in the house. same issue. gallery fine, harem drops to title a few seconds on the full loading screen with the spinny thing on the bottom right.

Desktop

    OS: Windows 11
    Game Version: 0.4.7
    Processor: Ryzen 7 5700G 3.8ghz
    Graphics: Integrated Radeon 8 "Raven" 2.0ghz w/ 8GB allocated
    Memory: 32GB

**Comment by johnathandarkly** [comment]
just for fun, here's a video of exactly what's happening, and not happening. https://youtu.be/9VjA6MEI9oQ

**Comment by johnathandarkly** [comment]
my error is most likely due to a corrupt server side data, i am able to enter harem mode with another test account. the error still exists on my main account, but i suspect this might be solved in the great user data wipe happening later in the year.
