### ISSUE TITLE
New Pose in 0.4.5 does not produce "Inspiration"

### ISSUE THREAD

**Issue by Panthear** [itsamewayu/OLFallenDoll#424]
Just got the new Pose "Front to Rear Double Double Dildo".
However this new pose does not seem to generate Inspiration.

No matter if single heart or double heart is clicked.

Also on Double Heart the typical message that "Erika gives you a like" is also not happening.

![grafik](https://user-images.githubusercontent.com/95415732/147491223-46fe57db-d1c7-4faf-b169-b329d74b6671.png)

**To Reproduce**
Simple select the Pose and wait...

**Expected behavior**
Inspiration produced

**Desktop (please complete the following information):**
 - OS: Win7
 - Game Version 0.45

PS: Restarted Game to double check: Same problem.

**Comment by poykun** [comment]
Verified the same issue on my end. Also, judging by chatter in discord, it might be all of the new experiments introduced in 4.5

**Comment by clifftor** [comment]
There are multiple new poses that doesn't give "Inspiration". Tracking all of them in this issue.

**Comment by poykun** [comment]
4.6 Update
I've tested out the following and they have given inspiration:
Kneeling One Handed Blow Job (Anya x Dreamer)
Reverse Lying Down Footjob (Anya x Ghast)
Cowgirl Doulbe Dildo (Anya x Erika)

**Comment by Panthear** [comment]
Inspiration now is produced, however there now seems to be a problem when climax at the same time, which normally gives a like...
For the new pose it doesn't:

As you can see: Normally when it says "Erika gives you a like" you get a Like (Like counter increased). If you do that with any old pose it works. On the new pose this seems to be broken, and I believe this is connected to the same issue as with the inspiration. 
PS: If this is better with another bug, let me know and I open a new one...

![20220105213207_1](https://user-images.githubusercontent.com/95415732/148393919-c2657a96-b3ef-4390-a25e-256a82d43e91.jpg)
![20220105213212_1](https://user-images.githubusercontent.com/95415732/148393925-4b2c99b7-41a1-4052-8ffd-275fbdf19122.jpg)

**Comment by Panthear** [comment]
Forget the last entry... likes now working with 0.4.7. at least for the experiment above.
So from my point bug can be closed.
