### ISSUE TITLE
[Model] Dr. Anya Pilot Suit

### ISSUE THREAD

**Issue by LeoMachiavelli** [itsamewayu/OLFallenDoll#425]
When using the Pilot Suit for Dr. Anya and selecting Upper Apparel as Half dressed. You can produce a noticeable gap between her head and body, you can see right through her neck essentially. It is visible on all places that model can be used.

**Comment by johnathandarkly** [comment]
duplicate of #70

**Comment by jinjin525** [comment]
Confirmed duplicate of #70
