### ISSUE TITLE
Buttons missing under player profile

### ISSUE THREAD

**Issue by drmilkdecow** [itsamewayu/OLFallenDoll#428]
**Describe the bug**
Are there supposed to be buttons or interface under the players profile? I realize that mine is empty. I also realized that other players can give me Likes 'mid-action' but I have to exit out from the 'action-phase' to give likes. 

**Screenshots**
See attached
![FD Error](https://user-images.githubusercontent.com/95328819/147526597-fb3bbb9d-bf37-4110-88aa-1033e2f6b2ac.JPG)

**Desktop (please complete the following information):**
 - OS: [e.g. Win10
 - Game Version 0.4.5

**Comment by TheSoulWizard** [comment]
Yes, but the devs temporary removed them due to a bug. They are aware of it.

**Comment by itsamewayu** [comment]
Removing of the buttons was intentional for now
