### ISSUE TITLE
Experiment has some problems

### ISSUE THREAD

**Issue by AloRitsuko** [itsamewayu/OLFallenDoll#429]
![图片](https://user-images.githubusercontent.com/95129072/147528964-f9d8f684-81df-4b4a-9cf6-938d5896fa9e.png)
the furniture can't be correctly highlighted and the angle is also not correct

**Comment by jinjin525** [comment]
Please provide some screenshot about this issue

**Comment by AloRitsuko** [comment]
![20211229174913_1](https://user-images.githubusercontent.com/95129072/147649510-79bbf775-dc54-445c-b7ff-e71bd48e985e.jpg)
![20211229174936_1](https://user-images.githubusercontent.com/95129072/147649511-ff064d18-ca6c-415a-ba47-0c9167c4329e.jpg)
