### ISSUE TITLE
Harem Mode - Crash to either black screen or Out of Memory Error

### ISSUE THREAD

**Issue by Psychoham** [itsamewayu/OLFallenDoll#431]
This occurs for me almost every time in Harem mode, usually within five minutes. I have tried multiple combinations of resolutions, textures etc, but I still receive the error. I have attached the image of the error message;

![image](https://user-images.githubusercontent.com/95140743/147572791-6e2bf0e9-d1c7-4c89-b492-5ad44c936782.jpeg)

- OS: Windows 10
- Game Version 0.45
- Processor(CPU): AMD Ryzen 5 3600
- Graphics Card: GeForce GTX 1650
- Memory: 4GB 

Link to DMP file:

https://1drv.ms/u/s!Aq2EmA2CiZFhwk7Y7YnhUPAgxVoT

**Additional context**
This bug has occurred in Harem in all builds. Gallery mode works perfectly however.

**Comment by Psychoham** [comment]
Workaround is to amend pagefile to a larger size. Have tested and can confirm this to work. 

Would still appear to be game specific though.

**Comment by jinjin525** [comment]
Your memory(4GB) is too low to meet the lowest requirement of this game.

**Comment by Psychoham** [comment]
Thanks, I didn't see the minimum listed on the steam page. 

However, this fix seems to have made mine stable, so happy days :)
