### ISSUE TITLE
[Harem] Players disappearing rapidly with no reason

### ISSUE THREAD

**Issue by ATE2336** [itsamewayu/OLFallenDoll#432]
**Describe the bug**
There is a red heart icon above "visible" icon. Please be sure this is a normal bug, because when this icon appears, player list is refreshing as quickly as I can see. Then no normal player exists, and yes, I'm out too.

**To Reproduce**
There is any possibility that is how you kill dead or lazy player threading. And so, it's a bug or someone's vicious assault.

**Expected behavior**
Players are squeezed out of the room.

**Screenshots**
![屏幕截图 2021-12-28 234010](https://user-images.githubusercontent.com/95136466/147585200-bc757a8d-f194-4572-afe6-e107405b444f.png)
![屏幕截图 2021-12-28 2340101](https://user-images.githubusercontent.com/95136466/147585212-da6a5cc6-5110-48a5-a32b-335a100fe20b.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Game Version 0.4.5
 Complete the following Computer Hardware Configurations if necessary:
 - Processor(CPU): 3900x
 - Graphics Card:RTX 2070s
 - Memory: 32GB

**Comment by TheSoulWizard** [comment]
A weird looking UI doesn't represent a network attack... It's a bug.

**Comment by poykun** [comment]
We're referring this as the Thanos snap bug in discord.

**Comment by jinjin525** [comment]
Well let me conclude the "player list is refreshing" and "Thanos snap"?
Players in the same lobby will randomly disappear(disconnected due to poor network maybe?) , sometimes the UI no longer shows some player but that player is actually in the lobby. If you insist to do experiments then issue #434 would appear. But I still don't know if this is related with that red heart icon rather than a UI bug in this case.

**Comment by jinjin525** [comment]
Should be something related to "- Players not active for prolonged periods (AFK) will be sent offline." in patch 0.45

**Comment by ATE2336** [comment]
What does this icon mean? Is it a design?

**Comment by ATE2336** [comment]
Hahaha, not just half players are out. Everyone! It's worse than Thanos snap.
