### ISSUE TITLE
[Animation] Anya/Elder Thing has no ejaculate effect

### ISSUE THREAD

**Issue by LeoMachiavelli** [itsamewayu/OLFallenDoll#433]
**Describe the bug**
During all poses/scenes with Anya and Elder thing when available using the "cum outside" feature doesn't produce any visible effect or render the visible ejaculation. Also inturn doesn't show actual semen on Anya after. This bug wasn't present on 0.34 build.

**To Reproduce**
1. Go to 'Workshop > Anya/Elder Thing'
2. Click on 'Any Option'
3. Scroll down to 'Use "Cum outside" when prompted'

**Expected behavior**
Visible Ejaculation effect.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Win10]
 - Game Version [0.45]
 Complete the following Computer Hardware Configurations if necessary:
 - Processor(CPU): [AMD FX-8350]
 - Graphics Card:[Nvidia GTX 1070]
 - Memory:[8GB]

**Comment by jinjin525** [comment]
Similar to issue #221
