### ISSUE TITLE
[Harem] Placing Experiment Down results in view from the center of the elevator 4.5 issue

### ISSUE THREAD

**Issue by Awfulwaffle1** [itsamewayu/OLFallenDoll#434]
**Describe the bug**
Placing Experiment Down results in view from the center of the elevator. Upon aborting the animation, the player is now standing back in the elevator and cannot move. ~~This is intermittent and does not happen 100% of the time.~~
This seems related to the thanos snap bug #432. Once this happens the following below can be done in the lobby.

**To Reproduce**
1. place down an experiment.
2. Observe.
3. If the Elevator view occurs, hit the ESC key
4. Attempt to move around

**Expected behavior**
Regular execution of experiments.

**Comment by beetalogist** [comment]
Experiencing this issue as well.

**Comment by HenriqueLin** [comment]
Had the same issue today, by using the following experiment
![image](https://user-images.githubusercontent.com/47987376/147607257-1cec186c-6c59-4e45-8ad3-b0824a2dce97.png)

**Comment by Agent7427** [comment]
This issue seems common with 0.45. The experiment when being placed doesn't activate and instead "warps" user to the central elevator in a frozen state but still with active camera control.

**Comment by bbutton92** [comment]
This happens to me 100% of the time :(

**Comment by poykun** [comment]
With the servers being more stable, I have not had this happen in quite some time. I'll leave this open for a bit for monitoring.
