### ISSUE TITLE
[Harem] [Camera] Glitch with Erika's "Held Up Anal Tentacle" experiment

### ISSUE THREAD

**Issue by HalcyonAnd0n** [itsamewayu/OLFallenDoll#436]
**Describe the bug**
When placing this experiment at one specific location, the camera goes into Erika's body and will not move.

**To Reproduce**
1. Go to the Workshop area
2. Place the experiment at the location shown in the attached image

**Screenshots**
![Erika_PoseGlitchArea](https://user-images.githubusercontent.com/95422572/147609448-31b1c019-7fa9-4c76-9f00-c3bed6be0342.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Game Version 0.4.5

**Additional context**
Video of the bug happening (at the end where I'm moving the cursor around, that is me left click dragging and the camera not panning):

https://user-images.githubusercontent.com/95422572/147611528-3d10a336-b1bc-4842-985b-1050358d6e42.mp4

**Comment by poykun** [comment]
There's a bug where learned experiments remains active after the 24 hour period. Can you verify you own this experiment?

**Comment by HalcyonAnd0n** [comment]
This is a camera related issue, maybe you responded to the wrong post? @poykun

**Comment by poykun** [comment]
Ahhh i gotcha. My bad I misunderstood the issue. I reproduced that on my end as well. My apologies!

**Comment by HalcyonAnd0n** [comment]
No problem at all, happens.
