### ISSUE TITLE
[Harem] Mislabeling of Experiments 4.5 Issue

### ISSUE THREAD

**Issue by poykun** [itsamewayu/OLFallenDoll#438]
**Describe the bug**
Possible mislabeling of experiments as they do not match the preview image on the card or the animation when experiment is executed.

**To Reproduce**
1. Go to Harem
2. Click on one of the following experiments below
3. Observe the title of the experiment
4. Observe the preview image on the experiment
5. Execute Experiment
6. Observe

**Expected behavior**
Preview Image and Animation should match the title of the experiment

**Screenshots**
**Card Title**: Cowgirl Double Dildo
**Possible Correction**: Standing Double Dildo
![Cowgirl Double Dildo](https://user-images.githubusercontent.com/95268330/147617353-b3a5b4f1-7aaa-4ff4-ba1f-0b978396a57a.jpg)

**Card Title**: Dildo Held Rear Entry
**Possible Correction**: Laying Down Cowgirl
![Dildo Held Rear Entry](https://user-images.githubusercontent.com/95268330/147617387-ee48d389-457f-41e1-b54a-04d5fc4a4a4e.jpg)

**Card Title**: Front to Rear Double Dildo
**Possible Correction**: Cowgirl Double Dildo
![Front to Rear Double Dildo](https://user-images.githubusercontent.com/95268330/147617448-062a2b2d-9c83-446b-b27b-c57e380ff0a7.jpg)

**Card Title**: Kneeling One Handed Blowjob
**Possible Correction**: Dildo Held Rear Entry???
![Kneeling One Handed Blowjob](https://user-images.githubusercontent.com/95268330/147617478-282728e3-bf02-489f-a4a1-d337427d6708.jpg)

**Card Title**: Laying Down Cowgirl
**Possible Correction**: Raised Cunnilingus
![Laying Down Cowgirl](https://user-images.githubusercontent.com/95268330/147617507-a11a7b69-351a-4c59-b0a0-90b0aa618bac.jpg)

**Card Title**: Raised Cunnilingus
**Possible Correction**: Kneeling One Handed Blowjob
![Raised Cunnilingus](https://user-images.githubusercontent.com/95268330/147617707-e3ded36d-ad7d-4482-981f-45e855173219.jpg)

**Card Title**: Sitting Cunnilingus
**Possible Correction**: Exhausted Lying Down
![Sitting Cunnilingus](https://user-images.githubusercontent.com/95268330/147617723-1fc4c848-4915-4e62-acaa-09e3beb699cd.jpg)

**Card Title**: Exhausted Lying Down
**Possible Correction**: Sitting Splitroast
![Exhausted Lying Down](https://user-images.githubusercontent.com/95268330/147617763-82afd084-33fc-4697-b2f1-7f259ef95ebc.jpg)

**Card Title**: Sitting Splitroast
**Possible Correction**: ???
![Split Roast](https://user-images.githubusercontent.com/95268330/147617804-6a6030c4-e154-4fb6-8b49-104139e0bf13.jpg)

**Card Title**: Standing Double Dildo
**Possible Correction**: Sitting Cunnilingus
![Standing Double Dildo](https://user-images.githubusercontent.com/95268330/147617943-2a7facf6-1329-4cbc-bd01-9c238e1895d3.jpg)

This one filename standard titled card.
**Card Title**: AletMale_Vagina05
**Possible Correction**: ???
![Generic Title](https://user-images.githubusercontent.com/95268330/147617970-04415309-1b03-4ccc-b3d7-d98842d5bc58.jpg)

**Comment by TheSoulWizard** [comment]
I believe that happened in version 0.4.5 when new poses were added. In the translation form, everything appears to be right.

**Comment by poykun** [comment]
All looks good, save for the AletMale_Vagina05 card. That still remains with the generic file title. Closing
