### ISSUE TITLE
[Model] Erika's feet changes when changing the state of Orthodox Bunny Girl costume

### ISSUE THREAD

**Issue by ogmecha** [itsamewayu/OLFallenDoll#439]
Erika's feet change when changing the state of the Orthodox Bunny Girl costume from Dressed to Nude in poses. Seems to only change while the leggings are off. 

**To Reproduce**
1. Go to Outfits setting while wearing the costume
2. Change from dressed to nude
3. Profit?

**Expected behavior**
feet shouldnt change 

**Screenshots**

![20211228192820_1](https://user-images.githubusercontent.com/59389558/147626733-36ebc265-8aae-4538-94f2-46b0fa58e826.jpg)

![20211228192823_1](https://user-images.githubusercontent.com/59389558/147626738-4c1a468d-4b4b-42db-acf8-602015720d5d.jpg)

**Desktop (please complete the following information):**
 - OS: win10
 - Game Version 0.4.5

**Comment by jinjin525** [comment]
Seems similar with issue #58

**Comment by TheSoulWizard** [comment]
> Seems similar with issue #58

It's on a different pose. 

It seems like the devs shrinked the size of the feet to prevent clipping when wearing shoes, but they should've come back to normal on a nude state.

The issue #58 is indeed the same bug, but it should be addressed since its on a different pose.

**Comment by ogmecha** [comment]
it may be the same. it isnt pose exclusive
