### ISSUE TITLE
[Harem] Missing outfits

### ISSUE THREAD

**Issue by LeoMachiavelli** [itsamewayu/OLFallenDoll#441]
**Describe the bug**
Anya's Commander suit is not show as a purchase outfit in menu, along with several others. Others have been seen using it. Also both other harem girls have all their default costumers available to buy.

**Desktop (please complete the following information):**
 - OS: [e.g. Win10/Ubuntu 20.04]
 - Game Version [0.4.5]

![Paralogue-Win64-Shipping_2021_12_28_14_20_17_339](https://user-images.githubusercontent.com/96741284/147700406-08fe2a2e-eab8-4fed-a85d-67eba155f043.jpg)

**Comment by LeoMachiavelli** [comment]
Just want to update that the most recent update (0.4.6) unfortunately didn't solve this issue.

**Comment by TheSoulWizard** [comment]
Some outfits can only be obtained from the store (Peer Review Committee) which rerolls every week. 
Maybe that's the case as i already own Voivode Commander suit, but i do not remember how i obtained it.
