### ISSUE TITLE
Daily inspiration did not update

### ISSUE THREAD

**Issue by drmilkdecow** [itsamewayu/OLFallenDoll#442]
**Describe the bug**
My daily inspiration did not update when I logged into Harem mode today. I received the popup of the 3 inspiration points but it was not added to my pool. 

**Expected behavior**
I originally had 3 inspiration points so when I logged in today, I should have a total of 6, but currently it still stands at 3 points. 

My ID is Eve1977

**Screenshots**
![Capture](https://user-images.githubusercontent.com/95328819/147715985-770d2315-8009-446c-b9ee-4978ceceb3e8.JPG)

**Desktop (please complete the following information):**
 - OS: [e.g. Win10]
 - Game Version [e.g. 0.4.2.5]

**Comment by poykun** [comment]
Inspiration would be the meter to your upper-right corner of the screen (not shown in the screenshot). What you have currently circled is Insight.
