### ISSUE TITLE
Steam freezes on attempt to download the beta game

### ISSUE THREAD

**Issue by blake2740** [itsamewayu/OLFallenDoll#443]
**Describe the bug**
Steam freezes on attempt to download

**To Reproduce**
1. Log on to steam
2. Click on download button 
3. See error

**Expected behavior**
starting download

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win10

**Comment by poykun** [comment]
Read up multiple instances of this and it might comedown to hardware issue if a reinstall of steam doesn't work.
HDD, mobo drivers, RAM.

Update: looks like it was a faulty drive.

**Comment by itsamewayu** [comment]
Issue looks resolved?
