### ISSUE TITLE
[harem] fatal error when attempting to enter harem

### ISSUE THREAD

**Issue by johnathandarkly** [itsamewayu/OLFallenDoll#448]
**Describe the bug**
- fatal error when attempting to enter harem for the first time since 0.4.6 patch.
- additional attempts just return to main menu at last step instead of throwing error.
- unable to enter harem since minor patch that happened AFTER 0.4.5 dropped. 0.4.5 worked for 6 hours after i updated, then there was another build pushed and kerplop.

**To Reproduce**
- clicked "harem" from main menu
- selected server (any)
- loading hex displayed
- full screen graphic displays for 2-3 seconds, spinner stops at horizontal
- "fatal error" modal appears
- sadness

**Expected behavior**
- entering harem
- happiness

**Desktop**
 - OS: Win 10 Home
 - Game Version: 0.4.6
 - Processor: i7-4790k
 - Graphics Card: RTX 2060 Super
 - Memory: 16GB

**Error Data**
- ol user: johnathan darkly
- steam: jdarkly
- [UE4Minidump.zip](https://github.com/itsamewayu/OLFallenDoll/files/7797589/UE4Minidump.zip)

**Comment by johnathandarkly** [comment]
I get the same results as above on an older notebook, no error, but a quick return to title when trying to enter harem. 

2.3ghz AMD A10-4600M quadcore APU with Radeon HD Graphics
16 GB 
Windows 10
Operation Lovecraft: 4.6.0

**Comment by johnathandarkly** [comment]
this prolly belongs as a part of #421

**Comment by johnathandarkly** [comment]
situation unchanged with ver 0.4.7

**Comment by johnathandarkly** [comment]
i just saw this error from all the way back at #86. is this really the same problem since november?

**Comment by albievalzak** [comment]
same issue repeatedly

**Comment by johnathandarkly** [comment]
threw in a 256gb ssd in my ryzen 7 build and installed windows 11 and the latest ati drivers. prolly the only "modern" processor in the house. same issue. gallery fine, harem drops to title a few seconds on the full loading screen with the spinny thing on the bottom right.

**Desktop**
 - OS: Windows 11
 - Game Version: 0.4.7
 - Processor: Ryzen 7 5700G 3.8ghz
 - Graphics:  Integrated Radeon 8 "Raven" 2.0ghz w/ 8GB allocated
 - Memory: 32GB

**Comment by johnathandarkly** [comment]
harem being denied and nice music for 33 seconds or so. https://youtu.be/9VjA6MEI9oQ

**Comment by johnathandarkly** [comment]
yep, new patch produces no change. just about 4 weeks and no access to harem now. just in case its an old processor problem ill check the new build

**Desktop**
 - OS: Win 10 Home
 - Game Version: 0.4.8
 - Processor: i7-4790k
 - Graphics Card: RTX 2060 Super
 - Memory: 16GB

**Comment by johnathandarkly** [comment]
win 10 / i7-4790k build works fine with alternate account. primary account still fails at same part of loading after successful harem access with test account. i have to believe the primary account is corrupt, possibly a connection drop or switching between windows and linux builds? who knows.
