### ISSUE TITLE
I have some bug feedback about the lens not showing up and as I am Chinese and don't speak English very well, I hope you can read it, please understand.

### ISSUE THREAD

**Issue by SUIXIN9HAO** [itsamewayu/OLFallenDoll#45]
Here is the English version：

Workshops not shown.
Arete Roigel 
Missionary position not shown

Anya The Ancient One 
Anya & the Ancient One Sexual intercourse 04 not shown

Anya Dreamwalker
AnyaX male handjob 02 not shown

Anya Arette
Tarzan's Cunnilingus no show

Arete Anya
Tarzan's Cunnilingus no show

Arete Dreamwalker
Forced anal sex in back position no show

Lab no show.
Arette, Erica.
Scissors position not shown

Alette, Erica
Reverse female top position a little crooked

Alette Dreamwalker
Kneeling oral sex not shown

Arette Mixed breed deep diver
Standing behind position not shown

Erika, Alette
Scissors position not shown

Erica Arlette
Reverse female top position slightly crooked

Anya Dreamwalker
Pressed standing behind position not shown

Here is the Chinese version：

工坊无显示：
阿蕾特 罗伊格尔 
传教士体位无显示

安雅 古老者 
安雅＆古老者 性交04无显示

安雅 梦行者
AnyaX男性手交02无显示

安雅 阿蕾特
泰山压顶舔阴无显示

阿蕾特 安雅
泰山压顶舔阴无显示

阿蕾特 梦行者
背后位强迫肛交无显示

实验室无显示：
阿蕾特 艾丽卡
剪刀位无显示

阿蕾特 艾丽卡
反向女上位有点歪

阿蕾特 梦行者
跪姿口交无显示

阿蕾特 混种深潜者
站立背后位无显示

艾丽卡 阿蕾特
剪刀位无显示

艾丽卡 阿蕾特
反向女上位有点歪

安雅 梦行者
压身站立背后位无显示

**Comment by ysy95109** [comment]
中文报告没问题的

**Comment by itsamewayu** [comment]
Already included and separated into their own issue threads
