### ISSUE TITLE
What button does this do? I see an alert but I cannot click on it

### ISSUE THREAD

**Issue by drmilkdecow** [itsamewayu/OLFallenDoll#450]
**Describe the bug**
3rd button on the right cannot be clicked despite showing a 'notification' alert

**Screenshots**
See attached
![Capture](https://user-images.githubusercontent.com/95328819/147852400-43c3267f-e6bb-4619-95e8-cb09d3b9f222.JPG)

**Desktop (please complete the following information):**
 - OS: Win10
 - Game Version 0.4.2.6

**Comment by itsamewayu** [comment]
It's meant to be a news update button, currently doesn't work, also a duplicate issue
