### ISSUE TITLE
An experiment cannot be placed  

### ISSUE THREAD

**Issue by wssth0306** [itsamewayu/OLFallenDoll#451]
Choking standing Doggystyle cannot be placed 

**To Reproduce**
1. Select Erika
2. Select Dreamer
3. Select experiment said below 
4.![expirment](https://user-images.githubusercontent.com/96948543/147854015-6682b5b0-6ad3-4b76-b0d6-8f15e07621d2.jpg)
4.Go to the highlighted prop
5.The experiment will snap to it's intended place but cannot be placed 
6.![expirment_pos](https://user-images.githubusercontent.com/96948543/147854068-8d6450a7-8275-4284-b6e5-de5b27635a9a.jpg)

**Expected behavior**
Green light to place the experiment 

**Desktop (please complete the following information):**
 - OS: Win10
 - Game Version  0.4.6
 Complete the following Computer Hardware Configurations if necessary:
 - Processor(CPU):  i7-8700
 - Graphics Card: RTX 2070s
 - Memory:16GB

**Additional context**
this bug has been in game since 0.4.5 and this experiment doesn't show up when in title screen

**Comment by istalo** [comment]
As of 0.4.9 I can confirm that this still doesn't work, animation doesn't even show on the full experiment list on the cahnging room.
