### ISSUE TITLE
There may be some bugs in daily tasks

### ISSUE THREAD

**Issue by christine-chris** [itsamewayu/OLFallenDoll#456]
I got two identical tasks yesterday.And when I completed one of them, the another was indicated completed. But I can't get a reward for the another one.

![image](https://user-images.githubusercontent.com/95476408/147863563-2333a9a6-b2a1-41e0-b5b9-4a73ad14557d.png)

**Comment by itsamewayu** [comment]
Known issue, devs are looking into it

closed due to repeat issue
