### ISSUE TITLE
[model] Graphics clipping in Erika's kneeling human blowjob scene

### ISSUE THREAD

**Issue by drmilkdecow** [itsamewayu/OLFallenDoll#457]
**Describe the bug**
See attached

**Screenshots**
![Capture](https://user-images.githubusercontent.com/95328819/147865389-3de81af5-7d57-4bb7-afbf-19a3be689f40.JPG)

**Desktop (please complete the following information):**
 - OS: [e.g. Win10]
 - Game Version [0.4.2.6]

**Comment by itsamewayu** [comment]
An issue with Erika's costumes overall, not limited to just this pose.

Closing due to duplicate issue
