### ISSUE TITLE
俩个双头龙动作没有！  谁有背对背劈腿双头龙   和  前后俯卧双头龙 这俩个动作实验室没有 但是游戏里动作卡有

### ISSUE THREAD

**Issue by 731649653** [itsamewayu/OLFallenDoll#459]
俩个双头龙动作没有！  谁有背对背劈腿双头龙   和  前后俯卧双头龙 这俩个动作实验室没有 但是游戏里动作卡有
![20220102214225_1](https://user-images.githubusercontent.com/63484640/147877777-93e27f04-aeda-4c93-b404-4c33ac74f61a.jpg)
![20220102214607_1](https://user-images.githubusercontent.com/63484640/147877790-726a3fc5-c272-4801-bd6d-9b12683403ac.jpg)

**Comment by itsamewayu** [comment]
已知的
