### ISSUE TITLE
[Resolution] Game is vert-  instead of hor+ 

### ISSUE THREAD

**Issue by Arkhchance** [itsamewayu/OLFallenDoll#46]
Hello, 
As the aspect ratio of the game goes up, the engine reduce the vertical view (it stretches, called vert-). 
It makes the game hard to play/enjoy on wide and ultra wide resolution (mine is 5120*1440) 

The behavior should be hor+ (vertical FOV stay the same, horizontal FOV goes up). 

Thanks !

**Comment by Arkhchance** [comment]
1080p (first) 
5102*1440 (second) 
![878_screnshot_n_878](https://user-images.githubusercontent.com/48889519/143682351-9e503eb8-318b-423d-b705-7e14875d20eb.jpg)
![877_screnshot_n_877](https://user-images.githubusercontent.com/48889519/143682358-ff4afe97-126a-406b-ab1b-494565c51eae.jpg)

**Comment by Fank** [comment]
Same Problem

Native (5120x1440 ratio 32:9):
![20211127154557_1](https://user-images.githubusercontent.com/1900106/143686172-92f8cdf1-ba83-401d-9e27-1003ff0e077c.jpg)

1920x1080 ratio 16:9
![20211127154611_1](https://user-images.githubusercontent.com/1900106/143686178-d617c347-94ec-4886-89b1-403571f54db0.jpg)
