### ISSUE TITLE
[0.4.6] LowLevelFatalError when trying to load game.

### ISSUE THREAD

**Issue by Carlincf** [itsamewayu/OLFallenDoll#462]
**Describe the bug**
The Closed Beta fails to load when opened, with the Unreal Engine throwing a "LowLevelFatalError"/

**To Reproduce**
1. Open Steam
2. Select the Closed Beta and click "Play"
3. Wait for the game to display the splash screen and then load.
4. Once loading seems to have completed, an error will be thrown and the game will crash.

**Expected behavior**
The game to complete loading successfully and open the main menu.

**Screenshots**
![image](https://user-images.githubusercontent.com/14362101/147893436-23af5105-6fc1-4338-9c5f-6763b76134c5.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Game Version 0.4.6
 Complete the following Computer Hardware Configurations if necessary:
 - Processor(CPU): AMD Ryzen 5 3600
 - Graphics Card: RTX 2070
 - Memory: 16GB

DMP File: https://drive.google.com/file/d/1QJ3mE8hKk1wZTu6w1f-Kol_y0yz10D0O/view?usp=sharing

**Comment by itsamewayu** [comment]
How consistent is this, and can you replicate it?

**Comment by Carlincf** [comment]
> How consistent is this, and can you replicate it?

Soul Wizard on the Discord pointed out that it may be a driver issue, and after uninstalling/reinstalling my NVIDIA drivers and the game, it now loads properly.
