### ISSUE TITLE
[UI] Improvement on Experiment interface to show various poses and preview video before selection

### ISSUE THREAD

**Issue by drmilkdecow** [itsamewayu/OLFallenDoll#463]
**Is your feature request related to a problem? Please describe.**
Current interface for initiating experiments (both harem and gallery mode) can be more intuitive as players cannot easily see which pose before toggling it and hard to find poses that they want. 

**Describe the solution you'd like**
Use a circular-type interface (eg. kinda like the mockup I did below) that allows the player to easily select...
- which girl (and view their current status)
- which partner (including other girls)
- which location (floor, wall or table)
- which pose (based on rarity)

It will also be good to convert the image in the cards into a preview video of sorts when the player 'mouse-over' the pose selection to allow players to see how does the 'action' look before they start it.

![PH New Interface Combined copy](https://user-images.githubusercontent.com/95328819/147895276-c4f1159b-b4f9-4f9d-b2b2-4d0d068eb00e.jpg)

Let me know if you need the PSD file for the design above if you are willing to consider this. I would be happy to help. :)

**Comment by itsamewayu** [comment]
As mentioned earlier in the Discord, the idea is nice but would fall apart once more options are added as the circle will become insanely cluttered and hard to read.

The animated cards would be a nice touch though, but I don't know if it would affect performance.

**Comment by drmilkdecow** [comment]
Yah I posted it here before I posted in Discord. 

Got your reply there too. No worries man. Cheers!
