### ISSUE TITLE
[Harem] [Daily] Objective bugged for daily, "Make male ejaculate 5 times by conducting experiments with the [Tease] tag."

### ISSUE THREAD

**Issue by HalcyonAnd0n** [itsamewayu/OLFallenDoll#465]
**Describe the bug**
Progress will not move.

**To Reproduce**
Daily task is set at 0/5, tried every pose (both anthro and xeno) with the Tease tag that I own, going all the way to ejaculation for the male and still no progress increment. Tried both before and after 'Temporary Insanity" kicked in.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Game Version 0.4.6

**Comment by itsamewayu** [comment]
Could you provide your user name? The devs are aware of the issue and are collecting info as they investigate the continuing issue.

**Comment by HalcyonAnd0n** [comment]
User name in game is 'Halcyon' and yes the bug has persisted for 2 daily resets now.

**Comment by HalcyonAnd0n** [comment]
Update: This daily is now progressing as intended.
