### ISSUE TITLE
[Harem]The peer review committee did not update the new outfit properly

### ISSUE THREAD

**Issue by maxwell666666** [itsamewayu/OLFallenDoll#466]
**Describe the bug**
I bought Dr. Anya’s sauna bathrobe in the peer review committee last week, but this Monday’s peer review committee is still Dr. Anya’s sauna bathrobe. I have requested that the above problem be fixed. Thank you very much

**Screenshots**
![image](https://user-images.githubusercontent.com/97087837/148031343-4105d0c4-1cab-4e72-b122-c49f01182587.png)

**Desktop (please complete the following information):**
 - OS: [Win10]
 - Game Version [0.46]
 Complete the following Computer Hardware Configurations if necessary:
 - Processor(CPU): [i7-11700K]
 - Graphics Card:[RTX 3060]
 - Memory:[32G]

**Comment by TheSoulWizard** [comment]
Last week was Alet's swimsuit, not Anya's bathrobe. 
I don't know how you got it last week.

**Comment by maxwell666666** [comment]
> 上周是 Alet 的泳衣，而不是 Anya 的浴袍。 我不知道你上周是怎么得到的。

I have been using Dr. Anja’s sauna bathrobe for three consecutive weeks, and I don’t know why this happens.

**Comment by TheSoulWizard** [comment]
> > 上周是 Alet 的泳衣，而不是 Anya 的浴袍。 我不知道你上周是怎么得到的。
> 
> I have been using Dr. Anja’s sauna bathrobe for three consecutive weeks, and I don’t know why this happens.

Every week a different clothing shows up, since there are no lots of clothing in the game yet, clothes that showed up a couple of weeks ago, will show up again.

This probably explains your situation. 

These clothes are exclusive to the peer review committee and cannot be obtained otherwise.

**Comment by ogmecha** [comment]
idk if it helps but ive had the anya bathrobe since launch on weekly store too 😥,

**Comment by maxwell666666** [comment]
> > > 一周是Alet的泳衣，而不是Anya的浴袍。我不知道你一周是怎么得到的。
> > 
> > 
> > 我已经连续三个星期使用 Anja 博士的桑拿浴袍了，我不知道为什么会出现这种情况。
> 
> 每周都会出现不同的衣服，因为游戏中还没有很多衣服，几周前出现的衣服会再次出现。
> 
> 这可能解释了您的情况。
> 
> 这些衣服是同行评审委员会独有的，否则无法获得。
Why did I not refresh Alet's swimsuit in the peer review committee? I think there are many people in the game. Isn't this a bug? Is this the case with me alone?
