### ISSUE TITLE
[Harem][Feature request] Hide player toggle unique hotkey

### ISSUE THREAD

**Issue by Awfulwaffle1** [itsamewayu/OLFallenDoll#467]
**Is your feature request related to a problem? Please describe.**
When navigating around inspect mode, one uses the right button click and hold to move the camera around. Upon finding another player, highlighting the player, and then releasing the right click button, the targeted player then is hidden/unhidden.

**Describe the solution you'd like**
Possibly a unique hotkey to toggle hidden/unhidden players after highlighting the target.
Currently the "T" key (i think?) and right button click are assigned to this functionality

**Comment by salsabeard** [comment]
In earlier builds, the hide option was actually expressly bound to RMB.  There was recently the addition to make hiding other players bound to "T".  I can confirm the hotkey works, but it seems the initial binding of RMB has not been fully removed.

**Comment by Awfulwaffle1** [comment]
Hiding has changed since 0.7.0. Closing as this is no longer an issue and one can hide players by using DND or clicking hide from the player list.
