### ISSUE TITLE
[Harem][Display] Daily Task complete pop-up repeats upon giving likes

### ISSUE THREAD

**Issue by Awfulwaffle1** [itsamewayu/OLFallenDoll#469]
**Describe the bug**
After completing a daily task, the pop-up occurs stating "Daily Task completed." 
Upon giving a like in the same session, the same pop-up reappears throughout.

**To Reproduce**
Pre-Req: Have a daily task just ready to complete
1. Go to Harem
2. Complete a daily task
3. Observe the "Daily Task completed." pop-up
4. Give a like to a researcher in the same lobby
5. Observe the "Daily Task completed." pop-up again.

**Expected behavior**
Only the "You gave {research name here} a like." text pop-up should occur.

**Desktop (please complete the following information):**
 - OS: Win10
 - Game Version 0.4.6

**Comment by poykun** [comment]
Persists in Game Version 0.4.9
