### ISSUE TITLE
[EAC] for proton/wine

### ISSUE THREAD

**Issue by holyfight6** [itsamewayu/OLFallenDoll#47]
**Describe the bug**
The game won't launch when running through proton.

**To Reproduce**
Just run the game through proton on linux. After clicking the play button, it changes to the playing state, but the game won't show up.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/3499782/143682083-e128234b-d6d2-43e9-911c-9983e1176374.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux 5.15.4-zen1
 - Browser chrome
 - Version: Build ID 7782512

**Additional context**
I can run the old standalone version of the game through proton without any problem. On discord Project Helius did say CBT version will [support proton](https://discord.com/channels/766887330518269962/830140124574253116/891333862658027530). Below is the EAC logs:
`[Info] Desktop screen settings detected. DPI: 96 DPI Multiplier: 1.000000 BPP: 32.
[Info] Localization loaded for: 'en-US'.
[Info] Settings file full path: 'Z:\games\steam-library\steamapps\common\Operation Lovecraft Fallen Doll Playtest\EasyAntiCheat\Settings.json'.
[Info] Start. ExecutablePath: 'Z:\games\steam-library\steamapps\common\Operation Lovecraft Fallen Doll Playtest\FallenDoll.exe' LaunchParameters: '' WorkingDirectory: ''.
[Info] Finished window initialization.
[Info] [LauncherProgress] 0%.
[Info] [LauncherProgress] 0%.
[Info] [LauncherProgress] 0%.
[Info] [LauncherProgress] 0%.
[Info] [LauncherProgress] 0%.
[Info] [LauncherProgress] 0%.
[Info] [LauncherProgress] 0%.
[Info] [LauncherProgress] 0%.`
Maybe EAC isn't enabled for proton/wine?

**Comment by ysy95109** [comment]
> EAC is a way for multiplayer games to protect their online experience, but it currently does not work with Proton as the service either fails to load or crashes games in progress before long.
- from Google search

**Comment by holyfight6** [comment]
@ysy95109 Hi, EAC already has [EAC Linux Wine / Proton Support](https://dev.epicgames.com/docs/services/en-US/GameServices/AntiCheat/#linuxwine/protonsupport), as long as the game enable it.

**Comment by smirgol** [comment]
I'm having the same issue, unfortunately. But for me the game starts, but then presents me with a black modal window and a blue button in the middle with the localized text "Verlassen" (Leave / Exit). I cannot get beyond this point. 
I'm using Proton 6.3 and Proton Experimental.
I'm not sure if this is already EAC blocking me out, or if it is a rendering problem, but whatever it is, EAC will be the major hurdle I think.

Please consider enabling Linux support in EAC. 
I'd be such a shame to not be able to play the final product I've backed and waited for so long. :(

@holyfight6 where did you find that EAC log?

**Comment by holyfight6** [comment]
> I'm having the same issue, unfortunately. But for me the game starts, but then presents me with a black modal window and a blue button in the middle with the localized text "Verlassen" (Leave / Exit). I cannot get beyond this point. 
That is the EAC error window.

> @holyfight6 where did you find that EAC log?
It's in "your_steam_library_dir/componentdata/1810920/pfx/driver_c/users/steamuser/Application Data/Easy Anti Cheat".

**Comment by l12436** [comment]
For Developer:
I found the main reason of EAC not working on proton.
EAC actually working on Proton, but with a exception
the url that provide to EAC
`cdn=https://modules-cdn.eac-prod.on.epicgames.com/builds/136/1992dddf-4269-4b28-b0a9-207a02c1a2a7/{{system}}`
The `{{system}}` in wine will pass wine64 which the full url is
https://modules-cdn.eac-prod.on.epicgames.com/builds/136/1992dddf-4269-4b28-b0a9-207a02c1a2a7/wine64
but the EAC website is actually not accept wine64, It will return access denied.
If I change {{system}} to wow64_win64 which is win10 EAC given to EAC, and it working.
so....，EAC website is not actully complete support wine at all, it should pass windows version of {{system}} to EAC
or the EAC should accept wine64

**Comment by holyfight6** [comment]
@l12436 Can confirm it works for me too.

**Comment by johnathandarkly** [comment]
> If I change `{{system}}` to `wow64_win64` which is win10 EAC given to EAC, and it working. 

i'm a ubuntu noob, using whatever steam installed (proton)... how do i change {{system}}?

**Comment by holyfight6** [comment]
> i'm a ubuntu noob, using whatever steam installed (proton)... how do i change {{system}}?

It's in the EAC config file shipped with the game,  you can simply use the "Browse local files" option to open the path, the file is called "FallenDoll.exe.eac".

**Comment by smirgol** [comment]
Wow, that is interesting that it indeed does work if you replace the placeholder `{{system}}` with `wow64_win64`.

I had the impression that the developer usually needs to also provide a binary for `wine64` (probably by enabling a flag in the engine when compiling the game) - that was how it worked for a different game in the past for me. There was one military shooter that also used EAC and was one of the very very few games, that actually had provided an EAC binary for `wine64` and it worked flawlessly out of the box. That was months ago, even before they said that proton compatibility for EAC can be enabled now - maybe it's just easier now to do so.

So, I'd say that is a nice workaround, but not sure if this is the proper solution. It won't work out of the box that way for sure, but it's at least something. :)

**Comment by johnathandarkly** [comment]
with 0.4.5 game drops out before title screen on my ubuntu machine. it lasts a little longer with the wow64_win64 edit, but it still can't quite make it.

**Comment by l12436** [comment]
yes, I can confirm, latest update break wine compatible.

**Comment by johnathandarkly** [comment]
still no luck with 0.4.7. could be related to my lockout from harem mode, but i can still no longer get to title screen with ubuntu/proton.

**Comment by johnathandarkly** [comment]
I thought there was a 0.4.7.1 patch that got Proton going again. This isn't obvious from 0.4.8... which still isnt working on my ubuntu build. 

**Desktop**
 - OS: Ubuntu 21.10
 - Game Version: 0.4.8
 - Processor: Ryzen 7 5700G 3.8ghz
 - Graphics:  Integrated Radeon 8 "Raven" 2.0ghz w/ 8GB allocated
 - Memory: 32GB
 - Emulator: Proton 6.3-8
