### ISSUE TITLE
[Harem] [System] Mouse cursor will reset position when a random user places an experiment.

### ISSUE THREAD

**Issue by TheSoulWizard** [itsamewayu/OLFallenDoll#475]
Everyone's mouse position will go back to the middle of the screen each time a random user places an experiment.

It doesn't matter if you have the game minimized or not, as soon as someone places an experiment, the cursor will reset back to the middle of the screen.

https://user-images.githubusercontent.com/40411642/148389279-cb162322-d97e-41bf-b24e-c64f9dbae838.mp4

Happens on either **0.4.6** or **0.4.7**
I believe this bug first appeared in patch 0.4.5, though im not 100% sure.

**Comment by CrimsonAmeri** [comment]
I'd also like to add that if this happens while you're in the middle of an experiment it breaks the stimulate keybind until you end the experiment and press space to switch from avatar camera to free camera.

**Comment by salsabeard** [comment]
I think I've observed this behavior when players enter and exit the server as well.
