### ISSUE TITLE
[Harem] Erika hair missing

### ISSUE THREAD

**Issue by User7276** [itsamewayu/OLFallenDoll#478]
Erika's hair will vanish and reappear depending on the angle and or zoom distance.  This is only for Erika, and only other players Erikas, I never have issue with my Erika.
![20220106121342_1](https://user-images.githubusercontent.com/95495776/148448439-86886e90-4e8c-491e-ae44-978f847390eb.jpg)
![20220105102955_1](https://user-images.githubusercontent.com/95495776/148448462-8ae16954-2c17-4208-bc02-1aa8a96547f2.jpg)

**Comment by TederyT** [comment]
I've met this before, not only Erika suffer this, but also Dr. Anya did. Sometime an entire human body is missing as well when seeing someone finish their actions, but I could see their customs and names, lol.
