### ISSUE TITLE
In 0.4.7 now multiple players appear duplicated for more than 5 Minutes (Instance synchronization problem)?

### ISSUE THREAD

**Issue by Panthear** [itsamewayu/OLFallenDoll#479]
[0.4.7], [bug], [system]

**Describe the bug**
When staying longer in the same instance (in case game doesn't crash), after a while players appear duplicated in the instance (most likely due to players crash?) => Isuee #400 . This doesn't get cleaned up timely. Additionally this makes issue #477 even worse as when mutiple cleanups are happening game might quit to desktop

**To Reproduce**
Stay in the instance and issue will appear. Visible if multiple player names are within the same instance.

**Expected behavior**
Clean up crashed players, when they log in again! (Or faster automatically)

**Screenshots**
Taken within the same minute: EDDF and Hardcoregamer are duplicate... shortly therafter another one.
![grafik](https://user-images.githubusercontent.com/95415732/148450882-0f628f60-9f72-4a25-9f24-1bc50f582989.png)
![grafik](https://user-images.githubusercontent.com/95415732/148450955-52b749f4-3677-4ddc-a352-eda20e5bdec6.png)
![grafik](https://user-images.githubusercontent.com/95415732/148451014-8c2d9e4b-b4d6-4dbf-a2c5-04575849ede8.png)

Interestingly enough "Likes" can be given to "both" appearences of the players....
Not sure if they count or not...

**Desktop (please complete the following information):**
N/A however if details are important see #400 or #477

**Comment by poykun** [comment]
#419 issue is related
