### ISSUE TITLE
[UI] Fonts used in the main menu and gallery mode don't support certain foreign letters.

### ISSUE THREAD

**Issue by oregano12** [itsamewayu/OLFallenDoll#48]
**==Description==**
Some of the fonts used in the main menu and gallery mode don't support certain letters of the included languages. 

Portuguese is missing letters such as "ç", "ã", "á", "é" and "í". 
Greek is missing letters such as "ό", "ί", "ύ", "έ" or any other letter with a ton (´).

Because of this, words that require these letters appear all messed up in-game or don't appear at all (see included screenshots).

**==To Reproduce==**
Simple change the in-game language to Portuguese or Greek and check the menus shown in the screenshots.

**==Expected behavior==**
The letters should be displayed correctly.

**==Screenshots==**
_=Portuguese=_
"Cão de Tíndalos"
"Raça"
"Híbrido"
![11](https://user-images.githubusercontent.com/88695057/143684382-1255a910-f984-4365-8ca4-c899719e9cbd.png)

"Customização"
![12](https://user-images.githubusercontent.com/88695057/143684394-82e25bff-9d1c-4c2e-9646-6a444c2a0c0e.png)

"Posição"
"Cabeça"
![13](https://user-images.githubusercontent.com/88695057/143684406-c091ace1-7e19-44b9-911b-e38f242db93a.png)

"Automática"
![14](https://user-images.githubusercontent.com/88695057/143948773-22b907b2-c1da-4137-a2ce-7c6b4c3f77a7.png)

"Padrão"
And Portuguese font on hair color menu needs to be shrinked due to the "confirmar".
![15](https://user-images.githubusercontent.com/88695057/143948863-a4a61be1-edde-471b-82c7-aa2e4bc734f8.png)

"Masculino" can be abbreviated to "Masc."
Font needs to be shrinked due to the "Invisível".
![16](https://user-images.githubusercontent.com/88695057/143949022-9cf5f8f8-2c5e-452c-8713-a8068dfd4240.png)

_=Greek=_
"λειτουργία Χαρεμιού είναι διαθέσιμη μόνο" 
"δοκιμαστές αυτήν"
"στιγμή"
"Κάνε Κλίκ"
"βάλεις"
"λίστα επιθυμιών"
![23](https://user-images.githubusercontent.com/88695057/143935419-8e4255fa-f312-4da9-93a7-61deba560545.png)

The translation for "Brightness" is missing.
![24](https://user-images.githubusercontent.com/88695057/143935666-a06366bf-c2fc-4c85-b4b2-7403a3bc60e2.png)

Greek font on hair color menu needs to be shrinked.
![34](https://user-images.githubusercontent.com/88695057/143947708-118bb52b-5fd7-42f5-b461-b0ba0a5005a6.png)

Select "Male" box is strangely long hiding the text.
![35](https://user-images.githubusercontent.com/88695057/143947831-434aa2d6-1cfb-49d1-b1a1-9823360bd6c2.png)

**Comment by Awfulwaffle1** [comment]
Still valid in current gallery.
