### ISSUE TITLE
An issue caused by the interruption of link

### ISSUE THREAD

**Issue by AloRitsuko** [itsamewayu/OLFallenDoll#480]
When the link between player's terminal and the server was interrupted due to internet error, the player might try to get into the harem lobby again. But this time "Start" button might become a "Resume" button, click "Resume" and you will return to the game main title.

**Comment by AloRitsuko** [comment]
[Suggestion: Give players a button to enforce their IDs go offline correctly]

**Comment by poykun** [comment]
Could be #160 related. When getting this, have you tried quitting to the title and starting it up again?

**Comment by AloRitsuko** [comment]
> Could be #160 related. When getting this, have you tried quitting to the title and starting it up again?

I tried quitting to the title, but it was still "resume"

**Comment by AloRitsuko** [comment]
This issue might disappear with the passage of time.
