### ISSUE TITLE
Cannot start the game

### ISSUE THREAD

**Issue by Krizz0815** [itsamewayu/OLFallenDoll#484]
When starting the game launcher via steam  the loading animation with
EAC is shown but after the loading bar is full the window just closes.

Tried to to start the game from the local folder, but FallenDollLauncher.exe
does the same when opened and FallenDoll.exe just goes to a black fullscreen
and closes the fullscreen window after about 8-10 seconds. I do not even get
an error message from either .exe file. 

**To Reproduce**
1. Go to steam
2. Click on launch/play game

Going to my local steam folder and opening
the FallesDoll.exe does the same thing.

Game is located in folder:
Z:\Program Files (x86)\SteamLibrary\steamapps\common\Operation Lovecraft Fallen Doll Playtest

**Expected behavior**
Being able to play the game

**Desktop (please complete the following information):**
 - OS: Win 11 Pro N 64 bit Version 10.0.22000 Build 22000
 - Game Version: Could not check because it doesn't show anywhere.
 - I can only look up the Build-ID in steam: 7978568
 - 
 Complete the following Computer Hardware Configurations if necessary:
 - Processor(CPU): AMD Ryzen R9 5950X Auto OC
 - Graphics Card: NVIDIA RTX 3080  GPU @2070 Mhz Memory @9702 Mhz
 - Memory:32 GB @ 3800 Mhz
 - Game is installed on a 1TB corsair mp600 pcie nvme ssd

*If your game crashed, remember to upload the dmp file with your issue.
It's located in C:\Users\ (USER ID) \AppData\Local\Paralogue

There is no dmp file in the specified location, because I could never
start the game once for it to create a dmp file.

The CrashReportClient.ini says:

[CrashReportClient]
bHideLogFilesOption=false
bIsAllowedToCloseWithoutSending=true
CrashConfigPurgeDays=2

**Comment by poykun** [comment]
The only thing I would suggest is checking the integrity of the files through steam or straight up doing a reinstall.

**Comment by Krizz0815** [comment]
> The only thing I would suggest is checking the integrity of the files through steam or straight up doing a reinstall.

The first thing I did was to check the file integrity. Steam says everything is fine. Will try a reinstall.

**Comment by Krizz0815** [comment]
> > The only thing I would suggest is checking the integrity of the files through steam or straight up doing a reinstall.
> 
> The first thing I did was to check the file integrity. Steam says that everything is fine. Will try a reinstall.

A reinstall did nothing. Still havin the same issue. But thanks anyway.

**Comment by Krizz0815** [comment]
After a little research on google the CrashReportClient.ini points towards an issue with unreal engine
which is kind of strange because the 0.34 build works just fine. Perhaps it is an AMD Ryzen specific issue?

Found a forum with asolution with the same issue for Intel CPUs, but do not know if this is really
the same issue :

https://forums.pixeltailgames.com/t/crash-on-startup-no-error-message/42094/23

**Comment by Krizz0815** [comment]
So I have narrowed it down to the issue being raytracing. I downloaded ue 4.27.2 from the epic store and
started the unreal engine editor. When starting a project with raytracing ue crashed every time. When starting
a project without raytracing the project loaded without a problem. So it comes down to an unreal engine raytracing
issue.

**Comment by Krizz0815** [comment]
Finally found the solution.

I had the realtime protection of Spybot S&D enabled which caused the Easy Anti Cheat to crash.
What a crappy piece of software EAC is. Seen many posts online of other software preventing EAC to 
launch that have nothing to do with cheating. In my case it was my additional realtime Antivirus
program running in the background. Epic Games should really rework their garbage program.
