### ISSUE TITLE
[Harem][Animation] various climax animation loops and restart is not functional

### ISSUE THREAD

**Issue by Awfulwaffle1** [itsamewayu/OLFallenDoll#485]
**Describe the bug**
For Anya x Byakhee Arms Held Sitting Deepthroat
Once the player clicks the cum inside button the animation seems to loop endlessly
The restart button becomes active immediately, but does not respond

**To Reproduce**
1. Go to Harem Mode
2. Click on Start to go into a lobby
3. Hit E to play down an Experiment
4. Select the following: Anya x Byakhee, Compatibility: Low, Location: Prop - Arms Held Sitting Deepthroat
5. Place the experiment at the appropriate location highlighted in Green
6. Increase Ecstacy of the Bykhee to the point of climax
7. Select Cum Inside icon
8. Observe
9. Attempt to click the restart button 

**Expected behavior**
The Cum Inside animation should play while the buttons to restart or abort should remain gray.
Upon completion of the animation, the restart button and abort buttons should become active and responsive.

 - Game Version 0.4.7

**Workaround**
Abort button or pressing ESC works fine to get out of the animation.

**Comment by Panthear** [comment]
I have a similar problem with the "On Top Scissoring".
After "double climax" you can press the "restart button", but nothing happens... Both buttons remain gray and there is no way to start the experiment again.

Abort button + ESC works.

![grafik](https://user-images.githubusercontent.com/95415732/148952735-b2372e6e-e4c1-4a03-af78-6e62985984f5.png)

**Comment by poykun** [comment]
If there's more we can change up this issue and use it as a tracker to collect all animations with the same problem. I'll play around with more when I get the chance

**Comment by Panthear** [comment]
Here is one more:

Alet: **Table Supported Blowjob => Internal Ejaculation** also cannot restart. External Ejaculation works. In this case it looks like the animation loop for the Internal Ejaculation isn't started btw...

Also going through the animation I have... will post once through with the ones missing. PS: Can confirm Alex X Hound...

**Comment by Panthear** [comment]
While experiemtin a little bit further on some of the issues, found an additional strange behavior. Experiements, which normally don't have 2 hearts (like the Table Supported Blowjob), can be "tricked" into having 2 hearts, if another experiment was terminated before Alet climaxxes...
By doing this, the experiemnt (Fellatio / Footjob) is having a "combined climaxx".... which leads to a "Like" and most interestingly:

Unlike the "internal" which isn't restartable, the combined heart displays the Animation and is restartable....

Halt any experiment before Autoclimax:
![grafik](https://user-images.githubusercontent.com/95415732/149619982-5e79c7e1-6874-4a3b-a409-53b7429721f6.png)

And then you get 2 Hearts with Fellatio:
![grafik](https://user-images.githubusercontent.com/95415732/149620005-91c09247-8565-44ac-bd93-33fc179c7cd7.png)
![grafik](https://user-images.githubusercontent.com/95415732/149620026-f34e8d79-f2e7-4665-a1d9-1e52fbdb3e8e.png)
