### ISSUE TITLE
[Harem] [UI] Task completed UI will appear when giving likes.

### ISSUE THREAD

**Issue by TheSoulWizard** [itsamewayu/OLFallenDoll#488]
**After** completing a Daily Task and "Daily Task Completed" UI appears, giving a Likes to someone will trigger the "Daily Task Completed" UI each time you give a Like.
![image](https://user-images.githubusercontent.com/40411642/149121073-e0931258-0bae-468e-a026-8370f4204cc9.png)
Version: **0.4.7**

**Comment by Panthear** [comment]
Looks like duplicat #469

**Comment by TheSoulWizard** [comment]
> Looks like duplicat #469 

Thanks for noticing. Issue Closed
