### ISSUE TITLE
None of my purchased experiments work 

### ISSUE THREAD

**Issue by EVIL666DEAD** [itsamewayu/OLFallenDoll#491]
**Describe the bug**
If I Study an experiment I can use it for 24 hours no problem. 
If I then purchase the experiment with data it stops working.
I have about 10 experiments that now doesn't work because of this.

**To Reproduce**
1. click experiment 
2. click floor/wall/table nothing happens

**Expected behavior**
The experiment to work after I've purchased it with data

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win10
 - Game Version  0.4.5
 Complete the following Computer Hardware Configurations if necessary:
Processor	Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz   3.19 GHz
Installed RAM	32.0 GB
System type	64-bit operating system, x64-based processor

*If your game crashed, remember to upload the dmp file with your issue.

It's located in C:\Users\ (USER ID) \AppData\Local\Paralogue

**Additional context**

**Comment by poykun** [comment]
Which experiments would this be for specifically. And the current game version available is 0.4.5, have you tried the updated version?

**Comment by EVIL666DEAD** [comment]
Ok, I checked today with both Erika and Alert. ALL of my data purchased experiments will not place. 

I can even re-study them even though I own them!

That's a lot of experiments and it's damn annoying.

I'll try Dr Anya tomorrow

**ERIKA's experiments**

Hound of Tindalos
Milking Handhjob

Dreamer
Handcrafted kneeling boobjob
Sideways grasshopper
Leg-raised hair-pull standing doggystyle
Penguin
Exhausted leg raised wedge
Bent knee boobjob
Standing dildo
Lying spreadlegs fingering

Ghast
Apollo

Doctor Anya
Dildo held rear entry
Standing double dildo
Splits double dildo

**ALERT's experiments**

Dreamer
Front entry and blowjob
Threesome arm-held spitroast
Exhausted lying down
Leaning forward cowgirl
Ass grabbing doggystyle

Sylph
Line up rear entry

Lloigr
AlertLloigr_vangina01

Dr Anya
Cunnilingus piledriver
wall cunnilingus 

Erika
Reverse cowgirl thigh grinding 
Ontop scissoring

**Comment by EVIL666DEAD** [comment]
I have the game as a high priority update but I can't see how to manually force an update on steam it should be automatic.

**Comment by EVIL666DEAD** [comment]
Ok, I updated it to 0.4.7 it still has exactly the same problems.

**Comment by poykun** [comment]
I can't seem to reproduce this on my end. I'll try with a few more experiments.

**Comment by EVIL666DEAD** [comment]
> I can't seem to reproduce this on my end. I'll try with a few more experiments.

It must be nice to have a working copy of the beta.

**Comment by EVIL666DEAD** [comment]
0.4.8 update and then problem persists
