### ISSUE TITLE
[Harem][Invalid] Functional Test Subject ... experiment visible with Alet, Spawn of Bastan and Dreamer

### ISSUE THREAD

**Issue by Panthear** [itsamewayu/OLFallenDoll#493]
**Describe the bug**
Minor issue... close if expected due to Alpha stage...
In 0.4.7. there is a "Functional Test Subject" experiment seen for Alet, Spawn of Bastan and Dreamer, which doesn't seem to exist yet...

**To Reproduce**
1. Choose Alet, Spawn of Bastan and Dreamer in the Experiment overview...
2. Observe the "Functional Test Subject" Experiment (blocked)

**Expected behavior**
Not visible... 

**Screenshots**
![grafik](https://user-images.githubusercontent.com/95415732/149400421-4a65927d-f800-4a73-aa10-9385e1988f61.png)

**Comment by poykun** [comment]
Add Alet X Lloigor => AletLLoigor_Vaginal01 as well
Compatibility: Low 
Location: Prop
