### ISSUE TITLE
[Harem][UI] Squatting Cowgirl Experiment missing Interspecies tag

### ISSUE THREAD

**Issue by Awfulwaffle1** [itsamewayu/OLFallenDoll#494]
**Describe the bug**
Erika X Deep One Hybrid - Squatting Cowgirl is missing the Interspecies Tag.

**To Reproduce**
1. Go to Harem
2. Go to Experiments
3. Type "Interspecies" to filter the experiments
4. Look through the list

**Expected behavior**
All Interspecies related experiments are tagged accordingly

**Screenshots**
![Squat_cow](https://user-images.githubusercontent.com/95268330/149444384-f008d672-8f26-470f-9703-55eba83159f2.jpg)

Missing the Alien icon and Interspecies Tag.

 **Game Version 0.4.7**

**Comment by poykun** [comment]
Still missing as of 0.4.9
