### ISSUE TITLE
[Harem][UI][Animation] Some experiments are missing Shoe Disabled Icons when they should and vice versa

### ISSUE THREAD

**Issue by Awfulwaffle1** [itsamewayu/OLFallenDoll#495]
**Describe the bug**
There are some experiments that allows for shoes to be worn when the experiment contains the Shoes Disabled tag and icon
Also, there are some experiments that are missing the Shoes Disabled icon, when shoes are not able to be worn.

**To Reproduce**
1. Go to Harem
2. Go into a lobby
3. Select an affected experiment 
4. (Alet X Sylph - Doggystyle Massage: Compatibility High, Prop Location)
5. Observe the experiment card first: Note the experiment does not have the Shoes Disabled icon
6. Place the experiment down to start
7. Navigate to the CUSTOM portlet
8. Click on the Outfit Icon
9. Observe

**Expected behavior**
For experiments WITHOUT  a Shoes Disabled tag/icon: they should be able to wear shoes
For experiments WITH the Shoes Disabled tag/icon: they shouldn't be able to wear shoes

**Game Version: 0.4.7**

Current list...although there may be more as I have many experiments locked:

**Shoes Disabled tag/icon missing**
_Doggystyle Massage_ - Alet x Sylph - High Compatibility - Prop Location
_Leg up Rear-Entry_ - Alet x Sylph - High Compatibility - Prop Location
_Table Supported Blowjob_ - Alet x Spawn - Full Compatibility - Prop Location
_Front Entry and Blowjob_ - Alex x Nymph - Mid Compatibility - Prop Location
_Reverse Cowgirl Thigh-Grinding_ - Alet x Erika - Full Compatibility - Floor Location
_Kissing Missionary_ - Erika x Hound - None Compatibility - Floor Location
_Held Down Prone Bone_ - Erika x Hound - None Compatibility - Floor Location
_Milking Handjob_ - Erika x Hound - High Compatibility - Floor Location
_Exhausted Leg Raised Wedge_ - Erika x Dreamer - Mid Compatibility - Prop Location
_Cuddling Handjob_ - Erika x Dreamer - Full Compatibility - Floor Location

**Shoes Disabled Icon is present, but shoes can still be worn**
_Leg-raised Anal Doggystyle_ - Alet x Dreamer - Mid Compatibility - Wall Location
_Chair Handjob_ - Alet x Dreamer - High Compatibility - Wall Location
_Submissive Sidekick_ - Erika x Hound - Mid Compatibility - Floor Location
_Kneeling Front Entry_ - Erika x Spawn - Mid Compatibility - Wall Location
_Face-Down-Ass-Up_ - Anya x Deep One Hybrid - Mid Compatibility - Floor Location
_Standing Handjob_ - Anya x Ghast - High Compatibility - Floor Location

**Has "Must Wear Shoes" icon, but it's optional**
_Lying Handjob While Kneeling_ - Alet x Ghast - Full Compatibility - Floor Location
_Leg-Raised Hair-Pull Standing Doggystyle_ - Erika x Dreamer - No Compatibility - Wall Location

**Comment by Panthear** [comment]
Few Additions:

**Shoes Disabled tag/icon missing**
_Restrainged Front-Entry_ - Alex x Yith - None Compatibility - Wall Location
**Shoes Disabled Icon is present, but shoes can still be worn**
_Reverse Doggystyle_ - Alet x Hound - High Compatibility - Floor Location
_Threesome Leg-Raised Standing Doggy with Handjob_ - Alex x Dreamer - Mid Compatibility - Floor Location
_Sideways Screw_ - Anya x Dreamer - Mid Compatibility - Prop Location

**Comment by Panthear** [comment]
Adding one experiment, where Tag (Shoes) is correct (as Anya wears shoes), however it leads to clipping... So may need to be finetuned:

_Leg Lifted Anal_ - Anya X Byakhee - Mid Comatibility - Prop Location

![grafik](https://user-images.githubusercontent.com/95415732/149818247-331f04d0-60b0-4362-b689-10f6f8ab3ea9.png)
