### ISSUE TITLE
[Harem][0.47][Model][Sitting cunnilingusl] Character pass through the Wall

### ISSUE THREAD

**Issue by TederyT** [itsamewayu/OLFallenDoll#498]
**Describe the bug**
Character pass through the wall, as well as Anya's hair always pass through her chest (Hope you guys could fix this, too)

**Expected behavior**
To be normal...

**Screenshots**
![image](https://user-images.githubusercontent.com/97818772/149647553-9d04a6cf-541e-422a-a08a-02956679e9a8.png)

Desktop

OS: WIN 10
Game Version 0.43
Processor(CPU): AMD RYZEN 7 5800X
Graphics Card: RTX 3090
Memory: 32 GB
Additional context
None

**Comment by Panthear** [comment]
This essentially can happen if shortly before posing the character the experiment "slips" below the surface (ground floor).

I experienced this today. While experiments which are "on ground" simply can't be placed then anymore (and you have to reopen the experiments), experiments which require a "wall" will then "clip" through the wall... 

Can easily be reproduced...
