### ISSUE TITLE
[Model] Missing Models in poses

### ISSUE THREAD

**Issue by itsamewayu** [itsamewayu/OLFallenDoll#5]
**OtaKhu** — Yesterday at 6:56 PM
Alet + Erika scissoring - they've disappeared. Just solely selection. Starting the animation does nothing. https://i.imgur.com/tyZWnhu.jpeg
![tyZWnhu](https://user-images.githubusercontent.com/11155504/143678532-41a4e85b-c6c6-4c75-9f9c-1608de635dc4.jpg)

correction, starting the animation starts the bar, but no models appear. Not anywhere in lab either when panning around.
Anya + alet piledriver cunnilingus in workshop - disappeared. https://i.imgur.com/xRenKkS.jpeg 
![xRenKkS](https://user-images.githubusercontent.com/11155504/143678540-e0547515-0260-40d5-a2f9-cb8b9a966ae6.jpg)

alet + deep one hybrid standing behind - no models https://i.imgur.com/CXTCUcd.jpeg
![CXTCUcd](https://user-images.githubusercontent.com/11155504/143678545-470cfa86-5698-4217-9c26-05f14e7e0bd5.jpg)

OtaKhu — Yesterday at 7:16 PM
alet + lloigor workshop restrained missionary - no models https://i.imgur.com/iUMPCRa.jpeg
![iUMPCRa](https://user-images.githubusercontent.com/11155504/143678557-b54633a3-98d4-4d3e-8238-98ccd1b48aa8.jpg)

anya + elder thing - not translated, no models https://i.imgur.com/ttfQHgS.jpeg

![ttfQHgS](https://user-images.githubusercontent.com/11155504/143678562-cd55c41c-208f-4d77-af6c-12da044e22ee.jpg)

anya + dreamer - not translated, no models https://i.imgur.com/rT9u6uc.jpeg
![rT9u6uc](https://user-images.githubusercontent.com/11155504/143678565-474245a0-62d4-42d8-96b5-20751074d09f.jpg)

**ADDITIONAL FROM USER 别扒拉我~**

反向女上位 有BUG
![95V6IDRX7_X4SI8W8G](https://user-images.githubusercontent.com/11155504/143678780-d59badbc-888b-4efc-84cb-d78e1cebe93b.png)

安雅博士 梦行者  压身站立后背位BUG
![unknown](https://user-images.githubusercontent.com/11155504/143678854-deeed1af-3f34-4456-803e-d1a7a760eddf.png)

阿蕾特  工坊 罗伊格尔 传教士 BUG
![unknown](https://user-images.githubusercontent.com/11155504/143678882-0ae21844-46c5-4a43-986b-d141c10e2456.png)

阿蕾特  工坊 安雅博士  泰山压顶 BUG
![unknown](https://user-images.githubusercontent.com/11155504/143678913-fd99c494-2ef9-4683-b52b-bd0c42d43027.png)

阿蕾特  工坊 梦行者  背后位强迫肛  BUG
![unknown](https://user-images.githubusercontent.com/11155504/143678901-46f82877-f6ff-4988-accb-4db9b70df360.png)

博士 工坊 古老者   性交04 BUG
![unknown](https://user-images.githubusercontent.com/11155504/143678918-282c58e4-c2f0-463c-8dd9-ed6ffc068bf4.png)

博士 工坊  梦行者 男性手02 BU
![unknown](https://user-images.githubusercontent.com/11155504/143678925-c9f13b33-3860-4bcf-b957-d3894c402f1f.png)
G

**Comment by TheSoulWizard** [comment]
Small Note for the dev: All characters and animations are correctly rendered, but on most poses the user camera is misplaced, and some characters are placed below the map.

**Comment by jinjin525** [comment]
From issue #3 : Models seems to be appearing underground.
From issue #12 :Cameras positioned incorrectly as well.

**Comment by Awfulwaffle1** [comment]
Some of these issues are obsolete and a whole bunch of other gallery issues are being tracked separately. Also, Gallery is currently out of scope for the foreseeable future. Closing.
