### ISSUE TITLE
Erika overall bugs

### ISSUE THREAD

**Issue by DarklynVall** [itsamewayu/OLFallenDoll#50]
1. Her skin texture glitched, and bunny suit name is in Japanese? (Text is set to English) Also bunny suit texture glitched.
![image](https://user-images.githubusercontent.com/95135071/143685274-a0465bac-3b3e-4db8-ae0d-473214ef4f26.png)
![image](https://user-images.githubusercontent.com/95135071/143685301-e5aeadc9-f3b1-4f01-865b-4ad6037acc6b.png)
![image](https://user-images.githubusercontent.com/95135071/143685320-334b213a-c9eb-4ae0-9063-99f2abbd4cc1.png)

2. Her idle/nsfw poses with funeral violinist clothing the texture glitched. Seems like to the costume that is glitched with something sticking out.
![image](https://user-images.githubusercontent.com/95135071/143685387-eb56c800-24d7-4af4-9528-2aad88107cf1.png)
![image](https://user-images.githubusercontent.com/95135071/143685430-a0916d18-ddfb-421e-8141-3abaf4c5f62a.png)
![image](https://user-images.githubusercontent.com/95135071/143685548-4171ef50-e915-4093-9da2-83f7867c13ec.png)

**Comment by ombra1501** [comment]
the broken skin weights of the violinist costume have been fixed

**Comment by itsamewayu** [comment]
Already have threads dedicated to each issue
