### ISSUE TITLE
[ANIMATION] Kneeling Fingering

### ISSUE THREAD

**Issue by DenkiKitsune** [itsamewayu/OLFallenDoll#502]
Anya and Erika Kneeling fingering scene - if you allow Erika to climax without hitting the button.  The animation will get stuck in a loop where Anya is rubbing Erika's back.   Erika's ecstasy bar depletes and doesn't begin gaining again.

**To Reproduce**
Select Anya/Erika - Kneeling Fingering. Allow animation to run until Erika reaches full ecstasy and animation will begin to loop endlessly.

**Expected behavior**
Animation to reset and Erika will begin to gain ecstasy.

**Screenshots**
![20220117144256_1](https://user-images.githubusercontent.com/95551471/149845031-8e4b68cd-ea07-4e7d-97f2-4e3baa9e9c85.jpg)
![20220117144257_1](https://user-images.githubusercontent.com/95551471/149845032-25fadb2b-26b8-46f6-99a1-59a5baef3d70.jpg)
![20220117144257_2](https://user-images.githubusercontent.com/95551471/149845034-27f0b0fa-20d6-4c68-9937-1ef5b249e521.jpg)

**Desktop (please complete the following information):**

Win 11 
ver 0.4.7
Processor(CPU): I7-10750H |  
Graphics Card: RTX 2070 |  
Memory: 16gb

**Comment by poykun** [comment]
Can add that to the #485 list.

**Comment by poykun** [comment]
This experiment is a bit weird as the icon to ejaculate outside is present when other fingering experiments has the Single Heart available for climaxing. Also when pressed no inspiration is given.
