### ISSUE TITLE
 Anya Pose - The table disappeared

### ISSUE THREAD

**Issue by ymxiaofx** [itsamewayu/OLFallenDoll#51]
The table is gone!
![Paralogue Screenshot 2021 11 27 - 22 25 16 45](https://user-images.githubusercontent.com/95134684/143685665-9d54cefb-55af-4555-b4b3-90265692cc34.png)
![Paralogue Screenshot 2021 11 27 - 22 26 42 01](https://user-images.githubusercontent.com/95134684/143685677-114c5920-8933-4bcc-9839-e56b06bab615.png)

**Comment by HeyItsNyX** [comment]
This is a duplicated post, refer to
https://github.com/itsamewayu/OLFallenDoll/issues/13
