### ISSUE TITLE
Game crashes constantly

### ISSUE THREAD

**Issue by ps4life2022** [itsamewayu/OLFallenDoll#512]
Fatal error!

Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0xffffffff

0x00007ffc622c146c VCRUNTIME140.dll!UnknownFunction []
0x00007ff728003988 Paralogue-Win64-Shipping.exe!UnknownFunction []
0x00007ff7282b5118 Paralogue-Win64-Shipping.exe!UnknownFunction []
0x00007ff72821c024 Paralogue-Win64-Shipping.exe!UnknownFunction []
0x00007ff72861c478 Paralogue-Win64-Shipping.exe!UnknownFunction []
0x00007ff7287025cb Paralogue-Win64-Shipping.exe!UnknownFunction []
0x00007ff7286fd311 Paralogue-Win64-Shipping.exe!UnknownFunction []
0x00007ffc7a9f7034 KERNEL32.DLL!UnknownFunction []
0x00007ffc7c642651 ntdll.dll!UnknownFunction []

Crash in runnable thread TaskGraphThreadNP 3

1. just starting the game normally from Steam and start Harem mode
2. game will crash after a few seconds

**Expected behavior**
Game crashes with the above error

![image](https://user-images.githubusercontent.com/98631046/151646727-9e6e5e62-9672-4419-bf32-c611301244de.png)

Desktop
 - OS: Win10
 - Game Version 0.4.8
 - Processor(CPU): AMD 5600x
 - Graphics Card: RTX 3070
 - Memory: 32GB

.dmp file has been uploaded to repository under my account (not sure if that is the right way to do it though).

**Comment by LFANA** [comment]
The ue4-at game has crashed and will close soon after I went in

**Comment by LFANA** [comment]
The ue4-at game has crashed and will close soon after I went in
桌面

操作系统：Win10
游戏版本 0.4.8
处理器：i7-10875H
显卡：Geforce RTX 2060
内存：32GB
