### ISSUE TITLE
Since the 0.4.8 unable to exit animation experiment 

### ISSUE THREAD

**Issue by EVIL666DEAD** [itsamewayu/OLFallenDoll#513]
**Describe the bug**
Since the 0.4.8 I'm unable to exit the animation at the end of the experiment (orgasm). No keyboard key including esc works and I have to use task manager to exit the game.

Desktop (please complete the following information):
To Reproduce
Steps to reproduce the behaviour:

click end experiment and nothing happens
Expected behaviour
The reverse of the above

OS: Win10
Game Version 0.4.5
Complete the following Computer Hardware Configurations if necessary:
Processor Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz 3.19 GHz
Installed RAM 32.0 GB
System type 64-bit operating system, x64-based processor
*If your game crashed, remember to upload the dmp file with your issue.

It's located in C:\Users\ (USER ID) \AppData\Local\Paralogue

Additional context

**Comment by poykun** [comment]
Just got this as well. Thought it was weird I was getting 45 fps in a full lobby. Everyone seemed to hang in limbo while I was continuing the experiment.

**Comment by Ackerlight** [comment]
I just got this today but I think it may have been ping/lag related.  I was able to force quit the game and come back.  Ping times were normal then and I could not reproduce it again.
