### ISSUE TITLE
[Harem][Camera] Camera anchors points not set on 2 experiments

### ISSUE THREAD

**Issue by Awfulwaffle1** [itsamewayu/OLFallenDoll#514]
**Describe the bug**
When starting one of the two experiments in question, the free camera doesn't rotate around the subject on a left mouse click and drag. This becomes more apparent when setting the camera to rotate as the camera pans around as if the viewer is spinning around.

Experiments affected:
_Anya X Deep One - Arm Held Anal Doggystyle (Mid - Comp, Floor - Position)
Anya X Mi Go Nymph - Kneeling Double Penetration (Mid - Comp, Wall - Position)_

**To Reproduce**
1. Go to Harem
2. Press E and select one of the experiments above
3. Attempt to move camera around
4. Set camera to rotate

**Expected behavior**
Camera should be working like the other experiments

**Vid**
![no_anchor](https://user-images.githubusercontent.com/95268330/152063316-8049b857-2a92-4fe4-a6f5-34f830177194.gif)

Game Version 0.4.9

**Comment by poykun** [comment]
Add the following old experiment(s) to the list:
_Alet X Dreamer - Rear Admiral (Low - Comp, Floor - Position)_
