### ISSUE TITLE
[Harem][Animation] Hair physics seems to reset with each animation transition

### ISSUE THREAD

**Issue by Awfulwaffle1** [itsamewayu/OLFallenDoll#516]
**Describe the bug**
Erika's hair physics reset with each scene transition for the following animation:
Pinned Anal Prone Bone - Erika X Byakhee (Low - Comp, Floor - Location)

**To Reproduce**
1. Go to Harem mode and join a lobby
2. Press E and select the following experiment above
3. Place experiment down and observe Erika's hair
4. Play animation and observe
5. Pause animation and observe

**Expected behavior**
Smooth animation transition between each pause, play, restart, etc. action.

**Video**
![hair_bug](https://user-images.githubusercontent.com/95268330/152450587-2d147e30-5841-4ff4-8fb0-254dbc90650e.gif)

**Game Version: 0.4.9**

**Comment by poykun** [comment]
Adding more to the mix as I notice them:

Held Down Prone Bone- Erika X Hound of Tindalos (Low - Comp, Floor - Location)
