### ISSUE TITLE
[Model][Harem][Animation] Erika's left eyeball during her dazed "ahegao" state is too far turned making it look deformed

### ISSUE THREAD

**Issue by chuankaimah** [itsamewayu/OLFallenDoll#519]
**Description**
While using the "Standing Dildo" experiment with Erika and Dreamer, in her ahegao dazed state, her left eye is turned all the way in making it look very awkward. However, immediately after letting her climax her eyes seemingly go back to normal. I have attached screenshots and a video below. 

**To Reproduce**
Step 1) Use _Standing Dildo_ experiment with Erika and Dreamer
Step 2) Get her to dazed/ahegao state

**Expected behavior**
Her left eyeball will immediately turn inwards to such a weird angle such that it doesn't look normal at all. 

**Screenshots/Video**
![Paralogue-Win64-Shipping_1OMTnJxLTz](https://user-images.githubusercontent.com/13800409/152757881-000cb6f4-432c-4c0c-a845-8309cad5827c.png)
_Awkward eyeball angle_

![Paralogue-Win64-Shipping_fsibWci9We](https://user-images.githubusercontent.com/13800409/152759330-a4c7c567-00cd-4194-a334-0621cfab7766.png)
_Another angle of her eye_

https://user-images.githubusercontent.com/13800409/152759459-6af6edbd-9096-4673-843e-9c788053883c.mp4

_As seen, her eye seems normal but immediately after restarting the animation her eyeball goes back into a wonky position_

**Desktop:**
 OS: Win10
 Game Version [0.4.9]
 
Processor(CPU): [i5-10600kf]
Graphics Card:[RTX 3070]
Memory:[16GB]

**Comment by poykun** [comment]
Personal workaround would be to switch the eye tracking to none. The eye weirdness seems to happen with all the girls at the default settings. So maybe having all experiments starting with none nome rather than "head"

**Comment by johnathandarkly** [comment]
'wonky' is the expected position for eyes in ahegao mode. in this case her right eye (viewer left) almost pointed at the camera the error.
