### ISSUE TITLE
Game crashes within seconds of starting harem mode: LowLevelFatalError [File:Unknown] [Line:3927] Retry was NOT successful.

### ISSUE THREAD

**Issue by mm314601** [itsamewayu/OLFallenDoll#520]
![image](https://user-images.githubusercontent.com/31632560/152988136-4914f9b6-841e-4c2c-b96d-0c5f93450449.png)

I see this popup within seconds of starting harem mode. Every time. Every server. Every character. Clicking "OK" closes the game. It has been literally unplayable since the latest update.

**Comment by poykun** [comment]
Just asking, but have you tried verifying the integrity of the files through steam? Had a few users in discord with the same issue and that did the trick.

**Comment by mm314601** [comment]
Don't know what that means, if I'm being honest, but a few afters after posting this, I did uninstall the game entirely and reinstall it. That seems to have done something, so it's possible that verifying the integrity would have also worked. Now it's just kicking me back to the title screen most of the time that I try to connect to a server instead of crashing, which is... progress.
