### ISSUE TITLE
[proton] failure to launch 

### ISSUE THREAD

**Issue by johnathandarkly** [itsamewayu/OLFallenDoll#525]
**Describe the bug**
closed beta test worked well in steam/proton ( with eac hack from issue #47 ) up until january 1, 2022. since then, only the eac window pops up for about 15-20 seconds when launched, then the launch stops. 

**To Reproduce**
1. run steam on ubuntu
2. launch operation lovecraft cbt
3. stare hopefully at monitor for up to 20 seconds
4. cry a little, and carry on with life

**Desktop**
 - OS: Ubuntu 21.10 + Proton 6.3-8 
 - Game Version: 0.4.9
 - Processor: Ryzen 7 5700G 3.8ghz
 - Graphics:  Integrated Radeon 8 "Raven" 2.0ghz w/ 8gb allocated
 - Memory: 32gb

think of all those poor steamdeck users!

**Comment by IsaacFehr** [comment]
Any update to this?  I recently subscribed to the beta.  I figured it would work on proton, since the demo does.  But I haven’t been able to play it at all!
