### ISSUE TITLE
[Harem][Model] Erika Succubus outfit missing leather straps on gloves/legging when upper is nude

### ISSUE THREAD

**Issue by Awfulwaffle1** [itsamewayu/OLFallenDoll#527]
**Describe the bug**
Could be an assumption, but it seems that the succubus costume is lacking the accessory toggle.
Because of it there seems to be some display weirdness. 
This is made apparent with #517 with Erika's horn disappearing when nude.
Another thing that happens is that the lace glove/leggings loses its straps

**To Reproduce**
1. Go to Harem
2. Click on place any experiment with Erika
3. Have Erika in the Succubus outfit
4. Have the settings for Leggings and Upper Apparel be set to Dressed
5. Now set the Upper Apparel to Nude
6. Observe stray textures where the leather straps use to be for the gloves/leggings

**Expected behavior**
Separate texture layers for different parts of the costumes if possible.

**Screenshots**

_Upper Apparel Dressed_
![20220215144245_1](https://user-images.githubusercontent.com/95268330/154163346-adebb9a9-6d0a-4dea-921c-6c10c131889d.jpg)

_Upper Apparel Nude_
![20220215144238_1](https://user-images.githubusercontent.com/95268330/154163362-1d169013-e71a-444a-81cb-861e6ee41102.jpg)

**Game Version: 0.4.9**

**Comment by johnathandarkly** [comment]
the fix here would be to move the **black upper arm garter band**, **lace glove forearm straps** and **stocking top bands** to the group with the lace textures so they remain in clothing state shown in the second image.
