### ISSUE TITLE
[Model] Dr. Anya's Head model vibrating——Anya博士头部异常抖动

### ISSUE THREAD

**Issue by raluohe** [itsamewayu/OLFallenDoll#53]
**Describe the bug**
In classic mode, selecting Dr.Anya will cause her head vibrating.
Switching different scene or outfit won't fix that.
Not appearing on Erika and Alet.
经典模式下，选择Anya博士为女主角会产生未知原因的头部模型异常抖动。更换场景、服装、男性npc并不会使该bug消失；另外两位女主角不会出现该bug。

**To Reproduce**
1.Enter the game 进入游戏、
2.Adjust multiple graphic settings including graphics, Anti-aliasing, HDR, SSAO
调整画质、抗锯齿、hdr、SSAO等画质选项
3.Enter Classic mode and select Dr.Anya 进入游戏，角色更改为安雅博士
4.Bug appeared 出现头部剧烈抖动的bug

**Screenshots**
![image](https://user-images.githubusercontent.com/95136069/143686421-d85d8810-2b66-48a4-90ec-4ecfb30381c1.png)

**Desktop**
windows7（service pack 1）
GTX 1050
Memory: 8G

**Additional context**
Sometimes restarting the game will reduce the probability of this bug from appearing, but it remains unclear. Possibility increased after adjusting graphic settings.
有时候重启游戏会减少此bug的反生概率，但是尚不明确是什么操作会导致此bug出现。疑似是调节画质选项后。

https://user-images.githubusercontent.com/95136069/143686671-ef113d5c-d378-4320-a631-76518d00d245.MP4

https://user-images.githubusercontent.com/95136069/143686702-7ea9cb17-bbac-4b87-b0d3-4f90993960e2.MP4

**Comment by raluohe** [comment]
附加信息：cpu   i7 4770
                  显卡   1050
                  内存    8G

**Comment by raluohe** [comment]
https://user-images.githubusercontent.com/95136069/143686922-a43dc7fd-7fe3-46a2-851b-e082f5c53ef7.MP4

**Comment by jinjin525** [comment]
Edited the whole issue and the title. I can't see the video, not sure if it's my own issue.
编辑了标题和内容增加英语翻译和可读性。
