### ISSUE TITLE
[UI] [Harem] Experimental research timer bug

### ISSUE THREAD

**Issue by Ackerlight** [itsamewayu/OLFallenDoll#530]
There is an issue with the way the game is handling the Experimental studies.  If you study someone's experiment and observe it, you are able to get the Experiment and run it for 24hrs.  However, if you are running that experiment when the timer expires, the game reports that you now own the card.  If you try and run the experiment however you cannot place it.  The UI shows that you own the card and can select it.  It even shows the outline and will look like you can place it fine.  But you cannot.  (II am guessing here) but I bet the game also will not let me purchase that card again as it is showing I already have the full version in my stack.

**To Reproduce**
1. Go into Harem
2. Observe someone's experiment and middle click to research it.
3. Run it like normal.
4. When time is about to run out to 1 minute, start the experiment.
5. Timer runs out and you are still running the experiment.
6. Go to your list of Experiments.  It will show you permanently now have it.
7. You can select the Experiment card.  You can attempt to place it but cannot.
8. The card still shows you already own the experiment but now cannot do anything with it and it is a dead card.

**Expected behavior**
When the 24hr countdown timer runs out, the temporary card should disappear from your Experiment deck.  You can then have a chance to Research it again, win it from the random card draws or complete the research with Data so that you can own the card for real.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Game Version 0.49 (?) - the latest Patreon Beta build off Steam
 Complete the following Computer Hardware Configurations if necessary:
 - Processor(CPU): i9-11980HK
 - Graphics Card: RTX-3080
 - Memory: 32GB

*If your game crashed, remember to upload the dmp file with your issue.

It's located in C:\Users\ (USER ID) \AppData\Local\Paralogue

**Additional context**
n/a

**Comment by Ackerlight** [comment]
Adding this may have been a server bug.  I am not sure when the servers reset or how that works, but after two days the dead card at the time (foot licking scissoring) is now shown as inactive.

**Comment by johnathandarkly** [comment]
this has been a bug so long, it might be a feature. :) see issue #258

**Comment by Ackerlight** [comment]
All right, closing ticket then if it is a dupe.
