### ISSUE TITLE
Unable to connect to servers

### ISSUE THREAD

**Issue by EVIL666DEAD** [itsamewayu/OLFallenDoll#532]
**Describe the bug**
Unable to connect to any of the 4  servers

**To Reproduce**
1. Go to the front page choose harem
2. Click on Every one of the servers (because none are working and I'm not writing this out 4 times)
3. Loads up to map of the planet 
4. Returns to the home screen

**Expected behavior**
Connect to one of the servers

OS: Win10
Game Version 0.4.5
Complete the following Computer Hardware Configurations if necessary:
Processor Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz 3.19 GHz
Installed RAM 32.0 GB
System type 64-bit operating system, x64-based processor
*If your game crashed, remember to upload the dmp file with your issue.

It's located in C:\Users\ (USER ID) \AppData\Local\Paralogue

**Comment by Ackerlight** [comment]
I got in for about 20 minutes then they went down again.  Seems like there is still a server issue.
