### ISSUE TITLE
[Harem][Model] Alet 3-Some Kneeling Missionary

### ISSUE THREAD

**Issue by Ackerlight** [itsamewayu/OLFallenDoll#536]
**Describe the bug**
In the experiment Alet's 3-some Kneeling Missionary, the front penis does not align with her mouth.  It is going through her jaw/bottom of her throat.

**To Reproduce**
1. Go to Harem
2. Select Alet and The Dreamer
3. Select 3-some Kneeling Missionary card
4. View scene

**Expected behavior**
The penis and mouth should align.  Right now her mouth moves every time she makes a noise and also in general the penis is pointed at the bottom of her chin/throat area and clips through her mouth.  This should not happen and penis should not clip through the mouth area.

**Screenshots**
n/a - I took a screenshot but can't find them in Steam

**Desktop (please complete the following information):**
 - OS:  Windows 11
 - Game Version [e.g. 0.49
 Complete the following Computer Hardware Configurations if necessary:
 - Processor(CPU): i9-11980HK
 - Graphics Card: RTX-3080
 - Memory: 32GBB

*If your game crashed, remember to upload the dmp file with your issue.

It's located in C:\Users\ (USER ID) \AppData\Local\Paralogue

**Additional context**

**Comment by johnathandarkly** [comment]
i've seen clipping like this when the head control is set to point at "camera" or "head" ... did you change that setting?

**Comment by Ackerlight** [comment]
No.  Nothing was changed from the defaults.
