### ISSUE TITLE
[Sound][Harem] Lack of intercourse sound during animation

### ISSUE THREAD

**Issue by Awfulwaffle1** [itsamewayu/OLFallenDoll#538]
**Describe the bug**
Lack of intercourse sounds (skin slapping, ejaculation, etc.) during animation for the following experiments:

_Upright Holding Doggystyle Anal - Anya X Dream (Comp - None, Location - Floor)
Face-Down-Ass-Up - Anya X Deep One Hybrid (Comp - Mid, Location - Floor)
Standing Doggystyle Against Desk - Anya X Deep One Hybrid (Comp - High, Location - Prop)_

**To Reproduce**
1. Go to Harem
2. Join a lobby
3. Press E, select one of the experiments above and place down the experiment
4. Play the play button to start the experiment
5. Error

**Expected behavior**
Intercourse sounds are expected to be heard.

**Game Version: 0.4.9**

**Comment by poykun** [comment]
Similar to #358
