### ISSUE TITLE
[Clipping] Frag Granade model piercing & Minor detail improvement

### ISSUE THREAD

**Issue by Dendrobatus** [itsamewayu/OLFallenDoll#54]
Issue 1:

Dr. Anya has model penetration when wearing frag granades at multiple poses.
![image](https://user-images.githubusercontent.com/9326605/143686605-1423248e-81fd-4c44-b303-b8b9741112af.png)
![image](https://user-images.githubusercontent.com/9326605/143686643-26f19684-1fa5-4c18-9b8c-d8cf509b7c5b.png)

Issue 2:

The two breast enities seems to be going through each other and do not have interaction.
![b27090680c94f7a1ae7bf8578973871](https://user-images.githubusercontent.com/9326605/143686736-24007d41-4b3d-438e-8d3b-79d5c6b7f0c1.png)
maybe it can be made more realistic by adding a contact surface and a little pressing effect?

**Comment by Awfulwaffle1** [comment]
Frag Grenades no longer an accessory. Closing.
