### ISSUE TITLE
[Model] Erika's Skin layer missing with Socks unequipped

### ISSUE THREAD

**Issue by ATE2336** [itsamewayu/OLFallenDoll#55]
When sock is nake status, socks are gone

1. Go to laboratory
2. Click on Erika
3. Scroll down to Night maid

change cloths.

![image](https://user-images.githubusercontent.com/95136466/143686920-d848fb8d-3ea6-4479-bd38-6ef995fc741d.png)

 - OS: Windows10
 - Version 0.40

**Comment by Awfulwaffle1** [comment]
Still some weirdness with it.
![image](https://github.com/itsamewayu/OLFallenDoll/assets/95268330/ec2d1c4a-6b60-4e3c-9545-81d91ed326ec)
![image](https://github.com/itsamewayu/OLFallenDoll/assets/95268330/713bfe88-0d59-4b93-b417-a89fc2d05625)
