### ISSUE TITLE
In game mouse cursor mis-aligned.

### ISSUE THREAD

**Issue by Neon-Reaper** [itsamewayu/OLFallenDoll#555]
**Describe the bug**
If Window's setting for Display>Scale and layout is set to anything other than default the in-game cursor is not aligned properly. 

**To Reproduce**
1. Use a 4k monitor with Win10 installed
2. Navigate to Window's settings > Display > Scale and Layout
3. Change the setting to a % other than the default (in my case 300%)
4. Open the game and try to navigate the in-game menus

**Expected behavior**
The mouse cursor should allow you to click on whatever UI element it is hovering over.

**Screenshots**

![20220515114510_1](https://user-images.githubusercontent.com/105601725/168485584-178e5e88-7fb5-46fb-b158-bcb24b575535.jpg)
![20220515114505_1](https://user-images.githubusercontent.com/105601725/168485620-7f1c011b-5306-45de-afa2-8fa090cd590f.jpg)
![20220515114453_1](https://user-images.githubusercontent.com/105601725/168486119-2ec35f5c-fd6a-4d3d-aea9-92acdf271ca2.jpg)
![20220515114445_1](https://user-images.githubusercontent.com/105601725/168486161-c96d82e2-f4f5-4135-ab12-d1573967c4a2.jpg)
![20211202042155_1](https://user-images.githubusercontent.com/105601725/168486166-0415c279-464b-456a-984c-c8475de53433.jpg)
![20211202042039_1](https://user-images.githubusercontent.com/105601725/168486195-91fb298b-3e95-4184-9874-02eb73213893.jpg)

**Desktop**
 - OS: Win 10
 - Game Version 0.4.8
 
 - Processor(CPU): i9-10900K 
 - Graphics Card: RTX 3090
 - Memory: 32GB

**Additional context**
Hovering the in-game cursor over a clickable UI element doesn't allow you to click it, and you must move the cursor slightly above and to the left of what you are trying to click. This happens when the scale and layout of windows are any % other than the default. Setting the scale and layout back to default fixes the issue, but thanks to my visual impairment, that's sadly not an option for me (and likely others). I have tried many ways of fixing this issue on my end but nothing works other than setting the scaling to default.

**Comment by Ajax28542** [comment]
I have the same issue.  I have to hover the mouse further up and to the left to select anything.  I also have a 4k monitor and even the default scaling (300%) doesn't seem to fix the issue.

OS: Win 11

Game Version: 0.4.9

CPU: i7-12700k

GPU: RTX 3080

Memory: 64G

![Screenshot (2)](https://user-images.githubusercontent.com/111250242/184556184-f1cfadf4-2a39-458f-9378-dcb289a90f0c.png)
![Screenshot (3)](https://user-images.githubusercontent.com/111250242/184556189-15bf7082-19b2-4e9a-872a-21492707325a.png)
![Screenshot (4)](https://user-images.githubusercontent.com/111250242/184556196-6f783327-5d66-4292-aedb-f41e9e8e72e0.png)
