### ISSUE TITLE
No longer getting daily tasks?

### ISSUE THREAD

**Issue by JohnCattle** [itsamewayu/OLFallenDoll#561]
I am no longer receiving a daily task update. I have none in the quine and only stopped receiving the tasks 2 days ago.

**Comment by BeardDragoon** [comment]
I also have this bug.

**Comment by Fasachi** [comment]
Also having this issue starting July 7th

**Comment by johnathandarkly** [comment]
same. devs say may be due to recent backend changes, and should come back "soon."

**Comment by Pearl-Fish** [comment]
Also the same, noticed around July 9th-10th I would guess.  Although yesterday (July 12th) I did get them back temporarily while server hoping, unfortunately I had already clicked to disconnect before I noticed they were there, now gone again :(

Fingers crossed the backend gets sorted soon :)

**Comment by johnathandarkly** [comment]
i think this is the first bug here that's actually been fixed! cuz it is! 

even the daily task i completed has shown up ready to be claimed.
