### ISSUE TITLE
Fallen Doll Closed Beta Version - EAC Fails on startup on Steam Deck

### ISSUE THREAD

**Issue by PingPangPong888** [itsamewayu/OLFallenDoll#564]
**Describe the bug**
The full Beta Test/demo/playtest version is inoperable because the EAC (Easy Anti-Cheat) fails on startup.
**To Reproduce**
1. Obtain Steam Beta Test Key
2. Download and install Fallen Doll Closed Beta Version
3. Start game on Steam Deck, fails every time with blank screen except for blue EXIT button - this is EAC failing in some way.

**Expected behavior**
Game runs properly and gives access to both Harem & Gallery modes.
**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Steam 3.2, Proton - any version]
 - Game Version [0.4.9]
 Complete the following Computer Hardware Configurations if necessary:
 - System: Steam Deck
 - Processor(CPU): [AMD Custom APU 0405]
 - Graphics Card:[AMD Custom GPU 0405]
 - Memory:[16GB]

**Additional context**

**Comment by johnathandarkly** [comment]
hasn't been working on proton since the new year, see https://github.com/itsamewayu/OLFallenDoll/issues/525, had been working before then, see https://github.com/itsamewayu/OLFallenDoll/issues/47
