### ISSUE TITLE
[Animation] Table Supported Blowjob: "cum inside" animation is broken

### ISSUE THREAD

**Issue by apugo** [itsamewayu/OLFallenDoll#568]
This applies to Harem mode. I know it worked in version 0.34 (the version before Steam).

When you select "cum inside," the animation terminates. The buttons to either resume or exit appear but remain inactive. The experiment must be terminated with the Escape key.

**Comment by johnathandarkly** [comment]
had this happen yesterday. no climax animation, and repeat and exit buttons unresponsive.
