### ISSUE TITLE
"Sex toy" keyword returns zero results

### ISSUE THREAD

**Issue by apugo** [itsamewayu/OLFallenDoll#569]
Some experiments have the "sex toy" tag, with a little picture of a dildo. There is also a daily task to make women climax using experiments with the "sex toy" tag.

However, when searching the Experiments in the Harem main menu, searching for "sex toy" doesn't work. There are no results.

(edit: this seems to also be true of searching for "elder thing.")

**Comment by johnathandarkly** [comment]
this is true, but as a fix... "sextoy" does work.
