### ISSUE TITLE
Empty Daily Task

### ISSUE THREAD

**Issue by bigmork** [itsamewayu/OLFallenDoll#572]
**Describe the bug**
Task called "taskId:0", with 0/0 progress. When I hit claim, nothing happens.

**To Reproduce**
Not sure? Just happened when I logged in. Bug is persistent even when restarting game. Not sure if it'll go away tomorrow, guess I have to find out.

**Screenshots**
![image](https://user-images.githubusercontent.com/109406234/179341977-dd6a97c4-ab11-45a0-bacd-021c5b835d11.png)

**Comment by vutaboss** [comment]
![image](https://user-images.githubusercontent.com/109444194/179379430-881205da-8804-4120-af93-b35246764885.png)

I'm having the same issue. In my case, I was playing when the daily insanity reset. At the stroke of 8 pm eastern I saw "Daily Task Completed" but it couldn't be possible that I completed one so fast. That's when I saw this.

**Comment by Fasachi** [comment]
I am also experiencing this bug as well after another bug of not receiving any tasks for several days

**Comment by weebowiffick** [comment]
Same, probably will be fixed in a day or two.

**Comment by vutaboss** [comment]
Waiting for the next day fixed it for me. I now have two working tasks.
