### ISSUE TITLE
Certain "Experiments" don't start

### ISSUE THREAD

**Issue by elverlee** [itsamewayu/OLFallenDoll#579]
**Describe the bug**

**To Reproduce**
Nothing in particular, I am playing the game normally. Load Harem mode, press E, pick an experiment and place it where the indicator shows green. At first I notice a few poses do nothing when I click but eventually more and more pose or experiments are affected. What I previously had no issue with, now I cannot seem to play that scene. 

**Expected behavior**
Well I expected the experiment to start once I place it on the green zone. 

**Screenshots**
Not applicable, the experiment just won't start. Nothing happens. 

**Desktop (please complete the following information):**
 - OS: win10 21H2
 - Game Version [e.g. 0.42]: current beta version. I think 0.43? 
 Complete the following Computer Hardware Configurations if necessary:
 - Processor(CPU): AMD Ryzen 5 1600
 - Graphics Card:[e.g. GTX1070
 - Memory:16 GB
*If your game crashed, remember to upload the dmp file with your issue.

It's located in C:\Users\ (USER ID) \AppData\Local\Paralogue

**Additional context**
None

**Comment by Awfulwaffle1** [comment]
Verified fixed as of 0.7.2b. Closing. Will create individual tickets for any singular experiments that may have trouble.
