### ISSUE TITLE
[Model] Erika foot model bug when changing cloths and shoes

### ISSUE THREAD

**Issue by clifftor** [itsamewayu/OLFallenDoll#58]
To reproduce the bug:

1. Go to classic mode, select "Laboratory" -> "Erika". Redo this until Erika sits on a washing table.
![erika foot bug 1](https://user-images.githubusercontent.com/20754595/143687731-bfbff491-e0fa-459c-8564-c11a354e86e1.png)

2. Stay outfits as "Nude", switch Shoes as "Dressed". The foot model doesn't switch as it should.
![erika foot bug 2](https://user-images.githubusercontent.com/20754595/143687920-c24b880b-dd70-4b1c-9db6-0d603ff3ce91.png)

3. Switch outfits to a different one, then change it back, the foot model changed to fits in the high heel.
![erika foot bug 3](https://user-images.githubusercontent.com/20754595/143687925-33bd4125-c40f-4178-bb76-7a366c808846.png)

4. Stay outfits as "Nude", switch Shoes as "Nude". The foot model doesn't change back, staying in a weird shape.
![erika foot bug 4](https://user-images.githubusercontent.com/20754595/143687937-4eab7106-b4a8-42f2-a1c0-d464638132fd.png)

**Comment by TheSoulWizard** [comment]
ouch
