### ISSUE TITLE
[Harem Mode] Multiple bugs when the room begins to fill up

### ISSUE THREAD

**Issue by Tlck3** [itsamewayu/OLFallenDoll#581]
###  **Describe the bug**

**The failure usually occurs when there are many players in the same room.**
(There are some screenshots in which the bugs occur even if many players are disconnected and leave the room half empty, you have to leave and re-enter the room). 

The failures are multiple:

-When a player connects or disconnects, the screen freezes (although it is only 1 second approximately), the failure is constant, you have to leave and re-enter the room so that the failures are not repeated, but if the room is still full, the failures are repeated again when some time passes.

-The glitches in the textures are huge, no matter what position you are in. When observing other players, it's scary to see the bugs: legs that disappear, characters without hair, characters without heads, characters with upside down breasts...

-There are also failures with the "likes" when players connect or disconnect, there are likes that are not counted, if it coincides that are about to reach the "climax" the game does not give you any point of "Inspiration" (this is super annoying).

-And the constant bug, the mouse pointer, it "jumps" around the screen, even if you don't move the mouse. This becomes unbearable when coupled with the other bugs. 

### **To Reproduce**
**Steps to reproduce the behavior:**

You just have to enter a full room and wait for a while, or when a room is filling up, you don't have to do anything else.

### **Expected behavior**
The number of players should be limited, or there should be an option in the game to make all players permanently invisible. And to give likes, you could create a button to give likes from the list of players.
This would eliminate these bugs and also as there would be no more players in the room, this would allow to use the entire room without having to wait for another player to stop using a location that you need for a position you want to use.

**Screenshots**

![332](https://user-images.githubusercontent.com/51722473/201070971-58ebffb2-f716-4444-aa0b-9a20f0c0ea26.png)

![333](https://user-images.githubusercontent.com/51722473/201071104-9972c7d5-ed45-4075-a4c4-d5d35d8a7181.png)

![334](https://user-images.githubusercontent.com/51722473/201071158-256742dd-5470-4b69-9601-6cfffa7b4e5b.png)

![335](https://user-images.githubusercontent.com/51722473/201071194-ef66329d-4e2c-4c0e-8591-5e6b716eac45.png)

### **Desktop (please complete the following information):**
 - OS: Win 10
 - Game Version: 0.4.9
 **Complete the following Computer Hardware Configurations if necessary:**
 - Processor(CPU): i5-9600K
 - Graphics Card: RTX 2060 Super 8GB
 - Memory: 16GB

### **Additional context**
These bugs become unbearable when they are all together, although **the mouse cursor bug is permanent**.
_(When you play you can see how there are players that when they see the room very full, they leave the room in seconds)._ 

I hope that you can incorporate the option to make invisible all players permanently and thus be able to play properly, without having to be waiting to use a position because there is someone using that site. And by putting a button that allows to give the likes from the players list, the "Harem" mode will still be able to be used as before. 
Also the mouse bug is very important to solve, it is permanent and is one of the most annoying bugs.

**If these changes are made, players will be able to be in a room "for ourselves" within the Harem mode, and at the same time those who wish to see the other players will be able to do so.**

**Comment by zh8650** [comment]
老师请给个游戏下载链接
