### ISSUE TITLE
[UI] A certain card has low a quality texture

### ISSUE THREAD

**Issue by richardgooden** [itsamewayu/OLFallenDoll#588]
**Describe the bug**
Was conducting research and all the cards were normal quality, when suddenly this low quality textured card came up

**To Reproduce**
1. Start researching any card pack
2. Click on next till it bug occurs

**Expected behavior**
All the cards should be have the same texture quality

**Screenshots**
![FallenDoll   28_2_2023 9_09_07 pm](https://user-images.githubusercontent.com/25347409/222137886-f12a69ae-abca-4c1b-b767-228031f660d1.png)

**Desktop:**
 - OS:  Win11
 - Game Version: 0.49
 - Processor(CPU): AMD Ryzen 5 4600H
 - Graphics Card: NVIDIA GeForce GTX 1650
 - Memory:  32GB

**Additional context**
There was an animation associated with it which was also low quality. 
I don't remember if this type of card had appeared earlier with normal textures. I think this is the first time this particular card texture/ design/ color showed up for me.
I entered harem mode soon after and all the textures were low quality and I was unable how to change change it in settings. Could be related?

**Comment by Awfulwaffle1** [comment]
Verified Resolved as of Build 0.7.2b. The blurred cards would usually be Celia experiments. Closing.
