### ISSUE TITLE
[Error] Unsupported host machine architecture. (ARM64)

### ISSUE THREAD

**Issue by amphineko** [itsamewayu/OLFallenDoll#59]
**Describe the bug**
The game won't start and reports "Unsupported host machine architecture. (ARM64)"

**To Reproduce**
1. Launch the game using Steam

**Expected behavior**
The game should start normally.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11 (ARM64)
 - Version: 10.0.22000 Build 22000

**Comment by polleoPotion** [comment]
I have the same issue, using a Macbook Pro with Parallels Windows 11 installed, couldn't run the game even using Steam.

**Comment by moodyomar** [comment]
same issue, M1 Max , Parallels windows 11 , trying to run APE, COD Warzone, Halo , nothing seem to work.
