### ISSUE TITLE
[UI] PLAYER AFFOARDANCE DISCREPENCY IN RESEARCH PASS

### ISSUE THREAD

**Issue by Nekokaburi0** [itsamewayu/OLFallenDoll#590]
-STEPS TO REPRO:

1: ENTER HAREM MODE

2: CLICK ON THE SHORCUT UI FOR ANY CHARACTER'S RESEARCH PASS

-RESULT: UNABLE TO LEAVE THE RESEARCH PASS SCREEN USING THE "ESC" KEY. CLICKING THE "BACK" TEXT IS THE ONLY WAY TO RESOLVE THE ISSUE.

**Comment by Awfulwaffle1** [comment]
Resolved as of 0.7.3. Closing.
