### ISSUE TITLE
[TEXT] TYPOGRAPHICAL ERROR IN ANYA'S TAGLINE DESCRIPTION

### ISSUE THREAD

**Issue by Nekokaburi0** [itsamewayu/OLFallenDoll#593]
THE TAGLINE FOR ANYA'S RESEARCH PASS SCROLLER HAS A TYPOGRAPHICAL ERROR.

DESIRED TEXT: "The Neurobiologist"

RESULTING TEXT: "TheNeurobiologist"

**Comment by Awfulwaffle1** [comment]
Verified Text is adjusted as of 0.7.3 build. Closing.
