### ISSUE TITLE
[GAMEPLAY] CAMERA BOUNDS/OBJECT COLLISION ISSUE

### ISSUE THREAD

**Issue by Nekokaburi0** [itsamewayu/OLFallenDoll#594]
-STEPS TO REPRO:

1: LAUNCH HAREM MODE AND ENTER THE EROTES NIGHTCLUB

2: GO BEHIND THE BAR AND APPROACH THE WALL

-RESULT: WALKING INTO ANY SPOT OF THE WALL WITH THE WINE RACKS BEHIND THE BAR WILL FORCE THE PLAYER CAMERA TO SWITCH TO A PSEUDO FIRST-PERSON ANGLE.

**Comment by Awfulwaffle1** [comment]
Issue verified resolved as of 0.7.3. Closing.
