### ISSUE TITLE
[UI] POLE DANCE UI-BOUNDS CLIP THROUGH FLOORING

### ISSUE THREAD

**Issue by Nekokaburi0** [itsamewayu/OLFallenDoll#595]
STEPS TO REPRO:

1: LAUNCH HAREM MODE AND ENTER THE EROTES NIGHT CLUB

2:GO BEHIND THE BAR AND WALK TO DEAD CENTER

-RESULT:
MENU UI FOR THE POLE DANCE EVENT ON THE FLOOR ABOVE IS DISPLAYED AND USABLE.

**Comment by Awfulwaffle1** [comment]
Verified Resolved as of 0.7.3. Closing.
