### ISSUE TITLE
Account linking error updated still broken 

### ISSUE THREAD

**Issue by Vixavil** [itsamewayu/OLFallenDoll#596]
Cant link Patreon and lost all my progress this is the error message
![82e2373bea78ece386a41f796836d5b1](https://user-images.githubusercontent.com/73802368/222943955-2e0d69fd-8e02-4795-a360-8ab73ace4dae.png)

**Comment by TheSoulWizard** [comment]
Give it a few minutes or and hour or two. This is likely due to high amount of traffic on the website.

**Comment by Vixavil** [comment]
New update to the problem it just changed the error message 
![82e2373bea78ece386a41f796836d5b1](https://user-images.githubusercontent.com/73802368/223012767-2e64a286-9ed5-4708-9027-655604223873.png)

**Comment by Vixavil** [comment]
Update to the issue it just changed the error message.
![0b9e4472a6639407a8c36cc870946973](https://user-images.githubusercontent.com/73802368/223012873-f7d7e661-b690-4870-acf0-647415901ba3.png)
