### ISSUE TITLE
[UI] Experiment Configuration Mistakes

### ISSUE THREAD

**Issue by Foolgy** [itsamewayu/OLFallenDoll#599]
The combination of characters dont match. I have Experiment #101, Alet spitroast with 2 dreamers. To get this animation to show up to select and play, i select Alet, Celia and dreamer. If i select Alet and Dreamer, the animation is not an option.

**To Reproduce**
1. Press E
2. Click on Alet, Celia and Dreamer
3. Experiment 101 shows up

**Expected behavior**
Celia should not be part of the combination to get this animation to display.

**Screenshots**
![image](https://user-images.githubusercontent.com/127007147/222944374-cb0c66df-9b2c-4c73-95d5-4c37293afad9.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Game Version 0.7?
 Complete the following Computer Hardware Configurations if necessary:
 - Processor(CPU): 7600X
 - Graphics Card: 4090
 - Memory: 32GB ddr5 6000Mhz

*If your game crashed, remember to upload the dmp file with your issue.

It's located in C:\Users\ (USER ID) \AppData\Local\Paralogue

**Additional context**

**Comment by Awfulwaffle1** [comment]
Verified Resolved as of 0.7.3 build. Closing.
