### ISSUE TITLE
[Clipping] Bunny Erika Outfit clipping

### ISSUE THREAD

**Issue by itsamewayu** [itsamewayu/OLFallenDoll#6]
CarlR — Yesterday at 6:59 PM
not sure what this dress is, but i think it's broken,  Also dress name is not English
![unknown](https://user-images.githubusercontent.com/11155504/143678626-8104cab6-d834-4a33-9055-dffcc98861af.png)

**Comment by Awfulwaffle1** [comment]
This ultimately has been resolved, but other issues have sprung up regarding clothing. Closing this for now.
