### ISSUE TITLE
[Clipping] Alet's Pantyhose Clipping

### ISSUE THREAD

**Issue by ymxiaofx** [itsamewayu/OLFallenDoll#60]
In some positions
①![1](https://user-images.githubusercontent.com/95134684/143690890-365faf77-60c4-41dd-95e9-35d51c3193f0.png)
②![2](https://user-images.githubusercontent.com/95134684/143690897-b7052170-5db1-4c4a-87cc-82e9089670d7.png)
③![3](https://user-images.githubusercontent.com/95134684/143690921-65215807-bb5a-43f4-9984-ef1716e9171f.png)

**Comment by Awfulwaffle1** [comment]
Minor clipping remains, but improved: 
![image](https://github.com/itsamewayu/OLFallenDoll/assets/95268330/3c6232d4-4eee-4463-9db8-7ac46aa10a62)
