### ISSUE TITLE
Missing Data from Pre-Phase Two update 0.7.0 launch

### ISSUE THREAD

**Issue by AiJohnnyBravo** [itsamewayu/OLFallenDoll#600]
**Describe the bug**
Data and progress from before the 27th is missing in game.
character Skin Tone / Hair color / last outfit
![example](https://user-images.githubusercontent.com/127007051/222944572-10dde487-d5fb-4d95-bccf-a3d449053672.png)
 still present however

**To Reproduce**
go into harem 

**Expected behavior**
Clothing unlocks and experiments to still be present 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Game Version 0.7.0
 Complete the following Computer Hardware Configurations if necessary:
 - Processor(CPU):  i7-8700K
 - Graphics Card: RTX 3080
 - Memory:16gb 

**Additional context**
noticed while playing around going back and forth on Character menu Tips box flashed Authentication error
![example2](https://user-images.githubusercontent.com/127007051/222944680-0cc07945-604e-489b-a353-92deb49f872b.png)
![example](https://user-images.githubusercontent.com/127007051/222944692-583e1134-ba44-43a1-ad72-434d69f388c3.png)

**Comment by Awfulwaffle1** [comment]
Expected issue as there was an account wipe. Phase 1 Progress rewards were given out for participants and a new account needed to be created. As of now there are no other expected wipes. Closing.
