### ISSUE TITLE
进入后宫模式之后卡在输入用户名界面

### ISSUE THREAD

**Issue by mayuzhexd** [itsamewayu/OLFallenDoll#603]
**Describe the bug**
进入后宫模式之后卡在输入用户名界面，之前进入后宫模式输入了一次用户名，之后掉线出来后，再进后宫模式就要重新输入用户名，并且弹出框说：真实姓名已经修改过了。 无法进入游戏，只能强行退出。之后每次进入后宫模式都要求输入用户名，并且输入任何名字都弹出框：真实姓名已经修改过了，游戏进度卡死在这个地方，无解。

**Screenshots**

![I8NLQH2~ ~A8@C$SO}@KQ2C](https://user-images.githubusercontent.com/127009059/222946648-5ba9897f-d70b-43fc-85d8-bf962c64f7ac.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Win10
 - Game Version [e.g. 0.70]
 Complete the following Computer Hardware Configurations if necessary:
 - Processor(CPU): [e.g.AMD 5900X]
 - Graphics Card:[e.g. RTX 3080Ti]
 - Memory:[e.g. 32GB]

**Comment by kaifueriko** [comment]
我也是这个问题，怎么办

**Comment by Awfulwaffle1** [comment]
closing as this has been resolved as of 0.7.3.
