### ISSUE TITLE
patreon linked but reward problem

### ISSUE THREAD

**Issue by warlongxd** [itsamewayu/OLFallenDoll#604]
**Describe the bug**

**To Reproduce**
1. Go to 'home page'
2. Click on 'linked patreon first and then click mail to caim rewards'
3. Scroll down to 'reward caim'

**Expected behavior**

1. Didn't get all the time limited rewards skins
2. Money calculation has some problem 
3. Capitalists didn't get a premium pass to unlock character

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Game Version [0.7.0]
 Complete the following Computer Hardware Configurations if necessary:
 - Processor(CPU): [Amd 7 3700x]
 - Graphics Card:[RTX 3060 Ti]
 - Memory:[32 GB]

*If your game crashed, remember to upload the dmp file with your issue.

It's located in C:\Users\ (USER ID) \AppData\Local\Paralogue

**Additional context**

since I already linked to my patreon, but I was supported one 36+ and 95+ USD and some sporadic sponsorship. Also caim all the time limited rewards, but in game after I linked my patreon I didn't get everything, for one of the my problem: Money, some people who supported 36+ and 95+ they got 5000, and mine just got 1384, I don't know how u guys calculate it, but it does something wrong in here. For another my problem is that limited reward skins, I do caim all the limited reward skins, but in game I didn't get every skins, for example, Erika has 7 skins in time limited reward skins, but I only got three of them, some people just also got 5.

![image](https://user-images.githubusercontent.com/80300897/222946838-5b79cfe0-b3fd-4be7-a8b9-7bf4d5a3b1c6.png)
![image2](https://user-images.githubusercontent.com/80300897/222946842-1e75e266-336a-406d-854b-0b3d231ed19c.png)

**Comment by warlongxd** [comment]
also forgot to prove my payment
![image3](https://user-images.githubusercontent.com/80300897/222946966-0a44343d-02cd-4d11-82b1-dd66dffc3892.png)

**Comment by Ledar** [comment]
You'd better provide your Steam ID,Player ID in game,Patreon email, we will check if there is something went wrong.

**Comment by warlongxd** [comment]
> 

oh, here is my ID, Steam ID: 76561198190649333, Player ID: WARLONGXD, Patreon email: warlongxd@gmail.com

**Comment by Ledar** [comment]
1. Didn't get all the time limited rewards skins
 We found that you only claimed August Supporter Bundle and February Supporter Bundle before 2023.01.27 which is the timeline for this time's beta, so you only got two month's Time-Limited reward.

2. Money calculation has some problem
We use your patreon lifetime support cents for our campaign to calculate NEP in game, the exchange rate is $1:NEP8, so there maybe no problem with the total NEP you got.

**Comment by warlongxd** [comment]
> 1. Didn't get all the time limited rewards skins
>    We found that you only claimed August Supporter Bundle and February Supporter Bundle before 2023.01.27 which is the timeline for this time's beta, so you only got two month's Time-Limited reward.
> 2. Money calculation has some problem
>    We use your patreon lifetime support cents for our campaign to calculate NEP in game, the exchange rate is $1:NEP8, so there maybe no problem with the total NEP you got.
> 
> 3.Capitalists didn't get a premium pass to unlock character This feature is under development

for the time limited rewards part: but in February I caim them all with my capitalist, isn't I should get them all?

**Comment by Awfulwaffle1** [comment]
All Time Limited rewards should have now been sent out. Please create another issue or a discord support ticket for further assitance @warlongxd
