### ISSUE TITLE
后宫模式卡在用户名输入界面，提示真实名字已经修改了

### ISSUE THREAD

**Issue by kaifueriko** [itsamewayu/OLFallenDoll#606]
之前我已经成功进入后宫模式，并且设置了用户名。但是我现在无法登陆，且需要重新设置用户名，但是系统提示我用户名已经修改过，无法登陆。请帮助我，谢谢。
![F7C11F67-31BE-4B4C-ABE6-A82EB7DDCBAC](https://user-images.githubusercontent.com/127014707/222950996-46c0a040-0b40-41f8-9435-5618dc8bbf03.jpeg)

**Comment by poykun** [comment]
Duplicate issue #603

**Comment by Awfulwaffle1** [comment]
Closing as this has been resolved as of 0.7.3.
