### ISSUE TITLE
[Model] 安雅在身着科考队紧身衣时，下部无物理表现（When anya wears expedition pilot suit, her pussy does not have the physical performance)

### ISSUE THREAD

**Issue by POP9Y** [itsamewayu/OLFallenDoll#61]
![image](https://user-images.githubusercontent.com/95142070/143691436-9b903aad-fa80-4c34-97f9-96395a1f2f79.png)

**Comment by TheSoulWizard** [comment]
Seems like it's fixed now. Unknown which version fixed that bug.
