### ISSUE TITLE
Gallery Mode - Alet - Non-stop Cumming

### ISSUE THREAD

**Issue by SMASH225** [itsamewayu/OLFallenDoll#612]
**Describe the bug**
Alet with Lord of Tindalos. after cumming, she kept cumming. took about 5 minutes to stop

**To Reproduce**
1. Go to 'gallery mode'
2. Click on 'Alet and Lord of Tindalos. most disliked bubble. anal scene and internal cum'
3. error - after cumming, she kept cumming for about 5 minutes even while witching scenes or switching partners

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 11
 - Game Version 0.7.0
 Complete the following Computer Hardware Configurations if necessary:
 - Processor(CPU): [i9 - 11900k]
 - Graphics Card:[rtx 3070ti]
 - Memory:[16GB]

*If your game crashed, remember to upload the dmp file with your issue.

It's located in C:\Users\ (USER ID) \AppData\Local\Paralogue

**Additional context**

**Comment by SMASH225** [comment]
Update - Alet will continuously cum for a few minutes for any sex scene wehn she does cum

**Comment by Awfulwaffle1** [comment]
I believe this also extended to Harem at one point, but should now be fixed. Closing.
