### ISSUE TITLE
VR自動啟動

### ISSUE THREAD

**Issue by Rabbitbeam** [itsamewayu/OLFallenDoll#614]
啟動0.7.0版的時候
會自動啟動STEAMVR
但我記得目前版本有公告說不包含VR對吧

自動啟動VR有辦法解決嗎?

**Comment by 0b5erv3r** [comment]
把你的VR启动选项设置成openxr

**Comment by 0b5erv3r** [comment]
打开你的oculus软件把启动选项设置成oculus

**Comment by poykun** [comment]
VR is not included and a similar issue was documented in #602. 
Workaround would be the following
> Update: you can use the launch option `-nohmd` to prevent it from launching any VR runtime.
