### ISSUE TITLE
Can't play harem mode

### ISSUE THREAD

**Issue by AQQQAAAqqq** [itsamewayu/OLFallenDoll#615]
The scene of entering the harem mode will automatically restart the game to the main interface
BUG can be reproduced

**Comment by Awfulwaffle1** [comment]
@AQQQAAAqqq as of 0.7.3 are you still experiencing this issue?

**Comment by Awfulwaffle1** [comment]
Closing, but please reopen or reach out if you're still have this issue @AQQQAAAqqq
