### ISSUE TITLE
[UI or server] authentication failed

### ISSUE THREAD

**Issue by DarkRaven2023** [itsamewayu/OLFallenDoll#616]
**Describe the bug**
![test1111](https://user-images.githubusercontent.com/127008409/222963587-f407306f-e12c-484f-b085-b9315b106ea6.jpg)

**To Reproduce**
This message often appears when entering the game screen. 

![20230305232458_1](https://user-images.githubusercontent.com/127008409/222969873-9377922d-3b37-408c-88d4-361d501f7a75.jpg)
↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
![20230305232520_1](https://user-images.githubusercontent.com/127008409/222969881-2abe98be-4154-4102-b708-2e5d560d5cc0.jpg)
↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
![20230305232540_1](https://user-images.githubusercontent.com/127008409/222969895-e2800886-abe3-4a69-9df8-cb5a5eabcd07.jpg)
↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
![20230305232544_1](https://user-images.githubusercontent.com/127008409/222969917-a1b5160a-8768-4871-8b38-bffaf5473fc5.jpg)
↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
![20230305232441_1](https://user-images.githubusercontent.com/127008409/222969927-85b6475e-105b-4c5e-a7eb-ac78eb267109.jpg)
↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
![20230305232458_1](https://user-images.githubusercontent.com/127008409/222969934-5d237fe5-af68-4aeb-820b-63e4297b6fb3.jpg)

**To Reproduce**
Sometimes I can enter harem mode, but when I enter  nightclub or space station, I will jump back to the warning and thanks screen. 

**Desktop (please complete the following information):**
 - OS: Win11
 - Game Version [e.g. 0.7.0]
 Complete the following Computer Hardware Configurations if necessary:
 - Processor(CPU): [e.g. i5-12600K]
 - Graphics Card:[e.g. RTX 3050]
 - Memory:[e.g. 32GB]

**Comment by Awfulwaffle1** [comment]
@DarkRaven2023 as of build 0.7.3 are you still experience this issue?

**Comment by Awfulwaffle1** [comment]
Marking resolved as of now, but please reopen if it's still an issue. @DarkRaven2023
