### ISSUE TITLE
[UI or server] The benefits of the capitalists, as well as the benefits of sponsorship, are gone

### ISSUE THREAD

**Issue by DarkRaven2023** [itsamewayu/OLFallenDoll#617]
The first time I logged in, I went to the mailbox to pick up something, but unfortunately I was kicked out of the server, and I connected online again but found that everything was gone.....There was nothing in the mailbox, cards are also none, and my capitalist benefits and clothing are gone.

![20230306194455_1](https://user-images.githubusercontent.com/127008409/223116940-d4896664-170e-45fc-8d32-4b67d86a329d.jpg)
![20230306195340_1](https://user-images.githubusercontent.com/127008409/223116992-dadaf0b0-1aab-48d5-a44b-b3e44e3ba8a2.jpg)
![20230306194851_1](https://user-images.githubusercontent.com/127008409/223117076-d288ed5a-2a2a-423d-a3c6-fe7766507dbe.jpg)

OS: Win11
Game Version [e.g. 0.7.0]
Complete the following Computer Hardware Configurations if necessary:
Processor(CPU): [e.g. i5-12600K]
Graphics Card:[e.g. RTX 3050]
Memory:[e.g. 32GB]

**Comment by Awfulwaffle1** [comment]
This should have been addressed after the 2nd wipe for Stress Test #2. Closing this issue, but please follow up with a support ticket in discord if this is still a problem.
