### ISSUE TITLE
[Account or server] Game can't find player ID

### ISSUE THREAD

**Issue by Krille340** [itsamewayu/OLFallenDoll#619]
When trying to open Harem mode, game loads for a couple of seconds, then error message stating that player ID is missing

1. Go to main menu.
2. Click on Harem mode.
3. Wait for a couple of seconds, then error message pops up.

![Screenshot_28](https://user-images.githubusercontent.com/127045208/222976656-890ac0c0-5fc6-4ef2-b595-0c4a0ace7f1f.png)

I have connected my patreon with steam/ the game, but haven't logged in into the game for a long time.
I can also get another error similar to this, but it instead states that it fails to get a response from the backend server. See the image below:

![Screenshot_29](https://user-images.githubusercontent.com/127045208/222976821-362639cd-929a-441e-b780-0d004477c27e.png)

**Comment by KBM2** [comment]
I got the same Problem, just not the same "uid". 
Last time I was able to enter Harem was November 2021.

**Comment by dakus570** [comment]
I have the same issue.

**Comment by Awfulwaffle1** [comment]
Should have been resolved as of Stress Test 2. Closing.
