### ISSUE TITLE
[0.7.0] In a multiplayer game, in the nightclub, When attempting to unlock the "pack" of cards, the same three poses unlock repeatedly, and reducing the number of "pack".

### ISSUE THREAD

**Issue by p0315167** [itsamewayu/OLFallenDoll#621]
**Describe the bug**
When attempting to unlock the "pack" of cards, the same three poses unlock repeatedly.
**To Reproduce**
In a multiplayer game, in the nightclub, if you open the "dressing room" to draw cards, you will draw 3 identical "cards" repeatedly, reducing the number of "pack".

**Expected behavior**
50 packs will be given when starting the game. I unlocked 23 "pack" ，but only unlocked 19 poses.

**Screenshots**
attach evidence :
https://imgur.com/a/4lJOvyY

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Game Version [0.7.0]
 Complete the following Computer Hardware Configurations if necessary:
 - Processor(CPU): intel i9-13900k
 - Graphics Card: MSI RTX 4090
 - Memory: DDR5 64GB

**Comment by Awfulwaffle1** [comment]
duplicate issue of #591
