### ISSUE TITLE
(0.7.0) (bug) Opening blueprint cards, only receiving duplicates, and not receiving experiments. 

### ISSUE THREAD

**Issue by plutonium142** [itsamewayu/OLFallenDoll#622]
**Describe the bug**

The bug I'm having is that when I got into harem mode, I tried to open my blueprint cards, however when I opened them, they all showed same experiments, then a blank tip screen popped up for each time I opened the cards. One of the tries i was able to get a tip but its in chinese. The same cards being opened again multiple times. When I restarted game it opened a different set of cards but still had same issue where all the subsequent cards that are opened are all duplicate cards. I started with 48 cards and now I'm down to 33 but with only 6 experiments now available since all the cards opened are somehow only duplicates.  

**To Reproduce**
1. connect on harem mode
2. click on blueprint to open
3. once you click your blueprint to open cards, blank tip screen pops up
4. click next, same exact cards open, and blank tip pops up
5. once you go back to harem mode screen, it shows you used blue prints
6. click to see your experiments that you can use, there will be none available

When

**Expected behavior**

When I open up blueprints, all the cards will be the same and it will constantly deplete your blueprints available without giving you new experiements.

**Screenshots**
attached are screen shots I know i did a bad job of taking them, but those are 4 separate times where I opened the same set of cards one after the other, with these errors messages in between

**Desktop (please complete the following information):**
 - OS:  Win10
 - Game Version: 0.70

*If your game crashed, remember to upload the dmp file with your issue.

It's located in C:\Users\ (USER ID) \AppData\Local\Paralogue

**Additional context**
![20230305160232_1](https://user-images.githubusercontent.com/127055006/222986027-7947e3fd-4bf4-4170-84ed-cc922418bac7.jpg)
![20230305160244_1](https://user-images.githubusercontent.com/127055006/222986028-df0cadcc-83f6-482f-b956-40f6cc7049cb.jpg)
![20230305160247_1](https://user-images.githubusercontent.com/127055006/222986029-176fff3a-d143-41e8-83c5-fe4f3ea9fb1d.jpg)
![20230305160254_1](https://user-images.githubusercontent.com/127055006/222986030-8dfa76f0-a318-4a5d-ad39-82f5f51b29ab.jpg)
![20230305160303_1](https://user-images.githubusercontent.com/127055006/222986031-4e92ca7f-d885-42cd-b392-400b086023d8.jpg)
![20230305160304_1](https://user-images.githubusercontent.com/127055006/222986032-e635e6dc-9a7f-41cf-b381-39db9142a878.jpg)
![20230305160309_1](https://user-images.githubusercontent.com/127055006/222986033-b97f9a22-9874-40ec-9d64-c4d63509b85d.jpg)

**Comment by Awfulwaffle1** [comment]
#591 duplicate
