### ISSUE TITLE
[refresh] After refresh the next day , Some content is not refreshed.

### ISSUE THREAD

**Issue by DAmbielSy** [itsamewayu/OLFallenDoll#623]
**Describe the bug**
The next day sanity is refreshed but the pole dance is still 10/10 unattainable and the character is still exhausted.

**To Reproduce**
1. I ran out of sanity on the first day.
2. The next day sanity refresh I logged on and was still exhausted and pole dancing 10/10.
3. I played it for a while to see if it changed, and it didn't.

**Expected behavior**
After sanity update, the character should be fresh and pole dancing can be reinspired 10 times.

**Screenshots**
![QQ截图20230306093722](https://user-images.githubusercontent.com/127064779/223000536-2bb597d1-3cc3-478c-8592-607ebe74e071.png)
![QQ截图20230306093955](https://user-images.githubusercontent.com/127064779/223000718-82edb574-3b35-49e0-8992-560ab83cfd42.png)
Screenshots from day 2

**Desktop (please complete the following information):**
 - OS: Win10
 - Game Version:  0.7.0
 - Processor(CPU):  i7-10700KF
 - Graphics Card: RTX 3080 LAPTOP
 - Memory: 32GB

**Comment by Awfulwaffle1** [comment]
@DAmbielSy please verify if this is still happening on your end.

**Comment by Awfulwaffle1** [comment]
Closing as this does not seem like an issue anymore. WIll reopen or create a new issue if it occurs again.
