### ISSUE TITLE
[0.7.0] [Bug] Unable to open Celia Grey bluprints and Green/Blue ones give a NULL card

### ISSUE THREAD

**Issue by Neeka1312** [itsamewayu/OLFallenDoll#624]
No matter what i try i can't open Celias Grey blueprints (other ones work), and her blue and green ones give a NULL card and disapear into the void.
Also cant seem to get any of her cards from the random blueprints. Opened arround 30 randos.
But i can buy and use them with Data.

1. Enter Harem Mode
2. Select a blue or green blueprint

**Screenshots**
Tried to open a green one.
![Pass](https://user-images.githubusercontent.com/127066201/223002321-312997a5-d682-4718-9947-6344e0692645.jpeg)
![Experiments](https://user-images.githubusercontent.com/127066201/223002364-6c71f704-f468-4755-bb7e-a9fcc06e6137.jpeg)
![Pre opening](https://user-images.githubusercontent.com/127066201/223002374-e90b1a62-0c36-41bb-bc3e-eb172519a10d.jpeg)
![Opened](https://user-images.githubusercontent.com/127066201/223002386-65a1bb62-ad6b-480c-a8b0-3099bbf0da17.jpeg)

**Additional context**
For me it's just Celia cards that seem to be bugged, other drop fine.
I first encontered this bug yesterday and lost both a green and blue blueprint to the void.
Replicated this to post here but it seems i still have the green blueplrint i tried to use.

**Comment by Awfulwaffle1** [comment]
Have not seen any other report of this happening since 0.7.3. Marking Resolved and closing.
