### ISSUE TITLE
Didn't receive the converted Levels to the in-game "Level booster"

### ISSUE THREAD

**Issue by Khado77** [itsamewayu/OLFallenDoll#625]
**Bug**:
I didn't receive the 50 converted levels as the in-game items (I was above level 50 in phase 1)

**Reproduce**:
0. Started the game and entered Harem
1. I selected one of the 3 types of the experiments (Xenology, etc.).
2. I choose the exact same Nickname as in phase 1.
3. I tried multiple times to click confirm but after getting a chinese pop up, which is translated means "Username is already taken" I tried other Nicknames.
4. I restarted the game and chose Harem
5. I got in with no choosing name.
6. The current Researcher Name displayed, is the same name as in phase 1 and the first name i tried to choose before restarting.
7. I linked my patreon successfully.
8. I got no Experiments or Blueprints and no in-game reward (except the Patreon rewards (Currency and Outfits) and no 50 Level booster. I also tried to claim the patreon rewards but i couldnt claim the currency. But after few times trying to claim the outfits i couldn't press claim on the outfits anymore. Also I don't see the outfits in the Character outfits.
9. I restarted a few times with the same result

**Expected behavior**:
It was stated that you will get a maximum of 50 level from phase 1 converted to in-game items for boosting your level in phase 2 when you start your game.

**Desktop**:
 - OS: Win 11
 - Game Version 0.7.0

 **Computer Hardware**:
 - Processor(CPU): i5-11400f
 - Graphics Card: RTX 3060
 - Memory: 32gb

**Comment by SpamFilter9k** [comment]
Got the same issue but without linking patreon account. I did the steps 0 - 6 in the same order and have no Blueprints, no Experiments, no starting currency.
Researcher name is same as used here (also was in phase 1).

System:
- OS: Win 10
- CPU: AMD Ryzen 7 3700X
- GPU: RTX 4090
- RAM: 32 Gb

**Comment by Ledar** [comment]
You'd better provide your Steam ID,Player ID in game,Patreon email, we will check if there is something went wrong.

**Comment by Khado77** [comment]
Where should i provide it?

**Comment by Khado77** [comment]
> You'd better provide your Steam ID,Player ID in game,Patreon email, we will check if there is something went wrong.

Where should i provide it?

**Comment by Ledar** [comment]
> > You'd better provide your Steam ID,Player ID in game,Patreon email, we will check if there is something went wrong.
> 
> Where should i provide it?

Here it is, without any risk to you

**Comment by Khado77** [comment]
> .

My Steam ID: 76561198224063888

**Comment by Khado77** [comment]
> > > You'd better provide your Steam ID,Player ID in game,Patreon email, we will check if there is something went wrong.
> > 
> > Where should i provide it?
> 
> Here it is, without any risk to you, only Steam ID.

My Steam ID: 76561198224063888

**Comment by SpamFilter9k** [comment]
My STeam ID: 76561197963345276

**Comment by Ledar** [comment]
I'm sorry to say that some level data in phase 1 was not imported, we are fixing it.

**Comment by SpamFilter9k** [comment]
Same here, no Expedited Certifcates.
But i got all starting Blueprints and ingame money from linking to my patreon account.

**Comment by Awfulwaffle1** [comment]
Closing as everyone should have received their Expedited Certs depending on what level they got during Phase 1. Max 50
