### ISSUE TITLE
[UI] Research Pass Selection locks player out of any other menus

### ISSUE THREAD

**Issue by P1wan** [itsamewayu/OLFallenDoll#626]
When attempting to view the characters in the Harem Mode menu, I was sent to the Research Pass selection screen, and there was no way of exiting without selecting a Research Pass to unlock, which I didn't and simply Alt + F4 the game since there are still account issues, after that, attempting to enter Harem Mode succesfully simply resulted in entering the Research Pass selection and no way of exiting

1. Go to Harem Mode
2 Click on a Character(in my case I clicked on Dr Anya, leading me to her research pass)
3 Enter the selection to unlock one of the Research Passes
4 No option for exiting can be found

![-2147483648_-210954](https://user-images.githubusercontent.com/127049192/223006339-b885f9be-0f9f-4e09-8848-43e3ba8920ee.jpg)

 - OS: Windows 10
 - Game Version 0.7

 - Processor(CPU): i7 8700K
 - Graphics Card: GTX 970
 - Memory: 8BG

Additional context:

Due to glitches and input issues, I am unsure if my attempt to exit the Research Pass screen actually might have resulted in trying to activate it

Also, I believe the game sent me to Dr Anya's research pass since the last time I played I had her equipped with the Bathrobe, which is an outfit in the Research Pass, so perhaps the game led me to it as it assumed I was trying to equip an outfit that was not unlocked

**Comment by Awfulwaffle1** [comment]
The screen in question is merely to select which pass you want to activate, meaning which pass progress goes towards. There is a separate screen for unlocking advanced passes for characters, which currently only Celia and Elizabeth require unlocking. Closing.
