### ISSUE TITLE
Noclip outside of bounds.

### ISSUE THREAD

**Issue by Enigma1234567** [itsamewayu/OLFallenDoll#627]
I can get outside and live in your walls.

**To Reproduce**
1. Pick the Celia No.417 Standing Handjob on Chair.
2. Walk up against a wall.
3. Start the animation.
4. You are now outside the walls.

**Expected behavior**
Obviously to not get there.

**Screenshots**
![image](https://user-images.githubusercontent.com/127070335/223010984-874c19b2-9e3c-4b12-b05e-c6e034ce6425.png)
![image](https://user-images.githubusercontent.com/127070335/223011021-e9ce3b94-4126-4fa8-88df-81a446d33099.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Game Version 4.0 (7.0 but not really obviously)

**Additional context**
Pretty simple here, the animation just doesn't have any boundaries set to it for not being able to place it, in theory this could be put anywhere at all that you want.

**Comment by Awfulwaffle1** [comment]
This should be fixed. Closing, but please reopen or create another issue if this is still an issue on your end.
