### ISSUE TITLE
The outfit/cloth/skin rewards by linking the Patreon account were missing!

### ISSUE THREAD

**Issue by XJ114514** [itsamewayu/OLFallenDoll#628]
**Problems**
I successfully linked my Patreon account and collected the green money and clothes/skins via the in-game mailbox.
But all I actually received was green money and no outfits/clothes/skins! When I look over the character, every character clearly showed that I unlocked 0 outfits/clothes/skins even if I did collect the reward via the mailbox.

**To Reproduce**
After linking the Patreon account and collecting both rewards from the in-game mailbox
1. Go to 'character'
2. Click on 'clothes''
3. showed "0 clothes were unlocked''

**Expected behavior**
After collecting the rewards, the clothes/skins should be shown via character. But clearly, it is not.

**Screenshots**
The rewards are collected via the in-game mailbox.
![image](https://user-images.githubusercontent.com/127024445/223017351-ad3bab55-6c9e-4710-87a3-770e45e1b32a.png)

"Character" showed that I do not unlock any outfit.
![image](https://user-images.githubusercontent.com/127024445/223017387-99807ba6-61f1-4ef8-9c09-f6d72624a0c7.png)

**Desktop:**
 - OS: Win10
 - Game Version: 0.70
Computer Hardware Configurations:
 - Processor(CPU): intel i7-11800H
 - Graphics Card: NVIDIA RTX 3060
 - Memory: 16GB

It's located in C:\Users\ (USER ID) \AppData\Local\Paralogue

**Additional context**
An additional problem, when I tried to enter "Archimedes station" or "Erotes Nightclub", the server will either directly restart my game or stuck in the loading page and then kick me out of harem mode.

**Comment by Awfulwaffle1** [comment]
@XJ114514 Let us know if this is still an issue on your end.

**Comment by Awfulwaffle1** [comment]
Closing but feel free to reach out if this is still an issue. @XJ114514
