### ISSUE TITLE
[Bug] Started game with no experiments, no blueprints and blueprints screen bugged

### ISSUE THREAD

**Issue by ImmortalLotus** [itsamewayu/OLFallenDoll#629]
**Describe the bug**
Started the game with 
1 - no experiments:
![image](https://user-images.githubusercontent.com/72933183/223017783-0307a2ed-3d08-46d6-9b71-a7c9ea991306.png)
2 - no blueprints and blueprints screen missing a lot of  things:
![image](https://user-images.githubusercontent.com/72933183/223017844-19f87f6a-4cc6-4200-ab54-1c0efbaec8ba.png)
3 - prompt that happens when I try to buy something on the blueprint I can see:
![image](https://user-images.githubusercontent.com/72933183/223018003-e34d9220-bbab-4da1-afdd-2ed29990d312.png)

been told to verify files:
![image](https://user-images.githubusercontent.com/72933183/223018120-a409f8fd-2fdd-4b08-9254-5f42c7839d35.png)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Game Version 0.7
 Complete the following Computer Hardware Configurations if necessary:
 - Processor(CPU):  Ryzen 5 1600AF
 - Graphics Card: GTX 1650
 - Memory:16GB

**Aditional Context**
On the first time I opened the new version, I was prompted to write an username, and select one of those 3 options(antrho something something xeno), and as I did that, I got stuck on that screen for a while, retrying with many different nicks(thought that might be the issue), and also selecting different cards. The username that shows in these prints refer to the first try. The thing that came out on prompt while I was trying to create an user was : 
![image](https://user-images.githubusercontent.com/72933183/223018515-2e8113ce-fce3-4a3d-9758-e48ba8628e27.png)

**Comment by ImmortalLotus** [comment]
Followup: Now when log in the game it redirects to the create user screen every single time
![image](https://user-images.githubusercontent.com/72933183/223205611-5cbd920b-ecb3-43fc-bccd-6f3b2000038a.png)

**Comment by Awfulwaffle1** [comment]
Should be resolved as of Stress Test #2. Marking resolved and closing, but please follow up with a support ticket in discord if there's any further issues.
