### ISSUE TITLE
[Model][Camera] Anya's model disappear and wrong camera angle in sex with Dreamer in Lab 

### ISSUE THREAD

**Issue by VectorKamarov** [itsamewayu/OLFallenDoll#63]
**Describe the bug**
Both Anya and Dreamer disappear when choosing the Standing Doggy-style against counter in Sexual Compatiability: mid in Laboratory. When setting camera angle to First person, both model load with no problem. But after switching back to third person angle, no model is loaded and camera is at a wrong angle.

**To Reproduce**
1. Go to Classic mode
2. Click on Laboratory
3. Click on Anya
4. Click on Dreamer
5. Click on Sexual Compatiability: Mid
6. Click on Standing Doggy-style against counter
7. See the error.

**Expected behavior**
Camera floating at an angle with neither Anya nor Dreamer visible. After switching to first person both are present. Disappear again after switching back to third person.

**Screenshots**
![20211128031618_1](https://user-images.githubusercontent.com/95145535/143719457-a006846b-74fc-4a6e-a920-a1f05d573838.jpg)
![20211128031638_1](https://user-images.githubusercontent.com/95145535/143719461-b1070286-0142-4ac0-8804-b2935373ccb0.jpg)
![20211128031710_1](https://user-images.githubusercontent.com/95145535/143719466-0408910e-b80c-40e1-a75b-ff94bbeae1d8.jpg)
First screenshot is the default position of camera after switching to the sex position.
Second screenshot shows the POV camera angle where both Anya and Dreamer are visible and fine.
Third screenshot shows from the third person camera that Anya and Dreamer are not shown at the position show in the POV camera.

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser chrome

**Comment by jinjin525** [comment]
Similiar to #5 but you provided a more detailed issue, thanks.
Will merge this issue with issue No.5
