### ISSUE TITLE
Harem Mode inaccessible

### ISSUE THREAD

**Issue by 8dman** [itsamewayu/OLFallenDoll#630]
Description:
I tried entering harem mode and it only gives a tool tip with the following message

Steps:
1. Launch game
2. Click on Harem mode
3. Tip error message: {"code":0, "msg":"got empty player-id from backend server1","uid":0} {"code":0,"msg":"uid":108340000}

Expected:
Harem mode to launch

**Screenshots**
![image](https://user-images.githubusercontent.com/127074042/223019275-2ca5de93-2e7d-4c9a-9813-de3b7feea9e7.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Game Version ver 0.7.0

**Comment by Awfulwaffle1** [comment]
Resolved as of Stress Test #2 build. Closing.
