### ISSUE TITLE
点击后宫模式后，弹出tips后没任何反应，或者显示一段代码

### ISSUE THREAD

**Issue by Horo2** [itsamewayu/OLFallenDoll#631]
**Describe the bug**
主菜单页面，点击后宫模式后，无法进入后宫模式

**To Reproduce**
1.开始游戏进入主菜单
2. 点击后宫模式，弹出Tips
3. 随后没有仍和响应无法进入后宫模式

**Expected behavior**
如何才能进入后宫模式？

**Screenshots**
![image](https://user-images.githubusercontent.com/49852694/223035253-de23bc29-5c62-4542-83aa-2b641559c7fb.png)
![QQ截图20230305222211](https://user-images.githubusercontent.com/49852694/223035301-2e6465a3-c40f-4f26-838f-e2271d04bee2.png)

**Desktop (please complete the following information):**
Win 1

**Comment by Awfulwaffle1** [comment]
Resolved as of Stress Test #2 build. Marking resolved and closing.
