### ISSUE TITLE
[UI] Trying to claim patreon costumes. "Invalid character '<' looking for beginning of value"

### ISSUE THREAD

**Issue by kblah40** [itsamewayu/OLFallenDoll#632]
**Describe the bug**
User tries to claim the Costumes mail from mailbox. Tips box appears with message "Invalid character '<' looking for beginning of value" 

**To Reproduce**
1. Mailbox
2. Click claim or claim all with costumes mail in mailbox
3. Error
4. 
**Expected behavior**
Claim costumes from mail

**Screenshots**
https://i.imgur.com/1uTFP3w.png

**Desktop (please complete the following information):**
 - OS: Win 10
 - Game Version 0.70
 Complete the following Computer Hardware Configurations if necessary:
 - Processor(CPU): 3700X
 - Graphics Card: RTX 3080 10GB
 - Memory: 32GB

*If your game crashed, remember to upload the dmp file with your issue.

It's located in C:\Users\ (USER ID) \AppData\Local\Paralogue

**Additional context**

**Comment by Awfulwaffle1** [comment]
Should have been resolved as of Stress Test #2 build at the end of March. Marking Resolved and closing.
