### ISSUE TITLE
Linked Patreon in game but it didn't open harem mode with it at second time.

### ISSUE THREAD

**Issue by VonSacred** [itsamewayu/OLFallenDoll#634]
**Describe the bug**

Went into harem mode, added name as "VonSacred", got in and linked it with patreon to get the bonus things. 
The game was bit laggy and didn't respond much when I clicked *claim* mail. Did a restart to the game, gave few errors with no text. In the end it let me in but it didn't log me in as VonSacred as I created and linked before put instead it wanted me to create a new. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Win10/Ubuntu 20.04]
 - Game Version [e.g. 0.42]
 Complete the following Computer Hardware Configurations if necessary:
 - Processor(CPU): [e.g. i7-9700K]
 - Graphics Card:[e.g. RTX 2070s]
 - Memory:[e.g. 16GB]

*If your game crashed, remember to upload the dmp file with your issue.

It's located in C:\Users\ (USER ID) \AppData\Local\Paralogue

**Additional context**

**Comment by Awfulwaffle1** [comment]
Duplicated of #635
