### ISSUE TITLE
Lost Progress

### ISSUE THREAD

**Issue by Mel412** [itsamewayu/OLFallenDoll#644]
**Describe the bug**
Every time i start up harem mode it sends me through the first time startup after a long delay. When trying to link to patreon afterwards i get an error code, potentially cause im already linked from before? but i also have no mail.

**To Reproduce**
1. start on Main Menu
2. click Harem
3. Enter name and pick preference
4. See error in chinese
5. finally get past error
6. press link patreon
7. Error popup Cannot link patreon

**Expected behavior**
My patreon would be linked, id be back to where i was before the last update, and id have items in my mail as promised.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win11
 - Game Version .70
 Complete the following Computer Hardware Configurations if necessary:
 - Processor(CPU): [e.g. i7-9700K]
 - Graphics Card:[e.g. RTX 2070s]
 - Memory:[e.g. 16GB]

*If your game crashed, remember to upload the dmp file with your issue.

It's located in C:\Users\ (USER ID) \AppData\Local\Paralogue

**Additional context**

**Comment by pshnawnawman** [comment]
Same issue here, although I haven't linked my patreon account yet since the discord advised against it until the issues are ironed out. All my progress from before this update seems to be missing, and I'm prompted to create a new account every time I try to enter Harem mode.

**Comment by Awfulwaffle1** [comment]
Related to #635
