### ISSUE TITLE
Missing Neo England Pound after purchasing Celia

### ISSUE THREAD

**Issue by witheredghost** [itsamewayu/OLFallenDoll#647]
After a rocky start trying to link account, today seemed to be all fine. After claiming in game mail I decided to try and unlock Celia for £150 Neo England Pounds. When I clicked on the button nothing happened, so I clicked again and again for a total of three times to be exact. Because it wasn't working I decided to close the game and reload to see if I still have the issue. Well after doing so I went from £848 to £398 because it counted all three times I clicked for a total of £450. She is now unlocked, but I'm missing £300.

edit: After the game reset my account status and it took me through the initial steps again, I had the opportunity to select a character of my choice and was able to select 50ish (don't recall the exact amount) Insights from the different categories. I now remember this was an option when I originally logged in, before I was able to link my Patreon account. I since have restarted the game and it's back to where I started this bug report. So basically I wasted my £ because she was the character selected, I'm missing extra £ due to a game bug, and I'm missing the 50ish Insights that I also originally selected.

![image](https://user-images.githubusercontent.com/127159864/223286268-de47d43e-9f86-4eef-b819-5811954c2cf0.png)
![image](https://user-images.githubusercontent.com/127159864/223286831-5b5c7cf8-856c-44e7-ac1b-ea4393ed66cf.png)
Second image shows I haven't spent any £ on Insight
 - Game Version 0.7.0

**Comment by Awfulwaffle1** [comment]
Should be resolved now as there was a few account wipes after the fact during the Stress Test. Closing, but feel free to create a ticket if this is still an issue.
