### ISSUE TITLE
Card information not found

### ISSUE THREAD

**Issue by TAKASIHABA26** [itsamewayu/OLFallenDoll#648]
**Describe the bug**

**To Reproduce**
1. Go to 後宮模式
2. Click on nothing
3. Scroll down to do nothing
4. See error Card information not found 未查詢到卡牌訊息

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/127162114/223291654-ebedc9f1-4543-42ba-ab46-9a5477b2a356.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Game Version 0.7.0
 Complete the following Computer Hardware Configurations if necessary:
 - Processor(CPU): i7-12700K
 - Graphics Card:[e.g.  RTX 3050
 - Memory:32GB

*If your game crashed, remember to upload the dmp file with your issue.

It's located in C:\Users\ (USER ID) \AppData\Local\Paralogue

**Additional context**

**Comment by Awfulwaffle1** [comment]
Should be resolved after the stress test was completed. Closing.
