### ISSUE TITLE
got empty player -id

### ISSUE THREAD

**Issue by Gmanhub** [itsamewayu/OLFallenDoll#649]
**Describe the bug**

**To Reproduce**
1. Go to '主页'
2. Click on '后宫模式'
3. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win11
 - Game Version [ 0.7.0]
![image](https://user-images.githubusercontent.com/90388896/223344980-fe0cb635-a07a-4d16-add1-988d6f36ad16.png)
 I loging to the game before but it happened again.

**Comment by Awfulwaffle1** [comment]
Stress Test issues that should now be Resolved at this point. Closing
