### ISSUE TITLE
[Texture][Graphics] Advanced/More Graphics Settings & Clothing Texture Resolution being Static

### ISSUE THREAD

**Issue by TheSoulWizard** [itsamewayu/OLFallenDoll#65]
As of 0.40 and older versions, the game lacks Settings for Graphics. These 3 options (Low, Medium, High) don't make much difference on characters, if not any (Except Hair). 
It has absoloutely no impact on the Clothing Textures or Character Detail/Polygons.
![Graphics Comparison](https://user-images.githubusercontent.com/40411642/143724060-395c7361-8733-4450-8ceb-43371b1811ea.jpg)
I think there should be an Advanced option for the User to adjust the graphics, by type:

- Character Resolution [Low, Medium, High, Ultra]
- Clothing Texture Resolution [Low, Medium, High, Ultra]
- Shadows [Disabled, Low, Medium, High]
- Reflections [Disabled, Low, Medium, High]
etc.

This can also lower the Mimimum Specs of the game and cover a wider portion of players with mid-end computers.

**Comment by Squirrelydood** [comment]
I've noticed a different issue, it seems like there's little difference between Low and medium other than shadow but a major change when selecting High quality which causes a massive dip in performance. Low and medium both have the same quality textures with the only difference being some lighting and shadow changes, while High quality changes the hair, lighting, outfit texture quality (fairly massively), and particle effects or animations in background objects.
![20211202014529_1](https://user-images.githubusercontent.com/33014098/144381455-e37a7168-659e-4c46-8544-491da33d0a63.jpg)
![20211202014544_1](https://user-images.githubusercontent.com/33014098/144381468-628a0587-fb98-43ba-b232-39ab7002c36f.jpg)
![20211202014600_1](https://user-images.githubusercontent.com/33014098/144381481-ef6f3951-52f4-490c-ace4-5375da178dca.jpg)

**Comment by TheSoulWizard** [comment]
> I've noticed a different issue, it seems like there's little difference between Low and medium other than shadow but a major change when selecting High quality which causes a massive dip in performance. Low and medium both have the same quality textures with the only difference being some lighting and shadow changes, while High quality changes the hair, lighting, outfit texture quality (fairly massively), and particle effects or animations in background objects. ![20211202014529_1](https://user-images.githubusercontent.com/33014098/144381455-e37a7168-659e-4c46-8544-491da33d0a63.jpg) ![20211202014544_1](https://user-images.githubusercontent.com/33014098/144381468-628a0587-fb98-43ba-b232-39ab7002c36f.jpg) ![20211202014600_1](https://user-images.githubusercontent.com/33014098/144381481-ef6f3951-52f4-490c-ace4-5375da178dca.jpg)

Well.... this thread is for adding more settings.... a suggestion, not a bug thread.

I've seen that issue in the discord chat. I personally don't know a fix to that..
