### ISSUE TITLE
Harem bug

### ISSUE THREAD

**Issue by dmpoole42** [itsamewayu/OLFallenDoll#650]
When clicking on Harem, the mode doesn't launch and simply greys out the button and makes it unselectable. Relaunching, uninstalling, and verifying the integrity of the game files has no effect. 

![Harem](https://user-images.githubusercontent.com/127195026/223382055-b69dde86-6d9f-4f36-8aca-ba3e1bcf12fe.JPG)

**Comment by Chriskarl29** [comment]
Same for me
![Screenshot (1)](https://user-images.githubusercontent.com/127222762/223459431-fd5ae7a3-1d61-4b3b-ac73-3cb2e8865062.png)

**Comment by RucolaBoi** [comment]
![image](https://user-images.githubusercontent.com/127653611/224532059-99c265da-c410-4631-8b0c-89511ecb3b8d.png)
Pretty much the same thing for me

**Comment by Awfulwaffle1** [comment]
Stress Test issues which should now be resolved. Closing.
