### ISSUE TITLE
[UI or server] The setting will lower itself

### ISSUE THREAD

**Issue by DarkRaven2023** [itsamewayu/OLFallenDoll#653]
**Describe the bug**
 The setting will lower itself

**To Reproduce**
1. Go to 'setting'    Various special effects settings are set
2. Click on 'Harem mode'  Enter harem mode (The same sometimes happens in galleries)
3. Scroll down to 'Enter the game'  Finding that the game graphics are not performing well, open the settings and find that all the values have been lowered

**Expected behavior**
 DLSS、ssao 、HDR 、Bloom and many other specifics will be turned down. I don't know why it was turned off or turned down

**Screenshots**
![20230307065310_1](https://user-images.githubusercontent.com/127008409/223544261-7fdc4975-bccb-46f3-8be7-6ce37aaff890.jpg)
![20230307065314_1](https://user-images.githubusercontent.com/127008409/223544329-3fb4e987-7c3f-4709-8b97-1ceb490bfa1a.jpg)
![20230307065406_1](https://user-images.githubusercontent.com/127008409/223544381-a95d9a2d-10e3-409e-8848-12890fa190f8.jpg)
![20230307220602_1](https://user-images.githubusercontent.com/127008409/223544897-b41c187c-9e03-46ae-87c3-cfe9cd6b4124.jpg)

**Desktop (please complete the following information):**
 OS: Win11
Game Version [e.g. 0.7.0]
Complete the following Computer Hardware Configurations if necessary:
Processor(CPU): [e.g. i5-12600K]
Graphics Card:[e.g. RTX 3050]
Memory:[e.g. 32GB]

**Additional context**

**Comment by Awfulwaffle1** [comment]
Resolved recently. This was due to VRAM limits, but now it should be resolved. @DarkRaven2023 please close out this issue if all is good on your end.
