### ISSUE TITLE
[model OR animation] Alet pole dancing but grabbing the air

### ISSUE THREAD

**Issue by DarkRaven2023** [itsamewayu/OLFallenDoll#655]
**Describe the bug**
Alet pole dancing but grabbing the air

**Screenshots**
![20230307064803_1](https://user-images.githubusercontent.com/127008409/223548143-e8001850-8d0a-4e93-8cd7-df4465e7b1a5.jpg)
![20230307064805_1](https://user-images.githubusercontent.com/127008409/223548194-16bb8dc3-3ac7-494f-bcd1-b03cd0684c6b.jpg)
![20230307064826_1](https://user-images.githubusercontent.com/127008409/223548229-2f6ad731-729f-4782-9148-446376346407.jpg)
![20230307064903_1](https://user-images.githubusercontent.com/127008409/223548336-f7d35d2e-4e77-42c6-b492-8f6daa105f10.jpg)

**Desktop (please complete the following information):**
OS: Win11
Game Version [e.g. 0.7.0]
Complete the following Computer Hardware Configurations if necessary:
Processor(CPU): [e.g. i5-12600K]
Graphics Card:[e.g. RTX 3050]
Memory:[e.g. 32GB]

**Comment by Awfulwaffle1** [comment]
Verified in 0.7.41
