### ISSUE TITLE
[model OR animation] Alet has a problem with the position of the left hand when masturbating

### ISSUE THREAD

**Issue by DarkRaven2023** [itsamewayu/OLFallenDoll#656]
**Describe the bug**
Alet has a problem with the position of the left hand when masturbating

**Screenshots**

![20230307064328_1](https://user-images.githubusercontent.com/127008409/223549238-55a9853b-2d81-41a6-a1b3-f5716a2ba9b9.jpg)
![20230307064333_1](https://user-images.githubusercontent.com/127008409/223549277-567f6b25-32f9-4379-9049-3a362601efbe.jpg)

**Desktop (please complete the following information):**
OS: Win11
Game Version [e.g. 0.7.0]
Complete the following Computer Hardware Configurations if necessary:
Processor(CPU): [e.g. i5-12600K]
Graphics Card:[e.g. RTX 3050]
Memory:[e.g. 32GB]

**Comment by Awfulwaffle1** [comment]
Left hand positioning looks proper as of 0.7.7d. Closing.
