### ISSUE TITLE
[UI] Disappearing interface

### ISSUE THREAD

**Issue by DarkRaven2023** [itsamewayu/OLFallenDoll#657]
**Describe the bug**
Whenever you enter pole dancing or masturbate and then exit, the custom interface disappears
(每當進入鋼管舞或是自慰，之後退出時，自定義的介面就會消失)
Unless you enter the locker room and return to the game, the custom interface will appear again
(除非進入更衣室再返回遊戲，自定義的介面才又會出現)

**Screenshots**
![20230307064914_1](https://user-images.githubusercontent.com/127008409/223551455-e40737e6-c564-46d9-a123-a06d61ad6e69.jpg)
![20230307064936_1](https://user-images.githubusercontent.com/127008409/223551474-7d0e1239-eace-4e4b-be8a-aac310b36895.jpg)

**Desktop (please complete the following information):**
OS: Win11
Game Version [e.g. 0.7.0]
Complete the following Computer Hardware Configurations if necessary:
Processor(CPU): [e.g. i5-12600K]
Graphics Card:[e.g. RTX 3050]
Memory:[e.g. 32GB]

**Comment by Awfulwaffle1** [comment]
Verified fix as of 0.7.41
