### ISSUE TITLE
Reworked Body Fluid Visuals not Present

### ISSUE THREAD

**Issue by dlrnrgus66** [itsamewayu/OLFallenDoll#658]
**Describe the bug**
The reworked body fluid visuals are no where to be seen in harem mode. Also, there are no floor stains caused by the fluids.
In gallery mode, the reworked Body Fluid visuals seem to work. However, once it's activated, the fluids continue to come out of the character without ever stopping.

**To Reproduce**
1. Go to '....'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Win10/Ubuntu 20.04]
 - Game Version [e.g. 0.42]
 Complete the following Computer Hardware Configurations if necessary:
 - Processor(CPU): [e.g. i7-9700K]
 - Graphics Card:[e.g. RTX 2070s]
 - Memory:[e.g. 16GB]

*If your game crashed, remember to upload the dmp file with your issue.

It's located in C:\Users\ (USER ID) \AppData\Local\Paralogue

**Additional context**

**Comment by Awfulwaffle1** [comment]
New body fluid is present in 0.7.4. Albeit not perfect, but it's implemented. Other issues can be made on a separate ticket. Closing.
