### ISSUE TITLE
[UI] about sitting resolution description

### ISSUE THREAD

**Issue by h24672002** [itsamewayu/OLFallenDoll#66]
Sitting something wrong

Set language to Traditional Chinese
Then change resolution to any 
--------------------------------------------
BTW confirm are still CHS

it should be show timer not [v]

![image](https://user-images.githubusercontent.com/59988226/143726170-af6e5fff-070f-46c9-95ae-ac13115a1922.png)

Windows 10
FD:OL v0.4.0

**Comment by TheSoulWizard** [comment]
Seems like it's fixed.
![image](https://user-images.githubusercontent.com/40411642/147864308-da3ea90e-aa6e-49ab-83d1-b58a8a2aa105.png)
