### ISSUE TITLE
Game not working as I expected

### ISSUE THREAD

**Issue by Xmarser** [itsamewayu/OLFallenDoll#660]
**Describe the bug**
Cannot connect to the server for harem mode, it keeps showing a window 'Server under maintenance', gallery mode working as expected(at least it opens when I click it)
**To Reproduce**
1. Go to title page
2. Click on 'HAREM'

**Expected behavior**
Open the Harem mode
**Screenshots**
If applicable, add screenshots to help explain your problem
(https://user-images.githubusercontent.com/127348719/223844406-e8dfb97a-1a7d-49d4-a495-bcc1bb9eebfe.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Game Version 0.70
 Complete the following Computer Hardware Configurations if necessary:
 - Processor(CPU): Razen 7 4800H
 - Graphics Card:RTX 2060
 - Memory:16GB

*If your game crashed, remember to upload the dmp file with your issue.

It's located in C:\Users\ (USER ID) \AppData\Local\Paralogue

**Additional context**
I tried this at 20:00 GMT +0.

**Comment by Awfulwaffle1** [comment]
Server issues were resolved awhile back during Stress Test 1 and 2. Closing.
