### ISSUE TITLE
Capitalist Qualification

### ISSUE THREAD

**Issue by bom062550** [itsamewayu/OLFallenDoll#667]
This is machine translation, my English is not good.

I am a player with capitalist qualifications (January 23, 2023), but when I unlock the advanced season pass, I need to spend another 150 green tickets

I hope to get my rights back, as well as the 150 green ticket, thank you very much.

**Comment by Awfulwaffle1** [comment]
@bom062550 this is working as expected. The 150 NEP given to you for each character release is to use to unlock the advanced research pass for each upcoming character. You should have gotten 150 for Celia and another 150 for Elizabeth. Please let us know if there's any further assistance regarding this issue. Closing for now.
