### ISSUE TITLE
Parts of chara disappear in the Night Club

### ISSUE THREAD

**Issue by Miku0416** [itsamewayu/OLFallenDoll#668]
**Describe the bug**
Some parts of the chara just start to be transparence 
**To Reproduce**
1. In the night club, I`ve got close to the holes and then started to run into the double doors at the end of the corridor
2. Then I step aside from the door and my chara lost some parts of her body
3. Its been fixed by interacting with sofa near the piano in middle hall

**Screenshots**
![image (1)](https://user-images.githubusercontent.com/129556251/229234485-d517582d-7696-43ed-9a80-c700e6caeee4.png)
![image](https://user-images.githubusercontent.com/129556251/229234501-ed752662-b3e3-4445-82ec-1300e6342f77.png)
![image (5)](https://user-images.githubusercontent.com/129556251/229234514-7980c53c-4e23-4112-ad34-22aaa03719fe.png)

**Desktop 
 - OS: [Win 11]

 - Game Version [0.7.1]
 - Processor(CPU): [Intel I7-12700KF]
 - Graphics Card:[RTX 4070]
 - Memory:[64GB]

**Comment by Awfulwaffle1** [comment]
Verified fix as of the 0.7.2b build. Closing.
