### ISSUE TITLE
neo england pound from previous pledge disappear 

### ISSUE THREAD

**Issue by LosOrange** [itsamewayu/OLFallenDoll#671]
**Describe the bug**
After I've linked my account and claimed the rewards (the neo england pound specifically) from the mail based on my previous pledge, it just disappeared. but the 200 nep from the maintenance is still here.
**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/129566573/229259612-11192837-eca0-47b9-9e5f-0da85d291c8f.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Win10/Ubuntu 20.04]
 - Game Version [e.g. 0.42]
 Complete the following Computer Hardware Configurations if necessary:
 - Processor(CPU): [e.g. i7-9700K]
 - Graphics Card:[e.g. RTX 2070s]
 - Memory:[e.g. 16GB]

*If your game crashed, remember to upload the dmp file with your issue.

It's located in C:\Users\ (USER ID) \AppData\Local\Paralogue

**Additional context**

**Comment by Awfulwaffle1** [comment]
@LosOrange Heya. I know this is an old issue. I'm just wondering if this has since been resolved since the last wipe in April?

**Comment by Awfulwaffle1** [comment]
Confirmed Resolved through discord.
