### ISSUE TITLE
Expedited certificate spent without progress gained

### ISSUE THREAD

**Issue by Floafer** [itsamewayu/OLFallenDoll#695]
**Describe the bug**
Expedited certificate spent without progress gained to the pass

**To Reproduce**
1. Go to 'store'
2. Click on 'Expedited certificate' spending 30 likes
3. Go to anyones pass (I used Anya, starting at level 0 with no progress on her)
4. Shows cost of boost as 50 NEP 1 Cert icon
5. Click to boost
6. "Insufficient NEP"
7. No progress gained, certificate spent

**Expected behavior**
5 lvl boost

**Desktop (please complete the following information):**
 - OS: win11
 - Game Version [.72]
 Complete the following Computer Hardware Configurations if necessary:
 - Processor(CPU): [i7-13700K]
 - Graphics Card:[6800XT]
 - Memory:[e.g. 64GB]

*If your game crashed, remember to upload the dmp file with your issue.

It's located in C:\Users\ (USER ID) \AppData\Local\Paralogue

**Additional context**
I like anya booba

**Comment by Awfulwaffle1** [comment]
Cannot reproduce and should be working as intended now.
