### ISSUE TITLE
[UI] Missing Translation

### ISSUE THREAD

**Issue by itsamewayu** [itsamewayu/OLFallenDoll#7]
winwingwind — Yesterday at 7:14 PM
missed translation
![unknown](https://user-images.githubusercontent.com/11155504/143678650-af4501d8-669e-44de-85e6-632f327cca65.png)
_MIYA NOTE: Highest sexual affinity, Anya Handjob 2 it looks_

**FROM TMOANE**
![unknown](https://user-images.githubusercontent.com/11155504/143679014-7e44fbe4-88d9-4f2d-b38b-b8546e5560fb.png)
![unknown](https://user-images.githubusercontent.com/11155504/143679017-9a835a2b-6be9-444a-92ef-fa9531982ab2.png)
![unknown](https://user-images.githubusercontent.com/11155504/143679019-42918b8d-8ac4-4df9-bc05-a11bd53f020e.png)
![unknown](https://user-images.githubusercontent.com/11155504/143679022-c0c0f85f-91eb-418b-9f6a-32fbef59c768.png)
![unknown](https://user-images.githubusercontent.com/11155504/143679024-160a2add-1528-44f1-96db-6a1d77b7583a.png)
![unknown](https://user-images.githubusercontent.com/11155504/143679028-5832d285-8e46-4e4c-abdd-754787c63a98.png)
![unknown](https://user-images.githubusercontent.com/11155504/143679031-948564d1-1ea0-4d82-a47f-152f2be8794c.png)

**Comment by Awfulwaffle1** [comment]
Some of the poses have been removed, and others that still remain an issue are just blank now.
