### ISSUE TITLE
[Model] Anya's Expedition Pilot Suit Issues

### ISSUE THREAD

**Issue by HeyItsNyX** [itsamewayu/OLFallenDoll#70]
Anya's neck can be seen thru to whatever is behind when she is Half-Dressed when on Expedition Pilot Suit. (I have tested other outfits for Anya, Only Half Dressed Expedition Pilot suit will reproduce this simlar result)

![1](https://user-images.githubusercontent.com/95136714/143736061-815bff33-3c10-4f78-a9ab-549671b6cd9f.png)

![2](https://user-images.githubusercontent.com/95136714/143735943-bfa5f959-6599-4f9e-91f4-f0fe716db8d0.png)
![3](https://user-images.githubusercontent.com/95136714/143735947-2f8cdf40-7762-4bd5-99e4-ec184f9180be.png)

**Comment by HeyItsNyX** [comment]
https://user-images.githubusercontent.com/95136714/143745432-a272ce9f-8170-4b66-b0ae-d883ac11836c.mp4

More Testing Results into mesh breaking, Half Dressed clothing texture are wrong

**Comment by jinjin525** [comment]
From alfi301 in issue #134 :
I managed to reproduce and get a screenshot
![Screenshot (155)](https://user-images.githubusercontent.com/95278116/144080949-b0525243-5e28-4a73-8c3a-9bc78778ca19.png)
