### ISSUE TITLE
关于赞助转化的绿票没有使用但是消失了。

### ISSUE THREAD

**Issue by Cheese1001** [itsamewayu/OLFallenDoll#701]
**Describe the bug**
我第一次上线在邮箱里领取了我赞助的绿票，但是在我第二次登录的时候绿票就消失了，只保有之前的200绿票，赞助转换的绿票全部消失了但是我没有使用。
**To Reproduce**

**Expected behavior**
希望我消失的赞助的绿票能回来。
**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Win10/Ubuntu 20.04]
 - Game Version [e.g. 0.42]
 Complete the following Computer Hardware Configurations if necessary:
 - Processor(CPU): [e.g. i7-9700K]
 - Graphics Card:[e.g. RTX 2070s]
 - Memory:[e.g. 16GB]
OS:Win10
Game Version 0.70
Processor(CPU):i5-12600K
Graphics Card:RX 6750 XT
Memory:16GB
*If your game crashed, remember to upload the dmp file with your issue.

It's located in C:\Users\ (USER ID) \AppData\Local\Paralogue

**Additional context**

**Comment by Awfulwaffle1** [comment]
Due to reset of accounts when stress testing. Closing.
