### ISSUE TITLE
Lose all of the unlocked experiments after login.

### ISSUE THREAD

**Issue by Aetherwise** [itsamewayu/OLFallenDoll#704]
**Describe the bug**
Lose all of the unlocked experiments after login.

**Expected behavior**
Lose all of the unlocked experiments after login.

**Screenshots**
![image](https://user-images.githubusercontent.com/34504251/229884558-93863567-faa8-4e4a-9531-0c0415b54eeb.png)

**Desktop (please complete the following information):**
 - OS: Win11
 - Game Version 0.7.0
 Complete the following Computer Hardware Configurations if necessary:
 - Processor(CPU): AMD R3500
 - Graphics Card: RTX 2070
 - Memory: 32 GB.

**Comment by DEXTRO123** [comment]
i also have the same issue. is your pass still showing the proper progress?

**Comment by Aetherwise** [comment]
> i also have the same issue. is your pass still showing the proper progress?

Yes.

**Comment by Ygolnac** [comment]
I have lost all experiments, and all costumes unlocks. Character progression level is still there, wich is worring since if the account does not get fixed I can't reunlock the costumes.

**Comment by DEXTRO123** [comment]
> I have lost all experiments, and all costumes unlocks. Character progression level is still there, wich is worring since if the account does not get fixed I can't reunlock the costumes.


same here

**Comment by Aetherwise** [comment]
![image](https://user-images.githubusercontent.com/34504251/230075168-2bc7fa3c-9a89-430c-800e-692a216598ed.png)
Now they reset my ID, At least they should announce what we should do in the case like this.

**Comment by Awfulwaffle1** [comment]
Due to account wipes after stress testing. Closing.

**Comment by dyingus** [comment]
me too, my card is reset
