### ISSUE TITLE
Notifications won't clear.

### ISSUE THREAD

**Issue by Gune14** [itsamewayu/OLFallenDoll#705]
**Describe the bug**
"Character" and "Blueprints" button notifications will not clear.

**Expected behavior**
After going through all new content in given section, they should disappear.

**Screenshots**
![Bug_001](https://user-images.githubusercontent.com/129925017/229983281-b0eda65c-7819-4126-ba7d-ab5c9c5e63f9.png)

**Desktop:**
 - OS: Win11
 - Game Version 0.71b
 - Processor(CPU): AMD Ryzen 9 7950X
 - Graphics Card RTX 4090
 - Memory: 60GB

**Comment by Awfulwaffle1** [comment]
Verified Fixed as of 0.7.41. Closing.
