### ISSUE TITLE
[Sound] issues at ultra-high sample rate settings on the output device in Windows.

### ISSUE THREAD

**Issue by IlySmall** [itsamewayu/OLFallenDoll#71]
**Describe the bug**
No sound at **over** 192kHz sample rate set on the output device (tested at 16-384, 24-384, 32-384)

**To Reproduce**
Have a high enough quality DAC to be able to pick 192+ KHz as the audio quality (the number of bits seems to not matter, 16-192, 24-192 and 32-192 all work flawlessly)
Do exactly that
Launch game
Listen to the lack of sound

**Expected behavior**
Soundn't

**Comment by 1843890303** [comment]
Can reproduce on my AE-7 Sound card, no sound at 16/24/32bit @384khz
