### ISSUE TITLE
The bondage action doest appear in the holes

### ISSUE THREAD

**Issue by Kechen1986** [itsamewayu/OLFallenDoll#711]
**Describe the bug**
When we approach the wall with the hole for bondage, doesnt appear the action to start it

**Screenshots**
![image](https://user-images.githubusercontent.com/12736976/230432734-00d79cf1-a6d5-4c42-97ca-9b5808c6ae5f.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Game Version: 0.7.1b
 - Processor(CPU): Ryzen 7300x
 - Graphics Card: GTX 1080TI
 - Memory: 16GB

**Comment by thorping** [comment]
I'm having the same issue. Not able to initiate the character to enter bondage (hole). I have more than 3 ideas when attempting.
![Screenshot 2023-04-09 032011](https://user-images.githubusercontent.com/130284348/230767296-533026ad-c704-461b-9bc5-3650c9177aac.png)

**Comment by johnathandarkly** [comment]
Same for the boxes on the station. Icon appears, but no action available. 

 - OS: Win 11 Pro
 - Game Version: 0.7.1
 - Processor: i5 12600K 
 - Graphics Card: RTX 2080 ti
 - Memory: 32gb

**Comment by johnathandarkly** [comment]
this is working for me today.

**Comment by johnathandarkly** [comment]
the working theory seems to be it fails on servers one by one over the course of a day, and rebooting might help? so bondage might be broken on one server, and working on another.
