### ISSUE TITLE
Doesnt received Double EXP when like Dancers when the Double EXP is activated

### ISSUE THREAD

**Issue by Kechen1986** [itsamewayu/OLFallenDoll#712]
**Describe the bug**
Im receiving single EXP when i like dancer, even if the Double EXP for Dancer is ON.
The problem still appear when I Observe a Dancer show and Like it there

**Expected behavior**
I expecte received 2 EXP every 1 like gived to a Dancer

**Screenshots**
(From any place)
![image](https://user-images.githubusercontent.com/12736976/230429740-cbd4a4b8-b265-478b-8e0a-a357008655d8.png)

![image](https://user-images.githubusercontent.com/12736976/230429849-b6a89ed0-76e4-4387-bb7c-056221c848fd.png)

![image](https://user-images.githubusercontent.com/12736976/230429883-cacb361c-4e89-45d8-b6f2-5fefad3825af.png)

(From the Observe position near the dancer)
![image](https://user-images.githubusercontent.com/12736976/230431946-0882c437-f918-4604-bb68-d193fe53b133.png)

![image](https://user-images.githubusercontent.com/12736976/230432048-930bb1da-ea04-4745-8b19-c8e5d6fc3d86.png)

![image](https://user-images.githubusercontent.com/12736976/230432105-6e29e84d-4d68-49ea-9310-3de5897fbaa6.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Game Version: 0.7.1b
 - Processor(CPU): Ryzen 7300x
 - Graphics Card: GTX 1080TI
 - Memory: 16GB

**Comment by Awfulwaffle1** [comment]
The double exp has been replaced with titilation as of 0.7.2b. Going to close this out. As this feature is now not part of the scope.
