### ISSUE TITLE
Custom hair doesn't save

### ISSUE THREAD

**Issue by Amb104** [itsamewayu/OLFallenDoll#721]
**Describe the bug**
When customizing the characters (skin, hair color etc.) it does not save. It resets as soon as I go back to title screen or shut off the game. The game only saves for Alet, not the other characters.

**To Reproduce**
No specific steps. Customize hair color (all characters except Alet), click apply, go to title screen, and it's reset.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win10
 - Game Version: 0.7.1 (steam)

**Comment by Awfulwaffle1** [comment]
#768 tracking issue here. Marking this as a duplicate and closing.
