### ISSUE TITLE
[0.7.1b] Like UI not correctly displaying likes given

### ISSUE THREAD

**Issue by Awfulwaffle1** [itsamewayu/OLFallenDoll#722]
**Describe the bug**
The Like given UI on the player list is not correctly displaying. All the player list should update the middle icon whenever the player gives a like to another player. Yet, (nearly) all the players have 0 for their listing.

**To Reproduce**
1. Go to Harme
2. Enter a Map
3. Click on a player name on the list to display the like.
4. Click Like
5. Observe.

**Expected behavior**
The like given icon should update by increments as they are given. ( Increment by 2 when applicable)

**Screenshots**

**Comment by johnathandarkly** [comment]
I have this too. Like counts are missing when displaying others in the server, and the popup notifications usually have the user name blank when giving or receiving likes. 

 - OS: Win 11 Pro
 - Game Version: 0.7.1
 - Processor: i5 12600K 
 - Graphics Card: RTX 2080 ti
 - Memory: 32gb

**Comment by Awfulwaffle1** [comment]
This seems to be working ok. Though enhancements may need to be done. Not sure if keeping track of a life-time is better than just a session time frame. Closing for now.
