### ISSUE TITLE
[System]Celia pose not generating male ecstacy (handstand doggy).

### ISSUE THREAD

**Issue by BlueTurtle766** [itsamewayu/OLFallenDoll#725]
**Describe the bug**

When using the Celia pose 'handstand doggy' the male ecstasy gauge doesn't increase.  This means that you have to keep cancelling the experiment

**To Reproduce**
Use the handstand doggy pose (Celia x Dreamer) on any map at any location.  The bug is consistent.

**Expected behavior**
Expected the gauge to build for the Dreamer, so that a climax action can be picked.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Win11]
 - Game Version [e.g. 7.1]
 Complete the following Computer Hardware Configurations if necessary:
 - Processor(CPU): [Ryzen 500 series
 - Graphics Card:[el RTX 3060s]
 - Memory:[e.g. 16GB]

*If your game crashed, remember to upload the dmp file with your issue.

It's located in C:\Users\ (USER ID) \AppData\Local\Paralogue

**Additional context**

**Comment by BlueTurtle766** [comment]
I would off added a tag, but don't know how to do it from my phone.

**Comment by Awfulwaffle1** [comment]
Verified fixed. Closing.
