### ISSUE TITLE
Crash when open game with VR mode

### ISSUE THREAD

**Issue by Hamakaze1s** [itsamewayu/OLFallenDoll#726]
My device is quest 2 and it works well with the previous version Paralogue0.34
But the newest game version crash when it starting (Before I can see the main menu). Also the fist screen of the game which include Content Warning was also misplaced (Seems the left screen displayed too right and the right screen displayed too left).

Here is the log.

LowLevelFatalError [File:Unknown] [Line: 902] 
Rendering thread exception:
Fatal error!

Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x0000000000000038

0x000000014270a593 Paralogue-Win64-Shipping.exe!UnknownFunction []

**Comment by Awfulwaffle1** [comment]
VR mode is not currently support for this build. It'll be implemented later on. @Hamakaze1s 
Current workaround is to go into the game properties on steam and add -nohmd to the starting option.
