### ISSUE TITLE
[Model] Anya's boobs are unstable, inverted 

### ISSUE THREAD

**Issue by kgt1964** [itsamewayu/OLFallenDoll#73]
**Describe the bug**
Anya's boobs are unstable when jiggle intensity is higher, ends up inverted in cowgirl pose

**To Reproduce**
cow  girl can be navigated anya - dreamer - compatibility none - Chinese char 6

**Screenshots**

![image](https://user-images.githubusercontent.com/81323759/143777902-1c5e4214-88f3-4d48-8e40-df2840fe5303.png)

**Comment by jinjin525** [comment]
From Gilverx in issue #212 
Breast physics seem off and too high for both Anya and Alet compared to previous builds of the game.

**Comment by johnathandarkly** [comment]
i've only started seeing this since 0.4.9, but the danger is real!

**Comment by Awfulwaffle1** [comment]
Jiggle physics for gallery is no longer functioning, so this particular bug is moot. Closing.
