### ISSUE TITLE
[UI][cursor] cannot move cursor to the right side when choose Options inside game mode

### ISSUE THREAD

**Issue by huyhoang880** [itsamewayu/OLFallenDoll#74]
When choose Option in game mode, after OK or Cancel, after that can only move about 80% of the screen. restart game cannot fix. also randomly got has black screen with sound and nothing showing

Need to use ALT Enter to switch between Windows and Fullscreen mode to fix. But if choose Option in game mode then get it again

Playing using Steam, with resolution 1920x1080, game down sized to 1536x684

https://user-images.githubusercontent.com/5572541/143778356-a5b40687-007d-461c-975e-a271c66e859b.mp4

**Comment by cederjack** [comment]
I had this same issue. My native screen resolution is 1920 x 1080, but ingame its 1680 x 1050 in fullsceen and i cant hover over confirm in options. Easy fix for this problem would be if they implemented the ability to use the arrow keys to browse though options

**Comment by Foxtrot1138** [comment]
I had the same issue but changed resolution and it worked fine after
