### ISSUE TITLE
[cost] experiment 326 says it costs 5 insp, but costs 10

### ISSUE THREAD

**Issue by johnathandarkly** [itsamewayu/OLFallenDoll#747]
**Describe the bug**
experiment 326 "legs up front entry" has a green header background and says it costs 5 inspiration, but it actually costs 10.

**To Reproduce**
1. try it
2. you'll see
 
**Expected behavior**
the experiment should either cost 5, or the header and displayed cost should be changed to reflect reality

**Desktop**
 - OS: Win 11 Pro
 - Game Version: 0.7.1
 - Processor: i5 12600K 
 - Graphics Card: RTX 2080 ti
 - Memory: 32gb

**Comment by Awfulwaffle1** [comment]
Known issue with Anya experiments that are learned through synthesis. This should have been resolved as of 0.7.2 build.

**Comment by Awfulwaffle1** [comment]
Should have been resolved as of 0.72b. Closing out
