### ISSUE TITLE
Infinite store opening sound

### ISSUE THREAD

**Issue by SuNNLov** [itsamewayu/OLFallenDoll#748]
Describe the bug
When the market/store opens to spend your points, a sound starts and repeats over and over again, and only stops until you enter a map or return to the harem menu.

1. Access the harem mode menu.
2. Click on the shop icon at the top.
3. You will hear the beginning of a looping sound.

Expected behavior
It was expected that when clicking on the store, a sound would be played only once and when leaving the store no looped sound would be played.

Desktop (fill in the following information):
- OS: Windows 11
- Game version 0.7.1b

**Comment by Awfulwaffle1** [comment]
This should be addressed as of the 0.7.2b build.

**Comment by Awfulwaffle1** [comment]
Verified Fixed as of 0.7.2b. Closing.
