### ISSUE TITLE
[0.7.2b] No new daily task given after the daily reset

### ISSUE THREAD

**Issue by Awfulwaffle1** [itsamewayu/OLFallenDoll#755]
**Describe the bug**
No Daily task was given after the reset

**To Reproduce**
1. Have an 0 to 2 daily tasks available before the daily reset
2. Wait for the daily reset
3. Observe the Daily Tasks panel

**Expected behavior**
One task should get added in.

 - Game Version [e.g. 0.7.2b]

**Additional context**
Seemed to happen after the reroll fix.

**Comment by Foolgy** [comment]
+1

**Comment by johnathandarkly** [comment]
samesies.

**Comment by Awfulwaffle1** [comment]
This should be resolved, but keeping it open for a few days to make sure it's working for all.

**Comment by Awfulwaffle1** [comment]
Seems to be resolved for sure. Closing out.
