### ISSUE TITLE
Impossible Daily Task and Study Problem

### ISSUE THREAD

**Issue by SuNNLov** [itsamewayu/OLFallenDoll#778]
When I clicked the "reroll" button, an impossible daily task called "Study 300 times from other researchers" appeared.
In addition to not showing progress, becoming static, it is not possible to study experiments that you already have, always showing the error "Experiment already owned".

Screenshots

![BUG Fall](https://github.com/itsamewayu/OLFallenDoll/assets/130314204/88533d7b-caaa-4100-a93e-3de556ae4a08)

**Comment by Awfulwaffle1** [comment]
Looks to be resolved as of 0.7.41. Will reopen if ran into again.
