### ISSUE TITLE
The description of some daily tasks does not match the actual movement

### ISSUE THREAD

**Issue by SagerasSimpson** [itsamewayu/OLFallenDoll#787]
According to players' feedback, the description of some daily tasks does not match the actual movement, 
the following example is, if a player want to complete the "cum with bondaged players 10 times", he actually need to drink at the bar 10 times, 
this is very misleading.

![错位](https://github.com/itsamewayu/OLFallenDoll/assets/95127591/cc02d290-4fc3-4c73-800a-7c5ed990864d)

Same situation recorded in #779

**Comment by Awfulwaffle1** [comment]
Closing as this is a duplicate issue.
