### ISSUE TITLE
[Model] 21 bugs i found so far, and a bit of other things

### ISSUE THREAD

**Issue by augustus123rng** [itsamewayu/OLFallenDoll#79]
Version: steam close beta 0.40

Camera/ model position bug:
1, Lab, alet, erika, sc4, pos1 
2, lab, alet, deep one hybrid(hereafter as doh), sc4, pos1
3, lab, erika, alet, sc4, pos1. Same as bug 1
4, shop, alet, lloigor, sc2, pos1
5, shop, alet, dreamer, sc1, pos3
6, shop, anya, dreamers sc5, pos3

Model disappearing:
1, Lab, alet, erika, sc4, pos2
2, lab, erika, aket, sc4, pos2, same as above
3, lab, anya, dreamer, sc3, pos3
4, shop, alet, lloigor, sc3, pos1
5, shop, alet, anya, sc5, pos1
6, shop, anya, alet, sc5, pos1
7, shop, anya, elder thing(et), sc5, pos2

Model :
1, Lab, alet, sylph, sc1, pos1, green vials on the table, floating or missing bottom holder 
2, lab, alet, dreamer, sc1, pos6, vial, same as above
3, lab, erika, dreamer, sc2, pos1, missing table. But this one is good for viewing, maybe intended?
4, lab, erika, dreamer, sc3, pos4, vial
5, lab, erika, doh, sc2, pos1, vial,
![16381568288094775387312063826843](https://user-images.githubusercontent.com/59657692/143804735-48fc125c-0e80-41f3-9b15-bdd2e205dfd1.jpg)
6, lab, anya, dreamer, sc1, pos2, braid, tits and arms,
![16381570754608854855206329501941](https://user-images.githubusercontent.com/59657692/143805042-85da1039-3de9-4c53-99db-eaacd0bd51b5.jpg)
And also the creampie animation seems off
7, lab, anya, doh, sc4, pos1, table, vial
8, lab, anya, spawn of basatan(sob), sc3, pos2, tits in the table, not rubbed against. Also tits physics seems different from previous builds

Regarding anya's tits, her braid used to bounce off her tits, refer to build 0.34, scene" lab, anya, dreamer, sc3, pos3", now it just go through them.

Regarding physics, namely tits bouncing, hips bouncing and tits against objects. Scene "lab, erika, yith, sc2, pos1" is a perfect example of how tits would be when bouncing and rubbed against an object, really beautiful work. But it seems it's not applied to all scenes.

**Comment by augustus123rng** [comment]
And the cursor is a bit off, makes it quite tricky to click smaller buttons, like changing an oufit

**Comment by jinjin525** [comment]
Camera/ model position bug: referring to #5 
Model disappearing: multiple issues reported.
Model : multiple issues reported. one referring to #33 
Creampie animation seems off: didn't notice so far. Will edit later.
Summarized lots of issues. Will keep this for a while.

**Comment by augustus123rng** [comment]
lab, anya, dreamer, sc1, pos2 is no longer available
