### ISSUE TITLE
Quality Settings does not seem to do anything

### ISSUE THREAD

**Issue by Awfulwaffle1** [itsamewayu/OLFallenDoll#792]
**Describe the bug**
When switching the Quality settings, it does not seem to do anything graphics-wise.

**To Reproduce**
1. Go to Harem
2. Observe the character
3. Go to settings and set quality to HIGH and click confirm
4. Observe character 
5. Go to settings and set quality to Medium
6. Observe
7. Go to settings and set quality to Low
8. Observe

**Expected behavior**
High settings should give the most quality picture.
Medium settings should be a balance of quality and performance
Low settings should be performance with lower quality

**Actual Behavior**
I'm not seeing any difference between the 3 settings.

**Comment by ktp23049a** [comment]
Year , me too , it always Low , quality is no change.

**Comment by ktp23049a** [comment]
在夜總會裡改變不了quality,一直都是lower quality ; 空間站倒是保持high quality,現在我不敢在空間站使用Quality settings,怕會變成像夜總會裡一樣永久保持lower quality無法更變.
Me too , it always lower quality , set to high or medium is no change.

**Comment by ktp23049a** [comment]
That not Resolved ,that not completed!!!

**Comment by ktp23049a** [comment]
This problem is still unresolved!!!!!!!!!So terrible!!!!!!!!!
[2023-11-05 (1)](https://github.com/itsamewayu/OLFallenDoll/assets/136036746/024a14ce-0c97-44f4-ba5c-4e0a4e031736)

**Comment by xishuai110** [comment]
> This problem is still unresolved!!!!!!!!!So terrible!!!!!!!!! [2023-11-05 (1)](https://github.com/itsamewayu/OLFallenDoll/assets/136036746/024a14ce-0c97-44f4-ba5c-4e0a4e031736)

Can you post your PC hardware?
