### ISSUE TITLE
No. 427 - Handstand Leglocking Doggystyle (Celia) - Male does not gain ecstasy. 

### ISSUE THREAD

**Issue by YoWaddupFD** [itsamewayu/OLFallenDoll#801]
Celia's experiment No. 427: Handstand Leglocking Doggystyle does not give the main participant any ecstasy, never allowing for simultaneous climax or a finished experiment. 

Video of Issue:
https://imgur.com/a/nkKHSwP

OS: Win 10 X64
Game Version: 7.3
Processor(CPU): Ryzen 5950x
Graphics Card: RTX 3090
Memory: 128 GB

**Comment by Awfulwaffle1** [comment]
duplicate of #765
