### ISSUE TITLE
Kabeshiri UI text issue - switch holes switches to vaginal

### ISSUE THREAD

**Issue by itsamewayu** [itsamewayu/OLFallenDoll#803]
The switch to vaginal/anal penetration button will change to say vaginal after some time.

Pressing the button while already in the vagina WILL switch properly, but the text will revert back to "switch to vaginal" even after switching back and forth.

![Paralogue-Win64-Shipping_qAyffZxtxB](https://github.com/itsamewayu/OLFallenDoll/assets/11155504/06128464-1ef6-40ea-89d0-43cf1acbd2b4)

Steam ID 76561198038698240

**Comment by Awfulwaffle1** [comment]
Verified as of 0.7.41
