### ISSUE TITLE
Bondage special action animations do not align with UI

### ISSUE THREAD

**Issue by NGC603** [itsamewayu/OLFallenDoll#808]
Special action buttons do not align with UI, i.e. Penetrate Harder plays Slap

Video - https://files.catbox.moe/nthj4l.mp4 timestamp 01:25

**Desktop (please complete the following information):**
 - OS: Win10
 - Game Version 0.7.4
 Complete the following Computer Hardware Configurations if necessary:
 - Processor(CPU): i9 12900k
 - Graphics Card: 3080ti
 - Memory: 64GB

**Comment by NGC603** [comment]
In the recent 0.7.3 update the audio issue has actually been fixed. However, I am experiencing a whole new host of bugs related to the bondage holes. I will update this ticket the collected information and steps to reproduce.

**Comment by NGC603** [comment]
As of the .7.4.5 the special action bug where the animation does not align with the UI still exists

**Comment by Awfulwaffle1** [comment]
Closing this one as the remaining issues have been split into two separate issues for tracking. Thanks again @NGC603
