### ISSUE TITLE
[VR] VR stuck at launch (black  screen on desktop, nothing in HMD)

### ISSUE THREAD

**Issue by Ghanth** [itsamewayu/OLFallenDoll#809]
**Describe the bug**
The game does not start in VR and stays stuck at launch on a black screen that shows only on the desktop. Nothing shows in HMD. There is no mention of the running game in the SteamVR UI.

**To Reproduce**
1. Open SteamVR (Valve Index here)
2. Click on 'play' in the Operation Lovercraft's Steam page
3. ...
4. See error described above

**Expected behavior**
Well, you know, having the game start in VR...

**Screenshots**
the desktop only shows a black screen with a blank white rectangle on its upper side. Nothing else... endlessly....

**Desktop:**
 - OS: Win10 pro
 - Game Version 0.7.3
 Complete the following Computer Hardware Configurations if necessary:
 - Processor(CPU): i7-8700K @ 3.70Ghz
 - Graphics Card: RTX 4090
 - Memory: 32GB

*If your game crashed, remember to upload the dmp file with your issue.

It's located in C:\Users\ (USER ID) \AppData\Local\Paralogue

Ther is no dmp file

**Additional context**
Valve Index VR system

**Comment by Awfulwaffle1** [comment]
Hello @Ghanth VR is still being worked on and not currently in the 0.7.4 build.
