### ISSUE TITLE
[EAC] Game won't launch without Internet Connection

### ISSUE THREAD

**Issue by TheSoulWizard** [itsamewayu/OLFallenDoll#81]
Not sure if this is a bug or not. But apparently EAC Requires Internet Connection for the game to Launch.
![image](https://user-images.githubusercontent.com/40411642/143880251-8b503171-7589-4c41-9f90-0530c140c909.png)

**Comment by mumu-pikapi** [comment]
The game is an online game. It shouldnt launch offline.

**Comment by TheSoulWizard** [comment]
> "It shouldnt launch offline."

I have to disagree with that. While the game does have an Online mode, Offline mode like Gallery/Classic should be working offline as intended.

Helius himself noted that the game _should_ launch without Internet Access, however it hasn't been tested and turns out that EAC (Easy Anti-Cheat) requires the user to have internet connection in order for the game to launch.

**Comment by Awfulwaffle1** [comment]
Game opens without internet connection now. Closing.
