### ISSUE TITLE
Fatal error after launching 

### ISSUE THREAD

**Issue by jusless2** [itsamewayu/OLFallenDoll#813]
I use Quest Pro and Quest link to launch SteamVR.
The game started with broken images then stucked in loading.
(I can see the laboratory, but only music worked.)
After a while, it showed "Fatal error" and jumped out the game.
Don't know what to do.

My system:

Win10
 i9-11980HK & 3080
Game version 0.7.4
Quest  version 55

**Comment by Awfulwaffle1** [comment]
@jusless2 VR isn't support for this build quite yet. It's being worked on, but still not released.

**Comment by jusless2** [comment]
Got it, thanks!

**Comment by Awfulwaffle1** [comment]
No problem. Closing this issue.
