### ISSUE TITLE
Ghost researchers in the bondage system and buggy animation when logging out

### ISSUE THREAD

**Issue by SuNNLov** [itsamewayu/OLFallenDoll#819]
I noticed that when a researcher is in the bondage system of the Archimedes Space Station and logs out of the game, a buggy animation appears and then two "ghost researchers" appear, both in the person who logged out and also in another bondage system of another researcher who did not have no interaction before at the same time.

Apparently, the offline researchers who were controlling a female character in bondage are randomly replaying the new "Special Actions" animations with the ghost researchers.

1. Go to Archimedes Space Station's, find a player in the bondage system.
2. Approach any bondage system in use.
3. You'll likely find two ghost players utilizing both bondage devices on the Archimedes Space Station itself.

**Screenshots**
In this image, a researcher logged out of the game a few moments ago.
![image](https://github.com/itsamewayu/OLFallenDoll/assets/130314204/02ce23b9-cbe4-4374-9483-54c69057de6d)

In this image is an example of the two "Ghost Researchers".
![image](https://github.com/itsamewayu/OLFallenDoll/assets/130314204/8615e606-488e-4169-b875-a39a2e643330)

 - OS: Win 11 Pro
 - Game Version: 0.7.4

**Comment by Awfulwaffle1** [comment]
T-posing Dreamers are still present.
