### ISSUE TITLE
Bondage System Lockout Bug

### ISSUE THREAD

**Issue by YoWaddupFD** [itsamewayu/OLFallenDoll#836]
Several people have submitted images of "Ghost" players t-posing at bondage devices. Example: 
<img width="450" alt="Capture" src="https://github.com/itsamewayu/OLFallenDoll/assets/136668781/5f4d1d96-2c0f-4353-9f39-ff772fc34f0b">

This is caused by two users using the doll in the bondage device, and leaving. 
 
In this image, the dreamers were me and another player before Erika logged out: 
![20230720210438_1](https://github.com/itsamewayu/OLFallenDoll/assets/136668781/a760f6da-7911-4a09-b90b-a8aed8c9b8c4)

causing Erika's player to become stuck  in a permanent loading screen, unable to rejoin. Upon attempting to rejoin, two "Phantom dreamers" popped into existence. The T-posing is likely caused by loading in to a lobby where this bug has occurred.

Reports suggest that the dreamers disappear on using a hole, and then reappear shortly after.

Edit: The player who is locked out of the game only sees this: 
![image](https://github.com/itsamewayu/OLFallenDoll/assets/136668781/ab546f0e-fa85-4cd5-b176-dea46922cf53)

**Comment by anonymouskommando** [comment]
I have also encountered this bug as described

**Comment by Awfulwaffle1** [comment]
I think the lockout has been addressed, but I'm still seeing T-pose dreamers. So...partially fixed? Still have to verify if the lockout still occurs or not.

**Comment by Awfulwaffle1** [comment]
Lockout indeed fixed, but visual bugs still remaining.

**Comment by Awfulwaffle1** [comment]
Closing this one out and tracking the visual bug in #819
