### ISSUE TITLE
[UI Feature] Tell the user that the server is not available/timed out/offline, and make the connection cancellable

### ISSUE THREAD

**Issue by hanyue112** [itsamewayu/OLFallenDoll#84]
**Is your feature request related to a problem? Please describe.**
The current imp, when the app tries to connect with the remote server, it will trap the user into an indefinitely waiting

**Describe the solution you'd like**
If the remote server is not reachable or timed out, display Message and let the user back to the main menu
If the remote server is not available due to reasons,  display reason(s) and let the user back to the main menu
When connecting with the remote server, make the UI cancellable so that the user may back to the main menu at any time

**Describe alternatives you've considered**
If the remote server is not reachable for whatever reason(s), display a generic Message and let the user back to the main menu
Optional: Display count down in second for the timing out and make the operation cancellable 

**Additional context**
N/A

**Comment by Awfulwaffle1** [comment]
Now returns a Cannot Connect to Steam if internet connectivity isn't active or steam is offline. Will spit out a connection error if one cannot access Harem. Closing.
