### ISSUE TITLE
Genital Dilation is spelled "Dilatation"

### ISSUE THREAD

**Issue by YoWaddupFD** [itsamewayu/OLFallenDoll#852]
Genital Dilation is spelled "Dilatation"

Image:

![20230722221210_1](https://github.com/itsamewayu/OLFallenDoll/assets/136668781/d21c8788-6c6e-4752-b6b9-3a429c43afb8)

**Comment by SagerasSimpson** [comment]
https://radiopaedia.org/articles/dilation-vs-dilatation?lang=us

**Comment by YoWaddupFD** [comment]
Huh. Learn something new every day.
