### ISSUE TITLE
can`t get/use inspiration

### ISSUE THREAD

**Issue by DAmbielSy** [itsamewayu/OLFallenDoll#853]
**Describe the bug**
Now when I enter the game, I can't use inspiration properly, I log in every day for the first time to get 3 inspiration can be seen, but when I enter the night club or station, the inspiration is gone, and I can't get inspiration.

**To Reproduce**
1. enter the game everyday
2. Log in and get 3 inspirations
3. Enter map(can`t get in [network problem])
4. can`t see/get/use inspirations

**Expected behavior**
get and use inspirations

**Screenshots**
![image](https://github.com/itsamewayu/OLFallenDoll/assets/127064779/cbb49b2f-ffdc-4256-8893-1e228f0634a3)
![image](https://github.com/itsamewayu/OLFallenDoll/assets/127064779/94d164b5-12f5-4e4f-ad30-2e46069ffd45)

**Desktop (please complete the following information):**
 - OS: [e.g. Win10]
 - Game Version [e.g. 0.74]
 Complete the following Computer Hardware Configurations if necessary:
 - Processor(CPU): [e.g. i7-10700KF]
 - Graphics Card:[e.g. RTX3080]
 - Memory:[e.g. 32GB]

**Comment by Awfulwaffle1** [comment]
@DAmbielSy can you verify if this is still happening for you?
