### ISSUE TITLE
Inspiration capping below 10

### ISSUE THREAD

**Issue by redwash** [itsamewayu/OLFallenDoll#855]
**Describe the bug**
Inspiration wheel does not fill to the max of 10 and has been capping at 8 for me for several days, today it has further dropped to a maximum of 7 inspiration. This bug is not visual and any inspiration earned past the cap can not be used.

**To Reproduce**
Unknown. Has been capping daily at 8 inspiration for me, today the cap has dropped to only 7 but I have made no changes to my game play that I am aware of.

**Expected behavior**
Inspiration cap should be 10 with the wheel full.

**Screenshots**

**Desktop (please complete the following information):**
 - Win 10
 - 0.7.4
 Complete the following Computer Hardware Configurations if necessary:
 - 13900k
 - 4090
 - 32GB

**Additional context**
Maybe related to issue #853

**Comment by Awfulwaffle1** [comment]
@redwash are you still having this issue on your end?

**Comment by redwash** [comment]
> @redwash are you still having this issue on your end?

@Awfulwaffle1 Not had it since 0.7.41 was released, but I didn't see it for the first few days after 0.7.4 dropped and then it got progressivly worse. Call it clear for now and if it pops up again I'll let you know/relog it.

**Comment by Awfulwaffle1** [comment]
@redwash thanks for the follow up! Closing.
