### ISSUE TITLE
[Menu] Fails at map when starting harem mode

### ISSUE THREAD

**Issue by gigantocircus** [itsamewayu/OLFallenDoll#86]
**Describe the bug**

**To Reproduce**
1. Go to the main menu
2. Click on Harem
3. Wait for loading please wait, then view the map for 1-2 seconds
4. Back at main menu

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Nvidia 2070 Max-Q

**Additional context**

**Comment by Reesha1992** [comment]
^

**Comment by Gurith85** [comment]
I am facing the same issue

Desktop (please complete the following information):

OS: Windows 10
Nvidia GeForce GTX 980

**Comment by Fank** [comment]
Same issue

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Nvidia GeForce RTX3090
 
![image](https://user-images.githubusercontent.com/1900106/144032762-96d90cfd-a471-4dc9-adb8-0575e3fce7e2.png)

**Comment by ToonPlim** [comment]
Same issue

Laptop

- OS: Windows 11 pro
- Nvidia GeForce GTX3080

**Comment by Fank** [comment]
I managed to get it work, took around 10 full game restarts.

**Comment by Cloudus16** [comment]
Same issue 

Desktop :

Windows 10
Nvidia GeForce GTX 1080

**Comment by Binaryshark5** [comment]
try restarting your computer, that fixed the problem for me.

**Comment by Gurith85** [comment]
Same here, it is now working. I had a pending windows update today so maybe it is related?
