### ISSUE TITLE
Low FPS and Blurred textures on Erotes Nightclub

### ISSUE THREAD

**Issue by SuNNLov** [itsamewayu/OLFallenDoll#860]
**Describe the bug**
I notice that when I enter the "Erotes Nightclub" map, the game is showing a lower FPS than in the Archimedes Space Station, and also FPS stutters, which from time to time makes the map texture blurry.

For example, when I move the camera towards the piano, there is an FPS stutter.
And apparently, textures can also become blurry on the Archimedes Space Station.

**To Reproduce**

1. Go to Erotes Nightclub OR Archimedes Space Station Map
2. Wait a few minutes
3. Notice small drops in FPS that occur suddenly
4. Note that with each FPS drop the texture gets blurred

**Expected behavior**
This started in version 0.7.41 and I believe there shouldn't be as many FPS stutters and blurry textures.

**Desktop (please complete the following information):**
 - OS: Win 11 Pro
 - Game Version: 0.7.41
 - Processor(CPU): Ryzen 7 5700X
 - Graphics Card: RTX 3060 TI 8GB
 - Memory: 16GB

**Comment by YoWaddupFD** [comment]
Images provided by another user:

![wtf2](https://github.com/itsamewayu/OLFallenDoll/assets/136668781/2438a83d-582b-4e80-818b-1eae602747ad)

![wtf](https://github.com/itsamewayu/OLFallenDoll/assets/136668781/f5038ac3-c6d8-40eb-8c22-7de8d920727f)

**Comment by Elegrand1** [comment]
![26 07 2023](https://github.com/itsamewayu/OLFallenDoll/assets/130096045/e7c0a71b-6288-4571-b4ef-ccccbba28302)

I have the same problem with the other level, since the update, the game looks very blurry. You can barely recognize the caracter's faces, and this on highest details and best screen resolution. See screenshot.

**Comment by Awfulwaffle1** [comment]
Marking as resolved on my end, but leave it up to the public to decide if this is resolved.
