### ISSUE TITLE
[Animation] Card reveal screen lingers and can't return to Harem menu after opening pack

### ISSUE THREAD

**Issue by beetalogist** [itsamewayu/OLFallenDoll#87]
**Describe the bug**
After opening a pack, the pose cards disappeared, but the card reveal screen stayed on and animated, with the music looping, and the only way to leave the screen was to force quit the game.

**To Reproduce**
1. Open a pack
2. Click on all the cards
3. When finished, the card reveal screen may stay up and not allow you to exit back to the Harem screen.

**Expected behavior**
The card screen to not linger and the Harem main menu to return

**Desktop (please complete the following information):**
 - OS: Windows 11

**Comment by Awfulwaffle1** [comment]
Doesn't seem to be an issue anymore. Closing.
