### ISSUE TITLE
Player logging out while you have them selected in Player List causes Player List to stop functioning.

### ISSUE THREAD

**Issue by redwash** [itsamewayu/OLFallenDoll#872]
If you have a player selected in the Player List so that the Like and Hide buttons are visable when they log out you will be unable to select another player to bring up the Like/Hide buttons when you click their name.

**To Reproduce**
Click a players name in the Player List (May have to give Like). Wait for player to log out. Click another player in the Player List and the drop down buttons will not appear. Game has to be closed and restarted toi fix issue.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Game Version 0.7.41
 Complete the following Computer Hardware Configurations if necessary:
 - Processor(CPU): 13900k
 - Graphics Card: 4090
 - Memory:[e.g. 32GB

**Comment by Awfulwaffle1** [comment]
#831 duplicate. Closing.
