### ISSUE TITLE
[System] Inspiration unable to be used in the Blueprints exchange

### ISSUE THREAD

**Issue by itsamewayu** [itsamewayu/OLFallenDoll#89]
**Describe the bug**
Inspiration resource isn't able to be used on Blueprints

**To Reproduce**
Go to Blueprints, try to make a new blueprint

**Expected behavior**
The blueprint should be made

**Screenshots**
No screenshots to be had, nothing gets added to inventory and Inspiration is not consumed.

**Comment by TheSoulWizard** [comment]
I guess that has been fixed? I am able to buy blueprints now.
