### ISSUE TITLE
[Model] Anya's Boobs Are Depressed

### ISSUE THREAD

**Issue by itsamewayu** [itsamewayu/OLFallenDoll#9]
Anya's boobs are depressed as if her upper apparel is half-dressed when in fact it is set to nude. Boobs behave correctly when you unequip her shoes.
![unknown](https://user-images.githubusercontent.com/11155504/143678982-4733491f-4680-4820-93d5-6afed44b6949.png)
![unknown](https://user-images.githubusercontent.com/11155504/143678983-464404ce-ebd8-423f-a11d-43b2d6002d5a.png)

There's a similar issue with her Expedition costume. Doesn't get fixed when you unequip her shoes for that one though 

From TMoane

**Comment by Awfulwaffle1** [comment]
Still an issue.
