### ISSUE TITLE
[UI] Mouse disappears in Harem mode going from Station to Changing Room

### ISSUE THREAD

**Issue by GunsightOne** [itsamewayu/OLFallenDoll#90]
**Describe the bug**
Mouse cursor no longer shows up going back to Changing Room from the Station in Harem Mode.

**To Reproduce**
1. Join an instance at the Station in Harem mode
2. Press escape and choose changing room from the menu
3. Cursor disappears once back in Changing Room
4. Icons are still interactable

**Desktop (please complete the following information):**
 - OS: Windows 10 21H2 19044.1387
 - OL Version 0.4
 - AMD Ryzen 9 5900X
 - Nvidia RTX 3090

**Comment by jinjin525** [comment]
From TheSoulWizard in issue #115 :
Hitting ESC (In-Session) on Harem Mode and then clicking Settings, the mouse cursor goes invisible, you can still click stuff though but it's a challenge.

**Comment by jinjin525** [comment]
This issue should be fixed, closing issue now.
Please submit this issue again if not fixed, we'll re-open this issue.
