### ISSUE TITLE
Celia T pose and texture issue with elizabeth

### ISSUE THREAD

**Issue by Jmay0884** [itsamewayu/OLFallenDoll#907]
**Describe the bug**

issue: whenever I use celia as an avatar, she is stuck in T-pose and floats around. And some of Elizabeth clothes glitches when half dressing them or taking tops off and leaving leggings on. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Win10/Ubuntu 20.04]
 - Game Version [e.g. 0.42]
 Complete the following Computer Hardware Configurations if necessary:
 - Processor(CPU): [e.g. i7-9700K]
 - Graphics Card:[e.g. RTX 2070s]
 - Memory:[e.g. 16GB]

*If your game crashed, remember to upload the dmp file with your issue.

It's located in C:\Users\ (USER ID) \AppData\Local\Paralogue

**Additional context**

**Comment by NGC603** [comment]
Celia T-pose seems to be fixed as of the latest hotfix.

**Comment by Awfulwaffle1** [comment]
Resolved as of 0.7.5d. Closing.
