### ISSUE TITLE
No. 525 Handheld Spooning pose available in Erotes

### ISSUE THREAD

**Issue by Fiwzie** [itsamewayu/OLFallenDoll#908]
**Describe the bug**

No. 525 Handheld Spooning , Elizabeth pose has no object to use it in Erotes Club , but it can be placed and you end up in a wall or somewhere .

**To Reproduce**
1. Go to  Erotes Club
2. Click on No. 525 Handheld Spooning 
3. Go near the bar and then look around to place the pose until the pose hologram disappears  , place the pose. ( See first screenshots for reference ) 

**Expected behavior**
End up in a wall ?

**Screenshots**
![Paralogue Screenshot 2023 09 28 - 19 39 17 48](https://github.com/itsamewayu/OLFallenDoll/assets/129328061/293bf450-4f39-4f29-9722-705c06dd8e37)
![Paralogue Screenshot 2023 09 28 - 19 37 12 14](https://github.com/itsamewayu/OLFallenDoll/assets/129328061/84155ba4-be21-481f-9775-e3331f038ec3)
![Paralogue Screenshot 2023 09 28 - 19 37 13 65](https://github.com/itsamewayu/OLFallenDoll/assets/129328061/a2e17661-43a5-4cdf-a066-4cbe37146181)

**Comment by Awfulwaffle1** [comment]
Issue verified fixed as of 0.7.75a. Closing.
