### ISSUE TITLE
No. 524 Dildo Raised Anvil animation 

### ISSUE THREAD

**Issue by Fiwzie** [itsamewayu/OLFallenDoll#909]
No. 524 Dildo Raised Anvil 

Dreamer lets go of the toy and it moves on it's own at the start of the animation, then Dreamer's animation becomes misaligned 

EDIT : it can be fixed if Special Action is used, until pose is reset, 
![Screenshot 2023-09-28 195447](https://github.com/itsamewayu/OLFallenDoll/assets/129328061/d339f669-9d3e-40ea-afe9-332b681b553a)

**Screenshots**

**Comment by Awfulwaffle1** [comment]
Fixed as of 0.7.7d. Closing.
