### ISSUE TITLE
[HAREM] [UI] Overlapping of background music.

### ISSUE THREAD

**Issue by mumu-pikapi** [itsamewayu/OLFallenDoll#91]
**Describe the bug**
When analyzing a blueprint from Harem homescreen/dashboard, both background music is playing. 
1. Packet opening BGM
2. Homescreen BGM

Note: The homescreen BGM is there but very soft. I had triple confirmed it myself.

**To Reproduce**
1. From Title, Go to 'Harem'
2. Click on 'Blueprints'
3. Select a card and press 'Analyze'

**Expected behavior**
Expected to have one BGM at a time.

**Screenshots**
Attached to below.

**Desktop:**
 - OS: WINDOWS 10

**Game Version:**
 - Version 0.4.0
 - STEAM APP ID: 1810920
 - STEAN BUILD ID: 7798709

**Additional context**
![2021-11-30 12_49_41-FallenDoll](https://user-images.githubusercontent.com/95267208/143988216-b991cd7f-e4b3-453f-92ef-a2eaab1fba1a.png)
![2021-11-30 12_50_09-FallenDoll](https://user-images.githubusercontent.com/95267208/143988221-245d34b5-6f66-44f5-8152-fd8e58805d0a.png)
![2021-11-30 12_57_49-Window](https://user-images.githubusercontent.com/95267208/143988227-02c999c1-00b8-45fb-9b26-e0fc1f9b7090.png)

**Comment by itsamewayu** [comment]
Repeat issue

**Comment by mumu-pikapi** [comment]
Pardon me but, when it's a repeat issue, can you add a link to the existing one?

**Comment by mumu-pikapi** [comment]
Duplicated issue with #85.
