### ISSUE TITLE
Floating Elizabeth hair in Do Not Distrurb Mode 

### ISSUE THREAD

**Issue by Fiwzie** [itsamewayu/OLFallenDoll#912]
Other players Elizabeth hair found floating then in bondage in Do Not Disturb Mode 

![Screenshot 2023-09-28 214333](https://github.com/itsamewayu/OLFallenDoll/assets/129328061/212c1f9b-8b40-47cb-8432-86e93f138a7e)

**Comment by Awfulwaffle1** [comment]
Verified fixed as of 0.7.5d. Closing
