### ISSUE TITLE
Elizabeth Hair flickering in yellow color

### ISSUE THREAD

**Issue by Fiwzie** [itsamewayu/OLFallenDoll#913]
**Describe the bug**

Elizabeth Hair flickering in yellow color while walking around in Erotes while looking slightly at the floor. If you run and look straight there's no issue.  Happens all the time 

**Desktop (please complete the following information):**
 - OS: Win 11 x64
 - Game Version : 0.7.5
 Complete the following Computer Hardware Configurations if necessary:
 - Processor(CPU): i5 13600
 - Graphics Card:  RTX 4070 ti
 - Memory:[e.g. 32GB]

https://github.com/itsamewayu/OLFallenDoll/assets/129328061/7f135792-713d-42c4-93ac-4ce2dc1113f9

**Comment by Awfulwaffle1** [comment]
Seems to be resolved. Could not reproduce this issue as of 0.7.7d.
