### ISSUE TITLE
Elizabeth's hair from other players is always showing in ''Do Not Disturb'' mode.

### ISSUE THREAD

**Issue by Jeieke48** [itsamewayu/OLFallenDoll#915]
**Describe the bug**
Even with ''Do Not Disturb'' mode enabled, Elizabeth's hair is showing ALWAYS, either in Erotes or Archimades, causing huge performance issues (I have around 60 FPS's when there are no Elizabeth's in the lobby with ''Do Not Disturb'' enabled, when there are 4+ Elizabeth's in the lobby I have around 18 FPS's with ''Do Not Disturb'' enabled, due to the hair not hiding.)

**To Reproduce**
1. Go to either Erotes or Archimades lobby.
2. Find any other Elizabeth player.
3. Turn on ''Do Not Disturb Mode''.
4. See Elizabeth's hair not hidden.

**Screenshots**
![Captura de pantalla (548)](https://github.com/itsamewayu/OLFallenDoll/assets/146381146/e40df0cd-8012-4f19-824a-aea963c1c3d2)
![Captura de pantalla (552)](https://github.com/itsamewayu/OLFallenDoll/assets/146381146/46813022-ad8d-4fa2-9d6a-b4926998dcc2)
![Captura de pantalla (554)](https://github.com/itsamewayu/OLFallenDoll/assets/146381146/356824fa-a1a4-4740-af5d-287c4db25bfe)

**Desktop:**
 - OS: Windows 10
 - Game Version 0.7.5
 - Processor(CPU): i7-4790K
 - Graphics Card: GTX 1070
 - Memory: 32 GB RAM

**Additional context**
Please fix it I'm laggy D':

**Comment by Awfulwaffle1** [comment]
Verified fixed as of 0.7.5d. Closing.
