### ISSUE TITLE
Cum volume notification is not displayed consistently

### ISSUE THREAD

**Issue by NGC603** [itsamewayu/OLFallenDoll#921]
Not sure if this is a bug or an oversight, however:

During vaginal+anal scenes (MMF) both the cum volume for both males in mL/L is shown on the side of the screen. When playing a oral+vaginal or oral+anal only 1 male cum volume is shown. 

Cum volume during oral only and external ejaculations are also not shown.

Tested with Anya, nearly empty, no cum inflation - https://files.catbox.moe/sknkkm.jpg

- MMF A+V, 2 notifications - https://files.catbox.moe/7yj1j2.mp4
- MMF O+V, 1 notification (perhaps they are added together?) - https://files.catbox.moe/q0gpfp.mp4
- MMF O+A, 1 notification - https://files.catbox.moe/08aqv3.mp4
- MF O, no notification - https://files.catbox.moe/y1uj3e.mp4
- MF External ejaculation, no notification - https://files.catbox.moe/dynuew.mp4
- MMF O+V External ejaculation, notification - https://files.catbox.moe/r71j8h.mp4

Will test at full cum inflation and with a different character later.

OS: Win10
Game Version 0.75d
Complete the following Computer Hardware Configurations if necessary:
Processor(CPU): i9 12900k
Graphics Card: 3080ti
Memory: 64GB

**Comment by Awfulwaffle1** [comment]
@NGC603 Can you verify if this happen inconsistently or only when a girl is full capacity cum inflation.

**Comment by NGC603** [comment]
> @NGC603 Can you verify if this happen inconsistently or only when a girl is full capacity cum inflation.

@Awfulwaffle1 

Tested with Anya, nearly empty, no cum inflation - https://files.catbox.moe/sknkkm.jpg

- MMF A+V, 2 notifications - https://files.catbox.moe/7yj1j2.mp4
- MMF O+V, 1 notification (perhaps they are added together?) - https://files.catbox.moe/q0gpfp.mp4
- MMF O+A, 1 notification - https://files.catbox.moe/08aqv3.mp4
- MF O, no notification - https://files.catbox.moe/y1uj3e.mp4
- MF External ejaculation, no notification - https://files.catbox.moe/dynuew.mp4
- MMF O+V External ejaculation, notification - https://files.catbox.moe/r71j8h.mp4

Will test at full cum inflation and with a different character later.

**Comment by NGC603** [comment]
Resolved as of 0.7.7d.
