### ISSUE TITLE
ARGUMENT and Pack Purchase not working

### ISSUE THREAD

**Issue by Exarch23** [itsamewayu/OLFallenDoll#93]
**Describe the bug**
The game starts me out with 48 Argument points , I opened all the packs and afterwards tried to buy some more packs , and it just sent me an error message that I have Insufficient Arguments.

**To Reproduce**
1. Go to 'CHARACTER'
2. Click on 'BLUERINTS'
3. Click on pack purchase button

**Expected behavior**
Receive the pack I purchased and get arguments deducted from my inventory

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Win10]
 - Browser [e.g. chrome]
 - Version [e.g. 4.0]

**Comment by itsamewayu** [comment]
Repeat issue
