### ISSUE TITLE
Hair simulation option suggested on Patreon is not present in game settings 0.75d

### ISSUE THREAD

**Issue by kmoonwalker** [itsamewayu/OLFallenDoll#934]
![image](https://github.com/itsamewayu/OLFallenDoll/assets/71607540/3eda5564-c89f-4e81-927d-c1cdf0cd1c4a)
![image](https://github.com/itsamewayu/OLFallenDoll/assets/71607540/4df21ebe-8919-434c-b69b-a2bab2314ac1)
![image](https://github.com/itsamewayu/OLFallenDoll/assets/71607540/6964afd5-975a-443a-bad9-313909385b9f)

**Comment by Awfulwaffle1** [comment]
Closing as it is present now.
