### ISSUE TITLE
Anti-aliasing is causing big FPS drops with Elizabeth's new hair simulation

### ISSUE THREAD

**Issue by SuNNLov** [itsamewayu/OLFallenDoll#935]
**Describe the bug**
Apparently, when you are in free mode with or without Elizabeth as the default avatar, her hair becomes completely buggy, as in the image below.
This causes a big drop in FPS when anti-aliasing is set to "Medium" or "High", reaching an average of up to 20 FPS, however, when setting anti-aliasing to "Low", a notable improvement in FPS is noticeable.

**To Reproduce**

1. Go to the Harem on any map with Elizabeth
2. Realize completely crazy hair
3. Click to set anti-aliasing to "Low"
4. Notice an improvement in FPS, but with some stutters

**Expected behavior**

Elizabeth's hair looks very messy and strange in free mode, plus the FPS is much lower than normal with Anti-Aliasing being able to improve the FPS as you change it.
Also, with the crazy hair and FPS on Elizabeth, the texture of everything starts to get blurry, and I believe that all of this shouldn't happen that way. And this is not a problem with VRAM, unless 8GB VRAM is low, this always happens.

**Screenshots**
![image](https://github.com/itsamewayu/OLFallenDoll/assets/130314204/3f2daad5-df25-405f-a1b0-8f7aaa6f8295)

**Desktop (please complete the following information):**

 - OS: Win 11 Pro
 - Game Version: 0.7.5d
 - Processor(CPU): Ryzen 7 5700X
 - Graphics Card: RTX 3060 TI 8GB
 - Memory: 16GB

**Comment by NGC603** [comment]
You can fix the "crazy hair" by going into settings and changing the quality (Low/Medium/High) to another setting, and then back to the original setting. However, all the other buggy issues with the hair and the performance issues will still exist.

**Comment by Awfulwaffle1** [comment]
@SuNNLov Getting a pulse check on how well the performance is after the 0.7.7d build. Please let us know.

**Comment by SuNNLov** [comment]
> @SuNNLov Getting a pulse check on how well the performance is after the 0.7.7d build. Please let us know.

Performance has improved a lot, my FPS is very high now and I don't find any blurry textures...

The only thing I notice now is some random freezes in the game, which freezes the screen for a few seconds, which seems to be caused by some action from another player, perhaps?

I already deleted my old configuration files, but it looks like these FPS freezes are something new.

**Comment by Awfulwaffle1** [comment]
> > @SuNNLov Getting a pulse check on how well the performance is after the 0.7.7d build. Please let us know.
> 
> Performance has improved a lot, my FPS is very high now and I don't find any blurry textures...
> 
> The only thing I notice now is some random freezes in the game, which freezes the screen for a few seconds, which seems to be caused by some action from another player, perhaps?
> 
> I already deleted my old configuration files, but it looks like these FPS freezes are something new.

@SuNNLov I gotcha. This might be a totally different issue as I'm seeing this as well, but more so when opening experiment lists and going in and out of a pole. Large dips. Though if all above for the original seems resolved please close this out. We'll most likely need another issue for the different areas of performance. Thanks again for checking~
