### ISSUE TITLE
Suggestions for fixing performance issues due to new Elizabeth's hair.

### ISSUE THREAD

**Issue by Jeieke48** [itsamewayu/OLFallenDoll#940]
Hello, since the release of Elizabeth there has been a lot of performance issues for many players, also for me. Even if Elizabeth's hair is disappearing successfully with ''Do Not Disturb'' mode enabled there are still a lot of performance issues compared to before.
And now after the latest hotfix on October 2, the performance is even worse...

**Here are some examples of the performance differences in between Elizabeth and Anya in a empty lobby:**
![Captura de pantalla (559)](https://github.com/itsamewayu/OLFallenDoll/assets/146381146/2150f06e-c7b4-4b62-aaff-bffdfaabe3db)
![Captura de pantalla (560)](https://github.com/itsamewayu/OLFallenDoll/assets/146381146/b4dc82cc-238b-4b0b-aee9-95c7bb8c9b3b)

If we add to this the fact of more players inside one lobby it gets even worse... Even with ''Do Not Disturb'' enabled it barely helps with 3-4 frames...

**My personal different suggestions:**

- If we could be allowed to create private lobbies all the issues would be gone. 

- A setting that allow us to get inside public lobbies without rendering the models from other users, making them completely unloaded unless we reconnect choosing the opposite.

- A setting that could allow us to lower the graphic quality of Elizabeth's new type of hair.

- A setting that could let us assign the distance view, to make things past certain distance to be not rendered, even if it does affect the map visibility, it'd be a helpful setting.

**My PC specs:**

**-SYSTEM:** Windows 10
**-GPU:** GTX 1070
**-CPU:** i7-4790K
**-RAM:** 32 GB

Thanks so much for reading!

**Comment by Awfulwaffle1** [comment]
Toggle for hair simulation was introduced and optimization. Closing for now, but feel free to re-open if you feel inclined to do so @Jeieke48
