### ISSUE TITLE
Experiment No. 511 is missing fluids

### ISSUE THREAD

**Issue by SuNNLov** [itsamewayu/OLFallenDoll#943]
**Describe the bug**
Elizabeth's experiment No. 511 is missing dynamics fluids when select climax outside.
I also notice that most of Elizabeth's experiments have a final climax animation that takes much longer than usual to finish.

**To Reproduce**
1. Go to any map with Elizabeth.
2. Place the experiment No. 511.
3. Select climax outside.

**Screenshots**
Experiment No. 511
![image](https://github.com/itsamewayu/OLFallenDoll/assets/130314204/d5bf07c0-8bd5-44ce-8d78-b19f89008342)

**Desktop (please complete the following information):**
 - OS: Win 11 Pro
 - Game Version: 0.7.5d

**Comment by Awfulwaffle1** [comment]
Working as of 0.7.7d build. Closing.
