### ISSUE TITLE
[Harem] [UI] Add confirm dialog for outfit purchases

### ISSUE THREAD

**Issue by null-dev** [itsamewayu/OLFallenDoll#95]
**Is your feature request related to a problem? Please describe.**
Clicked on an outfit expecting a preview but it instead immediately purchased it. Was kinda frustrating as a user.

**Describe the solution you'd like**
Display a dialog to allow the user to confirm a purchase instead of immediately performing the purchase.

**Comment by jinjin525** [comment]
From poykun in issue #152 which seems to be more detailed:

**Is your feature request related to a problem? Please describe.**
I wanted to see if I could preview outfits before purchasing. Clicked the outfit icon and instantly purchased.

**Describe the solution you'd like**
A prompt asking if you're sure you'd like to purchase the selected item

**Describe alternatives you've considered**
An alternative is to limit the purchase hit box to the lower 1/4 where the Like/Purchase button is displayed

**Comment by Awfulwaffle1** [comment]
Still valid feature request...
