### ISSUE TITLE
Error 1100: Internal server error ErrorCode:1100

### ISSUE THREAD

**Issue by SnowmanSN** [itsamewayu/OLFallenDoll#952]
**Describe the bug**
When I try to start harem mode, Error 1100 appears and I can't proceed any further.

**To Reproduce**
Click Harem Mode
Click start
Click Archimedes Launch Station
Click to enter the harem
After that, the deployment continues for a while and you cannot enter the harem, and an error similar to the attached screenshot is displayed.
Error 1100: Internal server error ErrorCode:1100

(This is a random English translation of the Japanese displayed by me, so the English notation may be incorrect.)

**Expected behavior**
Naturally, I think I can enter harem mode without any errors.

**Screenshots**
![DeployError](https://github.com/itsamewayu/OLFallenDoll/assets/148922133/eac7d820-b0c1-4197-b652-5dcbad65d855)

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro 22H2
 - Game Version 0.7.5
 
 Complete the following Computer Hardware Configurations if necessary:
 - Processor(CPU): i5-13400
 - Graphics Card: RTX4070
 - Memory:64gb

*If your game crashed, remember to upload the dmp file with your issue.
[CrashReportClient.zip](https://github.com/itsamewayu/OLFallenDoll/files/13143919/CrashReportClient.zip)

**Additional context**

**Comment by HRT39** [comment]
the same

**Comment by SnowmanSN** [comment]
I updated to version 0.77, but this time I don't get an error and the "Deploy" and "Loading" message continues forever.

**Comment by SnowmanSN** [comment]
I updated to version 0.77, but this time I don't get an error and the "Deploy Loading" message continues forever.

**Comment by SnowmanSN** [comment]
When I set up a VPN for the app and accessed it from the US, I was able to enter harem mode without any problems.
This matter will be closed.
