### ISSUE TITLE
No. 550 Lifted Spread pose, piano textures

### ISSUE THREAD

**Issue by Fiwzie** [itsamewayu/OLFallenDoll#954]
**Describe the bug**
Elizabeth No. 550 Lifted Spread Missionary pose, piano becomes sort of transparent, not sure in intentional. 

![Screenshot 2023-10-25 141326](https://github.com/itsamewayu/OLFallenDoll/assets/129328061/33699440-55ba-43a3-887c-29872dd24f0c)

**Comment by Awfulwaffle1** [comment]
No longer receiving the transparent piano after placing the experiment as of 0.7.7d. Closing.
