### ISSUE TITLE
No. 504 Chair Doggy, second dreamer settings missing

### ISSUE THREAD

**Issue by Fiwzie** [itsamewayu/OLFallenDoll#955]
**Describe the bug**
Elizabeth No. 504 Chair Doggy Blowjob pose,  second dreamer has no settings to manage.  

![Screenshot 2023-10-25 142206](https://github.com/itsamewayu/OLFallenDoll/assets/129328061/b2b292dc-5e80-4408-bb62-c74bdcc5f6a3)

**Comment by Awfulwaffle1** [comment]
Verified fixed as of 0.7.75a. Closing
