### ISSUE TITLE
0.7.6 Unable to Access Harem Mode

### ISSUE THREAD

**Issue by bnl76** [itsamewayu/OLFallenDoll#961]
Describe the bug
Unable to access harem mode, producing an Error showing:
Error 1100: Server Internal Error ErrorCode:408

To Reproduce

1. Go to main page
2. Click on Harem
3. Wait 15 Sec
4. See error - Error 1100: Server Interval Error ErrorCode 408

Should be able to login to the harem mode.
The game work well before today.

Screenshots

Desktop (please complete the following information):

OS: Win10 22H2
Game Version 0.7.6
Complete the following Computer Hardware Configurations if necessary:
Processor(CPU): i7-3930K 
Graphics Card: RTX 2060 12GB
Memory: 16GB
*If your game crashed, remember to upload the dmp file with your issue.

It's located in C:\Users\ (USER ID) \AppData\Local\Paralogue

Additional context
Tried uninstall and reinstall the game and the entire system and enable steam to online mode, still would not fix the issue.

**Comment by bnl76** [comment]
[UE4Minidump.zip](https://github.com/itsamewayu/OLFallenDoll/files/13249290/UE4Minidump.zip)

**Comment by HRT39** [comment]
the same
