### ISSUE TITLE
Christmas Outfits are in the wrong language

### ISSUE THREAD

**Issue by YoWaddupFD** [itsamewayu/OLFallenDoll#963]
Anya, Alet, Erika and Celia's Christmas outfits are now GirlName[chinese] instead of their name.

<img width="176" alt="Capture" src="https://github.com/itsamewayu/OLFallenDoll/assets/136668781/e79fa9e7-f7be-4cb9-afb8-ebe933f13bf8">

**Comment by Awfulwaffle1** [comment]
Looks good on my end as of 0.7.75a. Closing.
