### ISSUE TITLE
Bug: Elizabeth's Celebrity Soiree Outfit

### ISSUE THREAD

**Issue by johanna-jane** [itsamewayu/OLFallenDoll#969]
**Describe the bug**
A graphical glitch with Elizabeth's Celebrity Soiree outfit leading to disappearing body parts and/or clipping.

When Upper Apparel is "Dressed" and Upper Underwear is "Nude", the middle of her torso disappears leaving a very obvious gap in her body that you can see through.

When Upper Apparel is "Nude" and Upper Underwear is "Dressed", both her nipples clip through the outfit mesh and visibly poke through the fabric.

**To Reproduce**
1. Go to Elizabeth's outfit tab and equip/preview the Celebrity Soiree outfit.
2. Set the Upper Apparel and Upper Underwear options as described above (one as "Dressed" and the other as "Nude" and vice-versa).
3. Observe the graphical glitches.

**Expected behavior**
No missing body parts and minimal clipping.

**Desktop (please complete the following information):**
 - OS: Win10
 - Game Version 0.7.6
 Complete the following Computer Hardware Configurations if necessary:
 - Processor(CPU): AMD Ryzen 7 1700 eight-core 3.00 GHz
 - Graphics Card: Radeon RX 570
 - Memory: 16GB

**Comment by Awfulwaffle1** [comment]
Verified fixed as of 0.7.7d
