### ISSUE TITLE
[Harem] [UI Sound] UI sound leak

### ISSUE THREAD

**Issue by TheSoulWizard** [itsamewayu/OLFallenDoll#97]
There's a sound leak on the harem's mode UI, even when everything audio related setting was set to 0, on harem main screen, when clicking on characters body, the dialogue sounds (alongside with other sounds) are audiable. Unfortunately i wasn't able to get a Video Recording as the servers went down shortly after.

**Comment by jinjin525** [comment]
From fallenDollPhobos in issue #161 
although all sounds are muted in options, footsteps are still being played when you switch to another character in harem mode
Also other soundeffects leaking mentioned.

**Comment by Awfulwaffle1** [comment]
Still an issue with doors, footsteps, and any'a chair squeak.
