### ISSUE TITLE
Bug: Volume Settings

### ISSUE THREAD

**Issue by johanna-jane** [itsamewayu/OLFallenDoll#970]
**Describe the bug**
Volume settings fail to control all sources of volume. Some sounds, such as footsteps and opening/closing doors, are unaffected by volume settings and continue to make sounds when all volumes are set to zero. This makes it impossible to mute the game or to properly configure volume.

**To Reproduce**
1. Set all volume settings to zero.
2. Listen to all the sounds that continue to play.

**Expected behavior**
All sources of volume should be configurable in the settings, and it should be possible to mute the game if desired.

**Desktop:**
 - OS: Win10
 - Game Version 0.7.6
 Complete the following Computer Hardware Configurations if necessary:
 - Processor(CPU): AMD Ryzen 7 1700 eight-core 3.00 GHz
 - Graphics Card: Radeon RX 570
 - Memory: 16GB

**Comment by Awfulwaffle1** [comment]
Verified fixed as of 0.7.75a. Closing. @johanna-jane feel free to re-open if you feel that this is still an issue.
