### ISSUE TITLE
[Animation] ALET become T pose when ecstasy

### ISSUE THREAD

**Issue by noople30** [itsamewayu/OLFallenDoll#98]
**Describe the bug**
ALET become T pose when ecstasy

**To Reproduce**
in harem mode
female A Erika
female B Alet
choose foot-licking scissoring
start Special 1
wait alet ecstasy

**Screenshots**
![20211130135216_1](https://user-images.githubusercontent.com/95269133/143990086-f6d057a4-3764-41c4-860c-be34633afe9b.jpg)

**Comment by Awfulwaffle1** [comment]
Not occurring anymore. Closing.
