### ISSUE TITLE
[UI] [System] White screen spills out to second monitor

### ISSUE THREAD

**Issue by shaunkeef** [itsamewayu/OLFallenDoll#99]
windowed set to "full" 
resolution set to 1920x1080
4k main monitor
happens on start and stays till I change the resolution

**To Reproduce**
1. open game 
2. close game
3. open game
4. close game
5. open game

**Comment by itsamewayu** [comment]
Do you have a screenshot or picture?

**Comment by shaunkeef** [comment]
![E9021BD5-F3F7-4139-A824-4C5A931BC68F](https://user-images.githubusercontent.com/95270092/144139832-8dd33017-13d5-4e8f-866b-45eaedb5c840.jpeg)

![3435CBEF-F140-4EBF-8476-E116E79F6BFC](https://user-images.githubusercontent.com/95270092/144139934-128be430-803e-4899-8975-8ac440261a9a.jpeg)

when game is focus and not focus

**Comment by Awfulwaffle1** [comment]
No longer seeing this on my end. Please reopen if this is still occurring.
