### ISSUE TITLE
OUTFIT Elizabeth's Midnight Rider top

### ISSUE THREAD

**Issue by Bl4cktalon** [itsamewayu/OLFallenDoll#996]
With the Upper apparel set to Nude and Lower Apparel set to Half Dressed the applied alpha erases a significan part of the visible naked body.

https://gyazo.com/c967ac31730f2b7be70ebc65ad14df42

**Comment by Awfulwaffle1** [comment]
This particular bug is fixed. Though a different issue arises when Elizabeth has an inflated belly. I'll create a separate issue for that. Closing this one
