### ISSUE TITLE
INTERFACE - 'Like' and 'Hidden' buttons under player names usually only become visible the second time you expand the tab containing those

### ISSUE THREAD

**Issue by Bl4cktalon** [itsamewayu/OLFallenDoll#997]
This bug would be a few moths old now, well a couple months at very least. The buttons are still there, just not visible and can be blind-clicked to send likes.

https://gyazo.com/62c569b5d40b95da24f02f7b71721bb4

**Comment by Awfulwaffle1** [comment]
@Bl4cktalon This one should be fixed as of 0.7.75b as well. Please close if you concur.

**Comment by Bl4cktalon** [comment]
Resolved, closing.
