### ISSUE TITLE
[Fatal Bug]能够进入后宫模式，但无法进入空间站或者是夜总会/Can enter harem mode, but cannot enter station or night club

### ISSUE THREAD

**Issue by GGW70** [itsamewayu/OLFallenDoll#999]
**Describe the bug**
能够进入后宫模式，但无法进入空间站或者是夜总会/Can enter harem mode, but cannot enter station or night club
已经使用VPN，网络状况正常/Network is not a problem
从后宫模式进入空间站时一直卡在loading中，没有任何响应，loading动画和bgm正常/Stuck in loading page of entering Station, can hear BGM
偶尔能听到后台其他声音/ Sometimes can hear some sound beside BGM

**To Reproduce**
see above

**Expected behavior**
能够正常进入空间站或夜总会/ Can play game as normal

**Screenshots**
![image](https://github.com/itsamewayu/OLFallenDoll/assets/151932179/01eb7774-408f-4ccd-9629-8a871a58c18b)
> stucking

**Desktop (please complete the following information):**
 - OS: Windows 11 专业版 22631.2715
 - Game Version 0.7.7
 Complete the following Computer Hardware Configurations if necessary:
 - Processor(CPU): i7-13700K   3.40 GHz
 - Graphics Card: RTX 4090
 - Memory: 32G DDR5
 

**Additional context**
已尝试删除以下目录，并重装显卡驱动，无效。
Tried delete "\AppData\Local\Paralogue\Saved\Config\WindowsNoEditor" and reinstall graphic card drive, not working

**Comment by Awfulwaffle1** [comment]
@GGW70 are you able to try using VPN and connecting through an North America or European region? Also if you can link your HLog folder it'd help the developers troubleshoot. It should be located in \steamapps\common\Operation Lovecraft Fallen Doll Playtest\Paralogue\Binaries\Win64

**Comment by GGW70** [comment]
Sure thing, here is the log file.
[HLog.zip](https://github.com/itsamewayu/OLFallenDoll/files/13464389/HLog.zip)

Checked the NetSpeed.speed file, cause by network problem:
22:55:40:480[Simple]---[SpeedTester]---Ping failed for ec2.ap-east-1.amazonaws.com
22:55:40:480[Simple]---[SpeedTester]---Ping failed for ec2.us-west-2.amazonaws.com
22:55:40:485[Simple]---[SpeedTester]---Ping failed for ec2.eu-central-1.amazonaws.com
22:55:40:490[Simple]---[SpeedTester]---Speed 初始化失败，数据为空
22:55:40:494[Simple]---[SpeedTester]---Ping 测试已完成出现异常，找不到合适的地区，Map【Speed】可能为空

I tried using different VPN region, and got ip addresses like:
1.
ISP: OVH SAS
City: Roubaix
Region: Hauts-de-France
Country: France

2.
ISP: Misaka Network Inc.
Services: [Suspected Network Sharing Device](https://whatismyipaddress.com/ip-services)
City: San Jose
Region: California
Country: United States

But still stuck in loading page.
Also I tried to ping these AWS server, got timeout. Did you guys put some restrictions on the server?


// update
Finally, I just turned off Merlin Clash installed in the modem, and use VPN client install on Windows, it worked!
Guess it may have some problem with fake ip mode

**Comment by suenxi7** [comment]
我也是。使用vpn能够进入后宫模式，但无法进入空间站或者是夜总会

**Comment by Am3th1st** [comment]
是怎么解决的呢，我最近也遇到了network error的问题
